<p class="navigation"><a class="navigation" href="http://^^JS:system.inet_addr^^/">Home</a> : <a class="navigation" href="index.ssjs">Groups</a> : <a class="navigation" href="subs.ssjs?msg_grp=^^group:name^^">%%group:description%%</a> : 
            <a class="navigation" href="msgs.ssjs?msg_sub=^^sub:code^^">%%sub:description%%</a></p>
<table class="posted" cellspacing="2" cellpadding="2">
    <tbody>
        <tr>
        <td class="posted">
            <h1>Message posted successfully</h1>
            <p class="posted"><a href="msgs.ssjs?msg_sub=^^sub:code^^">Return to %%sub:description%%</a></p>
        </td>
        </tr>
    </tbody>
</table>
