<form action="savemsg.ssjs" method="post">
<table class="postmsg" border="0" cellspacing="2" cellpadding="0">
<input type="hidden" name="msg_sub" value="%%sub:code%%" />
  <tbody>
    <tr>
      <td class="postmsg">Subject: <input class="postmsg" type="text" name="subject" value="" /></td>
      <td class="postmsg">To: <input class="postmsg" type="text" name="to" value="All" /></td>
    </tr>
	<tr>
	  <td class="postmsg" colspan="2">@@anonnote@@</td>
	</tr>
	<tr>
	  <td class="postmsg" colspan="2">@@privnote@@</td>
	</tr>
    <tr>
      <td class="postmsg" colspan="2"><textarea class="postmsg" name=body rows="20" cols="80" wrap="hard"></textarea></td>
      </tr>
    <tr>
      <td align="center" class="postmsg" colspan="2"><input type="submit" value="Post Message" /></td>
    </tr>
  </tbody>
</table>
</form>

