                                  chSynchronet
                                 r Blackjack! 
w
        As you might have guessed, this is a blackjack game. But not just any
blackjack game. With Synchronet Blackjack, you play against the house for
credits and your friends can play along side you simultaneously from the same
card shoe. You can even carry on a conversation while a hand is in play!

        Beware, you are gambling with your credits if you choose to play, but
the odds are pretty good. House pays double on a natural blackjack or three
sevens, 1« to 1 on regular blackjack, even money on other winning hands and 
ties (pushes) break even. You can double down if you have enough dough and even
split pairs!

        If you choose to play, note that it is much more enjoyable with a
friend at the table with you. While the dealer is fast and curteous, he doesn't
make a very good conversationalist.

	If you notice that you're not seeing the card symbols for 'clubs' you
may have Compuserve Quick B transfers enabled or another answerback to Ctrl-E.
This should be disabled, or you should toggle card symbols OFF.


