OBJS       = $(MTOBJODIR)$(DIRSEP)tbd$(OFILE) \
			$(MTOBJODIR)$(DIRSEP)tbd2$(OFILE) \
			$(MTOBJODIR)$(DIRSEP)tbd_pack$(OFILE) \
			$(MTOBJODIR)$(DIRSEP)xsdk$(OFILE) \
			$(MTOBJODIR)$(DIRSEP)xsdkvars$(OFILE)

MAPMAKER_OBJS = $(MTOBJODIR)$(DIRSEP)mapmaker$(OFILE)

REROLL_OBJS	= $(MTOBJODIR)$(DIRSEP)reroll$(OFILE)
