/* Generated by genpack.pl from tbd.h on Tue Jun 12 23:22:14 2007 */

#ifndef _INCLUDED_TBD_PACK_H
#define _INCLUDED_TBD_PACK_H

#include "tbd.h"
#include "xpendian.h"

/* Function prototypes */
#if defined(__cplusplus)
extern "C" {
#endif
int pack_user_t_struct(char *buf, user_t *data);
int unpack_user_t_struct(user_t *data, char *buf);
#if defined(__cplusplus)
}
#endif

#endif /* Do not add anything after this line! */
