l                              chSynchronet Callback

	ngWhen you continue the automatic validation process, chSynchronet Callback
(SCB) ngwill ask you for your phone number.  This rhMUSTng be the phone number that 
your modem is connected to and it must contain all of the digits necessary for
chSCBng to call you back (including a '1' and area code if necessary).

	If you choose not to continue with the validation process, answer hNOng
to the 'hContinue with verification?ng' question that chSCBng will ask you next.

	After you have entered an hACCEPTABLEng phone number, chSCBng will display a
short message, and call you back.  When your phone rings you will need to
answer it with your modem.  You should see a 'hRINGng' appear on your screen
(and you may also hear your phone ring if one is connected to the same line as
your modem), when this happens, you will need to type 'hATAng' and press hENTERng.
rhDO NOTng answer the phone by voice!

	The modems will then connect, and you will be given several chances to
enter your correct password.  Once you have entered the hCORRECTng password, chSCBng
will display a short message notifying you of this, validate your account,
and then disconnect.  If you enter your password hINCORRECTLYng, chSCBng will rhNOTng
validate your account.
