ng    Synchronet Callback can be used to verify your modem phone number.
If your modem phone number is verified, your access on the BBS may be 
immediately upgraded or the sysop will be notified of the verification and your
access may be upgraded later.

    Some BBSs may not allow long distance verification calls.  If you are 
not a local call from this BBS and it doesn't allow long distance calls,
you will be notified of this when you start the verification procedure.
