/* Generated by tools/gen_symbols.py from port/symbols.csv and port/cga/symbols_cga.csv. Do not edit. */
#pragma once
#include "build.h"

#if TD_CGA
/* ---- TDCGA.EXE */

/* DGROUP globals (offsets for DSB/DSW/DSS/DSL) */
#define DS_str_herc                              0x0040  /* platform, char[] */
#define DS_demo_mode                             0x0090  /* simulation, u16 */
#define DS_g_carAutoSelected                     0x0092  /* game_flow, int16 */
#define DS_g_numCars                             0x0094  /* game_flow, int16 */
#define DS_herc_mode                             0x0096  /* platform, u16 */
#define DS_g_introArchive                        0x0124  /* game_flow, far ptr */
#define DS_STAGE_SCORE_FACTOR                    0x0294  /* game_flow, int16[5] */
#define DS_STAGE_PAR_TIME                        0x029E  /* game_flow, int16[5] */
#define DS_STAGE_CONST_B                         0x02A8  /* game_flow, int16[5] */
#define DS_MSG_TABLES                            0x0770  /* game_flow, near char*[33] */
#define DS_GAS_SIGN_NAMES                        0x07B2  /* game_flow, near char*[4] */
#define DS_road_buf_desc                         0x0890  /* platform, far ptr */
#define DS_road_buf_sprite                       0x0894  /* scene_render, far ptr */
#define DS_road_buf_rowtab                       0x0898  /* scene_render, u16 */
#define DS_buf_desc_b                            0x089A  /* platform, far ptr */
#define DS_inst_buf_sprite                       0x089E  /* scene_render, far ptr */
#define DS_inst_x                                0x08A2  /* scene_render, u16 */
#define DS_inst_y                                0x08A4  /* scene_render, u16 */
#define DS_inst_h                                0x08A6  /* scene_render, u16 */
#define DS_inst_wbytes                           0x08A8  /* scene_render, u16 */
#define DS_speedo_pivot                          0x08AA  /* scene_render, 2xu16 */
#define DS_tach_pivot                            0x08AE  /* scene_render, 2xu16 */
#define DS_buf_desc_c                            0x08B2  /* platform, far ptr */
#define DS_gbox_buf_sprite                       0x08B6  /* scene_render, far ptr */
#define DS_gbox_x                                0x08BA  /* scene_render, u16 */
#define DS_gbox_y                                0x08BC  /* scene_render, u16 */
#define DS_gearbox_display_toggle                0x08BE  /* simulation, u8 */
#define DS_gearbox_prev                          0x08BF  /* scene_render, u8 */
#define DS_marker_save_sprite                    0x08C0  /* scene_render, sprite hdr */
#define DS_marker_save_x                         0x08D8  /* scene_render, s16 */
#define DS_marker_save_y                         0x08DA  /* scene_render, s16 */
#define DS_grind_timer                           0x08DC  /* simulation, u8 */
#define DS_road_pos                              0x08EE  /* simulation, u16 */
#define DS_road_pos_prev                         0x08F0  /* simulation, u16 */
#define DS_yaw_lateral                           0x08F2  /* simulation, i16 */
#define DS_view_heading                          0x08F4  /* simulation, i16 */
#define DS_unused_090e                           0x08F6  /* simulation, i16 */
#define DS_car_x                                 0x08F8  /* simulation, i16 */
#define DS_sub_unit                              0x08FA  /* simulation, i16 */
#define DS_steer_angle                           0x08FC  /* simulation, i16 */
#define DS_cur_ratio                             0x08FE  /* simulation, u16 */
#define DS_road_curve                            0x0901  /* simulation, i16 */
#define DS_rpm                                   0x0903  /* scene_render, u16 */
#define DS_rpm_smooth                            0x0905  /* simulation, u16 */
#define DS_dash_timer                            0x0907  /* simulation, u8 */
#define DS_gate_node                             0x0908  /* simulation, u8 */
#define DS_gate_shift_mode                       0x0909  /* simulation, u8 */
#define DS_gearbox_dirty                         0x090A  /* simulation, u8 */
#define DS_gauges_dirty                          0x090B  /* simulation, u8 */
#define DS_skidding                              0x090C  /* simulation, u8 */
#define DS_accel_mag                             0x090D  /* simulation, u16 */
#define DS_g_carSpeedFixed                       0x090F  /* game_flow, int16 */
#define DS_g_stageEvent                          0x0911  /* game_flow, uint8 */
#define DS_stage_end_pos                         0x0912  /* simulation, u16 */
#define DS_proj_cx_main                          0x0914  /* scene_render, s16 */
#define DS_proj_horizon_main                     0x0916  /* scene_render, s16 */
#define DS_proj_cx_mirror                        0x0918  /* scene_render, s16 */
#define DS_proj_y_mirror_off                     0x091A  /* scene_render, s16 */
#define DS_old_int0_vector                       0x091C  /* simulation, far ptr */
#define DS_ending_shown                          0x0920  /* simulation, u8 */
#define DS_pit_tick_count                        0x0922  /* simulation, u16 */
#define DS_clock_running                         0x0924  /* simulation, u8 */
#define DS_oncoming_count                        0x0929  /* simulation, u8 */
#define DS_samedir_count                         0x092A  /* simulation, u8 */
#define DS_r_traffic_count_l                     0x092B  /* scene_render, u8 */
#define DS_r_traffic_count_r                     0x092C  /* scene_render, u8 */
#define DS_oncoming_list                         0x092D  /* simulation, ent8[5] */
#define DS_samedir_list                          0x0955  /* simulation, ent8[5] */
#define DS_radar_trap                            0x0985  /* simulation, ent8 */
#define DS_hazard                                0x098D  /* simulation, ent8 */
#define DS_r_traffic_slots                       0x0995  /* scene_render, 13x8 bytes */
#define DS_snapshot_radar_trap_pos               0x09ED  /* simulation, u16 */
#define DS_r_hazard_slot                         0x09F5  /* scene_render, 8 bytes */
#define DS_trap_speed_table                      0x09FD  /* simulation, u16[3] */
#define DS_traffic_speed_table                   0x0A03  /* simulation, u16[3] */
#define DS_speed_limit_idx                       0x0A09  /* simulation, u16 */
#define DS_cop_state                             0x0A0B  /* simulation, u8 */
#define DS_r_cop_state                           0x0A0C  /* scene_render, u8 */
#define DS_cop_speed                             0x0A0D  /* simulation, u16 */
#define DS_cop_timer                             0x0A0F  /* simulation, u8 */
#define DS_cop_tail_timer                        0x0A10  /* simulation, u8 */
#define DS_cop_lateral                           0x0A11  /* simulation, u16 */
#define DS_cop_sub                               0x0A13  /* simulation, u16 */
#define DS_cop_pos                               0x0A15  /* simulation, u16 */
#define DS_cop_block_idx                         0x0A17  /* simulation, u8 */
#define DS_r_cop_pos                             0x0A18  /* scene_render, u16 */
#define DS_r_cop_lane                            0x0A1A  /* scene_render, s16 */
#define DS_r_cop_sub                             0x0A1C  /* scene_render, s16 */
#define DS_cop_state_jump_table                  0x0A1E  /* simulation, u16[8] */
#define DS_cop_lane_curve                        0x0A2E  /* simulation, u8[49] */
#define DS_fire_held                             0x0A5F  /* simulation, u8 */
#define DS_gear                                  0x0A60  /* simulation, u8 */
#define DS_throttle_in                           0x0A61  /* simulation, i8 */
#define DS_steer_in                              0x0A62  /* simulation, i8 */
#define DS_knob_anim                             0x0A63  /* simulation, u8 */
#define DS_shift_latch                           0x0A64  /* simulation, u8 */
#define DS_knob_x                                0x0A65  /* simulation, u16 */
#define DS_knob_y                                0x0A67  /* scene_render, s16 */
#define DS_knob_target_x                         0x0A69  /* simulation, u16 */
#define DS_unit_advanced                         0x0A6D  /* simulation, u8 */
#define DS_steer_dir_table                       0x0A6E  /* simulation, i8[9] */
#define DS_throttle_dir_table                    0x0A9B  /* simulation, i8[9] */
#define DS_gear_delta_table                      0x0AA4  /* simulation, i8[9] */
#define DS_drag_table                            0x0AAD  /* simulation, u8[64] */
#define DS_SONG_INGAME                           0x0AED  /* game_flow, bytecode */
#define DS_xroada_handles                        0x0F76  /* scene_render, 117 far ptrs */
#define DS_spr_govr                              0x1006  /* game_flow, far ptr */
#define DS_spr_deal                              0x100A  /* game_flow, far ptr */
#define DS_spr_note                              0x100E  /* game_flow, far ptr */
#define DS_spr_tick                              0x1012  /* game_flow, far ptr */
#define DS_xroadb_handles                        0x1146  /* scene_render, 50 far ptrs */
#define DS_car_handles                           0x1356  /* scene_render, 25 far ptrs */
#define DS_spr_mirr                              0x138E  /* game_flow, far ptr */
#define DS_spr_roof                              0x13AE  /* game_flow, far ptr */
#define DS_digit_handles                         0x13BA  /* scene_render, 15 far ptrs */
#define DS_int0_handler                          0x13EA  /* scene_render, code */
#define DS_road_anim_counter                     0x13FA  /* simulation, u8 */
#define DS_dash_counter                          0x13FB  /* scene_render, u8 */
#define DS_mirror_rows_done                      0x13FC  /* scene_render, u16 */
#define DS_crest_sy                              0x13FE  /* scene_render, u8 */
#define DS_cached_top_sy                         0x1400  /* scene_render, u8 */
#define DS_cached_top_row                        0x1402  /* scene_render, u16 */
#define DS_obj_scale                             0x1404  /* scene_render, u16 */
#define DS_xclip_px                              0x1406  /* scene_render, u16 */
#define DS_xclip_bytes                           0x1408  /* scene_render, u16 */
#define DS_cached_top_row_mirror                 0x140A  /* scene_render, u16 */
#define DS_wheel_state                           0x140C  /* scene_render, u8 */
#define DS_marker_saved                          0x140D  /* scene_render, u8 */
#define DS_cop_light_timer                       0x140E  /* simulation, u16 */
#define DS_span_bit                              0x1436  /* scene_render, u16 */
#define DS_span_ol                               0x1438  /* scene_render, s16[111] */
#define DS_span_l                                0x1516  /* scene_render, s16[111] */
#define DS_span_r                                0x15F4  /* scene_render, s16[111] */
#define DS_span_or                               0x16D2  /* scene_render, s16[111] */
#define DS_span_ol_mirror                        0x17B0  /* scene_render, s16[18] */
#define DS_span_l_mirror                         0x17D4  /* scene_render, s16[18] */
#define DS_span_r_mirror                         0x17F8  /* scene_render, s16[18] */
#define DS_span_or_mirror                        0x181C  /* scene_render, s16[18] */
#define DS_walk_ptr                              0x1840  /* scene_render, u16 */
#define DS_r_road_ptr                            0x1842  /* scene_render, u16 */
#define DS_r_subpos                              0x1844  /* scene_render, s16 */
#define DS_heading_acc                           0x1846  /* scene_render, s16 */
#define DS_slope_acc                             0x1848  /* scene_render, s16 */
#define DS_row_X                                 0x184A  /* scene_render, s16[40] */
#define DS_row_Y                                 0x189A  /* scene_render, s16[40] */
#define DS_row_X_mirror                          0x18EA  /* scene_render, s16[25] */
#define DS_row_Y_mirror                          0x193A  /* scene_render, s16[25] */
#define DS_cut_x                                 0x198A  /* scene_render, s16 */
#define DS_cut_sy                                0x198C  /* scene_render, u16 */
#define DS_cut_row                               0x198E  /* scene_render, u16 */
#define DS_cut_row_mirror                        0x1990  /* scene_render, u16 */
#define DS_cut_top_sy                            0x1992  /* scene_render, u8 */
#define DS_cut_top_sy_mirror                     0x1994  /* scene_render, u8 */
#define DS_min_ol                                0x1996  /* scene_render, s16 */
#define DS_min_ol_sy                             0x1998  /* scene_render, u8 */
#define DS_first_changed_row                     0x199A  /* scene_render, u16 */
#define DS_prev_row_limit                        0x199C  /* scene_render, u16 */
#define DS_row_limit_main                        0x199E  /* scene_render, u16 */
#define DS_top_sy                                0x19A0  /* scene_render, u8 */
#define DS_top_row                               0x19A2  /* scene_render, u16 */
#define DS_span_clamp_min                        0x19A4  /* scene_render, s16 */
#define DS_span_clamp_max                        0x19A6  /* scene_render, s16 */
#define DS_cut_x_mirror                          0x19A8  /* scene_render, s16 */
#define DS_cut_sy_mirror                         0x19AA  /* scene_render, u16 */
#define DS_min_ol_mirror                         0x19AC  /* scene_render, s16 */
#define DS_min_ol_sy_mirror                      0x19AE  /* scene_render, u8 */
#define DS_row_limit_mirror                      0x19B0  /* scene_render, u16 */
#define DS_top_sy_mirror                         0x19B2  /* scene_render, u8 */
#define DS_top_row_mirror                        0x19B4  /* scene_render, u16 */
#define DS_row_ol                                0x19B6  /* scene_render, s16[40] */
#define DS_row_l                                 0x1A06  /* scene_render, s16[40] */
#define DS_row_r                                 0x1A56  /* scene_render, s16[40] */
#define DS_row_or                                0x1AA6  /* scene_render, s16[40] */
#define DS_row_cx                                0x1AF6  /* scene_render, s16[40] */
#define DS_row_sy                                0x1B46  /* scene_render, u8 at even offsets */
#define DS_row_obj                               0x1CD6  /* scene_render, u8 at even offsets */
#define DS_row_ol_mirror                         0x1D26  /* scene_render, s16[25] */
#define DS_row_l_mirror                          0x1D62  /* scene_render, s16[25] */
#define DS_row_r_mirror                          0x1D9E  /* scene_render, s16[25] */
#define DS_row_or_mirror                         0x1DDA  /* scene_render, s16[25] */
#define DS_row_cx_mirror                         0x1E16  /* scene_render, s16[25] */
#define DS_row_sy_mirror                         0x1E52  /* scene_render, u8 at even offsets */
#define DS_row_obj_mirror                        0x1F7E  /* scene_render, u8 at even offsets */
#define DS_cur_curve                             0x200E  /* scene_render, u8 */
#define DS_roadside_pattern                      0x2011  /* scene_render, u16[16] */
#define DS_engine_note_div_table                 0x204A  /* simulation, u16[151] */
#define DS_road_halfwidth_q4                     0x2178  /* scene_render, u16[40] */
#define DS_traffic_scale_main                    0x21C8  /* scene_render, u8[40] */
#define DS_traffic_scale_mirror                  0x21F1  /* scene_render, u8[25] */
#define DS_row_depth_Z                           0x221A  /* scene_render, u16[40] */
#define DS_sinq_table                            0x226A  /* simulation, u8[91] */
#define DS_sine_x15                              0x22C5  /* scene_render, u16[91] */
#define DS_wheel_sin90                           0x237B  /* scene_render, u8[60] */
#define DS_wheel_cos90                           0x23B7  /* scene_render, u8[61] */
#define DS_persp_T                               0x23F3  /* scene_render, u16[91] */
#define DS_tan256                                0x24A9  /* scene_render, u16[46] */
#define DS_crack_counts                          0x2505  /* scene_render, u8[7] */
#define DS_crack_ptrs                            0x250C  /* scene_render, u16[7] */
#define DS_car_num_gears                         0x2662  /* simulation, u8 */
#define DS_car_rpm_limit                         0x2666  /* simulation, u16 */
#define DS_car_grip_limit                        0x266A  /* simulation, i16 */
#define DS_car_skid_drift                        0x266C  /* simulation, u8 */
#define DS_car_gear_ratio                        0x2674  /* simulation, u16[7] */
#define DS_car_knob_xy                           0x2682  /* simulation, u16[7][2] */
#define DS_car_gate_next                         0x26DE  /* simulation, u8[144] */
#define DS_car_node_gear                         0x276E  /* simulation, u8[16] */
#define DS_car_torque                            0x277E  /* simulation, u8[80] */
#define DS_road_record_curve                     0x2B41  /* simulation, u8 */
#define DS_joy_dir_map                           0x6366  /* platform, u8[16] */
#define DS_ext_scan_dir_map                      0x6376  /* platform, u8[12] */
#define DS_digit_dir_map                         0x6382  /* platform, u8[10] */
#define DS_kbd_shift_btn                         0x63AE  /* platform, u8 */
#define DS_joy_menu_scan                         0x63B0  /* platform, u16[16] */
#define DS_joy_menu_last                         0x63DE  /* platform, u16 */
#define DS_input_mode                            0x63E0  /* platform, u16 */
#define DS_modal_pause                           0x63E2  /* platform, u8 */
#define DS_old_int8                              0x63E4  /* platform, far ptr */
#define DS_tick_count                            0x63E8  /* platform, u16 */
#define DS_snd_ptr                               0x63EA  /* platform, seg (642C) : off (642E) */
#define DS_snd_loop_ptr                          0x63EE  /* platform, seg (6430) : off (6432) */
#define DS_chain_reload                          0x63F2  /* platform, u16 */
#define DS_chain_count                           0x63F4  /* platform, s16 */
#define DS_note_left                             0x63F6  /* platform, u16 */
#define DS_note_cut                              0x63F8  /* platform, u16 */
#define DS_snd_shift                             0x63FA  /* platform, u8 */
#define DS_snd_playing                           0x63FB  /* platform, u8 */
#define DS_snd_flags                             0x63FC  /* platform, u8 */
#define DS_chain_enable                          0x63FD  /* platform, u8 */
#define DS_loop_cnt                              0x63FE  /* platform, s16[3] */
#define DS_loop_start                            0x6404  /* platform, u16[3] */
#define DS_loop_end                              0x640A  /* platform, u16[3] */
#define DS_note_div                              0x6410  /* platform, u16[0x5E] */
#define DS_note_div_engine                       0x64BA  /* platform, u16 */
#define DS_note_div_skid                         0x64BC  /* platform, u16 */
#define DS_note_div_beep                         0x64BE  /* platform, u16 */
#define DS_deadline_start                        0x64CA  /* platform, u16 */
#define DS_deadline_len                          0x64CC  /* platform, u16 */
#define DS_rand8_idx                             0x64EC  /* platform, u16 */
#define DS_rand8_tab                             0x64EE  /* platform, u8[256] */
#define DS_herc_crtc_gfx                         0x661C  /* platform, u8[12] */
#define DS_herc_crtc_text                        0x6628  /* platform, u8[12] */
#define DS_joy_enabled                           0x66C2  /* platform, u8 */
#define DS_joy_calibrated                        0x66C3  /* platform, u8 */
#define DS_calib_sq_x                            0x66C4  /* platform, u16[9] */
#define DS_calib_sq_y                            0x66D6  /* platform, u16[9] */
#define DS_text_fg                               0x68E8  /* platform, u16 */
#define DS_text_bg                               0x68EA  /* platform, u16 */
#define DS_text_margin_x                         0x68EC  /* platform, u16 */
#define DS_text_x                                0x68EE  /* platform, u16 */
#define DS_text_y                                0x68F0  /* platform, u16 */
#define DS_text_font                             0x68F6  /* platform, far ptr */
#define DS_text_adv_y                            0x68FC  /* platform, u16 */
#define DS_joy_x                                 0x6900  /* platform, u16 */
#define DS_joy_port_pre                          0x6904  /* platform, u8 */
#define DS_joy_result                            0x6905  /* platform, u8 */
#define DS_joy_xmin                              0x6906  /* platform, u16 */
#define DS_joy_xover_min                         0x690A  /* platform, u16 */
#define DS_joy_xlo                               0x690E  /* platform, u16 */
#define DS_joy_ymin                              0x6912  /* platform, u16 */
#define DS_gfx_target_save_area                  0x6986  /* platform, u16[24] */
#define DS_g_showroomCarSpr                      0x7380  /* game_flow, far ptr */
#define DS_g_lives                               0x7384  /* game_flow, int16 */
#define DS_g_songIntro                           0x7386  /* game_flow, far ptr */
#define DS_g_avgSpeed                            0x738A  /* game_flow, int16 */
#define DS_g_carSBArchive                        0x738C  /* game_flow, far ptr */
#define DS_g_carNames                            0x7390  /* game_flow, near char*[10] */
#define DS_g_songCarSel                          0x73A4  /* game_flow, far ptr */
#define DS_g_selectedCar                         0x73A8  /* game_flow, int16 */
#define DS_g_resultLineCount                     0xCD82  /* game_flow, int16 */
#define DS_g_scrollDelay                         0xCF84  /* game_flow, int16 */
#define DS_mem_bot                               0xCF86  /* platform, u16 seg */
#define DS_g_stage                               0xCF88  /* game_flow, int16 */
#define DS_g_xroadA                              0xCF8A  /* game_flow, far ptr */
#define DS_mem_low                               0xCF92  /* platform, u16 seg */
#define DS_g_xroadC                              0xCF8E  /* game_flow, far ptr */
#define DS_g_songHiScore                         0xCF98  /* game_flow, far ptr */
#define DS_g_carArchive                          0xCF9C  /* game_flow, far ptr */
#define DS_mem_top                               0xD1A0  /* platform, u16 seg */
#define DS_cache_slots                           0xD1A2  /* platform, 16 B × 30 */
#define DS_mem_high                              0xD382  /* platform, u16 seg */
#define DS_page_buf_desc                         0xD384  /* platform, far ptr */
#define DS_buf_slots                             0xD388  /* platform, 4 B × 8 */
#define DS_g_stageConstB                         0xD3A8  /* game_flow, int16 */
#define DS_g_tooSlow                             0xD3AA  /* game_flow, int16 */
#define DS_g_sbArchiveName                       0xD3AC  /* game_flow, char[30] */
#define DS_g_carNameBuf                          0xD3CA  /* game_flow, char[] */
#define DS_g_songGas                             0xD4F6  /* game_flow, far ptr */
#define DS_g_parTime                             0xD4FA  /* game_flow, int16 */
#define DS_g_totalScore                          0xD4FC  /* game_flow, int32 */
#define DS_g_stageTime                           0xD500  /* game_flow, int16 */
#define DS_g_resultTextY                         0xD502  /* game_flow, int16 */

/* Original functions (image offsets) */
#define FN_main                                  0x0010  /* game_flow, int main(int argc char **argv) */
#define FN_load_cars_txt                         0x023E  /* game_flow, void(void) */
#define FN_play_again_menu                       0x02BA  /* game_flow, int(void) */
#define FN_run_intro                             0x0375  /* game_flow, int(void) */
#define FN_intro_accolade                        0x03EF  /* game_flow, int(void) */
#define FN_intro_testdrive_car                   0x0516  /* game_flow, int(void) */
#define FN_intro_testdrive_logo                  0x078D  /* game_flow, int(void) */
#define FN_car_select                            0x0987  /* game_flow, int(void) */
#define FN_show_car                              0x0AAD  /* game_flow, void(int idx int dir) */
#define FN_showroom_drive_away                   0x0D3F  /* game_flow, void(int idx) */
#define FN_read_line_strip                       0x0FCA  /* game_flow, void(char *buf int n FILE *f) */
#define FN_run_game                              0x0FFA  /* game_flow, int(void) */
#define FN_stage_score                           0x11FD  /* game_flow, long(void) */
#define FN_high_scores                           0x127B  /* game_flow, int(long newScore) */
#define FN_scores_load                           0x1309  /* game_flow, void(char *names long *scores char *cars */
#define FN_scores_enter_name                     0x1422  /* game_flow, void(long score int car char *names long */
#define FN_scores_save                           0x15CE  /* game_flow, void(char *names long *scores char *cars */
#define FN_scores_show                           0x1677  /* game_flow, int(char *names long *scores char *cars) */
#define FN_credits_show                          0x180E  /* game_flow, int(void) */
#define FN_stage_results                         0x1933  /* game_flow, void(long score) */
#define FN_results_text                          0x1AD6  /* game_flow, void(long score) */
#define FN_results_add_line                      0x1C9A  /* game_flow, void(const char *s) */
#define FN_results_scroll                        0x1CC0  /* game_flow, void(void) */
#define FN_run_stage                             0x1D60  /* game_flow, int(void) */
#define FN_stage_init_road_ptr                   0x1ECC  /* scene_render, void(void) */
#define FN_wait_fire_button                      0x1EF9  /* scene_render, void(void) */
#define FN_reset_car_state                       0x1F11  /* scene_render, void(void) */
#define FN_snapshot_sim_state                    0x1F91  /* scene_render, void(void) */
#define FN_project_road_main                     0x1FD2  /* scene_render, void(void) */
#define FN_proj_x_main                           0x2370  /* scene_render, AX=f(BX X;DX Z) */
#define FN_proj_y_main                           0x239F  /* scene_render, AX=f(BX X;DX Z;CX Y) */
#define FN_project_road_mirror                   0x23F6  /* scene_render, void(void) */
#define FN_proj_x_mirror                         0x27AA  /* scene_render, AX=f(BX X;DX Z) */
#define FN_proj_y_mirror                         0x27D9  /* scene_render, AX=f(BX X;DX Z;CX Y) */
#define FN_draw_road_main                        0x2843  /* scene_render, void(void) */
#define FN_fill_road_scanlines_main              0x2D58  /* scene_render, void(void) */
#define FN_fill_span_to                          0x2DF2  /* scene_render, ZF=f(AX end;DX bytepos;DI;ES) */
#define FN_fill_scenery_above_road               0x2E5C  /* scene_render, void(void) */
#define FN_draw_road_mirror                      0x2EE1  /* scene_render, void(void) */
#define FN_fill_road_scanlines_mirror            0x3259  /* scene_render, void(void) */
#define FN_fill_span_to_mirror                   0x32EF  /* scene_render, ZF=f(AX end;DX;DI;ES) */
#define FN_draw_mirror_background                0x3365  /* scene_render, void(void) */
#define FN_draw_buffer_overlays                  0x33FB  /* scene_render, void(void) */
#define FN_draw_gear_box                         0x3478  /* scene_render, void(void) */
#define FN_draw_dashboard_dynamic                0x3524  /* scene_render, void(void) */
#define FN_draw_digit                            0x3818  /* scene_render, (BL digit;DX x) */
#define FN_dealership_ending                     0x3836  /* scene_render, void(void) */
#define FN_crash_windscreen_sequence             0x3875  /* scene_render, void(void) */
#define FN_sin_deg                               0x392A  /* scene_render, AX=f(AX deg) */
#define FN_atan_lookup                           0x3957  /* scene_render, AX=f(AX ratio256) */
#define FN_interp_edge_span                      0x3976  /* scene_render, (AX a;BX b;CL n;DL n;DI dst) */
#define FN_select_screen                         0x3A01  /* scene_render, void(void) */
#define FN_select_road_buffer                    0x3A0D  /* scene_render, void(void) */
#define FN_present_road_buffer                   0x3A36  /* scene_render, void(void) */
#define FN_sim_isr_exit_jmp                      0x3A54  /* simulation, label */
#define FN_sim_timer_isr                         0x3A57  /* simulation, interrupt */
#define FN_sim_input_charkey                     0x3AEC  /* simulation, label */
#define FN_sim_tick                              0x3B22  /* simulation, label */
#define FN_sim_input_direction                   0x3BF0  /* simulation, label */
#define FN_sim_steering                          0x3CB5  /* simulation, label */
#define FN_sim_shift_knob_anim                   0x3D13  /* simulation, label */
#define FN_sim_engine                            0x3DE2  /* simulation, label */
#define FN_sim_update_rpm                        0x3EE5  /* simulation, u16 DX(void) */
#define FN_sim_motion                            0x3F20  /* simulation, label */
#define FN_sim_advance_unit                      0x4036  /* simulation, label */
#define FN_sim_lookahead                         0x4179  /* simulation, label */
#define FN_sim_traffic_update                    0x41B7  /* simulation, label */
#define FN_sim_cop_fsm                           0x42C2  /* simulation, label */
#define FN_sim_object_cleanup                    0x4497  /* simulation, label */
#define FN_sim_spawn_object                      0x45B5  /* simulation, label */
#define FN_stage_enter_install_isr               0x46CA  /* simulation, void(void) */
#define FN_car_data_ptr                          0x4853  /* simulation, u16(void) */
#define FN_gfx_fill_rect                         0x4857  /* platform, void (s16 x, s16 y, s16 w, s16 h, u8 col */
#define FN_gfx_clear_screen                      0x4AD8  /* platform, void (u8 colour) */
#define FN_gfx_draw_text                         0x4AF7  /* platform, void (char *s, s16 x, s16 y) */
#define FN_gfx_draw_text_at_cursor               0x4B0E  /* platform, void (char *s) */
#define FN_gfx_set_border                        0x4BC2  /* platform, void (u8 colour) */
#define FN_gfx_set_palette                       0x4BCE  /* platform, void (u16 ds_table) */
#define FN_gfx_init_ega                          0x4BDA  /* platform, void (void) */
#define FN_blit_or_clip_hot                      0x4C0C  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_or_clip_own                      0x4C4E  /* platform, void (u16 off, u16 seg) */
#define FN_gfx_set_clip                          0x4DF6  /* platform, void (u16 doff, u16 dseg, s16 x0, s16 x1 */
#define FN_gfx_shutdown                          0x4E53  /* platform, void (void) */
#define FN_gfx_select_target                     0x4E7D  /* platform, void (u16 doff, u16 dseg) */
#define FN_gfx_create_buffer                     0x4EA5  /* platform, far desc (u16 w_bytes, u16 h, u16 plane_ */
#define FN_input_poll_drive                      0x58F8  /* platform, u16 (void) */
#define FN_blit_copy_clip_hot                    0x5A30  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_copy_clip_raw                    0x5A54  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_copy_clip_own                    0x5A72  /* platform, void (u16 off, u16 seg) */
#define FN_res_find                              0x5C55  /* platform, far ptr (u16 aoff, u16 aseg, char *name4 */
#define FN_getkey_wait                           0x5CD0  /* platform, u16 (void) */
#define FN_getkey                                0x5CDB  /* platform, u16 (void) */
#define FN_getkey_kbd                            0x5CEB  /* platform, mode 0 */
#define FN_getkey_kbd_joy_level                  0x5D01  /* platform, mode 2 */
#define FN_getkey_kbd_ctrl                       0x5D39  /* platform, internal */
#define FN_getkey_kbd_joy_edge                   0x5DE7  /* platform, mode 4 (used) */
#define FN_kbd_flush                             0x5E2C  /* platform, u16 (void) */
#define FN_timer_restore                         0x5E3D  /* platform, void (void) */
#define FN_timer_install_drive                   0x5E7F  /* platform, void (void) */
#define FN_timer_install_menu                    0x5E91  /* platform, void (void) */
#define FN_timer_install_div                     0x5EA9  /* platform, void (int unused, u16 divisor) */
#define FN_timer_install_common                  0x5EC2  /* platform, DX = divisor */
#define FN_timer_isr                             0x5F12  /* platform, INT 8 handler */
#define FN_snd_fetch                             0x5F9B  /* platform, internal */
#define FN_delay_ticks                           0x612E  /* platform, void (u16 n) */
#define FN_getkey_timeout                        0x614E  /* platform, u16 (u16 n) */
#define FN_gfx_set_text_colours                  0x6178  /* platform, void (u16 fg, u16 bg) */
#define FN_blit_copy_hot                         0x6189  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_copy_raw                         0x61AD  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_copy_own                         0x61CB  /* platform, void (u16 off, u16 seg) */
#define FN_gfx_set_text_cursor                   0x62DC  /* platform, void (s16 x, s16 y) */
#define FN_gfx_clear_clip                        0x62ED  /* platform, void (u8 colour) */
#define FN_gfx_dissolve                          0x634C  /* platform, void (u16 off, u16 seg, u8 phase) */
#define FN_getkey_until_deadline                 0x63FE  /* platform, u16 (void) */
#define FN_wait_deadline                         0x641B  /* platform, void (void) */
#define FN_set_deadline                          0x642E  /* platform, void (u16 ticks) */
#define FN_load_raw_archive                      0x643F  /* platform, far ptr (char *fname, u16 reserve) */
#define FN_gfx_free_buffer                       0x6599  /* platform, void (u16 doff, u16 dseg) */
#define FN_blit_or_hot                           0x65D1  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_or_own                           0x6613  /* platform, void (u16 off, u16 seg) */
#define FN_blit_and_hot                          0x6717  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_and_own                          0x6759  /* platform, void (u16 off, u16 seg) */
#define FN_blit_xor_hot                          0x6865  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_xor_own                          0x68A7  /* platform, void (u16 off, u16 seg) */
#define FN_blit_xor_clip_hot                     0x4C0C  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_and_clip_hot                     0x6B94  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_gfx_draw_line                         0x6D97  /* platform, void (s16 x0, s16 y0, s16 x1, s16 y1, u8 */
#define FN_snd_stop_oneshot                      0x7091  /* platform, void (void) */
#define FN_snd_off                               0x7097  /* platform, void (void) */
#define FN_snd_on                                0x709D  /* platform, void (void) */
#define FN_snd_oneshot_active                    0x70A3  /* platform, u8 (void) */
#define FN_snd_stop_all                          0x70A9  /* platform, void (void) */
#define FN_snd_set_loop                          0x70AF  /* platform, void (u16 off, u16 seg) */
#define FN_snd_play_oneshot                      0x70DF  /* platform, void (u16 off, u16 seg) */
#define FN_load_archive                          0x70FC  /* platform, far ptr (char *fname, u16 reserve) */
#define FN_input_set_mode                        0x72A5  /* platform, void (u16 mode) */
#define FN_gfx_grab_screen                       0x72B0  /* platform, void (s16 sx, s16 sy, s16 dx, s16 dy, s1 */
#define FN_rand8                                 0x731F  /* platform, u8 (void) */
#define FN_grab_into_sprite_hot                  0x733C  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_grab_into_sprite_raw                  0x7360  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_grab_into_sprite_own                  0x737E  /* platform, void (u16 off, u16 seg) */
#define FN_mem_init                              0x755B  /* platform, void (void) */
#define FN_herc_init                             0x7587  /* platform, void (void) */
#define FN_herc_shutdown                         0x75D7  /* platform, void (void) */
#define FN_crc8_b8                               0x7627  /* platform, u8 (u8 *buf, int len, u8 seed) */
#define FN_copy_protection_check                 0x7662  /* platform, int (void) */
#define FN_gfx_scroll_window                     0x5A54  /* platform, void (s16 x, s16 y, s16 w, s16 h, s16 ro */
#define FN_text_input_line                       0x7A6A  /* platform, int (char *buf, int maxlen, int x, int y */
#define FN_fatal                                 0x7C6D  /* platform, void (char *fmt, ...) */
#define FN_res_find_list                         0x7C89  /* platform, void (far arc, char *names, far ptr *out */
#define FN_draw_text_centered                    0x7CC9  /* platform, void (char *s, int y) */
#define FN_draw_rect_outline                     0x7CF2  /* platform, void (x0, y0, x1, y1, colour) */
#define FN_menu_key                              0x7D72  /* platform, int (void) */
#define FN_toupper_c                             0x7D9B  /* platform, int (char c) */
#define FN_joy_calibrate_screen                  0x7DB6  /* platform, void (void) */
#define FN_ticks_now                             0x7F8E  /* platform, u16 (void) */
#define FN_ticks_elapsed                         0x7F92  /* platform, u16 (u16 start) */
#define FN_draw_glyph                            0x8006  /* platform, void (int x, int y, int idx) */
#define FN_joy_read                              0x8023  /* platform, u8 (void) */
#define FN_cache_find                            0x8174  /* platform, u16 seg (char *fname) */
#define FN_cache_alloc                           0x81B2  /* platform, u16 seg (char *fname, u16 paras, u16 res */
#define FN_buf_alloc                             0x8234  /* platform, u16 seg (u16 paras) */
#define FN_buf_free                              0x8272  /* platform, void (u16 seg) */
#define FN_gfx_target_save                       0x82AB  /* platform, void (void) */
#define FN_gfx_target_restore                    0x82BF  /* platform, void (void) */
#define FN_mem_debug_dump                        0x82D3  /* platform, void (void) */
#define FN_gfx_get_target_ptr                    0x83CD  /* platform, u32 (void) */
#define FN_abort                                 0x83D7  /* platform */
#define FN_close                                 0x83EC  /* platform */
#define FN__astart                               0x8400  /* platform */
#define FN_fclose                                0x84AA  /* platform */
#define FN_fgets                                 0x854D  /* platform */
#define FN_fopen                                 0x85A5  /* platform */
#define FN_fprintf                               0x85CB  /* platform */
#define FN_fscanf                                0x8602  /* platform */
#define FN_free                                  0x8616  /* platform */
#define FN_malloc                                0x8624  /* platform */
#define FN_open                                  0x866A  /* platform */
#define FN_printf                                0x87BB  /* platform */
#define FN_srand                                 0x87F1  /* platform */
#define FN_rand                                  0x8802  /* platform */
#define FN_read                                  0x882E  /* platform */
#define FN_sprintf                               0x88F4  /* platform */
#define FN_sscanf                                0x8945  /* platform */
#define FN_strcmp                                0x897C  /* platform */
#define FN_strlen                                0x89B1  /* platform */
#define FN_strncpy                               0x89CC  /* platform */
#define FN__filbuf                               0x89F4  /* platform */
#define FN__flsbuf                               0x8AD6  /* platform */
#define FN__freebuf                              0x8C01  /* platform */
#define FN__openfile                             0x8C30  /* platform */
#define FN__stbuf                                0x8D33  /* platform */
#define FN__ftbuf                                0x8DD2  /* platform */
#define FN__nmalloc                              0x8E5B  /* platform */
#define FN__amlink                               0x8F3C  /* platform */
#define FN__amexpand                             0x8F76  /* platform */
#define FN__amallocbrk                           0x8F98  /* platform */
#define FN__nullcheck                            0x8FB7  /* platform */
#define FN_creat                                 0x8FD3  /* platform */
#define FN_umask                                 0x9046  /* platform */
#define FN__cinit                                0x9059  /* platform */
#define FN_exit                                  0x9108  /* platform */
#define FN__exit                                 0x911F  /* platform */
#define FN__ctermsub                             0x914B  /* platform */
#define FN__initterm                             0x9164  /* platform */
#define FN__dosret0                              0x9173  /* platform */
#define FN__dosretax                             0x917B  /* platform */
#define FN_fflush                                0x91BB  /* platform */
#define FN__input_B32F                           0x9223  /* platform */
#define FN__input_B698                           0x958C  /* platform */
#define FN_itoa                                  0x99F3  /* platform */
#define FN__NMSG_TEXT                            0x9A0E  /* platform */
#define FN__NMSG_WRITE                           0x9A3E  /* platform */
#define FN__output_BB73                          0x9A67  /* platform */
#define FN__output_BE03                          0x9CF7  /* platform */
#define FN__setargv                              0xA276  /* platform */
#define FN__setenvp                              0xA35B  /* platform */
#define FN_strcat                                0xA3C1  /* platform */
#define FN_strcpy                                0xA3F2  /* platform */
#define FN__getstream                            0xA417  /* platform */
#define FN_unlink                                0xA44E  /* platform */
#define FN_sbrk                                  0xA45B  /* platform */
#define FN__growseg                              0xA4C9  /* platform */
#define FN__chkstk                               0xA51F  /* platform */
#define FN_isatty                                0xA538  /* platform */
#define FN_ungetc                                0xA5A6  /* platform */
#define FN_write                                 0xA600  /* platform */
#define FN_flushall                              0xA73D  /* platform */
#define FN__aNldiv                               0xA76E  /* platform */
#define FN__aNlmul                               0xA811  /* platform */
#define FN__aNlshl                               0xA83D  /* platform */
#define FN__aNlshr                               0xA848  /* platform */
#define FN__aNaldiv                              0xA853  /* platform */
#define FN__aNalshl                              0xA875  /* platform */

#else
/* ---- TDEGA.EXE */

/* DGROUP globals (offsets for DSB/DSW/DSS/DSL) */
#define DS_str_herc                              0x0040  /* platform, char[] */
#define DS_demo_mode                             0x0084  /* simulation, u16 */
#define DS_g_carAutoSelected                     0x0086  /* game_flow, int16 */
#define DS_g_numCars                             0x0088  /* game_flow, int16 */
#define DS_herc_mode                             0x008A  /* platform, u16 */
#define DS_pal_game                              0x00CC  /* platform, u8[17] */
#define DS_LAUNCH_PASSWORD                       0x00DE  /* game_flow, char[21] */
#define DS_g_introArchive                        0x0118  /* game_flow, far ptr */
#define DS_STAGE_SCORE_FACTOR                    0x029E  /* game_flow, int16[5] */
#define DS_STAGE_PAR_TIME                        0x02A8  /* game_flow, int16[5] */
#define DS_STAGE_CONST_B                         0x02B2  /* game_flow, int16[5] */
#define DS_MSG_TABLES                            0x077A  /* game_flow, near char*[33] */
#define DS_GAS_SIGN_NAMES                        0x07BC  /* game_flow, near char*[4] */
#define DS_road_buf_desc                         0x0890  /* platform, far ptr */
#define DS_road_buf_sprite                       0x0894  /* scene_render, far ptr */
#define DS_road_buf_rowtab                       0x0898  /* scene_render, u16 */
#define DS_buf_desc_b                            0x089A  /* platform, far ptr */
#define DS_inst_buf_sprite                       0x089E  /* scene_render, far ptr */
#define DS_inst_x                                0x08A2  /* scene_render, u16 */
#define DS_inst_y                                0x08A4  /* scene_render, u16 */
#define DS_inst_h                                0x08A6  /* scene_render, u16 */
#define DS_inst_wbytes                           0x08A8  /* scene_render, u16 */
#define DS_speedo_pivot                          0x08AA  /* scene_render, 2xu16 */
#define DS_tach_pivot                            0x08AE  /* scene_render, 2xu16 */
#define DS_buf_desc_c                            0x08B2  /* platform, far ptr */
#define DS_gbox_buf_sprite                       0x08B6  /* scene_render, far ptr */
#define DS_gbox_x                                0x08BA  /* scene_render, u16 */
#define DS_gbox_y                                0x08BC  /* scene_render, u16 */
#define DS_gearbox_display_toggle                0x08BE  /* simulation, u8 */
#define DS_gearbox_prev                          0x08BF  /* scene_render, u8 */
#define DS_marker_save_sprite                    0x08C0  /* scene_render, sprite hdr */
#define DS_marker_save_x                         0x08F0  /* scene_render, s16 */
#define DS_marker_save_y                         0x08F2  /* scene_render, s16 */
#define DS_grind_timer                           0x08F4  /* simulation, u8 */
#define DS_road_pos                              0x0906  /* simulation, u16 */
#define DS_road_pos_prev                         0x0908  /* simulation, u16 */
#define DS_yaw_lateral                           0x090A  /* simulation, i16 */
#define DS_view_heading                          0x090C  /* simulation, i16 */
#define DS_unused_090e                           0x090E  /* simulation, i16 */
#define DS_car_x                                 0x0910  /* simulation, i16 */
#define DS_sub_unit                              0x0912  /* simulation, i16 */
#define DS_steer_angle                           0x0914  /* simulation, i16 */
#define DS_cur_ratio                             0x0916  /* simulation, u16 */
#define DS_road_curve                            0x0919  /* simulation, i16 */
#define DS_rpm                                   0x091B  /* scene_render, u16 */
#define DS_rpm_smooth                            0x091D  /* simulation, u16 */
#define DS_dash_timer                            0x091F  /* simulation, u8 */
#define DS_gate_node                             0x0920  /* simulation, u8 */
#define DS_gate_shift_mode                       0x0921  /* simulation, u8 */
#define DS_gearbox_dirty                         0x0922  /* simulation, u8 */
#define DS_gauges_dirty                          0x0923  /* simulation, u8 */
#define DS_skidding                              0x0924  /* simulation, u8 */
#define DS_accel_mag                             0x0925  /* simulation, u16 */
#define DS_g_carSpeedFixed                       0x0927  /* game_flow, int16 */
#define DS_g_stageEvent                          0x0929  /* game_flow, uint8 */
#define DS_stage_end_pos                         0x092A  /* simulation, u16 */
#define DS_proj_cx_main                          0x092C  /* scene_render, s16 */
#define DS_proj_horizon_main                     0x092E  /* scene_render, s16 */
#define DS_proj_cx_mirror                        0x0930  /* scene_render, s16 */
#define DS_proj_y_mirror_off                     0x0932  /* scene_render, s16 */
#define DS_old_int0_vector                       0x0934  /* simulation, far ptr */
#define DS_ending_shown                          0x0938  /* simulation, u8 */
#define DS_pit_tick_count                        0x093A  /* simulation, u16 */
#define DS_clock_running                         0x093C  /* simulation, u8 */
#define DS_oncoming_count                        0x0941  /* simulation, u8 */
#define DS_samedir_count                         0x0942  /* simulation, u8 */
#define DS_r_traffic_count_l                     0x0943  /* scene_render, u8 */
#define DS_r_traffic_count_r                     0x0944  /* scene_render, u8 */
#define DS_oncoming_list                         0x0945  /* simulation, ent8[5] */
#define DS_samedir_list                          0x096D  /* simulation, ent8[5] */
#define DS_spill_slot                            0x0995  /* simulation, ent8 */
#define DS_radar_trap                            0x099D  /* simulation, ent8 */
#define DS_hazard                                0x09A5  /* simulation, ent8 */
#define DS_r_traffic_slots                       0x09AD  /* scene_render, 13x8 bytes */
#define DS_snapshot_radar_trap_pos               0x0A05  /* simulation, u16 */
#define DS_r_hazard_slot                         0x0A0D  /* scene_render, 8 bytes */
#define DS_trap_speed_table                      0x0A15  /* simulation, u16[3] */
#define DS_traffic_speed_table                   0x0A1B  /* simulation, u16[3] */
#define DS_speed_limit_idx                       0x0A21  /* simulation, u16 */
#define DS_cop_state                             0x0A23  /* simulation, u8 */
#define DS_r_cop_state                           0x0A24  /* scene_render, u8 */
#define DS_cop_speed                             0x0A25  /* simulation, u16 */
#define DS_cop_timer                             0x0A27  /* simulation, u8 */
#define DS_cop_tail_timer                        0x0A28  /* simulation, u8 */
#define DS_cop_lateral                           0x0A29  /* simulation, u16 */
#define DS_cop_sub                               0x0A2B  /* simulation, u16 */
#define DS_cop_pos                               0x0A2D  /* simulation, u16 */
#define DS_cop_block_idx                         0x0A2F  /* simulation, u8 */
#define DS_r_cop_pos                             0x0A30  /* scene_render, u16 */
#define DS_r_cop_lane                            0x0A32  /* scene_render, s16 */
#define DS_r_cop_sub                             0x0A34  /* scene_render, s16 */
#define DS_cop_state_jump_table                  0x0A36  /* simulation, u16[8] */
#define DS_cop_lane_curve                        0x0A46  /* simulation, u8[49] */
#define DS_fire_held                             0x0A77  /* simulation, u8 */
#define DS_gear                                  0x0A78  /* simulation, u8 */
#define DS_throttle_in                           0x0A79  /* simulation, i8 */
#define DS_steer_in                              0x0A7A  /* simulation, i8 */
#define DS_knob_anim                             0x0A7B  /* simulation, u8 */
#define DS_shift_latch                           0x0A7C  /* simulation, u8 */
#define DS_knob_x                                0x0A7D  /* simulation, u16 */
#define DS_knob_y                                0x0A7F  /* scene_render, s16 */
#define DS_knob_target_x                         0x0A81  /* simulation, u16 */
#define DS_unit_advanced                         0x0A85  /* simulation, u8 */
#define DS_steer_dir_table                       0x0A86  /* simulation, i8[9] */
#define DS_throttle_dir_table                    0x0AB3  /* simulation, i8[9] */
#define DS_gear_delta_table                      0x0ABC  /* simulation, i8[9] */
#define DS_drag_table                            0x0AC5  /* simulation, u8[64] */
#define DS_SONG_INGAME                           0x0B05  /* game_flow, bytecode */
#define DS_xroada_handles                        0x0F9F  /* scene_render, 117 far ptrs */
#define DS_spr_govr                              0x102F  /* game_flow, far ptr */
#define DS_spr_gvrm                              0x1033  /* game_flow, far ptr */
#define DS_spr_deal                              0x1037  /* game_flow, far ptr */
#define DS_spr_note                              0x103B  /* game_flow, far ptr */
#define DS_spr_tick                              0x103F  /* game_flow, far ptr */
#define DS_xroadb_handles                        0x1173  /* scene_render, 50 far ptrs */
#define DS_xroadc_handles                        0x123B  /* scene_render, 82 far ptrs */
#define DS_car_handles                           0x1383  /* scene_render, 25 far ptrs */
#define DS_spr_mirr                              0x13BB  /* game_flow, far ptr */
#define DS_spr_roof                              0x13DB  /* game_flow, far ptr */
#define DS_digit_handles                         0x13E7  /* scene_render, 15 far ptrs */
#define DS_int0_handler                          0x1423  /* scene_render, code */
#define DS_road_anim_counter                     0x1433  /* simulation, u8 */
#define DS_dash_counter                          0x1434  /* scene_render, u8 */
#define DS_mirror_rows_done                      0x1435  /* scene_render, u16 */
#define DS_crest_sy                              0x1437  /* scene_render, u8 */
#define DS_cached_top_sy                         0x1439  /* scene_render, u8 */
#define DS_cached_top_row                        0x143B  /* scene_render, u16 */
#define DS_obj_scale                             0x143D  /* scene_render, u16 */
#define DS_xclip_px                              0x143F  /* scene_render, u16 */
#define DS_xclip_bytes                           0x1441  /* scene_render, u16 */
#define DS_cached_top_row_mirror                 0x1443  /* scene_render, u16 */
#define DS_wheel_state                           0x1445  /* scene_render, u8 */
#define DS_marker_saved                          0x1446  /* scene_render, u8 */
#define DS_cop_light_timer                       0x1447  /* simulation, u16 */
#define DS_mask_left_from_bit                    0x1449  /* scene_render, u8[8] */
#define DS_mask_right_to_bit                     0x1451  /* scene_render, u8[8] */
#define DS_mask_single_pixel                     0x1459  /* scene_render, u8[8] */
#define DS_span_bit                              0x1463  /* scene_render, u16 */
#define DS_span_ol                               0x1465  /* scene_render, s16[111] */
#define DS_span_l                                0x1543  /* scene_render, s16[111] */
#define DS_span_r                                0x1621  /* scene_render, s16[111] */
#define DS_span_or                               0x16FF  /* scene_render, s16[111] */
#define DS_span_ol_mirror                        0x17DD  /* scene_render, s16[18] */
#define DS_span_l_mirror                         0x1801  /* scene_render, s16[18] */
#define DS_span_r_mirror                         0x1825  /* scene_render, s16[18] */
#define DS_span_or_mirror                        0x1849  /* scene_render, s16[18] */
#define DS_walk_ptr                              0x186D  /* scene_render, u16 */
#define DS_r_road_ptr                            0x186F  /* scene_render, u16 */
#define DS_r_subpos                              0x1871  /* scene_render, s16 */
#define DS_heading_acc                           0x1873  /* scene_render, s16 */
#define DS_slope_acc                             0x1875  /* scene_render, s16 */
#define DS_row_X                                 0x1877  /* scene_render, s16[40] */
#define DS_row_Y                                 0x18C7  /* scene_render, s16[40] */
#define DS_row_X_mirror                          0x1917  /* scene_render, s16[25] */
#define DS_row_Y_mirror                          0x1967  /* scene_render, s16[25] */
#define DS_cut_x                                 0x19B7  /* scene_render, s16 */
#define DS_cut_sy                                0x19B9  /* scene_render, u16 */
#define DS_cut_row                               0x19BB  /* scene_render, u16 */
#define DS_cut_row_mirror                        0x19BD  /* scene_render, u16 */
#define DS_cut_top_sy                            0x19BF  /* scene_render, u8 */
#define DS_cut_top_sy_mirror                     0x19C1  /* scene_render, u8 */
#define DS_min_ol                                0x19C3  /* scene_render, s16 */
#define DS_min_ol_sy                             0x19C5  /* scene_render, u8 */
#define DS_first_changed_row                     0x19C7  /* scene_render, u16 */
#define DS_prev_row_limit                        0x19C9  /* scene_render, u16 */
#define DS_row_limit_main                        0x19CB  /* scene_render, u16 */
#define DS_top_sy                                0x19CD  /* scene_render, u8 */
#define DS_top_row                               0x19CF  /* scene_render, u16 */
#define DS_span_clamp_min                        0x19D1  /* scene_render, s16 */
#define DS_span_clamp_max                        0x19D3  /* scene_render, s16 */
#define DS_cut_x_mirror                          0x19D5  /* scene_render, s16 */
#define DS_cut_sy_mirror                         0x19D7  /* scene_render, u16 */
#define DS_min_ol_mirror                         0x19D9  /* scene_render, s16 */
#define DS_min_ol_sy_mirror                      0x19DB  /* scene_render, u8 */
#define DS_row_limit_mirror                      0x19DD  /* scene_render, u16 */
#define DS_top_sy_mirror                         0x19DF  /* scene_render, u8 */
#define DS_top_row_mirror                        0x19E1  /* scene_render, u16 */
#define DS_row_ol                                0x19E3  /* scene_render, s16[40] */
#define DS_row_l                                 0x1A33  /* scene_render, s16[40] */
#define DS_row_r                                 0x1A83  /* scene_render, s16[40] */
#define DS_row_or                                0x1AD3  /* scene_render, s16[40] */
#define DS_row_cx                                0x1B23  /* scene_render, s16[40] */
#define DS_row_sy                                0x1B73  /* scene_render, u8 at even offsets */
#define DS_row_obj                               0x1D03  /* scene_render, u8 at even offsets */
#define DS_row_ol_mirror                         0x1D53  /* scene_render, s16[25] */
#define DS_row_l_mirror                          0x1D8F  /* scene_render, s16[25] */
#define DS_row_r_mirror                          0x1DCB  /* scene_render, s16[25] */
#define DS_row_or_mirror                         0x1E07  /* scene_render, s16[25] */
#define DS_row_cx_mirror                         0x1E43  /* scene_render, s16[25] */
#define DS_row_sy_mirror                         0x1E7F  /* scene_render, u8 at even offsets */
#define DS_row_obj_mirror                        0x1FAB  /* scene_render, u8 at even offsets */
#define DS_cur_curve                             0x203B  /* scene_render, u8 */
#define DS_roadside_pattern                      0x203E  /* scene_render, u16[16] */
#define DS_engine_note_div_table                 0x2077  /* simulation, u16[151] */
#define DS_road_halfwidth_q4                     0x21A5  /* scene_render, u16[40] */
#define DS_traffic_scale_main                    0x21F5  /* scene_render, u8[40] */
#define DS_traffic_scale_mirror                  0x221E  /* scene_render, u8[25] */
#define DS_row_depth_Z                           0x2247  /* scene_render, u16[40] */
#define DS_sinq_table                            0x2297  /* simulation, u8[91] */
#define DS_sine_x15                              0x22F2  /* scene_render, u16[91] */
#define DS_wheel_sin90                           0x23A8  /* scene_render, u8[60] */
#define DS_wheel_cos90                           0x23E4  /* scene_render, u8[61] */
#define DS_persp_T                               0x2420  /* scene_render, u16[91] */
#define DS_tan256                                0x24D6  /* scene_render, u16[46] */
#define DS_crack_counts                          0x2532  /* scene_render, u8[7] */
#define DS_crack_ptrs                            0x2539  /* scene_render, u16[7] */
#define DS_car_num_gears                         0x268F  /* simulation, u8 */
#define DS_car_rpm_limit                         0x2693  /* simulation, u16 */
#define DS_car_grip_limit                        0x2697  /* simulation, i16 */
#define DS_car_skid_drift                        0x2699  /* simulation, u8 */
#define DS_car_gear_ratio                        0x26A1  /* simulation, u16[7] */
#define DS_car_knob_xy                           0x26AF  /* simulation, u16[7][2] */
#define DS_car_gate_next                         0x270B  /* simulation, u8[144] */
#define DS_car_node_gear                         0x279B  /* simulation, u8[16] */
#define DS_car_torque                            0x27AB  /* simulation, u8[80] */
#define DS_road_record_curve                     0x2B71  /* simulation, u8 */
#define DS_fill_left_mask                        0x636C  /* platform, u8[8] */
#define DS_fill_right_mask                       0x6374  /* platform, u8[8] */
#define DS_pal_default                           0x637C  /* platform, u8[17] */
#define DS_joy_dir_map                           0x63A8  /* platform, u8[16] */
#define DS_ext_scan_dir_map                      0x63B8  /* platform, u8[12] */
#define DS_digit_dir_map                         0x63C4  /* platform, u8[10] */
#define DS_kbd_shift_btn                         0x63F0  /* platform, u8 */
#define DS_joy_menu_scan                         0x63F2  /* platform, u16[16] */
#define DS_joy_menu_last                         0x6420  /* platform, u16 */
#define DS_input_mode                            0x6422  /* platform, u16 */
#define DS_modal_pause                           0x6424  /* platform, u8 */
#define DS_old_int8                              0x6426  /* platform, far ptr */
#define DS_tick_count                            0x642A  /* platform, u16 */
#define DS_snd_ptr                               0x642C  /* platform, seg (642C) : off (642E) */
#define DS_snd_loop_ptr                          0x6430  /* platform, seg (6430) : off (6432) */
#define DS_chain_reload                          0x6434  /* platform, u16 */
#define DS_chain_count                           0x6436  /* platform, s16 */
#define DS_note_left                             0x6438  /* platform, u16 */
#define DS_note_cut                              0x643A  /* platform, u16 */
#define DS_snd_shift                             0x643C  /* platform, u8 */
#define DS_snd_playing                           0x643D  /* platform, u8 */
#define DS_snd_flags                             0x643E  /* platform, u8 */
#define DS_chain_enable                          0x643F  /* platform, u8 */
#define DS_loop_cnt                              0x6440  /* platform, s16[3] */
#define DS_loop_start                            0x6446  /* platform, u16[3] */
#define DS_loop_end                              0x644C  /* platform, u16[3] */
#define DS_note_div                              0x6452  /* platform, u16[0x5E] */
#define DS_note_div_engine                       0x64FC  /* platform, u16 */
#define DS_note_div_skid                         0x64FE  /* platform, u16 */
#define DS_note_div_beep                         0x6500  /* platform, u16 */
#define DS_deadline_start                        0x650C  /* platform, u16 */
#define DS_deadline_len                          0x650E  /* platform, u16 */
#define DS_rand8_idx                             0x6520  /* platform, u16 */
#define DS_rand8_tab                             0x6522  /* platform, u8[256] */
#define DS_herc_crtc_gfx                         0x6642  /* platform, u8[12] */
#define DS_herc_crtc_text                        0x664E  /* platform, u8[12] */
#define DS_joy_enabled                           0x66E8  /* platform, u8 */
#define DS_joy_calibrated                        0x66E9  /* platform, u8 */
#define DS_calib_sq_x                            0x66EA  /* platform, u16[9] */
#define DS_calib_sq_y                            0x66FC  /* platform, u16[9] */
#define DS_text_fg                               0x690E  /* platform, u16 */
#define DS_text_bg                               0x6910  /* platform, u16 */
#define DS_text_margin_x                         0x6912  /* platform, u16 */
#define DS_text_x                                0x6914  /* platform, u16 */
#define DS_text_y                                0x6916  /* platform, u16 */
#define DS_text_glyph_h                          0x691A  /* platform, u16 */
#define DS_text_font                             0x691C  /* platform, far ptr */
#define DS_text_adv_x                            0x6920  /* platform, u16 */
#define DS_text_adv_y                            0x6922  /* platform, u16 */
#define DS_text_enabled                          0x6924  /* platform, u16 */
#define DS_lzw_tables                            0x6A3C  /* platform, u16 */
#define DS_joy_x                                 0x6A3E  /* platform, u16 */
#define DS_joy_port_pre                          0x6A42  /* platform, u8 */
#define DS_joy_result                            0x6A43  /* platform, u8 */
#define DS_joy_xmin                              0x6A44  /* platform, u16 */
#define DS_joy_xover_min                         0x6A48  /* platform, u16 */
#define DS_joy_xlo                               0x6A4C  /* platform, u16 */
#define DS_joy_ymin                              0x6A50  /* platform, u16 */
#define DS_gfx_target_save_area                  0x6AC4  /* platform, u16[24] */
#define DS_font_ptrs                             0x6E2C  /* platform, u16[256] */
#define DS_lzw_tab_ptrs                          0x746C  /* platform, u16 ×3 (746C/7470/748C) */
#define DS_rle_state                             0x7478  /* platform, u16 */
#define DS_pack_inptr                            0x78E0  /* platform, u16 */
#define DS_g_showroomCarSpr                      0x78E2  /* game_flow, far ptr */
#define DS_g_lives                               0x78E6  /* game_flow, int16 */
#define DS_g_songIntro                           0x78E8  /* game_flow, far ptr */
#define DS_g_avgSpeed                            0x78EC  /* game_flow, int16 */
#define DS_g_carSBArchive                        0x78EE  /* game_flow, far ptr */
#define DS_g_carNames                            0x78F2  /* game_flow, near char*[10] */
#define DS_g_songCarSel                          0x7906  /* game_flow, far ptr */
#define DS_g_selectedCar                         0x790A  /* game_flow, int16 */
#define DS_g_resultLineCount                     0x790C  /* game_flow, int16 */
#define DS_unpacked_len                          0x790E  /* platform, u32 */
#define DS_g_scrollDelay                         0x7B12  /* game_flow, int16 */
#define DS_mem_bot                               0x7B14  /* platform, u16 seg */
#define DS_g_stage                               0x7B16  /* game_flow, int16 */
#define DS_out_count                             0x7B18  /* platform, u32 */
#define DS_g_xroadA                              0x7B1C  /* game_flow, far ptr */
#define DS_g_xroadB                              0x7B20  /* game_flow, far ptr */
#define DS_mem_low                               0x7B24  /* platform, u16 seg */
#define DS_g_xroadC                              0x7B26  /* game_flow, far ptr */
#define DS_g_songHiScore                         0x7B2A  /* game_flow, far ptr */
#define DS_packed_left                           0x7B2E  /* platform, u32 */
#define DS_g_carArchive                          0x7B32  /* game_flow, far ptr */
#define DS_mem_top                               0x7D36  /* platform, u16 seg */
#define DS_cache_slots                           0x7D38  /* platform, 16 B × 30 */
#define DS_mem_high                              0x7F18  /* platform, u16 seg */
#define DS_page_buf_desc                         0x7F1A  /* platform, far ptr */
#define DS_buf_slots                             0x7F1E  /* platform, 4 B × 8 */
#define DS_pack_inbuf                            0x7F3E  /* platform, u16 */
#define DS_g_stageConstB                         0x7F40  /* game_flow, int16 */
#define DS_pack_fd                               0x7F42  /* platform, u16 */
#define DS_g_tooSlow                             0x7F44  /* game_flow, int16 */
#define DS_g_sbArchiveName                       0x7F46  /* game_flow, char[30] */
#define DS_g_carNameBuf                          0x7F64  /* game_flow, char[] */
#define DS_g_songGas                             0x8090  /* game_flow, far ptr */
#define DS_g_parTime                             0x8094  /* game_flow, int16 */
#define DS_pack_inpos                            0x8096  /* platform, u16 */
#define DS_g_totalScore                          0x8098  /* game_flow, int32 */
#define DS_pack_outptr                           0x809C  /* platform, huge ptr */
#define DS_in_count                              0x80A0  /* platform, u32 */
#define DS_g_stageTime                           0x80A4  /* game_flow, int16 */
#define DS_g_resultTextY                         0x80A6  /* game_flow, int16 */

/* Original functions (image offsets) */
#define FN_main                                  0x0010  /* game_flow, int main(int argc char **argv) */
#define FN_load_cars_txt                         0x0243  /* game_flow, void(void) */
#define FN_play_again_menu                       0x02BF  /* game_flow, int(void) */
#define FN_run_intro                             0x037A  /* game_flow, int(void) */
#define FN_intro_accolade                        0x03F4  /* game_flow, int(void) */
#define FN_intro_testdrive_car                   0x051B  /* game_flow, int(void) */
#define FN_intro_testdrive_logo                  0x0792  /* game_flow, int(void) */
#define FN_car_select                            0x098C  /* game_flow, int(void) */
#define FN_show_car                              0x0AB2  /* game_flow, void(int idx int dir) */
#define FN_showroom_drive_away                   0x0D75  /* game_flow, void(int idx) */
#define FN_read_line_strip                       0x1000  /* game_flow, void(char *buf int n FILE *f) */
#define FN_run_game                              0x1030  /* game_flow, int(void) */
#define FN_stage_score                           0x125D  /* game_flow, long(void) */
#define FN_high_scores                           0x12DB  /* game_flow, int(long newScore) */
#define FN_scores_load                           0x1369  /* game_flow, void(char *names long *scores char *cars */
#define FN_scores_enter_name                     0x1482  /* game_flow, void(long score int car char *names long */
#define FN_scores_save                           0x162E  /* game_flow, void(char *names long *scores char *cars */
#define FN_scores_show                           0x16D7  /* game_flow, int(char *names long *scores char *cars) */
#define FN_credits_show                          0x186E  /* game_flow, int(void) */
#define FN_stage_results                         0x1993  /* game_flow, void(long score) */
#define FN_results_text                          0x1B36  /* game_flow, void(long score) */
#define FN_results_add_line                      0x1CFA  /* game_flow, void(const char *s) */
#define FN_results_scroll                        0x1D20  /* game_flow, void(void) */
#define FN_run_stage                             0x1DC0  /* game_flow, int(void) */
#define FN_stage_init_road_ptr                   0x1F4E  /* scene_render, void(void) */
#define FN_wait_fire_button                      0x1F7B  /* scene_render, void(void) */
#define FN_reset_car_state                       0x1F93  /* scene_render, void(void) */
#define FN_snapshot_sim_state                    0x2013  /* scene_render, void(void) */
#define FN_project_road_main                     0x2054  /* scene_render, void(void) */
#define FN_proj_x_main                           0x23F2  /* scene_render, AX=f(BX X;DX Z) */
#define FN_proj_y_main                           0x2421  /* scene_render, AX=f(BX X;DX Z;CX Y) */
#define FN_project_road_mirror                   0x2478  /* scene_render, void(void) */
#define FN_proj_x_mirror                         0x282C  /* scene_render, AX=f(BX X;DX Z) */
#define FN_proj_y_mirror                         0x285B  /* scene_render, AX=f(BX X;DX Z;CX Y) */
#define FN_draw_road_main                        0x28C5  /* scene_render, void(void) */
#define FN_fill_road_scanlines_main              0x2DEE  /* scene_render, void(void) */
#define FN_fill_span_to                          0x2E8B  /* scene_render, ZF=f(AX end;DX bytepos;DI;ES) */
#define FN_fill_scenery_above_road               0x2EDC  /* scene_render, void(void) */
#define FN_draw_road_mirror                      0x2F7A  /* scene_render, void(void) */
#define FN_fill_road_scanlines_mirror            0x3306  /* scene_render, void(void) */
#define FN_fill_span_to_mirror                   0x339E  /* scene_render, ZF=f(AX end;DX;DI;ES) */
#define FN_draw_mirror_background                0x33FB  /* scene_render, void(void) */
#define FN_draw_buffer_overlays                  0x349D  /* scene_render, void(void) */
#define FN_draw_gear_box                         0x351A  /* scene_render, void(void) */
#define FN_draw_dashboard_dynamic                0x35C6  /* scene_render, void(void) */
#define FN_draw_digit                            0x38CD  /* scene_render, (BL digit;DX x) */
#define FN_dealership_ending                     0x38EB  /* scene_render, void(void) */
#define FN_crash_windscreen_sequence             0x392C  /* scene_render, void(void) */
#define FN_sin_deg                               0x39EB  /* scene_render, AX=f(AX deg) */
#define FN_atan_lookup                           0x3A18  /* scene_render, AX=f(AX ratio256) */
#define FN_interp_edge_span                      0x3A37  /* scene_render, (AX a;BX b;CL n;DL n;DI dst) */
#define FN_select_screen                         0x3AC2  /* scene_render, void(void) */
#define FN_select_road_buffer                    0x3ACE  /* scene_render, void(void) */
#define FN_present_road_buffer                   0x3AF7  /* scene_render, void(void) */
#define FN_sim_isr_exit_jmp                      0x3B1C  /* simulation, label */
#define FN_sim_timer_isr                         0x3B1F  /* simulation, interrupt */
#define FN_sim_input_charkey                     0x3BB4  /* simulation, label */
#define FN_sim_tick                              0x3BEA  /* simulation, label */
#define FN_sim_input_direction                   0x3CB8  /* simulation, label */
#define FN_sim_steering                          0x3D7D  /* simulation, label */
#define FN_sim_shift_knob_anim                   0x3DDB  /* simulation, label */
#define FN_sim_engine                            0x3EAA  /* simulation, label */
#define FN_sim_update_rpm                        0x3FAD  /* simulation, u16 DX(void) */
#define FN_sim_motion                            0x3FE8  /* simulation, label */
#define FN_sim_advance_unit                      0x40FE  /* simulation, label */
#define FN_sim_lookahead                         0x4241  /* simulation, label */
#define FN_sim_traffic_update                    0x427F  /* simulation, label */
#define FN_sim_cop_fsm                           0x438A  /* simulation, label */
#define FN_sim_object_cleanup                    0x455F  /* simulation, label */
#define FN_sim_spawn_object                      0x467D  /* simulation, label */
#define FN_stage_enter_install_isr               0x4792  /* simulation, void(void) */
#define FN_car_data_ptr                          0x493D  /* simulation, u16(void) */
#define FN_gfx_fill_rect                         0x4941  /* platform, void (s16 x, s16 y, s16 w, s16 h, u8 col */
#define FN_gfx_clear_screen                      0x4B98  /* platform, void (u8 colour) */
#define FN_gfx_draw_text                         0x4BD0  /* platform, void (char *s, s16 x, s16 y) */
#define FN_gfx_draw_text_at_cursor               0x4BE7  /* platform, void (char *s) */
#define FN_gfx_set_border                        0x4D78  /* platform, void (u8 colour) */
#define FN_gfx_set_palette                       0x4D84  /* platform, void (u16 ds_table) */
#define FN_gfx_init_ega                          0x4D96  /* platform, void (void) */
#define FN_blit_or_clip_hot                      0x4DF1  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_or_clip_raw                      0x4E05  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_or_clip_own                      0x4E19  /* platform, void (u16 off, u16 seg) */
#define FN_gfx_set_clip                          0x50A1  /* platform, void (u16 doff, u16 dseg, s16 x0, s16 x1 */
#define FN_gfx_shutdown                          0x50FE  /* platform, void (void) */
#define FN_gfx_select_target                     0x5128  /* platform, void (u16 doff, u16 dseg) */
#define FN_gfx_create_buffer                     0x5150  /* platform, far desc (u16 w_bytes, u16 h, u16 plane_ */
#define FN_input_poll_drive                      0x5C24  /* platform, u16 (void) */
#define FN_blit_copy_clip_hot                    0x5D84  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_copy_clip_raw                    0x5DB6  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_copy_clip_own                    0x5DE2  /* platform, void (u16 off, u16 seg) */
#define FN_res_find                              0x6762  /* platform, far ptr (u16 aoff, u16 aseg, char *name4 */
#define FN_getkey_wait                           0x67DD  /* platform, u16 (void) */
#define FN_getkey                                0x67E8  /* platform, u16 (void) */
#define FN_getkey_kbd                            0x67F8  /* platform, mode 0 */
#define FN_getkey_kbd_joy_level                  0x680E  /* platform, mode 2 */
#define FN_getkey_kbd_ctrl                       0x6846  /* platform, internal */
#define FN_getkey_kbd_joy_edge                   0x68F4  /* platform, mode 4 (used) */
#define FN_kbd_flush                             0x6939  /* platform, u16 (void) */
#define FN_timer_restore                         0x694A  /* platform, void (void) */
#define FN_timer_install_drive                   0x698C  /* platform, void (void) */
#define FN_timer_install_menu                    0x699E  /* platform, void (void) */
#define FN_timer_install_div                     0x69B6  /* platform, void (int unused, u16 divisor) */
#define FN_timer_install_common                  0x69CF  /* platform, DX = divisor */
#define FN_timer_isr                             0x6A1F  /* platform, INT 8 handler */
#define FN_snd_fetch                             0x6AA8  /* platform, internal */
#define FN_delay_ticks                           0x6C3B  /* platform, void (u16 n) */
#define FN_getkey_timeout                        0x6C5B  /* platform, u16 (u16 n) */
#define FN_gfx_set_text_colours                  0x6C85  /* platform, void (u16 fg, u16 bg) */
#define FN_blit_copy_hot                         0x6CBE  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_copy_raw                         0x6CF0  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_copy_own                         0x6D1C  /* platform, void (u16 off, u16 seg) */
#define FN_gfx_set_text_cursor                   0x74E3  /* platform, void (s16 x, s16 y) */
#define FN_gfx_clear_clip                        0x74F4  /* platform, void (u8 colour) */
#define FN_gfx_dissolve                          0x768B  /* platform, void (u16 off, u16 seg, u8 phase) */
#define FN_getkey_until_deadline                 0x7864  /* platform, u16 (void) */
#define FN_wait_deadline                         0x7881  /* platform, void (void) */
#define FN_set_deadline                          0x7894  /* platform, void (u16 ticks) */
#define FN_load_raw_archive                      0x78A5  /* platform, far ptr (char *fname, u16 reserve) */
#define FN_gfx_free_buffer                       0x79FF  /* platform, void (u16 doff, u16 dseg) */
#define FN_blit_or_hot                           0x7A37  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_or_raw                           0x7A4B  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_or_own                           0x7A5F  /* platform, void (u16 off, u16 seg) */
#define FN_blit_and_hot                          0x7C3B  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_and_raw                          0x7C4F  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_and_own                          0x7C63  /* platform, void (u16 off, u16 seg) */
#define FN_blit_xor_hot                          0x7E54  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_xor_raw                          0x7E68  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_xor_own                          0x7E7C  /* platform, void (u16 off, u16 seg) */
#define FN_blit_xor_clip_hot                     0x8058  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_xor_clip_raw                     0x806C  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_xor_clip_own                     0x8080  /* platform, void (u16 off, u16 seg) */
#define FN_blit_and_clip_hot                     0x8308  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_and_clip_raw                     0x831C  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_blit_and_clip_own                     0x8330  /* platform, void (u16 off, u16 seg) */
#define FN_gfx_draw_line                         0x85D5  /* platform, void (s16 x0, s16 y0, s16 x1, s16 y1, u8 */
#define FN_snd_stop_oneshot                      0x89F0  /* platform, void (void) */
#define FN_snd_off                               0x89F6  /* platform, void (void) */
#define FN_snd_on                                0x89FC  /* platform, void (void) */
#define FN_snd_oneshot_active                    0x8A02  /* platform, u8 (void) */
#define FN_snd_stop_all                          0x8A08  /* platform, void (void) */
#define FN_snd_set_loop                          0x8A0E  /* platform, void (u16 off, u16 seg) */
#define FN_snd_play_oneshot                      0x8A3E  /* platform, void (u16 off, u16 seg) */
#define FN_load_archive                          0x8A5B  /* platform, far ptr (char *fname, u16 reserve) */
#define FN_input_set_mode                        0x8AFD  /* platform, void (u16 mode) */
#define FN_gfx_grab_screen                       0x8B08  /* platform, void (s16 sx, s16 sy, s16 dx, s16 dy, s1 */
#define FN_rand8                                 0x8BAF  /* platform, u8 (void) */
#define FN_grab_into_sprite_hot                  0x8BDC  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_grab_into_sprite_raw                  0x8C00  /* platform, void (u16 off, u16 seg, s16 x, s16 y) */
#define FN_grab_into_sprite_own                  0x8C1E  /* platform, void (u16 off, u16 seg) */
#define FN_mem_init                              0x8CC0  /* platform, void (void) */
#define FN_herc_init                             0x8CEC  /* platform, void (void) */
#define FN_herc_shutdown                         0x8D3C  /* platform, void (void) */
#define FN_crc8_b8                               0x8D8C  /* platform, u8 (u8 *buf, int len, u8 seed) */
#define FN_copy_protection_check                 0x8DC7  /* platform, int (void) */
#define FN_gfx_scroll_window                     0x91CF  /* platform, void (s16 x, s16 y, s16 w, s16 h, s16 ro */
#define FN_text_input_line                       0x92A8  /* platform, int (char *buf, int maxlen, int x, int y */
#define FN_fatal                                 0x94AB  /* platform, void (char *fmt, ...) */
#define FN_res_find_list                         0x94C7  /* platform, void (far arc, char *names, far ptr *out */
#define FN_draw_text_centered                    0x9507  /* platform, void (char *s, int y) */
#define FN_draw_rect_outline                     0x9530  /* platform, void (x0, y0, x1, y1, colour) */
#define FN_menu_key                              0x95B0  /* platform, int (void) */
#define FN_toupper_c                             0x95D9  /* platform, int (char c) */
#define FN_joy_calibrate_screen                  0x95F4  /* platform, void (void) */
#define FN_rect_clear_plane                      0x97D4  /* platform, asm: ES:DI dst, DX width, SI rows, CX sk */
#define FN_rect_set_plane                        0x981E  /* platform, same */
#define FN_rect_xor_plane                        0x9868  /* platform, same */
#define FN_rect_clear_plane_ega                  0x98C2  /* platform, same */
#define FN_rect_set_plane_ega                    0x992B  /* platform, same */
#define FN_rect_xor_plane_ega                    0x9994  /* platform, same */
#define FN_ticks_now                             0x9A01  /* platform, u16 (void) */
#define FN_ticks_elapsed                         0x9A05  /* platform, u16 (u16 start) */
#define FN_draw_glyph                            0x9A69  /* platform, void (int x, int y, int idx) */
#define FN_load_packed_archive                   0x9A86  /* platform, far ptr (char *fname, u16 reserve) */
#define FN_huff_read_tree                        0x9C1E  /* platform, void (void) */
#define FN_huff_read_word                        0x9C76  /* platform, int (void) */
#define FN_huff_decode                           0x9C90  /* platform, int (void) */
#define FN_rle90_out                             0x9CF9  /* platform, void (u8 c) */
#define FN_pack_getc                             0x9D64  /* platform, int (void) */
#define FN_pack_putc                             0x9DD3  /* platform, void (u8 c) */
#define FN_lzw_decompress                        0x9E1D  /* platform, void (void) */
#define FN_lzw_getcode                           0x9FA2  /* platform, int (void) */
#define FN_lzw_alloc_tables                      0xA0CF  /* platform, void (void) */
#define FN_lzw_free_tables                       0xA111  /* platform, void (void) */
#define FN_joy_read                              0xA12F  /* platform, u8 (void) */
#define FN_cache_find                            0xA280  /* platform, u16 seg (char *fname) */
#define FN_cache_alloc                           0xA2BE  /* platform, u16 seg (char *fname, u16 paras, u16 res */
#define FN_buf_alloc                             0xA340  /* platform, u16 seg (u16 paras) */
#define FN_buf_free                              0xA37E  /* platform, void (u16 seg) */
#define FN_gfx_target_save                       0xA3B7  /* platform, void (void) */
#define FN_gfx_target_restore                    0xA3CB  /* platform, void (void) */
#define FN_mem_debug_dump                        0xA3DF  /* platform, void (void) */
#define FN_gfx_get_target_ptr                    0xA4D9  /* platform, u32 (void) */
#define FN_abort                                 0xA4E3  /* platform */
#define FN_close                                 0xA4F8  /* platform */
#define FN__astart                               0xA50C  /* platform */
#define FN_fclose                                0xA5B6  /* platform */
#define FN_fgets                                 0xA659  /* platform */
#define FN_fopen                                 0xA6B1  /* platform */
#define FN_fprintf                               0xA6D7  /* platform */
#define FN_fscanf                                0xA70E  /* platform */
#define FN_free                                  0xA722  /* platform */
#define FN_malloc                                0xA730  /* platform */
#define FN_open                                  0xA776  /* platform */
#define FN_printf                                0xA8C7  /* platform */
#define FN_srand                                 0xA8FD  /* platform */
#define FN_rand                                  0xA90E  /* platform */
#define FN_read                                  0xA93A  /* platform */
#define FN_sprintf                               0xAA00  /* platform */
#define FN_sscanf                                0xAA51  /* platform */
#define FN_strcmp                                0xAA88  /* platform */
#define FN_strlen                                0xAABD  /* platform */
#define FN_strncpy                               0xAAD8  /* platform */
#define FN__filbuf                               0xAB00  /* platform */
#define FN__flsbuf                               0xABE2  /* platform */
#define FN__freebuf                              0xAD0D  /* platform */
#define FN__openfile                             0xAD3C  /* platform */
#define FN__stbuf                                0xAE3F  /* platform */
#define FN__ftbuf                                0xAEDE  /* platform */
#define FN__nmalloc                              0xAF67  /* platform */
#define FN__amlink                               0xB048  /* platform */
#define FN__amexpand                             0xB082  /* platform */
#define FN__amallocbrk                           0xB0A4  /* platform */
#define FN__nullcheck                            0xB0C3  /* platform */
#define FN_creat                                 0xB0DF  /* platform */
#define FN_umask                                 0xB152  /* platform */
#define FN__cinit                                0xB165  /* platform */
#define FN_exit                                  0xB214  /* platform */
#define FN__exit                                 0xB22B  /* platform */
#define FN__ctermsub                             0xB257  /* platform */
#define FN__initterm                             0xB270  /* platform */
#define FN__dosret0                              0xB27F  /* platform */
#define FN__dosretax                             0xB287  /* platform */
#define FN_fflush                                0xB2C7  /* platform */
#define FN__input_B32F                           0xB32F  /* platform */
#define FN__input_B698                           0xB698  /* platform */
#define FN_itoa                                  0xBAFF  /* platform */
#define FN__NMSG_TEXT                            0xBB1A  /* platform */
#define FN__NMSG_WRITE                           0xBB4A  /* platform */
#define FN__output_BB73                          0xBB73  /* platform */
#define FN__output_BE03                          0xBE03  /* platform */
#define FN__setargv                              0xC382  /* platform */
#define FN__setenvp                              0xC467  /* platform */
#define FN_strcat                                0xC4CD  /* platform */
#define FN_strcpy                                0xC4FE  /* platform */
#define FN__getstream                            0xC523  /* platform */
#define FN_unlink                                0xC55A  /* platform */
#define FN_sbrk                                  0xC567  /* platform */
#define FN__growseg                              0xC5D5  /* platform */
#define FN__chkstk                               0xC62B  /* platform */
#define FN_isatty                                0xC644  /* platform */
#define FN_ungetc                                0xC6B2  /* platform */
#define FN_write                                 0xC70C  /* platform */
#define FN_flushall                              0xC849  /* platform */
#define FN__aNldiv                               0xC87A  /* platform */
#define FN__aNlmul                               0xC91D  /* platform */
#define FN__aNlshl                               0xC949  /* platform */
#define FN__aNlshr                               0xC954  /* platform */
#define FN__aNaldiv                              0xC95F  /* platform */
#define FN__aNalshl                              0xC981  /* platform */
#define FN_div0_isr                              0xDDC3  /* platform, INT 0 handler (data segment) */

#endif
