/* SyncRPG -- door entry point.
 *
 * Boots the vendored EasyRPG Player headless through our BaseUi_termgfx
 * backend (ui_term.cpp), the door analogue of syncscumm's OSystem_Termgfx.
 * termgfx_termio_init() parses DOOR32.SYS / -s<fd> and stands up the terminal
 * session; we then hand EasyRPG a clean argv (never the raw door argv -- the
 * engine's own parser would reject -s<fd>/a DOOR32 path) and run it.
 *
 * Task 3 got the engine loading RPG_RT.ldb/.lmt and reaching the title
 * without crashing, with our UI installed; Task 4 wired video, Task 5 wired
 * keyboard input, and Task 6 (M3) wires audio -- EasyRPG now runs with its
 * real audio backend (no --no-audio), routed to termgfx_stream by
 * ui_term.cpp / audio_term.h.
 *
 * The game to run is taken from the SYNCRPG_GAME environment variable, or the
 * first door-argv token termgfx_termio_init() did not consume -- a test seam
 * until getdata.js (Task 7) provides the real per-package project path.
 *
 * Task 8 (M4) adds per-user saves: a door-level `--save-path=<dir>` argument
 * (the install-xtrn cmd passes `%juser/%4/yumenikki`, mirroring
 * synclure/syncscumm's `--savepath=%juser/%4/lure`) is translated to
 * EasyRPG's OWN `--save-path PATH` option (player.cpp; verified against
 * `easyrpg/src/player.cpp`'s `--help` text: "Instead of storing save files in
 * the game directory, store them in PATH"). Like ScummVM's --savepath,
 * EasyRPG's FileFinder::Root().Create() only resolves an EXISTING directory
 * -- data/user/<####>/yumenikki/ does not exist yet on a user's first launch,
 * so we mkpath() it here before Player::Init() ever looks at it (same
 * reasoning as syncscumm.cpp's savepath mkpath(), see that file's comment).
 */
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include "player.h"

#include "syncrpg_version.h"
#include "git_hash.h"   /* generated by synchronet_gitinfo(): GIT_HASH / GIT_DATE */

extern "C" {
#include "termgfx_termio.h"
#include "dirwrap.h"
}

/* NOT inside the extern "C" above: both carry their own `extern "C"` guard,
 * and ini_file.h reaches <winsock2.h>/wspiapi.h on MSVC, whose templates are
 * a hard error ("templates cannot be declared to have 'C' linkage") when the
 * include lands inside one. */
#include "genwrap.h"    /* xpdev: strnicmp() */
#include "ini_file.h"   /* xpdev: iniReadFile()/iniGetString() */

/* Help-page hotkey: reserve a control key that opens the door's help/about
 * overlay (help_term.h). termgfx already reserves Ctrl+<letter> for this in all
 * three of its keyboard decode paths -- legacy bytes, kitty CSI-u and SyncTERM
 * evdev -- and hands it back through termgfx_termio_menu_requested(), so unlike
 * F1 (which the door decodes itself) this one works on every terminal without
 * a key code of its own. Configurable per package: syncrpg.ini
 * "[input] menu_key = ctrl-<letter>", or "off". Default Ctrl-G, matching
 * syncscumm; F1 works regardless, so "off" costs the caller nothing but the
 * terminal-independent route. Parsed exactly like syncscumm's resolveMenuKey()
 * -- same ini key, same spellings -- so a sysop learns one convention. */
static void syncrpg_resolve_menu_key()
{
	int   letter = 'g';   /* default: Ctrl-G, even with no syncrpg.ini present */
	FILE *f      = fopen("syncrpg.ini", "r");

	if (f != NULL) {
		str_list_t ini = iniReadFile(f);
		char       val[INI_MAX_VALUE_LEN];

		fclose(f);
		iniGetString(ini, "input", "menu_key", "ctrl-g", val);
		strListFree(&ini);
		letter = 0;   /* "off"/unparseable disables it */
		if (strnicmp(val, "ctrl", 4) == 0) {
			const char *p = val + 4;
			if (*p == '-' || *p == '+' || *p == ' ')
				p++;
			if (*p >= 'A' && *p <= 'Z')
				letter = *p - 'A' + 'a';
			else if (*p >= 'a' && *p <= 'z')
				letter = *p;
		}
	}
	termgfx_termio_set_menu_key(letter);
	if (letter)
		fprintf(stderr, "syncrpg: help hotkey: Ctrl-%c (or F1)\n", letter - 'a' + 'A');
	else
		fputs("syncrpg: help hotkey: off (F1 only)\n", stderr);
}

/* The DOOR's version, bumped by hand per release -- the sibling doors'
 * SYNCDOOM_VERSION / SYNCDUKE_VERSION / SR_VERSION / SYNCMOO1_VERSION. The git
 * hash and build date shown beside it come from the build, not from here. */
#define SYNCRPG_VERSION "v0.1"

/* See door/syncrpg_version.h. Called from the vendored startup splash
 * (easyrpg/src/scene_logo.cpp, PROVENANCE local patch #1) -- kept HERE, in
 * door-owned code, so that patch stays one #include plus one call and all of
 * the door identity is ours. */
const char *syncrpg_version_line()
{
	static char line[64];

	if (line[0] == '\0') {
		/* GIT_DATE is "Jul 23 2026 00:33" -- a clock time is noise on a
		 * version line, so %.11s keeps just the date, as syncretro/main.c
		 * and syncmoo1_door.c do.
		 *
		 * SINGLE spaces, unlike the siblings' double: this shares one 288px
		 * row with EasyRPG's own version on the splash, and the splash font's
		 * half-width cell is 6px (font.cpp: HEIGHT 12, HALF_WIDTH 6), so the
		 * row holds 48 characters total. "v0.8.1" takes 6 of them, leaving 42;
		 * this line is 40 with single spaces and 43 with double, which would
		 * collide. */
		snprintf(line, sizeof(line), "%s %s %.11s synchro.net",
		         SYNCRPG_VERSION, GIT_HASH, GIT_DATE);
	}
	return line;
}

int main(int argc, char **argv)
{
	// Pin the door name termgfx derives its syncrpg.ini, its <DOOR>_* env-vars
	// and its diagnostic paths from, rather than letting it fall back to
	// argv[0]'s basename -- the sysop's ini keeps working if the binary is
	// renamed.
	termgfx_termio_set_app_name("syncrpg");
	termgfx_termio_init(argc, argv);
	atexit(termgfx_termio_shutdown);
	syncrpg_resolve_menu_key();   /* Ctrl+<letter> -> the help overlay */

	/* Resolve the game/project path (env first, else the first non-option
	 * argv token the door layer did not claim) and the optional per-user
	 * --save-path=<dir>, from whatever argv tokens termgfx_termio_init() left
	 * for us. */
	const char *game = getenv("SYNCRPG_GAME");
	std::string game_path;
	std::string save_path;
	static const char save_path_opt[] = "--save-path=";

	if (game != NULL && *game != '\0')
		game_path = game;
	for (int i = 1; i < argc; i++) {
		if (termgfx_termio_consumed(i))
			continue;
		if (strncmp(argv[i], save_path_opt, sizeof(save_path_opt) - 1) == 0) {
			save_path = argv[i] + sizeof(save_path_opt) - 1;
			continue;
		}
		if (game_path.empty())
			game_path = argv[i];
	}
	if (game_path.empty()) {
		fputs("syncrpg: no game path (set SYNCRPG_GAME or pass a project dir)\n",
			stderr);
		return 1;
	}

	/* Fail closed on a broken/partial install: only proceed if game_path is a
	 * real RM2k/2k3 project (has RPG_RT.ldb). If it doesn't, EasyRPG's
	 * Player::Init() falls through to Scene_GameBrowser -- its command window
	 * exposes Settings/About, engine UI a locked-down door must never surface
	 * -- so we must catch this BEFORE any EasyRPG call, not rely on the engine
	 * to do the right thing. */
	std::string ldb_path = game_path;
	if (!ldb_path.empty() && !IS_PATH_DELIM(ldb_path[ldb_path.size() - 1]))
		ldb_path += PATH_DELIM;
	ldb_path += "RPG_RT.ldb";
	if (!fexist(ldb_path.c_str())) {
		fprintf(stderr,
			"syncrpg: %s is not a valid RPG Maker project (missing %s)\n",
			game_path.c_str(), ldb_path.c_str());
		return 1;
	}

	/* Build EasyRPG's own argv from scratch. args[0] is the program name (the
	 * engine's command-line parser skips it); the rest are real EasyRPG
	 * options only. No --no-audio: Task 6 (M3) wires GetAudio() to a real
	 * termgfx-backed audio interface (see ui_term.cpp / audio_term.h), so the
	 * engine is left free to use it. */
	std::vector<std::string> args;
	args.push_back("syncrpg");
	args.push_back("--project-path");
	args.push_back(game_path);
	if (!save_path.empty()) {
		mkpath(save_path.c_str());
		args.push_back("--save-path");
		args.push_back(save_path);
	}

	Player::Init(std::move(args));
	Player::Run();

	termgfx_termio_shutdown();
	return 0;
}
