# TODO: Add support for GTK utilities
#       The bad touching needs to be solved in the build system, but
#       maybe there's a way to automate it with needs?

spec:
  inputs:
    os:
    platform:
    tagname:
    cross_platform:
      default: 'no'
    build_flags:
      default: 'RELEASE=1'
    no_javascript:
      default: 'no'
    has_curses:
      default: 'yes'
---

".$[[ inputs.os ]]":
  extends: .rules
  tags: 
    - "$[[ inputs.tagname ]]"

".$[[ inputs.os ]]-build":
  stage: build
  extends: .$[[ inputs.os ]]

".$[[ inputs.os ]]-test":
  stage: test
  extends: .$[[ inputs.os ]]

"spidermonkey-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd 3rdp/build
    - touch depend
    - gmake $[[ inputs.build_flags ]] libmozjs
  artifacts:
    expire_in: 30 mins
    name: "spidermonkey-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "3rdp/*.*.*.release/mozjs"
  rules:
    - if: "$[[ inputs.no_javascript ]]" == "yes"
      when: never
    - !reference [.rules, rules]

"cryptlib-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd 3rdp/build
    - touch depend
    - gmake $[[ inputs.build_flags ]] cryptlib
  artifacts:
    expire_in: 30 mins
    name: "cryptlib-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "3rdp/*.*.*.release/cl"

"xpdev-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/xpdev
    - touch depend
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    expire_in: 30 mins
    name: "xpdev-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/xpdev/*.*.*.lib.release*"
      - "src/xpdev/*.*.*.obj.release*/*.o*"

"encode-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/encode
    - touch depend
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    expire_in: 30 mins
    name: "encode-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/encode/*.*.*.lib.release*"
      - "src/encode/*.*.*.obj.release*/*.o*"

"hash-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/hash
    - touch depend
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    expire_in: 30 mins
    name: "hash-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/hash/*.*.*.lib.release*"
      - "src/hash/*.*.*.obj.release*/*.o*"

"ciolib-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/conio
    - touch depend
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    expire_in: 30 mins
    name: "ciolib-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/conio/*.*.*.lib.release*"
      - "src/conio/*.*.*.obj.release*/*.o*"

"sftp-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/sftp
    - touch depend
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    expire_in: 30 mins
    name: "sftp-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/sftp/*.*.*.lib.release*"
      - "src/sftp/*.*.*.obj.release*/*.o*"

"smblib-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/smblib
    - touch depend
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    expire_in: 30 mins
    name: "smblib-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/smblib/*.*.*.lib.release*"
      - "src/smblib/*.*.*.obj.release*/*.o*"

"uifc-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/uifc
    - touch depend
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    expire_in: 30 mins
    name: "uifc-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/uifc/*.*.*.lib.release*"
      - "src/uifc/*.*.*.obj.release*/*.o*"

"gitinfo-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/sbbs3
    - touch depend
    - gmake $[[ inputs.build_flags ]] gitinfo
  artifacts:
    expire_in: 30 mins
    name: "gitinfo-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/sbbs3/git_*.h"

"scfg-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/sbbs3/scfg
    - touch depend
    - touch xpdev
    - touch xpdev-mt
    - touch encode
    - touch hash
    - touch smblib
    - touch ciolib-mt
    - touch uifc
    - touch uifc-mt
    - touch cl
    - gmake $[[ inputs.build_flags ]] GIT=NO
  artifacts:
    expire_in: 30 mins
    name: "scfg-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/sbbs3/scfg/*.exe.release/*"
      - "src/sbbs3/scfg/*.obj.release*/*.o*"
  needs:
    - job: "ciolib-$[[ inputs.os ]]"
    - job: "cryptlib-$[[ inputs.os ]]"
    - job: "encode-$[[ inputs.os ]]"
    - job: "hash-$[[ inputs.os ]]"
    - job: "smblib-$[[ inputs.os ]]"
    - job: "uifc-$[[ inputs.os ]]"
    - job: "xpdev-$[[ inputs.os ]]"
    - job: "gitinfo-$[[ inputs.os ]]"

"uedit-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/sbbs3/uedit
    - touch depend
    - touch xpdev
    - touch xpdev-mt
    - touch encode
    - touch hash
    - touch smblib
    - touch ciolib-mt
    - touch uifc
    - touch uifc-mt
    - gmake $[[ inputs.build_flags ]] GIT=NO
  artifacts:
    expire_in: 30 mins
    name: "uedit-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/sbbs3/uedit/*.exe.release/*"
      - "src/sbbs3/uedit/*.obj.release*/*.o*"
  needs:
    - job: "ciolib-$[[ inputs.os ]]"
    - job: "encode-$[[ inputs.os ]]"
    - job: "hash-$[[ inputs.os ]]"
    - job: "smblib-$[[ inputs.os ]]"
    - job: "uifc-$[[ inputs.os ]]"
    - job: "xpdev-$[[ inputs.os ]]"
    - job: "gitinfo-$[[ inputs.os ]]"
  rules:
    - if: "$[[ inputs.has_curses ]]" == "no"
      when: never
    - !reference [.rules, rules]

"umonitor-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/sbbs3/umonitor
    - touch depend
    - touch xpdev
    - touch xpdev-mt
    - touch encode
    - touch hash
    - touch smblib
    - touch ciolib-mt
    - touch uifc
    - touch uifc-mt
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    expire_in: 30 mins
    name: "umonitor-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/sbbs3/umonitor/*.exe.release/*"
      - "src/sbbs3/umonitor/*.obj.release*/*.o*"
  needs:
    - job: "ciolib-$[[ inputs.os ]]"
    - job: "encode-$[[ inputs.os ]]"
    - job: "hash-$[[ inputs.os ]]"
    - job: "smblib-$[[ inputs.os ]]"
    - job: "uifc-$[[ inputs.os ]]"
    - job: "xpdev-$[[ inputs.os ]]"

"utils-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/sbbs3
    - touch cl
    - touch depend
    - touch xpdev
    - touch xpdev-mt
    - touch encode
    - touch hash
    - touch smblib
    - touch ciolib-mt
    - touch uifc
    - touch uifc-mt
    - gmake $[[ inputs.build_flags ]] GIT=NO standalone-utils
  artifacts:
    expire_in: 30 mins
    name: "utils-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/sbbs3/*.exe.release/*"
      - "src/sbbs3/*.obj.release*/*.o*"
  needs:
    - job: "ciolib-$[[ inputs.os ]]"
    - job: "cryptlib-$[[ inputs.os ]]"
    - job: "encode-$[[ inputs.os ]]"
    - job: "gitinfo-$[[ inputs.os ]]"
    - job: "hash-$[[ inputs.os ]]"
    - job: "smblib-$[[ inputs.os ]]"
    - job: "uifc-$[[ inputs.os ]]"
    - job: "xpdev-$[[ inputs.os ]]"

"sbbs-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/sbbs3
    - touch depend
    - touch xpdev
    - touch xpdev-mt
    - touch smblib
    - touch uifc
    - touch uifc-mt
    - touch ciolib-mt
    - touch encode
    - touch hash
    - touch smblib
    - touch sftp-mt
    - touch cl
    - touch scfg/xpdev-mt
    - touch scfg/uifc-mt
    - touch scfg/ciolib-mt
    - touch scfg/smblib
    - touch scfg/encode
    - touch scfg/hash
    - touch scfg/cl
    - touch uedit/smblib
    - touch uedit/uifc-mt
    - touch uedit/ciolib-mt
    - touch uedit/xpdev-mt
    - touch umonitor/ciolib-mt
    - touch umonitor/uifc-mt
    - touch umonitor/xpdev-mt
    - touch umonitor/smblib
    - gmake $[[ inputs.build_flags ]] GIT=NO all
  artifacts:
    name: "sbbs-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/sbbs3/*.exe.release/*"
      - "src/sbbs3/*.lib.release/*"
      - "src/sbbs3/*/*.exe.release/*"
  needs:
    - job: "spidermonkey-$[[ inputs.os ]]"
    - job: "cryptlib-$[[ inputs.os ]]"
    - job: "xpdev-$[[ inputs.os ]]"
    - job: "encode-$[[ inputs.os ]]"
    - job: "hash-$[[ inputs.os ]]"
    - job: "sftp-$[[ inputs.os ]]"
    - job: "smblib-$[[ inputs.os ]]"
    - job: "ciolib-$[[ inputs.os ]]"
    - job: "uifc-$[[ inputs.os ]]"
    - job: "gitinfo-$[[ inputs.os ]]"
    - job: "scfg-$[[ inputs.os ]]"
    - job: "uedit-$[[ inputs.os ]]"
    - job: "umonitor-$[[ inputs.os ]]"
    - job: "utils-$[[ inputs.os ]]"
  rules:
    - if: "$[[ inputs.no_javascript ]]" == "yes"
      when: never
    - if: "$[[ inputs.cross_platform ]]" == "yes"
      when: never
    - !reference [.rules, rules]

"syncterm-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/syncterm
    - touch depend
    - touch xpdev
    - touch xpdev-mt
    - touch encode
    - touch hash
    - touch ciolib-mt
    - touch uifc
    - touch uifc-mt
    - touch sftp-mt
    - touch cl
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    name: "syncterm-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/syncterm/*.exe.release/*"
  needs:
    - job: "ciolib-$[[ inputs.os ]]"
    - job: "cryptlib-$[[ inputs.os ]]"
    - job: "encode-$[[ inputs.os ]]"
    - job: "hash-$[[ inputs.os ]]"
    - job: "sftp-$[[ inputs.os ]]"
    - job: "uifc-$[[ inputs.os ]]"
    - job: "xpdev-$[[ inputs.os ]]"

"syncdraw-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/syncdraw
    - touch depend
    - touch xpdev
    - touch xpdev-mt
    - touch ciolib-mt
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    name: "syncdraw-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/syncdraw/*.exe.release/*"
  needs:
    - job: "ciolib-$[[ inputs.os ]]"
    - job: "xpdev-$[[ inputs.os ]]"

"jsdoor-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/sbbs3
    - touch depend
    - touch xpdev
    - touch xpdev-mt
    - touch encode
    - touch hash
    - touch smblib
    - touch ciolib-mt
    - touch uifc
    - touch uifc-mt
    - touch sftp-mt
    - touch cl
    - touch js
    - gmake $[[ inputs.build_flags ]] jsdoor
  artifacts:
    name: "jsdoor-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/sbbs3/*.exe.release/*"
  needs:
    - job: "ciolib-$[[ inputs.os ]]"
    - job: "cryptlib-$[[ inputs.os ]]"
    - job: "encode-$[[ inputs.os ]]"
    - job: "hash-$[[ inputs.os ]]"
    - job: "sftp-$[[ inputs.os ]]"
    - job: "smblib-$[[ inputs.os ]]"
    - job: "spidermonkey-$[[ inputs.os ]]"
    - job: "uifc-$[[ inputs.os ]]"
    - job: "xpdev-$[[ inputs.os ]]"
  rules:
    - if: "$[[ inputs.no_javascript ]]" == "yes"
      when: never
    - !reference [.rules, rules]

"sexpots-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-build
  script:
    - cd src/sexpots
    - touch depend
    - touch xpdev
    - touch xpdev-mt
    - gmake $[[ inputs.build_flags ]]
  artifacts:
    name: "sexpots-$[[ inputs.os ]]-$[[ inputs.platform ]]"
    paths:
      - "src/sexpots/*.exe.release/*"
  needs:
    - job: "xpdev-$[[ inputs.os ]]"

"js-testsuite-$[[ inputs.os ]]":
  extends:
    - .$[[ inputs.os ]]-test
  script:
    - "src/sbbs3/*.exe.release/jsdoor exec/tests/test.js"
  dependencies:
    - "jsdoor-$[[ inputs.os ]]"
  rules:
    - if: "$[[ inputs.cross_platform ]]" == "yes"
      when: never
    - if: "$[[ inputs.no_javascript ]]" == "yes"
      when: never
    - !reference [.rules, rules]
