# dir_attr.inc

# Baja include file defining DOS Directory Entry Attribute constants
# Specifically used with the SET_FILE_ATTRIB and GET_FILE_ATTRIB functions

# $id: $

# @format.tab-size 8, @format.use-tabs true

!define FA_NORMAL   0x00
!define FA_RDONLY   0x01
!define FA_HIDDEN   0x02
!define FA_SYSTEM   0x04
!define FA_LABEL    0x08
!define FA_DIREC    0x10
!define FA_ARCH     0x20

# End of DIR_ATTR.INC
