# Synchronet Baja Module Makefile (for Borland make)

# Requires Baja v2.20+

# @format.tab-size 8, @format.use-tabs true

# $id: $

all : 	\
    ftp.bin \
	matrix.bin \
	sdos.bin \
	simple.bin \

.src.bin:
	@baja.exe /q $<
