# Synchronet Baja Module Makefile (for Borland make)

# Requires Baja v2.20+

# @format.tab-size 8, @format.use-tabs true

# $id: $

all : 	\
    ftp.bin \
	major.bin \
	matrix.bin \
	obv-2.bin \
	pcboard.bin \
	ra_emu.bin \
	renegade.bin \
	sdos.bin \
	simple.bin \
	wildcat.bin \
	wwiv.bin


.src.bin:
	@baja.exe /q $<
