OBJS       = $(MTOBJODIR)$(DIRSEP)dpoker$(OFILE) \
			$(MTOBJODIR)$(DIRSEP)xsdk$(OFILE) \
			$(MTOBJODIR)$(DIRSEP)xsdkvars$(OFILE)

DPCLEAN_OBJS = $(MTOBJODIR)$(DIRSEP)dpclean$(OFILE) \
			$(MTOBJODIR)$(DIRSEP)xsdk$(OFILE) \
			$(MTOBJODIR)$(DIRSEP)xsdkvars$(OFILE)

DPCONFIG_OBJS = $(MTOBJODIR)$(DIRSEP)dpconfig$(OFILE)
