DPOKER		=	$(EXEODIR)$(DIRSEP)dpoker$(EXEFILE)
DPCLEAN		=	$(EXEODIR)$(DIRSEP)dpclean$(EXEFILE)
DPCONFIG	=	$(EXEODIR)$(DIRSEP)dpconfig$(EXEFILE)

all: xpdev xpdev-mt $(MTOBJODIR) $(EXEODIR) $(DPOKER) $(DPCLEAN) $(DPCONFIG)

$(DPCONFIG): $(XPDEV-MT_LIB) $(CIOLIB-MT) $(UIFCLIB-MT)
