UIFCLIB  =       $(CONIO_SRC)$(DIRSEP)$(LIBODIR)$(DIRSEP)$(LIBPREFIX)uifc$(LIBFILE)
UIFCLIB-MT  =       $(CONIO_SRC)$(DIRSEP)$(LIBODIR)$(DIRSEP)$(LIBPREFIX)uifc-mt$(LIBFILE)

UIFC_CFLAGS   =       -I$(UIFC_SRC)
UIFC_LDFLAGS  =       -L$(UIFC_SRC)$(DIRSEP)$(LIBODIR)
UIFC-MT_CFLAGS   =       -I$(UIFC_SRC)
UIFC-MT_LDFLAGS  =       -L$(UIFC_SRC)$(DIRSEP)$(LIBODIR)
