var ports_init=[
	{
		 Name:"Sol"
		,Sector:1
		,Class:1
		,OreProduction:0
		,OrgProduction:0
		,EquProduction:0
		,OreDeduction:0
		,OrgDeduction:0
		,EquDeduction:0
	}
	,{
		 Name:"Alpha Centauri"
		,Sector:3
		,Class:2
		,OreProduction:50
		,OrgProduction:150
		,EquProduction:25
		,OreDeduction:-25
		,OrgDeduction:22
		,EquDeduction:-21
	}
	,{
		 Name:"Wolf 359"
		,Sector:5
		,Class:3
		,OreProduction:200
		,OrgProduction:75
		,EquProduction:75
		,OreDeduction:20
		,OrgDeduction:-23
		,EquDeduction:-21
	}
	,{
		 Name:"Sirius"
		,Sector:7
		,Class:1
		,OreProduction:150
		,OrgProduction:75
		,EquProduction:100
		,OreDeduction:-15
		,OrgDeduction:-23
		,EquDeduction:26
	}
	,{
		 Name:"Centaurus"
		,Sector:10
		,Class:2
		,OreProduction:20
		,OrgProduction:40
		,EquProduction:5
		,OreDeduction:-50
		,OrgDeduction:50
		,EquDeduction:-50
	}
	,{
		 Name:"Arcturus"
		,Sector:18
		,Class:2
		,OreProduction:30
		,OrgProduction:15
		,EquProduction:5
		,OreDeduction:-48
		,OrgDeduction:50
		,EquDeduction:-50
	}
	,{
		 Name:"Rigel"
		,Sector:19
		,Class:1
		,OreProduction:60
		,OrgProduction:10
		,EquProduction:80
		,OreDeduction:-72
		,OrgDeduction:-75
		,EquDeduction:80
	}
	,{
		 Name:"T'xe"
		,Sector:21
		,Class:2
		,OreProduction:30
		,OrgProduction:40
		,EquProduction:6
		,OreDeduction:-60
		,OrgDeduction:60
		,EquDeduction:-60
	}
	,{
		 Name:"New Paris"
		,Sector:22
		,Class:2
		,OreProduction:30
		,OrgProduction:40
		,EquProduction:7
		,OreDeduction:-63
		,OrgDeduction:80
		,EquDeduction:-70
	}
	,{
		 Name:"Palmer's World"
		,Sector:23
		,Class:2
		,OreProduction:30
		,OrgProduction:20
		,EquProduction:5
		,OreDeduction:-45
		,OrgDeduction:40
		,EquDeduction:-43
	}
	,{
		 Name:"NGC-33"
		,Sector:35
		,Class:3
		,OreProduction:40
		,OrgProduction:20
		,EquProduction:10
		,OreDeduction:40
		,OrgDeduction:-30
		,EquDeduction:-29
	}
	,{
		 Name:"Bourne's Star"
		,Sector:37
		,Class:2
		,OreProduction:50
		,OrgProduction:30
		,EquProduction:10
		,OreDeduction:-55
		,OrgDeduction:60
		,EquDeduction:-57
	}
	,{
		 Name:"Aldebaran"
		,Sector:38
		,Class:2
		,OreProduction:40
		,OrgProduction:35
		,EquProduction:8
		,OreDeduction:-80
		,OrgDeduction:52
		,EquDeduction:-69
	}
	,{
		 Name:"LNC Nebulae"
		,Sector:39
		,Class:2
		,OreProduction:40
		,OrgProduction:50
		,EquProduction:40
		,OreDeduction:-40
		,OrgDeduction:40
		,EquDeduction:-50
	}
	,{
		 Name:"Second Home"
		,Sector:41
		,Class:2
		,OreProduction:30
		,OrgProduction:30
		,EquProduction:10
		,OreDeduction:-51
		,OrgDeduction:49
		,EquDeduction:-50
	}
	,{
		 Name:"Daleth"
		,Sector:43
		,Class:3
		,OreProduction:50
		,OrgProduction:20
		,EquProduction:10
		,OreDeduction:75
		,OrgDeduction:-50
		,EquDeduction:-54
	}
	,{
		 Name:"Bettelgeuse"
		,Sector:45
		,Class:3
		,OreProduction:60
		,OrgProduction:20
		,EquProduction:15
		,OreDeduction:48
		,OrgDeduction:-50
		,EquDeduction:-51
	}
	,{
		 Name:"Koph System"
		,Sector:46
		,Class:1
		,OreProduction:70
		,OrgProduction:10
		,EquProduction:100
		,OreDeduction:-70
		,OrgDeduction:-85
		,EquDeduction:66
	}
	,{
		 Name:"Lonely Hole"
		,Sector:48
		,Class:3
		,OreProduction:20
		,OrgProduction:15
		,EquProduction:12
		,OreDeduction:48
		,OrgDeduction:-30
		,EquDeduction:-34
	}
	,{
		 Name:"NGC-78"
		,Sector:51
		,Class:3
		,OreProduction:30
		,OrgProduction:15
		,EquProduction:10
		,OreDeduction:30
		,OrgDeduction:-38
		,EquDeduction:-34
	}
	,{
		 Name:"NGC-4151"
		,Sector:53
		,Class:3
		,OreProduction:40
		,OrgProduction:20
		,EquProduction:15
		,OreDeduction:52
		,OrgDeduction:-60
		,EquDeduction:-47
	}
	,{
		 Name:"Outpost 7"
		,Sector:57
		,Class:3
		,OreProduction:30
		,OrgProduction:25
		,EquProduction:12
		,OreDeduction:60
		,OrgDeduction:-25
		,EquDeduction:-48
	}
	,{
		 Name:"Youlose"
		,Sector:58
		,Class:3
		,OreProduction:50
		,OrgProduction:35
		,EquProduction:15
		,OreDeduction:50
		,OrgDeduction:-70
		,EquDeduction:-86
	}
	,{
		 Name:"Last Hope"
		,Sector:60
		,Class:3
		,OreProduction:30
		,OrgProduction:40
		,EquProduction:10
		,OreDeduction:36
		,OrgDeduction:-60
		,EquDeduction:-54
	}
	,{
		 Name:"Epsilon Erandi"
		,Sector:62
		,Class:2
		,OreProduction:30
		,OrgProduction:50
		,EquProduction:50
		,OreDeduction:-50
		,OrgDeduction:70
		,EquDeduction:-50
	}
	,{
		 Name:"Fort Dallas"
		,Sector:66
		,Class:2
		,OreProduction:50
		,OrgProduction:60
		,EquProduction:50
		,OreDeduction:-70
		,OrgDeduction:80
		,EquDeduction:-70
	}
	,{
		 Name:"Antares"
		,Sector:69
		,Class:2
		,OreProduction:20
		,OrgProduction:40
		,EquProduction:30
		,OreDeduction:-70
		,OrgDeduction:40
		,EquDeduction:-70
	}
	,{
		 Name:"Gateway"
		,Sector:71
		,Class:2
		,OreProduction:40
		,OrgProduction:20
		,EquProduction:40
		,OreDeduction:-75
		,OrgDeduction:84
		,EquDeduction:-75
	}
	,{
		 Name:"Sirus II"
		,Sector:73
		,Class:1
		,OreProduction:70
		,OrgProduction:40
		,EquProduction:50
		,OreDeduction:-70
		,OrgDeduction:-70
		,EquDeduction:60
	}
	,{
		 Name:"Czar'ak"
		,Sector:77
		,Class:1
		,OreProduction:80
		,OrgProduction:60
		,EquProduction:70
		,OreDeduction:-69
		,OrgDeduction:-75
		,EquDeduction:50
	}
	,{
		 Name:"Vega"
		,Sector:88
		,Class:2
		,OreProduction:40
		,OrgProduction:30
		,EquProduction:40
		,OreDeduction:-50
		,OrgDeduction:30
		,EquDeduction:-40
	}
	,{
		 Name:"Canopus"
		,Sector:89
		,Class:3
		,OreProduction:20
		,OrgProduction:30
		,EquProduction:50
		,OreDeduction:35
		,OrgDeduction:-40
		,EquDeduction:-80
	}
	,{
		 Name:"Ross 154"
		,Sector:93
		,Class:3
		,OreProduction:30
		,OrgProduction:40
		,EquProduction:30
		,OreDeduction:70
		,OrgDeduction:-60
		,EquDeduction:-60
	}
	,{
		 Name:"Luyten 789-6"
		,Sector:94
		,Class:3
		,OreProduction:40
		,OrgProduction:45
		,EquProduction:50
		,OreDeduction:40
		,OrgDeduction:-30
		,EquDeduction:-30
	}
	,{
		 Name:"Bozone"
		,Sector:97
		,Class:3
		,OreProduction:30
		,OrgProduction:30
		,EquProduction:20
		,OreDeduction:20
		,OrgDeduction:-40
		,EquDeduction:-25
	}
	,{
		 Name:"Insearch"
		,Sector:101
		,Class:1
		,OreProduction:50
		,OrgProduction:20
		,EquProduction:75
		,OreDeduction:-20
		,OrgDeduction:-15
		,EquDeduction:40
	}
	,{
		 Name:"Ptolemy"
		,Sector:105
		,Class:2
		,OreProduction:30
		,OrgProduction:30
		,EquProduction:30
		,OreDeduction:-40
		,OrgDeduction:35
		,EquDeduction:-45
	}
	,{
		 Name:"Frontier 3"
		,Sector:107
		,Class:3
		,OreProduction:35
		,OrgProduction:35
		,EquProduction:20
		,OreDeduction:51
		,OrgDeduction:-30
		,EquDeduction:-45
	}
	,{
		 Name:"Pleione"
		,Sector:111
		,Class:3
		,OreProduction:40
		,OrgProduction:10
		,EquProduction:35
		,OreDeduction:30
		,OrgDeduction:-20
		,EquDeduction:-20
	}
	,{
		 Name:"Orion"
		,Sector:113
		,Class:1
		,OreProduction:30
		,OrgProduction:40
		,EquProduction:50
		,OreDeduction:-10
		,OrgDeduction:-30
		,EquDeduction:45
	}
	,{
		 Name:"Triffid 4"
		,Sector:116
		,Class:1
		,OreProduction:130
		,OrgProduction:70
		,EquProduction:85
		,OreDeduction:-15
		,OrgDeduction:-36
		,EquDeduction:50
	}
	,{
		 Name:"Diamond"
		,Sector:118
		,Class:3
		,OreProduction:30
		,OrgProduction:30
		,EquProduction:15
		,OreDeduction:40
		,OrgDeduction:-52
		,EquDeduction:-30
	}
	,{
		 Name:"Last Chance"
		,Sector:120
		,Class:1
		,OreProduction:110
		,OrgProduction:15
		,EquProduction:60
		,OreDeduction:-10
		,OrgDeduction:-75
		,EquDeduction:32
	}
	,{
		 Name:"Polaris"
		,Sector:122
		,Class:3
		,OreProduction:30
		,OrgProduction:16
		,EquProduction:26
		,OreDeduction:80
		,OrgDeduction:-30
		,EquDeduction:-45
	}
	,{
		 Name:"Yaxa"
		,Sector:124
		,Class:2
		,OreProduction:40
		,OrgProduction:30
		,EquProduction:20
		,OreDeduction:-75
		,OrgDeduction:10
		,EquDeduction:-35
	}
	,{
		 Name:"Jorgasnovara"
		,Sector:125
		,Class:2
		,OreProduction:30
		,OrgProduction:40
		,EquProduction:75
		,OreDeduction:-40
		,OrgDeduction:40
		,EquDeduction:-40
	}
	,{
		 Name:"Quilst"
		,Sector:130
		,Class:1
		,OreProduction:15
		,OrgProduction:75
		,EquProduction:100
		,OreDeduction:-12
		,OrgDeduction:-26
		,EquDeduction:55
	}
	,{
		 Name:"Qeegiz"
		,Sector:133
		,Class:3
		,OreProduction:86
		,OrgProduction:45
		,EquProduction:37
		,OreDeduction:70
		,OrgDeduction:-23
		,EquDeduction:-12
	}
	,{
		 Name:"Zumerbalt"
		,Sector:138
		,Class:2
		,OreProduction:20
		,OrgProduction:30
		,EquProduction:50
		,OreDeduction:-85
		,OrgDeduction:30
		,EquDeduction:-10
	}
	,{
		 Name:"Felgercarb"
		,Sector:139
		,Class:1
		,OreProduction:20
		,OrgProduction:20
		,EquProduction:20
		,OreDeduction:-28
		,OrgDeduction:-25
		,EquDeduction:50
	}
	,{
		 Name:"Nodi"
		,Sector:141
		,Class:2
		,OreProduction:30
		,OrgProduction:25
		,EquProduction:12
		,OreDeduction:-23
		,OrgDeduction:42
		,EquDeduction:-36
	}
	,{
		 Name:"Dazzel"
		,Sector:144
		,Class:3
		,OreProduction:40
		,OrgProduction:25
		,EquProduction:5
		,OreDeduction:41
		,OrgDeduction:-50
		,EquDeduction:-43
	}
	,{
		 Name:"Yimx"
		,Sector:145
		,Class:3
		,OreProduction:40
		,OrgProduction:30
		,EquProduction:10
		,OreDeduction:12
		,OrgDeduction:-36
		,EquDeduction:-71
	}
	,{
		 Name:"Gedemondas"
		,Sector:149
		,Class:2
		,OreProduction:17
		,OrgProduction:27
		,EquProduction:37
		,OreDeduction:-85
		,OrgDeduction:50
		,EquDeduction:-40
	}
	,{
		 Name:"Crill"
		,Sector:153
		,Class:2
		,OreProduction:10
		,OrgProduction:15
		,EquProduction:50
		,OreDeduction:-41
		,OrgDeduction:37
		,EquDeduction:-18
	}
	,{
		 Name:"Samaara"
		,Sector:155
		,Class:2
		,OreProduction:40
		,OrgProduction:50
		,EquProduction:90
		,OreDeduction:-30
		,OrgDeduction:30
		,EquDeduction:-50
	}
	,{
		 Name:"Lofz"
		,Sector:157
		,Class:2
		,OreProduction:20
		,OrgProduction:30
		,EquProduction:85
		,OreDeduction:-20
		,OrgDeduction:24
		,EquDeduction:-73
	}
	,{
		 Name:"Tsunamis"
		,Sector:161
		,Class:3
		,OreProduction:18
		,OrgProduction:29
		,EquProduction:46
		,OreDeduction:36
		,OrgDeduction:-50
		,EquDeduction:-64
	}
	,{
		 Name:"Furiaz"
		,Sector:165
		,Class:1
		,OreProduction:19
		,OrgProduction:39
		,EquProduction:44
		,OreDeduction:-70
		,OrgDeduction:-65
		,EquDeduction:66
	}
	,{
		 Name:"ZTX 4"
		,Sector:166
		,Class:1
		,OreProduction:70
		,OrgProduction:40
		,EquProduction:50
		,OreDeduction:-84
		,OrgDeduction:-40
		,EquDeduction:35
	}
	,{
		 Name:"Ilik-69"
		,Sector:169
		,Class:3
		,OreProduction:80
		,OrgProduction:20
		,EquProduction:60
		,OreDeduction:45
		,OrgDeduction:-40
		,EquDeduction:-55
	}
	,{
		 Name:"Marsh System"
		,Sector:171
		,Class:1
		,OreProduction:40
		,OrgProduction:110
		,EquProduction:70
		,OreDeduction:-40
		,OrgDeduction:-55
		,EquDeduction:75
	}
	,{
		 Name:"Stargate"
		,Sector:173
		,Class:3
		,OreProduction:50
		,OrgProduction:30
		,EquProduction:10
		,OreDeduction:60
		,OrgDeduction:-42
		,EquDeduction:-43
	}
	,{
		 Name:"Ridiculous 1"
		,Sector:176
		,Class:2
		,OreProduction:20
		,OrgProduction:40
		,EquProduction:30
		,OreDeduction:-70
		,OrgDeduction:50
		,EquDeduction:-60
	}
	,{
		 Name:"Ceti-Alpha VI"
		,Sector:182
		,Class:2
		,OreProduction:30
		,OrgProduction:15
		,EquProduction:30
		,OreDeduction:-40
		,OrgDeduction:40
		,EquDeduction:-65
	}
	,{
		 Name:"Frontier 8"
		,Sector:183
		,Class:2
		,OreProduction:20
		,OrgProduction:30
		,EquProduction:25
		,OreDeduction:-63
		,OrgDeduction:80
		,EquDeduction:-70
	}
	,{
		 Name:"New America"
		,Sector:186
		,Class:3
		,OreProduction:60
		,OrgProduction:20
		,EquProduction:15
		,OreDeduction:40
		,OrgDeduction:-40
		,EquDeduction:-50
	}
	,{
		 Name:"Criton"
		,Sector:190
		,Class:1
		,OreProduction:30
		,OrgProduction:25
		,EquProduction:20
		,OreDeduction:-70
		,OrgDeduction:-60
		,EquDeduction:40
	}
	,{
		 Name:"Moskva"
		,Sector:191
		,Class:2
		,OreProduction:200
		,OrgProduction:10
		,EquProduction:15
		,OreDeduction:-75
		,OrgDeduction:75
		,EquDeduction:-45
	}
	,{
		 Name:"Ahzdar"
		,Sector:192
		,Class:1
		,OreProduction:90
		,OrgProduction:90
		,EquProduction:90
		,OreDeduction:-80
		,OrgDeduction:-80
		,EquDeduction:70
	}
	,{
		 Name:"Sukered-ya"
		,Sector:194
		,Class:3
		,OreProduction:10
		,OrgProduction:200
		,EquProduction:99
		,OreDeduction:49
		,OrgDeduction:-50
		,EquDeduction:-53
	}
	,{
		 Name:"Gamma 12"
		,Sector:196
		,Class:1
		,OreProduction:42
		,OrgProduction:16
		,EquProduction:50
		,OreDeduction:-70
		,OrgDeduction:-70
		,EquDeduction:60
	}
	,{
		 Name:"Sqeel"
		,Sector:199
		,Class:2
		,OreProduction:70
		,OrgProduction:69
		,EquProduction:70
		,OreDeduction:-75
		,OrgDeduction:95
		,EquDeduction:-65
	}
	,{
		 Name:"Darion"
		,Sector:214
		,Class:3
		,OreProduction:75
		,OrgProduction:45
		,EquProduction:45
		,OreDeduction:80
		,OrgDeduction:-51
		,EquDeduction:-53
	}
	,{
		 Name:"Caspan"
		,Sector:218
		,Class:2
		,OreProduction:50
		,OrgProduction:150
		,EquProduction:25
		,OreDeduction:-25
		,OrgDeduction:22
		,EquDeduction:-21
	}
	,{
		 Name:"Paegan"
		,Sector:225
		,Class:2
		,OreProduction:80
		,OrgProduction:100
		,EquProduction:68
		,OreDeduction:-50
		,OrgDeduction:61
		,EquDeduction:-40
	}
	,{
		 Name:"Mongo"
		,Sector:236
		,Class:3
		,OreProduction:80
		,OrgProduction:40
		,EquProduction:45
		,OreDeduction:85
		,OrgDeduction:-50
		,EquDeduction:-50
	}
	,{
		 Name:"Tori"
		,Sector:242
		,Class:1
		,OreProduction:190
		,OrgProduction:120
		,EquProduction:190
		,OreDeduction:-20
		,OrgDeduction:-25
		,EquDeduction:45
	}
	,{
		 Name:"Fomalhaut"
		,Sector:247
		,Class:2
		,OreProduction:40
		,OrgProduction:30
		,EquProduction:20
		,OreDeduction:-50
		,OrgDeduction:50
		,EquDeduction:-50
	}
	,{
		 Name:"Xanthii"
		,Sector:248
		,Class:2
		,OreProduction:30
		,OrgProduction:55
		,EquProduction:50
		,OreDeduction:-60
		,OrgDeduction:75
		,EquDeduction:-61
	}
	,{
		 Name:"Sinuiji"
		,Sector:250
		,Class:3
		,OreProduction:70
		,OrgProduction:30
		,EquProduction:30
		,OreDeduction:30
		,OrgDeduction:-40
		,EquDeduction:-35
	}
	,{
		 Name:"Sardar"
		,Sector:254
		,Class:3
		,OreProduction:90
		,OrgProduction:50
		,EquProduction:40
		,OreDeduction:50
		,OrgDeduction:-52
		,EquDeduction:-49
	}
	,{
		 Name:"Behr'ak"
		,Sector:256
		,Class:2
		,OreProduction:40
		,OrgProduction:60
		,EquProduction:55
		,OreDeduction:-50
		,OrgDeduction:70
		,EquDeduction:-50
	}
	,{
		 Name:"Bellatrix"
		,Sector:259
		,Class:3
		,OreProduction:30
		,OrgProduction:40
		,EquProduction:15
		,OreDeduction:35
		,OrgDeduction:-70
		,EquDeduction:-55
	}
	,{
		 Name:"Acrux"
		,Sector:262
		,Class:3
		,OreProduction:100
		,OrgProduction:60
		,EquProduction:28
		,OreDeduction:70
		,OrgDeduction:-45
		,EquDeduction:-50
	}
	,{
		 Name:"Horok"
		,Sector:263
		,Class:3
		,OreProduction:80
		,OrgProduction:30
		,EquProduction:50
		,OreDeduction:50
		,OrgDeduction:-40
		,EquDeduction:-45
	}
	,{
		 Name:"K'ushui"
		,Sector:273
		,Class:1
		,OreProduction:80
		,OrgProduction:120
		,EquProduction:200
		,OreDeduction:-72
		,OrgDeduction:-80
		,EquDeduction:90
	}
	,{
		 Name:"Mialplacidas"
		,Sector:276
		,Class:3
		,OreProduction:110
		,OrgProduction:80
		,EquProduction:105
		,OreDeduction:50
		,OrgDeduction:-30
		,EquDeduction:-35
	}
	,{
		 Name:"Rigil Kentaurus"
		,Sector:280
		,Class:2
		,OreProduction:50
		,OrgProduction:70
		,EquProduction:50
		,OreDeduction:-75
		,OrgDeduction:85
		,EquDeduction:-75
	}
	,{
		 Name:"Jassan"
		,Sector:285
		,Class:2
		,OreProduction:155
		,OrgProduction:200
		,EquProduction:110
		,OreDeduction:-45
		,OrgDeduction:50
		,EquDeduction:-45
	}
	,{
		 Name:"Oomaru"
		,Sector:290
		,Class:2
		,OreProduction:45
		,OrgProduction:70
		,EquProduction:40
		,OreDeduction:-40
		,OrgDeduction:42
		,EquDeduction:-50
	}
	,{
		 Name:"Eskiis"
		,Sector:293
		,Class:3
		,OreProduction:90
		,OrgProduction:50
		,EquProduction:60
		,OreDeduction:84
		,OrgDeduction:-65
		,EquDeduction:-35
	}
	,{
		 Name:"Taan"
		,Sector:295
		,Class:2
		,OreProduction:80
		,OrgProduction:90
		,EquProduction:60
		,OreDeduction:-60
		,OrgDeduction:65
		,EquDeduction:-60
	}
	,{
		 Name:"Saaula"
		,Sector:298
		,Class:3
		,OreProduction:75
		,OrgProduction:40
		,EquProduction:45
		,OreDeduction:75
		,OrgDeduction:-40
		,EquDeduction:-35
	}
	,{
		 Name:"Kep Salu"
		,Sector:301
		,Class:1
		,OreProduction:80
		,OrgProduction:100
		,EquProduction:130
		,OreDeduction:-40
		,OrgDeduction:-40
		,EquDeduction:50
	}
	,{
		 Name:"Alam'ak"
		,Sector:304
		,Class:2
		,OreProduction:95
		,OrgProduction:150
		,EquProduction:100
		,OreDeduction:-40
		,OrgDeduction:50
		,EquDeduction:-33
	}
	,{
		 Name:"Wezen"
		,Sector:305
		,Class:3
		,OreProduction:70
		,OrgProduction:25
		,EquProduction:25
		,OreDeduction:30
		,OrgDeduction:-40
		,EquDeduction:-25
	}
	,{
		 Name:"Ghondr"
		,Sector:307
		,Class:3
		,OreProduction:110
		,OrgProduction:50
		,EquProduction:50
		,OreDeduction:60
		,OrgDeduction:-40
		,EquDeduction:-35
	}
	,{
		 Name:"K'hotan"
		,Sector:311
		,Class:3
		,OreProduction:70
		,OrgProduction:40
		,EquProduction:30
		,OreDeduction:51
		,OrgDeduction:-30
		,EquDeduction:-45
	}
	,{
		 Name:"Androcus"
		,Sector:316
		,Class:1
		,OreProduction:110
		,OrgProduction:120
		,EquProduction:180
		,OreDeduction:-71
		,OrgDeduction:-65
		,EquDeduction:85
	}
	,{
		 Name:"Regulus"
		,Sector:319
		,Class:3
		,OreProduction:50
		,OrgProduction:35
		,EquProduction:20
		,OreDeduction:80
		,OrgDeduction:-50
		,EquDeduction:-30
	}
	,{
		 Name:"Proxima"
		,Sector:329
		,Class:2
		,OreProduction:125
		,OrgProduction:115
		,EquProduction:100
		,OreDeduction:-45
		,OrgDeduction:70
		,EquDeduction:-60
	}
	,{
		 Name:"Achernar B"
		,Sector:334
		,Class:2
		,OreProduction:30
		,OrgProduction:90
		,EquProduction:45
		,OreDeduction:-50
		,OrgDeduction:70
		,EquDeduction:-55
	}
	,{
		 Name:"Ndele"
		,Sector:337
		,Class:3
		,OreProduction:190
		,OrgProduction:90
		,EquProduction:100
		,OreDeduction:25
		,OrgDeduction:-25
		,EquDeduction:-20
	}
	,{
		 Name:"Tali"
		,Sector:341
		,Class:2
		,OreProduction:40
		,OrgProduction:80
		,EquProduction:40
		,OreDeduction:-50
		,OrgDeduction:30
		,EquDeduction:-45
	}
	,{
		 Name:"Tutakai"
		,Sector:342
		,Class:3
		,OreProduction:50
		,OrgProduction:35
		,EquProduction:20
		,OreDeduction:60
		,OrgDeduction:-80
		,EquDeduction:-85
	}
	,{
		 Name:"Dubhe"
		,Sector:344
		,Class:1
		,OreProduction:200
		,OrgProduction:110
		,EquProduction:195
		,OreDeduction:-25
		,OrgDeduction:-20
		,EquDeduction:38
	}
	,{
		 Name:"Annobon"
		,Sector:348
		,Class:2
		,OreProduction:40
		,OrgProduction:70
		,EquProduction:65
		,OreDeduction:-60
		,OrgDeduction:80
		,EquDeduction:-60
	}
	,{
		 Name:"Lux"
		,Sector:350
		,Class:3
		,OreProduction:50
		,OrgProduction:30
		,EquProduction:20
		,OreDeduction:53
		,OrgDeduction:-62
		,EquDeduction:-46
	}
	,{
		 Name:"Mirfak"
		,Sector:356
		,Class:2
		,OreProduction:95
		,OrgProduction:115
		,EquProduction:90
		,OreDeduction:-63
		,OrgDeduction:85
		,EquDeduction:-70
	}
	,{
		 Name:"Zindar"
		,Sector:360
		,Class:2
		,OreProduction:100
		,OrgProduction:160
		,EquProduction:45
		,OreDeduction:-26
		,OrgDeduction:27
		,EquDeduction:-21
	}
	,{
		 Name:"Adao"
		,Sector:362
		,Class:3
		,OreProduction:60
		,OrgProduction:40
		,EquProduction:30
		,OreDeduction:30
		,OrgDeduction:-40
		,EquDeduction:-35
	}
	,{
		 Name:"Theseus 2"
		,Sector:366
		,Class:2
		,OreProduction:80
		,OrgProduction:60
		,EquProduction:45
		,OreDeduction:-55
		,OrgDeduction:60
		,EquDeduction:-50
	}
	,{
		 Name:"Azrael"
		,Sector:369
		,Class:3
		,OreProduction:80
		,OrgProduction:40
		,EquProduction:40
		,OreDeduction:50
		,OrgDeduction:-40
		,EquDeduction:-35
	}
	,{
		 Name:"Etzel"
		,Sector:373
		,Class:2
		,OreProduction:80
		,OrgProduction:155
		,EquProduction:85
		,OreDeduction:-36
		,OrgDeduction:50
		,EquDeduction:-28
	}
	,{
		 Name:"Xerxes"
		,Sector:379
		,Class:2
		,OreProduction:90
		,OrgProduction:75
		,EquProduction:50
		,OreDeduction:-80
		,OrgDeduction:52
		,EquDeduction:-70
	}
	,{
		 Name:"Loki"
		,Sector:383
		,Class:2
		,OreProduction:50
		,OrgProduction:160
		,EquProduction:30
		,OreDeduction:-28
		,OrgDeduction:30
		,EquDeduction:-20
	}
	,{
		 Name:"Hashishyun"
		,Sector:384
		,Class:3
		,OreProduction:60
		,OrgProduction:20
		,EquProduction:25
		,OreDeduction:70
		,OrgDeduction:-30
		,EquDeduction:-50
	}
	,{
		 Name:"Akbar"
		,Sector:386
		,Class:3
		,OreProduction:120
		,OrgProduction:100
		,EquProduction:110
		,OreDeduction:50
		,OrgDeduction:-30
		,EquDeduction:-35
	}
	,{
		 Name:"Abu Bekr"
		,Sector:387
		,Class:3
		,OreProduction:50
		,OrgProduction:30
		,EquProduction:20
		,OreDeduction:40
		,OrgDeduction:-27
		,EquDeduction:-23
	}
	,{
		 Name:"Appollyon"
		,Sector:389
		,Class:1
		,OreProduction:110
		,OrgProduction:60
		,EquProduction:150
		,OreDeduction:-71
		,OrgDeduction:-83
		,EquDeduction:65
	}
	,{
		 Name:"Iblis"
		,Sector:390
		,Class:2
		,OreProduction:105
		,OrgProduction:115
		,EquProduction:70
		,OreDeduction:-61
		,OrgDeduction:85
		,EquDeduction:-75
	}
	,{
		 Name:"Siva"
		,Sector:393
		,Class:2
		,OreProduction:30
		,OrgProduction:60
		,EquProduction:30
		,OreDeduction:-40
		,OrgDeduction:40
		,EquDeduction:-45
	}
	,{
		 Name:"Tyr"
		,Sector:394
		,Class:1
		,OreProduction:110
		,OrgProduction:120
		,EquProduction:180
		,OreDeduction:-78
		,OrgDeduction:-69
		,EquDeduction:81
	}
	,{
		 Name:"Alaric"
		,Sector:395
		,Class:2
		,OreProduction:90
		,OrgProduction:50
		,EquProduction:45
		,OreDeduction:-50
		,OrgDeduction:65
		,EquDeduction:-57
	}
	,{
		 Name:"Aeolus"
		,Sector:397
		,Class:2
		,OreProduction:40
		,OrgProduction:20
		,EquProduction:40
		,OreDeduction:-75
		,OrgDeduction:85
		,EquDeduction:-75
	}
	,{
		 Name:"Tonti"
		,Sector:408
		,Class:3
		,OreProduction:40
		,OrgProduction:30
		,EquProduction:25
		,OreDeduction:85
		,OrgDeduction:-45
		,EquDeduction:-50
	}
	,{
		 Name:"Canus Minor"
		,Sector:418
		,Class:2
		,OreProduction:20
		,OrgProduction:40
		,EquProduction:35
		,OreDeduction:-75
		,OrgDeduction:75
		,EquDeduction:-75
	}
	,{
		 Name:"Equulus"
		,Sector:421
		,Class:3
		,OreProduction:60
		,OrgProduction:40
		,EquProduction:20
		,OreDeduction:80
		,OrgDeduction:-40
		,EquDeduction:-50
	}
	,{
		 Name:"Monoceros"
		,Sector:423
		,Class:2
		,OreProduction:30
		,OrgProduction:50
		,EquProduction:15
		,OreDeduction:-40
		,OrgDeduction:45
		,EquDeduction:-80
	}
	,{
		 Name:"Corvus"
		,Sector:426
		,Class:2
		,OreProduction:80
		,OrgProduction:110
		,EquProduction:75
		,OreDeduction:-60
		,OrgDeduction:65
		,EquDeduction:-75
	}
	,{
		 Name:"Phoenix"
		,Sector:429
		,Class:3
		,OreProduction:86
		,OrgProduction:60
		,EquProduction:45
		,OreDeduction:90
		,OrgDeduction:-80
		,EquDeduction:-60
	}
	,{
		 Name:"Tucana"
		,Sector:435
		,Class:1
		,OreProduction:70
		,OrgProduction:40
		,EquProduction:85
		,OreDeduction:-80
		,OrgDeduction:-85
		,EquDeduction:65
	}
	,{
		 Name:"Apian"
		,Sector:438
		,Class:3
		,OreProduction:80
		,OrgProduction:70
		,EquProduction:65
		,OreDeduction:65
		,OrgDeduction:-65
		,EquDeduction:-65
	}
	,{
		 Name:"Doppler"
		,Sector:440
		,Class:3
		,OreProduction:86
		,OrgProduction:45
		,EquProduction:37
		,OreDeduction:85
		,OrgDeduction:-40
		,EquDeduction:-78
	}
	,{
		 Name:"Palitzsch"
		,Sector:443
		,Class:2
		,OreProduction:30
		,OrgProduction:60
		,EquProduction:40
		,OreDeduction:-40
		,OrgDeduction:65
		,EquDeduction:-40
	}
	,{
		 Name:"Seagate"
		,Sector:445
		,Class:3
		,OreProduction:45
		,OrgProduction:15
		,EquProduction:25
		,OreDeduction:85
		,OrgDeduction:-60
		,EquDeduction:-40
	}
	,{
		 Name:"Chandrasekher"
		,Sector:446
		,Class:2
		,OreProduction:80
		,OrgProduction:140
		,EquProduction:90
		,OreDeduction:-70
		,OrgDeduction:55
		,EquDeduction:-62
	}
	,{
		 Name:"Cratuer"
		,Sector:452
		,Class:1
		,OreProduction:130
		,OrgProduction:40
		,EquProduction:180
		,OreDeduction:-65
		,OrgDeduction:-80
		,EquDeduction:70
	}
	,{
		 Name:"Ibn Duad"
		,Sector:459
		,Class:2
		,OreProduction:30
		,OrgProduction:60
		,EquProduction:50
		,OreDeduction:-85
		,OrgDeduction:85
		,EquDeduction:-85
	}
	,{
		 Name:"Pilar"
		,Sector:463
		,Class:2
		,OreProduction:40
		,OrgProduction:80
		,EquProduction:25
		,OreDeduction:-75
		,OrgDeduction:80
		,EquDeduction:-40
	}
	,{
		 Name:"Ketoi"
		,Sector:466
		,Class:2
		,OreProduction:30
		,OrgProduction:60
		,EquProduction:30
		,OreDeduction:-40
		,OrgDeduction:65
		,EquDeduction:-65
	}
	,{
		 Name:"Tulan"
		,Sector:468
		,Class:3
		,OreProduction:40
		,OrgProduction:16
		,EquProduction:30
		,OreDeduction:75
		,OrgDeduction:-25
		,EquDeduction:-40
	}
	,{
		 Name:"Alvarado"
		,Sector:469
		,Class:2
		,OreProduction:90
		,OrgProduction:120
		,EquProduction:80
		,OreDeduction:-60
		,OrgDeduction:70
		,EquDeduction:-35
	}
	,{
		 Name:"Hrok 1"
		,Sector:471
		,Class:1
		,OreProduction:90
		,OrgProduction:50
		,EquProduction:150
		,OreDeduction:-45
		,OrgDeduction:-75
		,EquDeduction:75
	}
	,{
		 Name:"Ramusik"
		,Sector:472
		,Class:3
		,OreProduction:50
		,OrgProduction:30
		,EquProduction:10
		,OreDeduction:65
		,OrgDeduction:-35
		,EquDeduction:-35
	}
	,{
		 Name:"Canus Major"
		,Sector:482
		,Class:3
		,OreProduction:70
		,OrgProduction:35
		,EquProduction:35
		,OreDeduction:70
		,OrgDeduction:-70
		,EquDeduction:-65
	}
	,{
		 Name:"H12"
		,Sector:483
		,Class:2
		,OreProduction:90
		,OrgProduction:180
		,EquProduction:100
		,OreDeduction:-40
		,OrgDeduction:50
		,EquDeduction:-25
	}
	,{
		 Name:"Spica"
		,Sector:489
		,Class:2
		,OreProduction:50
		,OrgProduction:60
		,EquProduction:40
		,OreDeduction:-70
		,OrgDeduction:59
		,EquDeduction:-36
	}
	,{
		 Name:"Yugonislom"
		,Sector:490
		,Class:3
		,OreProduction:46
		,OrgProduction:29
		,EquProduction:20
		,OreDeduction:50
		,OrgDeduction:-50
		,EquDeduction:-45
	}
/* Not in the real game...
	,{
		 Name:"Alfr"
		,Sector:492
		,Class:2
		,OreProduction:20
		,OrgProduction:85
		,EquProduction:30
		,OreDeduction:-20
		,OrgDeduction:50
		,EquDeduction:-35
	}
	,{
		 Name:"Tall Grass"
		,Sector:494
		,Class:3
		,OreProduction:65
		,OrgProduction:40
		,EquProduction:30
		,OreDeduction:60
		,OrgDeduction:-60
		,EquDeduction:-60
	}
	,{
		 Name:"H9"
		,Sector:496
		,Class:3
		,OreProduction:110
		,OrgProduction:60
		,EquProduction:50
		,OreDeduction:80
		,OrgDeduction:-40
		,EquDeduction:-65
	} */
];
