/*
 * scfgindex.h - AUTO-GENERATED. Do not edit by hand.
 *
 * Generated by gen_option_index.py from snprintf(opt[..],..)
 * and uifc.list(..) calls in the surrounding scfg*.c files.
 * Re-run that script whenever option labels, menu titles,
 * or call relationships change.
 */
#ifndef SCFGINDEX_H
#define SCFGINDEX_H

#include "scfgsrch.h"

static const scfg_option_t scfg_option_index[] = {
	{
		"40 Column PETSCII Support",
		"Terminal Server",
		"Servers > Terminal Server > 40 Column PETSCII Support"
	},
	{
		"80 Column PETSCII Support",
		"Terminal Server",
		"Servers > Terminal Server > 80 Column PETSCII Support"
	},
	{
		"Access Log Format",
		"Web Server",
		"Servers > Web Server > Access Log Format"
	},
	{
		"Access Logging",
		"Web Server",
		"Servers > Web Server > Access Logging"
	},
	{
		"Access Requirements",
		"Chat Channel",
		"Chat Features > Multinode Chat Channels > Chat Channel > Access Requirements"
	},
	{
		"Access Requirements",
		"Command Shell",
		"Command Shells > Command Shell > Access Requirements"
	},
	{
		"Access Requirements",
		"Compressible File Type",
		"File Options > Compressible File Types > Compressible File Type > Access Requirements"
	},
	{
		"Access Requirements",
		"Directory",
		"File Areas > Directories > Directory > Access Requirements"
	},
	{
		"Access Requirements",
		"Download Event",
		"File Options > Download Events > Download Event > Access Requirements"
	},
	{
		"Access Requirements",
		"Editor",
		"External Programs > Message Editors > Editor > Access Requirements"
	},
	{
		"Access Requirements",
		"Extractable File Type",
		"File Options > Extractable File Types > Extractable File Type > Access Requirements"
	},
	{
		"Access Requirements",
		"File Transfer Protocol",
		"File Options > File Transfer Protocols > File Transfer Protocol > Access Requirements"
	},
	{
		"Access Requirements",
		"Group",
		"Message Areas > Group > Access Requirements"
	},
	{
		"Access Requirements",
		"Guru",
		"Chat Features > Artificial Gurus > Guru > Access Requirements"
	},
	{
		"Access Requirements",
		"Library",
		"File Areas > Library > Access Requirements"
	},
	{
		"Access Requirements",
		"Module",
		"System > Loadable Modules... > Login > Module > Access Requirements"
	},
	{
		"Access Requirements",
		"Multinode Chat Channels",
		"Chat Features > Multinode Chat Channels > Access Requirements"
	},
	{
		"Access Requirements",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Access Requirements"
	},
	{
		"Access Requirements",
		"Program Section",
		"External Programs > Online Programs (Doors) > Program Section > Access Requirements"
	},
	{
		"Access Requirements",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Access Requirements"
	},
	{
		"Access Requirements",
		"Sysop Chat Pager #",
		"Chat Features > External Sysop Chat Pagers > Sysop Chat Pager # > Access Requirements"
	},
	{
		"Access Requirements",
		"Testable File Type",
		"File Options > Testable File Types > Testable File Type > Access Requirements"
	},
	{
		"Access Requirements",
		"Text Section Internal Code",
		"Text File Sections > Text Section Internal Code > Access Requirements"
	},
	{
		"Access Requirements",
		"Viewable File Type",
		"File Options > Viewable File Types > Viewable File Type > Access Requirements"
	},
	{
		"Action Set Name",
		"Chat Action Set",
		"Chat Features > Multinode Chat Actions > Chat Action Set > Action Set Name"
	},
	{
		"Actual File Path",
		"Directory",
		"File Areas > Directories > Directory > Actual File Path"
	},
	{
		"Additional Credits",
		"Quick-Validation Set",
		"System > Security Options... > Quick-Validation Set > Additional Credits"
	},
	{
		"Advanced Options",
		"Directory",
		"File Areas > Directories > Directory > Advanced Options"
	},
	{
		"Advanced Options",
		"Network Hubs...",
		"Networks > Network Hubs... > Advanced Options"
	},
	{
		"Advanced Options",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Advanced Options"
	},
	{
		"Advanced Options",
		"System",
		"System > Advanced Options"
	},
	{
		"Advanced Options...",
		"Directory",
		"File Areas > Directories > Directory > Advanced Options..."
	},
	{
		"Advanced Options...",
		"Network Hubs...",
		"Networks > Network Hubs... > Advanced Options..."
	},
	{
		"Advanced Options...",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Advanced Options..."
	},
	{
		"Advanced Options...",
		"System",
		"System > Advanced Options..."
	},
	{
		"Allow Anonymous E-mail",
		"Message Options",
		"Message Options > Allow Anonymous E-mail"
	},
	{
		"Allow Anonymous Posts",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Allow Anonymous Posts"
	},
	{
		"Allow Bounce Transfers",
		"FTP Server",
		"Servers > FTP Server > Allow Bounce Transfers"
	},
	{
		"Allow Credit Conversions",
		"Toggle Options",
		"System > Toggle Options > Allow Credit Conversions"
	},
	{
		"Allow File Attachments",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > Allow File Attachments"
	},
	{
		"Allow File Attachments",
		"Internet E-mail",
		"Networks > Internet E-mail > Allow File Attachments"
	},
	{
		"Allow File Tagging",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Allow File Tagging"
	},
	{
		"Allow Forwarding to NetMail",
		"Message Options",
		"Message Options > Allow Forwarding to NetMail"
	},
	{
		"Allow Login by Real Name",
		"Security Options...",
		"System > Security Options... > Allow Login by Real Name"
	},
	{
		"Allow Login by User Number",
		"Security Options...",
		"System > Security Options... > Allow Login by User Number"
	},
	{
		"Allow Message Quoting",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Allow Message Quoting"
	},
	{
		"Allow Message Tagging",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Allow Message Tagging"
	},
	{
		"Allow Message Voting",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Allow Message Voting"
	},
	{
		"Allow Private Posts",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Allow Private Posts"
	},
	{
		"Allow Quoting in E-mail",
		"Message Options",
		"Message Options > Allow Quoting in E-mail"
	},
	{
		"Allow Sending of E-mail",
		"Internet E-mail",
		"Networks > Internet E-mail > Allow Sending of E-mail"
	},
	{
		"Allow Sending of NetMail",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > Allow Sending of NetMail"
	},
	{
		"Allow Sysop Access",
		"Security Options...",
		"System > Security Options... > Allow Sysop Access"
	},
	{
		"Allow Time Banking",
		"Toggle Options",
		"System > Toggle Options > Allow Time Banking"
	},
	{
		"Allow Uploads in E-mail",
		"Message Options",
		"Message Options > Allow Uploads in E-mail"
	},
	{
		"Allow User Aliases",
		"Toggle Options",
		"System > Toggle Options > Allow User Aliases"
	},
	{
		"Allow Users to Relay Mail",
		"Mail Server",
		"Servers > Mail Server > Allow Users to Relay Mail"
	},
	{
		"Allowed Filename Characters",
		"File Options",
		"File Options > Allowed Filename Characters"
	},
	{
		"Allowed Filename Length",
		"File Options",
		"File Options > Allowed Filename Length"
	},
	{
		"Always Prompt for Password",
		"Security Options...",
		"System > Security Options... > Always Prompt for Password"
	},
	{
		"Always Run After (re)Init",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Always Run After (re)Init"
	},
	{
		"Anonymous Uploads",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Anonymous Uploads"
	},
	{
		"Append Tag/Origin Line",
		"Network Options",
		"Message Areas > Sub-boards > Sub-board > Network Options > Append Tag/Origin Line"
	},
	{
		"Apply Markup Codes",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Apply Markup Codes"
	},
	{
		"Archive Format",
		"Network Hubs...",
		"Networks > Network Hubs... > Archive Format"
	},
	{
		"Archive Requirements",
		"Mail Server",
		"Servers > Mail Server > Archive Requirements"
	},
	{
		"Artificial Gurus",
		"Chat Features",
		"Chat Features > Artificial Gurus"
	},
	{
		"Australian Central",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Australian Central"
	},
	{
		"Australian Eastern",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Australian Eastern"
	},
	{
		"Authentication Methods",
		"Web Server",
		"Servers > Web Server > Authentication Methods"
	},
	{
		"Auto Message",
		"Loadable Modules",
		"System > Loadable Modules > Auto Message"
	},
	{
		"Auto-Add Sub-directories",
		"Library",
		"File Areas > Library > Auto-Add Sub-directories"
	},
	{
		"Auto-detect UTF-8 Msgs",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Auto-detect UTF-8 Msgs"
	},
	{
		"Auto-exempt Recipients",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Auto-exempt Recipients"
	},
	{
		"Auto-Filter Duration",
		"Max Concurrent Connections",
		"Servers > Terminal Server > Max Concurrent Connections > Auto-Filter Duration"
	},
	{
		"Auto-Filter Threshold",
		"Max Concurrent Connections",
		"Servers > Terminal Server > Max Concurrent Connections > Auto-Filter Threshold"
	},
	{
		"Auto-generate Index File",
		"FTP Server",
		"Servers > FTP Server > Auto-generate Index File"
	},
	{
		"Automatic Filter Duration",
		"Failed Login Attempts...",
		"Servers > FTP Server > Failed Login Attempts... > Automatic Filter Duration"
	},
	{
		"Automatic Filter Threshold",
		"Failed Login Attempts...",
		"Servers > FTP Server > Failed Login Attempts... > Automatic Filter Threshold"
	},
	{
		"Automatically Quoted Text",
		"Editor",
		"External Programs > Message Editors > Editor > Automatically Quoted Text"
	},
	{
		"Azores",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Azores"
	},
	{
		"Background Execution",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Background Execution"
	},
	{
		"Bangkok",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Bangkok"
	},
	{
		"Batch Download Command Line",
		"File Transfer Protocol",
		"File Options > File Transfer Protocols > File Transfer Protocol > Batch Download Command Line"
	},
	{
		"Batch Transfer",
		"Loadable Modules",
		"System > Loadable Modules > Batch Transfer"
	},
	{
		"Batch Upload Command Line",
		"File Transfer Protocol",
		"File Options > File Transfer Protocols > File Transfer Protocol > Batch Upload Command Line"
	},
	{
		"BBS Drop File Type",
		"Editor",
		"External Programs > Message Editors > Editor > BBS Drop File Type"
	},
	{
		"BBS Drop File Type",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > BBS Drop File Type"
	},
	{
		"BBS ID for QWK Packets",
		"Message Options",
		"Message Options > BBS ID for QWK Packets"
	},
	{
		"BBS Name",
		"System",
		"System > BBS Name"
	},
	{
		"Bind Retry Count",
		"Global Settings",
		"Servers > Global Settings > Bind Retry Count"
	},
	{
		"Bind Retry Delay",
		"Global Settings",
		"Servers > Global Settings > Bind Retry Delay"
	},
	{
		"Bogota",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Bogota"
	},
	{
		"Bombay",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Bombay"
	},
	{
		"Broker Address",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Broker Address"
	},
	{
		"Broker Port",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Broker Port"
	},
	{
		"CA Cert",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > CA Cert"
	},
	{
		"Cache Filter Files",
		"Advanced Options",
		"System > Advanced Options > Cache Filter Files"
	},
	{
		"Calculate/Store Hash of Files",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Calculate/Store Hash of Files"
	},
	{
		"Call-out Command Line",
		"Network Hubs...",
		"Networks > Network Hubs... > Call-out Command Line"
	},
	{
		"Call-out Days",
		"Network Hubs...",
		"Networks > Network Hubs... > Call-out Days"
	},
	{
		"Call-out Frequency",
		"Network Hubs...",
		"Networks > Network Hubs... > Call-out Frequency"
	},
	{
		"Call-out Node",
		"Network Hubs...",
		"Networks > Network Hubs... > Call-out Node"
	},
	{
		"Call-out Time",
		"Network Hubs...",
		"Networks > Network Hubs... > Call-out Time"
	},
	{
		"Calls Per Day",
		"Security Level Values",
		"System > Security Options... > Security Level Values > Calls Per Day"
	},
	{
		"Caracas",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Caracas"
	},
	{
		"Central Europe (CET)",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Central Europe (CET)"
	},
	{
		"CGI Support...",
		"Web Server",
		"Servers > Web Server > CGI Support..."
	},
	{
		"Channel Action Set",
		"Chat Channel",
		"Chat Features > Multinode Chat Channels > Chat Channel > Channel Action Set"
	},
	{
		"Channel Guru",
		"Chat Channel",
		"Chat Features > Multinode Chat Channels > Chat Channel > Channel Guru"
	},
	{
		"Chat Action Set",
		"Multinode Chat Actions",
		"Chat Features > Multinode Chat Actions > Chat Action Set"
	},
	{
		"Chat Channel",
		"Multinode Chat Channels",
		"Chat Features > Multinode Chat Channels > Chat Channel"
	},
	{
		"Chat Features",
		"",
		"Chat Features"
	},
	{
		"Chat Section",
		"Loadable Modules",
		"System > Loadable Modules > Chat Section"
	},
	{
		"Check for File Existence",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Check for File Existence"
	},
	{
		"Check Headers against DNSBL",
		"Mail Server",
		"Servers > Mail Server > Check Headers against DNSBL"
	},
	{
		"Choose NetMail Source Address",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > Choose NetMail Source Address"
	},
	{
		"Clean-up Command Line",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Clean-up Command Line"
	},
	{
		"Clear Requirements",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Clear Requirements"
	},
	{
		"Client Cert",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Client Cert"
	},
	{
		"Clone Options",
		"Group",
		"Message Areas > Group > Clone Options"
	},
	{
		"Clone Settings",
		"Directory Default Settings",
		"File Areas > Directory Default Settings > Clone Settings"
	},
	{
		"Command Debug",
		"Telnet Support...",
		"Servers > Terminal Server > Telnet Support... > Command Debug"
	},
	{
		"Command Line",
		"Compressible File Type",
		"File Options > Compressible File Types > Compressible File Type > Command Line"
	},
	{
		"Command Line",
		"Ctrl- Hot Key Event",
		"External Programs > Global Hot Key Events > Ctrl- Hot Key Event > Command Line"
	},
	{
		"Command Line",
		"Download Event",
		"File Options > Download Events > Download Event > Command Line"
	},
	{
		"Command Line",
		"Editor",
		"External Programs > Message Editors > Editor > Command Line"
	},
	{
		"Command Line",
		"Event",
		"External Programs > Fixed Events > New User > Event > Command Line"
	},
	{
		"Command Line",
		"Extractable File Type",
		"File Options > Extractable File Types > Extractable File Type > Command Line"
	},
	{
		"Command Line",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Command Line"
	},
	{
		"Command Line",
		"Sysop Chat Pager #",
		"Chat Features > External Sysop Chat Pagers > Sysop Chat Pager # > Command Line"
	},
	{
		"Command Line",
		"Testable File Type",
		"File Options > Testable File Types > Testable File Type > Command Line"
	},
	{
		"Command Line",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Command Line"
	},
	{
		"Command Line",
		"Viewable File Type",
		"File Options > Viewable File Types > Viewable File Type > Command Line"
	},
	{
		"Command Shell",
		"Command Shells",
		"Command Shells > Command Shell"
	},
	{
		"Command Shell",
		"New User Values",
		"System > New User Values > Command Shell"
	},
	{
		"Command Shells",
		"",
		"Command Shells"
	},
	{
		"Compress Messages (LZH)",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Compress Messages (LZH)"
	},
	{
		"Compressible File Type",
		"Compressible File Types",
		"File Options > Compressible File Types > Compressible File Type"
	},
	{
		"Compressible File Types",
		"File Options",
		"File Options > Compressible File Types"
	},
	{
		"Configuration Backups",
		"Advanced Options",
		"System > Advanced Options > Configuration Backups"
	},
	{
		"Configuration File",
		"Services Server",
		"Servers > Services Server > Configuration File"
	},
	{
		"Configure Chat Actions...",
		"Chat Action Set",
		"Chat Features > Multinode Chat Actions > Chat Action Set > Configure Chat Actions..."
	},
	{
		"Connect Timeout",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Connect Timeout"
	},
	{
		"Connect Timeout",
		"SSH Support...",
		"Servers > Terminal Server > SSH Support... > Connect Timeout"
	},
	{
		"Content Root Directory",
		"Web Server",
		"Servers > Web Server > Content Root Directory"
	},
	{
		"Control Key Pass-through",
		"Advanced Options",
		"System > Advanced Options > Control Key Pass-through"
	},
	{
		"Control Port",
		"FTP Server",
		"Servers > FTP Server > Control Port"
	},
	{
		"Cost in Credits",
		"Chat Channel",
		"Chat Features > Multinode Chat Channels > Chat Channel > Cost in Credits"
	},
	{
		"Cost to Send E-mail",
		"Internet E-mail",
		"Networks > Internet E-mail > Cost to Send E-mail"
	},
	{
		"Cost to Send NetMail",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > Cost to Send NetMail"
	},
	{
		"Create Self-signed Certificate",
		"Security Options...",
		"System > Security Options... > Create Self-signed Certificate"
	},
	{
		"Credit Downloads",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Credit Downloads"
	},
	{
		"Credit on Download",
		"Directory",
		"File Areas > Directories > Directory > Credit on Download"
	},
	{
		"Credit on Download",
		"Directory Default Settings",
		"File Areas > Directory Default Settings > Credit on Download"
	},
	{
		"Credit on Upload",
		"Directory",
		"File Areas > Directories > Directory > Credit on Upload"
	},
	{
		"Credit on Upload",
		"Directory Default Settings",
		"File Areas > Directory Default Settings > Credit on Upload"
	},
	{
		"Credit Uploads",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Credit Uploads"
	},
	{
		"Credit with Minutes",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Credit with Minutes"
	},
	{
		"Credits",
		"New User Values",
		"System > New User Values > Credits"
	},
	{
		"Credits Per Dollar",
		"Advanced Options",
		"System > Advanced Options > Credits Per Dollar"
	},
	{
		"Ctrl- Hot Key Event",
		"Global Hot Key Events",
		"External Programs > Global Hot Key Events > Ctrl- Hot Key Event"
	},
	{
		"Daily Event",
		"Node Configuration",
		"Nodes > Node Configuration > Daily Event"
	},
	{
		"Data Directory",
		"Advanced Options",
		"System > Advanced Options > Data Directory"
	},
	{
		"Data Directory",
		"Advanced Options",
		"File Areas > Directories > Directory > Advanced Options > Data Directory"
	},
	{
		"Data Directory",
		"Directory Default Settings",
		"File Areas > Directory Default Settings > Data Directory"
	},
	{
		"Days of New Messages",
		"New User Values",
		"System > New User Values > Days of New Messages"
	},
	{
		"Days of New Messages for Guest",
		"Message Options",
		"Message Options > Days of New Messages for Guest"
	},
	{
		"Days to Preserve Deleted Users",
		"Security Options...",
		"System > Security Options... > Days to Preserve Deleted Users"
	},
	{
		"Deduct Upload Time",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Deduct Upload Time"
	},
	{
		"Default Content-Type",
		"CGI Support...",
		"Servers > Web Server > CGI Support... > Default Content-Type"
	},
	{
		"Default Credit on Download",
		"File Options",
		"File Options > Default Credit on Download"
	},
	{
		"Default Credit on Upload",
		"File Options",
		"File Options > Default Credit on Upload"
	},
	{
		"Default On for New Scan",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Default On for New Scan"
	},
	{
		"Default On for Your Scan",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Default On for Your Scan"
	},
	{
		"Default Origin Line",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > Default Origin Line"
	},
	{
		"Default Recipient",
		"Mail Server",
		"Servers > Mail Server > Default Recipient"
	},
	{
		"Default Tagline",
		"Networks",
		"Networks > Default Tagline"
	},
	{
		"Default Toggles...",
		"New User Values",
		"System > New User Values > Default Toggles..."
	},
	{
		"Delay",
		"Failed Login Attempts...",
		"Servers > FTP Server > Failed Login Attempts... > Delay"
	},
	{
		"Delivery Method",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Delivery Method"
	},
	{
		"Demand High Quality Password",
		"Security Options...",
		"System > Security Options... > Demand High Quality Password"
	},
	{
		"Dhaka",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Dhaka"
	},
	{
		"Directories",
		"File Areas",
		"File Areas > Directories"
	},
	{
		"Directory",
		"CGI Support...",
		"Servers > Web Server > CGI Support... > Directory"
	},
	{
		"Directory",
		"Directories",
		"File Areas > Directories > Directory"
	},
	{
		"Directory Default Settings",
		"File Areas",
		"File Areas > Directory Default Settings"
	},
	{
		"Directory Defaults...",
		"Library",
		"File Areas > Library > Directory Defaults..."
	},
	{
		"Directory Index",
		"Advanced Options",
		"File Areas > Directories > Directory > Advanced Options > Directory Index"
	},
	{
		"Disable Local Display",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Disable Local Display"
	},
	{
		"Display Node List During Logon",
		"Toggle Options",
		"System > Toggle Options > Display Node List During Logon"
	},
	{
		"Display Sys Info During Logon",
		"Toggle Options",
		"System > Toggle Options > Display Sys Info During Logon"
	},
	{
		"Display/Log Passwords Locally",
		"Security Options...",
		"System > Security Options... > Display/Log Passwords Locally"
	},
	{
		"DNS-Blacklisted Servers",
		"Mail Server",
		"Servers > Mail Server > DNS-Blacklisted Servers"
	},
	{
		"DOS Program Support",
		"Terminal Server",
		"Servers > Terminal Server > DOS Program Support"
	},
	{
		"Download Command Line",
		"File Transfer Protocol",
		"File Options > File Transfer Protocols > File Transfer Protocol > Download Command Line"
	},
	{
		"Download Event",
		"Download Events",
		"File Options > Download Events > Download Event"
	},
	{
		"Download Events",
		"File Options",
		"File Options > Download Events"
	},
	{
		"Download Notifications",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Download Notifications"
	},
	{
		"Download Protocol",
		"New User Values",
		"System > New User Values > Download Protocol"
	},
	{
		"Download Requirements",
		"Directory",
		"File Areas > Directories > Directory > Download Requirements"
	},
	{
		"Download Requirements",
		"Library",
		"File Areas > Library > Download Requirements"
	},
	{
		"Downloads Per Day",
		"Security Level Values",
		"System > Security Options... > Security Level Values > Downloads Per Day"
	},
	{
		"Dubai",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Dubai"
	},
	{
		"Duplicate Checking",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Duplicate Checking"
	},
	{
		"Duplicate E-mail Checking",
		"Message Options",
		"Message Options > Duplicate E-mail Checking"
	},
	{
		"Eastern Europe (EET)",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Eastern Europe (EET)"
	},
	{
		"EchoMail Semaphore",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > EchoMail Semaphore"
	},
	{
		"Editor",
		"Message Editors",
		"External Programs > Message Editors > Editor"
	},
	{
		"Editor",
		"New User Values",
		"System > New User Values > Editor"
	},
	{
		"Editor Information Files",
		"Editor",
		"External Programs > Message Editors > Editor > Editor Information Files"
	},
	{
		"Edmonton",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Edmonton"
	},
	{
		"Email Per Day",
		"Security Level Values",
		"System > Security Options... > Security Level Values > Email Per Day"
	},
	{
		"Email Section",
		"Loadable Modules",
		"System > Loadable Modules > Email Section"
	},
	{
		"Enabled",
		"CGI Support...",
		"Servers > Web Server > CGI Support... > Enabled"
	},
	{
		"Enabled",
		"Event",
		"External Programs > Fixed Events > New User > Event > Enabled"
	},
	{
		"Enabled",
		"Filebase Support...",
		"Servers > Web Server > Filebase Support... > Enabled"
	},
	{
		"Enabled",
		"FTP Server",
		"Servers > FTP Server > Enabled"
	},
	{
		"Enabled",
		"HTTP Support...",
		"Servers > Web Server > HTTP Support... > Enabled"
	},
	{
		"Enabled",
		"HTTPS Support...",
		"Servers > Web Server > HTTPS Support... > Enabled"
	},
	{
		"Enabled",
		"Mail Server",
		"Servers > Mail Server > Enabled"
	},
	{
		"Enabled",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Enabled"
	},
	{
		"Enabled",
		"Network Hubs...",
		"Networks > Network Hubs... > Enabled"
	},
	{
		"Enabled",
		"POP3 Support",
		"Servers > Mail Server > POP3 Support > Enabled"
	},
	{
		"Enabled",
		"POP3/TLS Support",
		"Servers > Mail Server > POP3/TLS Support > Enabled"
	},
	{
		"Enabled",
		"RLogin Support...",
		"Servers > Terminal Server > RLogin Support... > Enabled"
	},
	{
		"Enabled",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Enabled"
	},
	{
		"Enabled",
		"Services Server",
		"Servers > Services Server > Enabled"
	},
	{
		"Enabled",
		"SSH Support...",
		"Servers > Terminal Server > SSH Support... > Enabled"
	},
	{
		"Enabled",
		"Submission Support",
		"Servers > Mail Server > Submission Support > Enabled"
	},
	{
		"Enabled",
		"Submission/TLS Support",
		"Servers > Mail Server > Submission/TLS Support > Enabled"
	},
	{
		"Enabled",
		"Telnet Support...",
		"Servers > Terminal Server > Telnet Support... > Enabled"
	},
	{
		"Enabled",
		"Terminal Server",
		"Servers > Terminal Server > Enabled"
	},
	{
		"Enabled",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Enabled"
	},
	{
		"Enabled",
		"Web Server",
		"Servers > Web Server > Enabled"
	},
	{
		"Error Level",
		"Notifications...",
		"System > Notifications... > Error Level"
	},
	{
		"Error Level",
		"SSH Support...",
		"Servers > Terminal Server > SSH Support... > Error Level"
	},
	{
		"Error Log Level",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Error Log Level"
	},
	{
		"Error Notifications",
		"Notifications...",
		"System > Notifications... > Error Notifications"
	},
	{
		"Error Sub-directory",
		"Web Server",
		"Servers > Web Server > Error Sub-directory"
	},
	{
		"Event",
		"New User",
		"External Programs > Fixed Events > New User > Event"
	},
	{
		"Event Log Level",
		"Terminal Server",
		"Servers > Terminal Server > Event Log Level"
	},
	{
		"Exec Directory",
		"Advanced Options",
		"System > Advanced Options > Exec Directory"
	},
	{
		"Execute on Event",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Execute on Event"
	},
	{
		"Execute QWK-related Events",
		"Terminal Server",
		"Servers > Terminal Server > Execute QWK-related Events"
	},
	{
		"Execute Timed Events",
		"Terminal Server",
		"Servers > Terminal Server > Execute Timed Events"
	},
	{
		"Execution Cost",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Execution Cost"
	},
	{
		"Execution Days of Month",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Execution Days of Month"
	},
	{
		"Execution Days of Week",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Execution Days of Week"
	},
	{
		"Execution Frequency",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Execution Frequency"
	},
	{
		"Execution Months",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Execution Months"
	},
	{
		"Execution Node",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Execution Node"
	},
	{
		"Execution Requirements",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Execution Requirements"
	},
	{
		"Execution Time",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Execution Time"
	},
	{
		"Exemption Requirements",
		"Directory",
		"File Areas > Directories > Directory > Exemption Requirements"
	},
	{
		"Exemption Requirements",
		"Library",
		"File Areas > Library > Exemption Requirements"
	},
	{
		"Exemptions",
		"New User Values",
		"System > New User Values > Exemptions"
	},
	{
		"Exemptions",
		"Quick-Validation Set",
		"System > Security Options... > Quick-Validation Set > Exemptions"
	},
	{
		"Exemptions to Remove",
		"Expired Account Values",
		"System > Security Options... > Expired Account Values > Exemptions to Remove"
	},
	{
		"Expand @-codes in Sysop Msgs",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Expand @-codes in Sysop Msgs"
	},
	{
		"Expiration Days",
		"New User Values",
		"System > New User Values > Expiration Days"
	},
	{
		"Expire To",
		"Security Level Values",
		"System > Security Options... > Security Level Values > Expire To"
	},
	{
		"Expired Account Values",
		"Security Options...",
		"System > Security Options... > Expired Account Values"
	},
	{
		"Expired Account Values...",
		"Security Options...",
		"System > Security Options... > Expired Account Values..."
	},
	{
		"Expired User",
		"Loadable Modules",
		"System > Loadable Modules > Expired User"
	},
	{
		"Export Areas...",
		"Group",
		"Message Areas > Group > Export Areas..."
	},
	{
		"Export Areas...",
		"Library",
		"File Areas > Library > Export Areas..."
	},
	{
		"Export ASCII Only",
		"Network Options",
		"Message Areas > Sub-boards > Sub-board > Network Options > Export ASCII Only"
	},
	{
		"Exported Ctrl-A Codes",
		"Network Hubs...",
		"Networks > Network Hubs... > Exported Ctrl-A Codes"
	},
	{
		"Extend Expiration",
		"Quick-Validation Set",
		"System > Security Options... > Quick-Validation Set > Extend Expiration"
	},
	{
		"Extended (QWKE) Packets",
		"Network Hubs...",
		"Networks > Network Hubs... > Extended (QWKE) Packets"
	},
	{
		"Extensions Allowed",
		"Advanced Options",
		"File Areas > Directories > Directory > Advanced Options > Extensions Allowed"
	},
	{
		"Extensions Allowed",
		"Directory Default Settings",
		"File Areas > Directory Default Settings > Extensions Allowed"
	},
	{
		"External Programs",
		"",
		"External Programs"
	},
	{
		"External Sysop Chat Pagers",
		"Chat Features",
		"Chat Features > External Sysop Chat Pagers"
	},
	{
		"Extra Attribute Codes...",
		"System",
		"System > Extra Attribute Codes..."
	},
	{
		"Extra Attribute Codes...",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Extra Attribute Codes..."
	},
	{
		"Extra Time",
		"Online Program Time Options",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Online Program Time Options > Extra Time"
	},
	{
		"Extractable File Type",
		"Extractable File Types",
		"File Options > Extractable File Types > Extractable File Type"
	},
	{
		"Extractable File Types",
		"File Options",
		"File Options > Extractable File Types"
	},
	{
		"Failed Login Attempts...",
		"FTP Server",
		"Servers > FTP Server > Failed Login Attempts..."
	},
	{
		"Failed Login Attempts...",
		"Global Settings",
		"Servers > Global Settings > Failed Login Attempts..."
	},
	{
		"Failed Login Attempts...",
		"Mail Server",
		"Servers > Mail Server > Failed Login Attempts..."
	},
	{
		"Failed Login Attempts...",
		"Services Server",
		"Servers > Services Server > Failed Login Attempts..."
	},
	{
		"Failed Login Attempts...",
		"Terminal Server",
		"Servers > Terminal Server > Failed Login Attempts..."
	},
	{
		"Failed Login Attempts...",
		"Web Server",
		"Servers > Web Server > Failed Login Attempts..."
	},
	{
		"Fernando de Noronha",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Fernando de Noronha"
	},
	{
		"FidoNet Address",
		"Network Options",
		"Message Areas > Sub-boards > Sub-board > Network Options > FidoNet Address"
	},
	{
		"FidoNet Area Tag",
		"Directory",
		"File Areas > Directories > Directory > FidoNet Area Tag"
	},
	{
		"FidoNet Area Tag",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > FidoNet Area Tag"
	},
	{
		"FidoNet EchoMail",
		"Network Options",
		"Message Areas > Sub-boards > Sub-board > Network Options > FidoNet EchoMail"
	},
	{
		"FidoNet EchoMail and NetMail",
		"Networks",
		"Networks > FidoNet EchoMail and NetMail"
	},
	{
		"File Areas",
		"",
		"File Areas"
	},
	{
		"File Directories...",
		"Library",
		"File Areas > Library > File Directories..."
	},
	{
		"File Extension",
		"Compressible File Type",
		"File Options > Compressible File Types > Compressible File Type > File Extension"
	},
	{
		"File Extension",
		"Download Event",
		"File Options > Download Events > Download Event > File Extension"
	},
	{
		"File Extension",
		"Extractable File Type",
		"File Options > Extractable File Types > Extractable File Type > File Extension"
	},
	{
		"File Extension",
		"Testable File Type",
		"File Options > Testable File Types > Testable File Type > File Extension"
	},
	{
		"File Extension",
		"Viewable File Type",
		"File Options > Viewable File Types > Viewable File Type > File Extension"
	},
	{
		"File Extensions",
		"CGI Support...",
		"Servers > Web Server > CGI Support... > File Extensions"
	},
	{
		"File Options",
		"",
		"File Options"
	},
	{
		"File Transfer (SFTP) Support",
		"SSH Support...",
		"Servers > Terminal Server > SSH Support... > File Transfer (SFTP) Support"
	},
	{
		"File Transfer Protocol",
		"File Transfer Protocols",
		"File Options > File Transfer Protocols > File Transfer Protocol"
	},
	{
		"File Transfer Protocols",
		"File Options",
		"File Options > File Transfer Protocols"
	},
	{
		"Filebase Support...",
		"Web Server",
		"Servers > Web Server > Filebase Support..."
	},
	{
		"Fixed Events",
		"External Programs",
		"External Programs > Fixed Events"
	},
	{
		"Flag Set #1",
		"New User Values",
		"System > New User Values > Flag Set #1"
	},
	{
		"Flag Set #1",
		"Quick-Validation Set",
		"System > Security Options... > Quick-Validation Set > Flag Set #1"
	},
	{
		"Flag Set #1 to Remove",
		"Expired Account Values",
		"System > Security Options... > Expired Account Values > Flag Set #1 to Remove"
	},
	{
		"Flag Set #2",
		"New User Values",
		"System > New User Values > Flag Set #2"
	},
	{
		"Flag Set #2",
		"Quick-Validation Set",
		"System > Security Options... > Quick-Validation Set > Flag Set #2"
	},
	{
		"Flag Set #2 to Remove",
		"Expired Account Values",
		"System > Security Options... > Expired Account Values > Flag Set #2 to Remove"
	},
	{
		"Flag Set #3",
		"New User Values",
		"System > New User Values > Flag Set #3"
	},
	{
		"Flag Set #3",
		"Quick-Validation Set",
		"System > Security Options... > Quick-Validation Set > Flag Set #3"
	},
	{
		"Flag Set #3 to Remove",
		"Expired Account Values",
		"System > Security Options... > Expired Account Values > Flag Set #3 to Remove"
	},
	{
		"Flag Set #4",
		"New User Values",
		"System > New User Values > Flag Set #4"
	},
	{
		"Flag Set #4",
		"Quick-Validation Set",
		"System > Security Options... > Quick-Validation Set > Flag Set #4"
	},
	{
		"Flag Set #4 to Remove",
		"Expired Account Values",
		"System > Security Options... > Expired Account Values > Flag Set #4 to Remove"
	},
	{
		"Force Content Ratings",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Force Content Ratings"
	},
	{
		"Force Users Off-line",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Force Users Off-line"
	},
	{
		"Forced On for New Scan",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Forced On for New Scan"
	},
	{
		"Format Output for 80 Columns",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Format Output for 80 Columns"
	},
	{
		"FOSSIL Only",
		"I/O Method",
		"Chat Features > External Sysop Chat Pagers > I/O Method > FOSSIL Only"
	},
	{
		"FOSSIL or UART",
		"I/O Method",
		"Chat Features > External Sysop Chat Pagers > I/O Method > FOSSIL or UART"
	},
	{
		"Free Credits Per Day",
		"Security Level Values",
		"System > Security Options... > Security Level Values > Free Credits Per Day"
	},
	{
		"Free Download Time",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Free Download Time"
	},
	{
		"Free Downloads",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Free Downloads"
	},
	{
		"FTP Server",
		"Servers",
		"Servers > FTP Server"
	},
	{
		"Gate Between Net Types",
		"Network Options",
		"Message Areas > Sub-boards > Sub-board > Network Options > Gate Between Net Types"
	},
	{
		"GC Interval",
		"JavaScript Settings...",
		"Servers > Global Settings > JavaScript Settings... > GC Interval"
	},
	{
		"Gender Options",
		"New User Values",
		"System > New User Values > Gender Options"
	},
	{
		"Global Hot Key",
		"Ctrl- Hot Key Event",
		"External Programs > Global Hot Key Events > Ctrl- Hot Key Event > Global Hot Key"
	},
	{
		"Global Hot Key Events",
		"External Programs",
		"External Programs > Global Hot Key Events"
	},
	{
		"Global Settings",
		"Servers",
		"Servers > Global Settings"
	},
	{
		"Group",
		"Message Areas",
		"Message Areas > Group"
	},
	{
		"Guru",
		"Artificial Gurus",
		"Chat Features > Artificial Gurus > Guru"
	},
	{
		"Guru Internal Code",
		"Guru",
		"Chat Features > Artificial Gurus > Guru > Guru Internal Code"
	},
	{
		"Guru Joins When Empty",
		"Chat Channel",
		"Chat Features > Multinode Chat Channels > Chat Channel > Guru Joins When Empty"
	},
	{
		"Guru Name",
		"Guru",
		"Chat Features > Artificial Gurus > Guru > Guru Name"
	},
	{
		"Hack Log Threshold",
		"Failed Login Attempts...",
		"Servers > FTP Server > Failed Login Attempts... > Hack Log Threshold"
	},
	{
		"Handle Soft CRs",
		"Editor",
		"External Programs > Message Editors > Editor > Handle Soft CRs"
	},
	{
		"Hash DNS-Blacklisted Msgs",
		"Mail Server",
		"Servers > Mail Server > Hash DNS-Blacklisted Msgs"
	},
	{
		"Heap Size",
		"JavaScript Settings...",
		"Servers > Global Settings > JavaScript Settings... > Heap Size"
	},
	{
		"Hong Kong",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Hong Kong"
	},
	{
		"HTTP Support...",
		"Web Server",
		"Servers > Web Server > HTTP Support..."
	},
	{
		"HTTPS Support...",
		"Web Server",
		"Servers > Web Server > HTTPS Support..."
	},
	{
		"Hub System ID",
		"Network Hubs...",
		"Networks > Network Hubs... > Hub System ID"
	},
	{
		"I/O Method",
		"Editor",
		"External Programs > Message Editors > Editor > I/O Method"
	},
	{
		"I/O Method",
		"External Sysop Chat Pagers",
		"Chat Features > External Sysop Chat Pagers > I/O Method"
	},
	{
		"I/O Method",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > I/O Method"
	},
	{
		"I/O Method",
		"Sysop Chat Pager #",
		"Chat Features > External Sysop Chat Pagers > Sysop Chat Pager # > I/O Method"
	},
	{
		"Identity",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Identity"
	},
	{
		"Import Areas...",
		"Group",
		"Message Areas > Group > Import Areas..."
	},
	{
		"Import Areas...",
		"Library",
		"File Areas > Library > Import Areas..."
	},
	{
		"Import Conferences...",
		"Network Hubs...",
		"Networks > Network Hubs... > Import Conferences..."
	},
	{
		"Import FILE_ID.DIZ",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Import FILE_ID.DIZ"
	},
	{
		"Inbound E-mail Semaphore",
		"Internet E-mail",
		"Networks > Internet E-mail > Inbound E-mail Semaphore"
	},
	{
		"Include HEADERS.DAT File",
		"Network Hubs...",
		"Networks > Network Hubs... > Include HEADERS.DAT File"
	},
	{
		"Include Kludge Lines",
		"Network Hubs...",
		"Networks > Network Hubs... > Include Kludge Lines"
	},
	{
		"Include MIME-encoded Text",
		"Network Hubs...",
		"Networks > Network Hubs... > Include MIME-encoded Text"
	},
	{
		"Include Signatures in E-mail",
		"Message Options",
		"Message Options > Include Signatures in E-mail"
	},
	{
		"Include Sysop in Statistics",
		"Toggle Options",
		"System > Toggle Options > Include Sysop in Statistics"
	},
	{
		"Include Transfers In Stats",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Include Transfers In Stats"
	},
	{
		"Include UTF-8 Characters",
		"Network Hubs...",
		"Networks > Network Hubs... > Include UTF-8 Characters"
	},
	{
		"Include VOTING.DAT File",
		"Network Hubs...",
		"Networks > Network Hubs... > Include VOTING.DAT File"
	},
	{
		"Index Filenames",
		"Web Server",
		"Servers > Web Server > Index Filenames"
	},
	{
		"Index Script",
		"Filebase Support...",
		"Servers > Web Server > Filebase Support... > Index Script"
	},
	{
		"Input SIF Questionnaire",
		"Advanced Options",
		"System > Advanced Options > Input SIF Questionnaire"
	},
	{
		"Interfaces",
		"HTTP Support...",
		"Servers > Web Server > HTTP Support... > Interfaces"
	},
	{
		"Interfaces",
		"HTTPS Support...",
		"Servers > Web Server > HTTPS Support... > Interfaces"
	},
	{
		"Interfaces",
		"RLogin Support...",
		"Servers > Terminal Server > RLogin Support... > Interfaces"
	},
	{
		"Interfaces",
		"SSH Support...",
		"Servers > Terminal Server > SSH Support... > Interfaces"
	},
	{
		"Interfaces",
		"Telnet Support...",
		"Servers > Terminal Server > Telnet Support... > Interfaces"
	},
	{
		"Internal Broker",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Internal Broker"
	},
	{
		"Internal Code",
		"Chat Channel",
		"Chat Features > Multinode Chat Channels > Chat Channel > Internal Code"
	},
	{
		"Internal Code",
		"Command Shell",
		"Command Shells > Command Shell > Internal Code"
	},
	{
		"Internal Code",
		"Directory",
		"File Areas > Directories > Directory > Internal Code"
	},
	{
		"Internal Code",
		"Editor",
		"External Programs > Message Editors > Editor > Internal Code"
	},
	{
		"Internal Code",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Internal Code"
	},
	{
		"Internal Code",
		"Program Section",
		"External Programs > Online Programs (Doors) > Program Section > Internal Code"
	},
	{
		"Internal Code",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Internal Code"
	},
	{
		"Internal Code",
		"Text Section Internal Code",
		"Text File Sections > Text Section Internal Code > Internal Code"
	},
	{
		"Internal Code",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Internal Code"
	},
	{
		"Internal Code Prefix",
		"Group",
		"Message Areas > Group > Internal Code Prefix"
	},
	{
		"Internal Code Prefix",
		"Library",
		"File Areas > Library > Internal Code Prefix"
	},
	{
		"Internet (UUCP/NNTP)",
		"Network Options",
		"Message Areas > Sub-boards > Sub-board > Network Options > Internet (UUCP/NNTP)"
	},
	{
		"Internet E-mail",
		"Networks",
		"Networks > Internet E-mail"
	},
	{
		"JavaScript Settings...",
		"Global Settings",
		"Servers > Global Settings > JavaScript Settings..."
	},
	{
		"JavaScript Settings...",
		"Mail Server",
		"Servers > Mail Server > JavaScript Settings..."
	},
	{
		"JavaScript Settings...",
		"Services Server",
		"Servers > Services Server > JavaScript Settings..."
	},
	{
		"JavaScript Settings...",
		"Terminal Server",
		"Servers > Terminal Server > JavaScript Settings..."
	},
	{
		"JavaScript Settings...",
		"Web Server",
		"Servers > Web Server > JavaScript Settings..."
	},
	{
		"Kabul",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Kabul"
	},
	{
		"Karachi",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Karachi"
	},
	{
		"Kathmandu",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Kathmandu"
	},
	{
		"Keep Node File Open",
		"Node Configuration",
		"Nodes > Node Configuration > Keep Node File Open"
	},
	{
		"Keep-alive",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Keep-alive"
	},
	{
		"Key",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Key"
	},
	{
		"Key File",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Key File"
	},
	{
		"Key File Password",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Key File Password"
	},
	{
		"Kill E-mail After Sent",
		"Internet E-mail",
		"Networks > Internet E-mail > Kill E-mail After Sent"
	},
	{
		"Kill NetMail After Sent",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > Kill NetMail After Sent"
	},
	{
		"Kill Read E-mail",
		"Message Options",
		"Message Options > Kill Read E-mail"
	},
	{
		"Kill Read Messages",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Kill Read Messages"
	},
	{
		"Kill SPAM When Read",
		"Mail Server",
		"Servers > Mail Server > Kill SPAM When Read"
	},
	{
		"Last Displayable Node",
		"Advanced Options",
		"System > Advanced Options > Last Displayable Node"
	},
	{
		"Leech Protocol Detection",
		"File Options",
		"File Options > Leech Protocol Detection"
	},
	{
		"Level",
		"Expired Account Values",
		"System > Security Options... > Expired Account Values > Level"
	},
	{
		"Level",
		"New User Values",
		"System > New User Values > Level"
	},
	{
		"Level",
		"Quick-Validation Set",
		"System > Security Options... > Quick-Validation Set > Level"
	},
	{
		"Library",
		"File Areas",
		"File Areas > Library"
	},
	{
		"Limit Rate of Connections",
		"Services Server",
		"Servers > Services Server > Limit Rate of Connections"
	},
	{
		"Limit Rate of Requests",
		"FTP Server",
		"Servers > FTP Server > Limit Rate of Requests"
	},
	{
		"Limit Rate of Requests",
		"Mail Server",
		"Servers > Mail Server > Limit Rate of Requests"
	},
	{
		"Limit Rate of Requests",
		"Web Server",
		"Servers > Web Server > Limit Rate of Requests"
	},
	{
		"Lines Per Message",
		"Security Level Values",
		"System > Security Options... > Security Level Values > Lines Per Message"
	},
	{
		"List Files",
		"Loadable Modules",
		"System > Loadable Modules > List Files"
	},
	{
		"List Logons",
		"Loadable Modules",
		"System > Loadable Modules > List Logons"
	},
	{
		"List Msgs",
		"Loadable Modules",
		"System > Loadable Modules > List Msgs"
	},
	{
		"List Nodes",
		"Loadable Modules",
		"System > Loadable Modules > List Nodes"
	},
	{
		"List Users",
		"Loadable Modules",
		"System > Loadable Modules > List Users"
	},
	{
		"Load Path",
		"JavaScript Settings...",
		"Servers > Global Settings > JavaScript Settings... > Load Path"
	},
	{
		"Loadable Modules",
		"System",
		"System > Loadable Modules"
	},
	{
		"Loadable Modules...",
		"System",
		"System > Loadable Modules..."
	},
	{
		"Local Time Zone",
		"System",
		"System > Local Time Zone"
	},
	{
		"Location",
		"System",
		"System > Location"
	},
	{
		"Log Level",
		"FTP Server",
		"Servers > FTP Server > Log Level"
	},
	{
		"Log Level",
		"Global Settings",
		"Servers > Global Settings > Log Level"
	},
	{
		"Log Level",
		"Mail Server",
		"Servers > Mail Server > Log Level"
	},
	{
		"Log Level",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Log Level"
	},
	{
		"Log Level",
		"Services Server",
		"Servers > Services Server > Log Level"
	},
	{
		"Log Level",
		"Terminal Server",
		"Servers > Terminal Server > Log Level"
	},
	{
		"Log Level",
		"Web Server",
		"Servers > Web Server > Log Level"
	},
	{
		"Login",
		"Loadable Modules",
		"System > Loadable Modules > Login"
	},
	{
		"Login",
		"Loadable Modules...",
		"System > Loadable Modules... > Login"
	},
	{
		"Login Info Save",
		"FTP Server",
		"Servers > FTP Server > Login Info Save"
	},
	{
		"Login Info Save",
		"Services Server",
		"Servers > Services Server > Login Info Save"
	},
	{
		"Login Info Save",
		"Web Server",
		"Servers > Web Server > Login Info Save"
	},
	{
		"Login Requirements",
		"FTP Server",
		"Servers > FTP Server > Login Requirements"
	},
	{
		"Login Requirements",
		"Global Settings",
		"Servers > Global Settings > Login Requirements"
	},
	{
		"Login Requirements",
		"Mail Server",
		"Servers > Mail Server > Login Requirements"
	},
	{
		"Login Requirements",
		"Node Configuration",
		"Nodes > Node Configuration > Login Requirements"
	},
	{
		"Login Requirements",
		"Services Server",
		"Servers > Services Server > Login Requirements"
	},
	{
		"Login Requirements",
		"Terminal Server",
		"Servers > Terminal Server > Login Requirements"
	},
	{
		"Login Requirements",
		"Web Server",
		"Servers > Web Server > Login Requirements"
	},
	{
		"Logoff",
		"Loadable Modules",
		"System > Loadable Modules > Logoff"
	},
	{
		"Logon",
		"Fixed Events",
		"External Programs > Fixed Events > Logon"
	},
	{
		"Logon",
		"Loadable Modules",
		"System > Loadable Modules > Logon"
	},
	{
		"Logout",
		"Fixed Events",
		"External Programs > Fixed Events > Logout"
	},
	{
		"Logout",
		"Loadable Modules",
		"System > Loadable Modules > Logout"
	},
	{
		"Logs Directory",
		"Advanced Options",
		"System > Advanced Options > Logs Directory"
	},
	{
		"Long Name",
		"Directory",
		"File Areas > Directories > Directory > Long Name"
	},
	{
		"Long Name",
		"Group",
		"Message Areas > Group > Long Name"
	},
	{
		"Long Name",
		"Library",
		"File Areas > Library > Long Name"
	},
	{
		"Long Name",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Long Name"
	},
	{
		"Lookup Client Hostname",
		"FTP Server",
		"Servers > FTP Server > Lookup Client Hostname"
	},
	{
		"Lookup Client Hostname",
		"Mail Server",
		"Servers > Mail Server > Lookup Client Hostname"
	},
	{
		"Lookup Client Hostname",
		"Services Server",
		"Servers > Services Server > Lookup Client Hostname"
	},
	{
		"Lookup Client Hostname",
		"Terminal Server",
		"Servers > Terminal Server > Lookup Client Hostname"
	},
	{
		"Lookup Client Hostname",
		"Web Server",
		"Servers > Web Server > Lookup Client Hostname"
	},
	{
		"Mail Database Backups",
		"Advanced Options",
		"System > Advanced Options > Mail Database Backups"
	},
	{
		"Mail Server",
		"Servers",
		"Servers > Mail Server"
	},
	{
		"MailBase Storage Method",
		"Message Options",
		"Message Options > MailBase Storage Method"
	},
	{
		"Mark Moved Files as New",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Mark Moved Files as New"
	},
	{
		"Mark Retrieved Mail as Read",
		"Mail Server",
		"Servers > Mail Server > Mark Retrieved Mail as Read"
	},
	{
		"Max Clients",
		"FTP Server",
		"Servers > FTP Server > Max Clients"
	},
	{
		"Max Clients",
		"Mail Server",
		"Servers > Mail Server > Max Clients"
	},
	{
		"Max Clients",
		"Web Server",
		"Servers > Web Server > Max Clients"
	},
	{
		"Max Concurrent Connections",
		"FTP Server",
		"Servers > FTP Server > Max Concurrent Connections"
	},
	{
		"Max Concurrent Connections",
		"Mail Server",
		"Servers > Mail Server > Max Concurrent Connections"
	},
	{
		"Max Concurrent Connections",
		"Terminal Server",
		"Servers > Terminal Server > Max Concurrent Connections"
	},
	{
		"Max Concurrent Connections",
		"Web Server",
		"Servers > Web Server > Max Concurrent Connections"
	},
	{
		"Max Delivery Attempts",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Max Delivery Attempts"
	},
	{
		"Max Dumb Login Inactivity",
		"Terminal Server",
		"Servers > Terminal Server > Max Dumb Login Inactivity"
	},
	{
		"Max Files in Batch DL Queue",
		"File Options",
		"File Options > Max Files in Batch DL Queue"
	},
	{
		"Max Files in Batch UL Queue",
		"File Options",
		"File Options > Max Files in Batch UL Queue"
	},
	{
		"Max Inactivity",
		"CGI Support...",
		"Servers > Web Server > CGI Support... > Max Inactivity"
	},
	{
		"Max Inactivity",
		"FTP Server",
		"Servers > FTP Server > Max Inactivity"
	},
	{
		"Max Inactivity",
		"Mail Server",
		"Servers > Mail Server > Max Inactivity"
	},
	{
		"Max Inactivity",
		"Web Server",
		"Servers > Web Server > Max Inactivity"
	},
	{
		"Max Messages Waiting",
		"Mail Server",
		"Servers > Mail Server > Max Messages Waiting"
	},
	{
		"Max New User Inactivity",
		"Terminal Server",
		"Servers > Terminal Server > Max New User Inactivity"
	},
	{
		"Max Receive Message Size",
		"Mail Server",
		"Servers > Mail Server > Max Receive Message Size"
	},
	{
		"Max Recipients Per Message",
		"Mail Server",
		"Servers > Mail Server > Max Recipients Per Message"
	},
	{
		"Max SFTP Inactivity",
		"SSH Support...",
		"Servers > Terminal Server > SSH Support... > Max SFTP Inactivity"
	},
	{
		"Max Uploaded File Size",
		"FTP Server",
		"Servers > FTP Server > Max Uploaded File Size"
	},
	{
		"Max User Inactivity",
		"Terminal Server",
		"Servers > Terminal Server > Max User Inactivity"
	},
	{
		"Max User Login Inactivity",
		"Terminal Server",
		"Servers > Terminal Server > Max User Login Inactivity"
	},
	{
		"Max Users in User Transfers",
		"File Options",
		"File Options > Max Users in User Transfers"
	},
	{
		"Maximum (Unauthenticated)",
		"Max Concurrent Connections",
		"Servers > Terminal Server > Max Concurrent Connections > Maximum (Unauthenticated)"
	},
	{
		"Maximum Days of User Inactivity",
		"Security Options...",
		"System > Security Options... > Maximum Days of User Inactivity"
	},
	{
		"Maximum Inactivity",
		"Online Program Time Options",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Online Program Time Options > Maximum Inactivity"
	},
	{
		"Maximum Log File Size",
		"Advanced Options",
		"System > Advanced Options > Maximum Log File Size"
	},
	{
		"Maximum Messages",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Maximum Messages"
	},
	{
		"Maximum Number of Files",
		"Directory",
		"File Areas > Directories > Directory > Maximum Number of Files"
	},
	{
		"Maximum Number of Files",
		"Directory Default Settings",
		"File Areas > Directory Default Settings > Maximum Number of Files"
	},
	{
		"Maximum Number of Minutes",
		"Advanced Options",
		"System > Advanced Options > Maximum Number of Minutes"
	},
	{
		"Maximum QWK Message Age",
		"Message Options",
		"Message Options > Maximum QWK Message Age"
	},
	{
		"Maximum QWK Messages",
		"Message Options",
		"Message Options > Maximum QWK Messages"
	},
	{
		"Maximum Retry Time",
		"Message Options",
		"Message Options > Maximum Retry Time"
	},
	{
		"Maximum Time",
		"Online Program Time Options",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Online Program Time Options > Maximum Time"
	},
	{
		"Maximum User Inactivity",
		"Advanced Options",
		"System > Advanced Options > Maximum User Inactivity"
	},
	{
		"Message Areas",
		"",
		"Message Areas"
	},
	{
		"Message Editors",
		"External Programs",
		"External Programs > Message Editors"
	},
	{
		"Message Options",
		"",
		"Message Options"
	},
	{
		"Message Queue Telemetry Transport",
		"Networks",
		"Networks > Message Queue Telemetry Transport"
	},
	{
		"Message Sub-boards...",
		"Group",
		"Message Areas > Group > Message Sub-boards..."
	},
	{
		"Midway",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Midway"
	},
	{
		"Military (24 hour) Time Format",
		"Toggle Options",
		"System > Toggle Options > Military (24 hour) Time Format"
	},
	{
		"Min Uploaded File Size",
		"FTP Server",
		"Servers > FTP Server > Min Uploaded File Size"
	},
	{
		"Minimum Free Disk Space",
		"File Options",
		"File Options > Minimum Free Disk Space"
	},
	{
		"Minutes",
		"New User Values",
		"System > New User Values > Minutes"
	},
	{
		"Minutes Per 100K Credits",
		"Advanced Options",
		"System > Advanced Options > Minutes Per 100K Credits"
	},
	{
		"Mnemonic (Command Key)",
		"File Transfer Protocol",
		"File Options > File Transfer Protocols > File Transfer Protocol > Mnemonic (Command Key)"
	},
	{
		"Moderated Posting User",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Moderated Posting User"
	},
	{
		"Modify User Data",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Modify User Data"
	},
	{
		"Mods Directory",
		"Advanced Options",
		"System > Advanced Options > Mods Directory"
	},
	{
		"Module",
		"Login",
		"System > Loadable Modules... > Login > Module"
	},
	{
		"Monitor Time Left",
		"Online Program Time Options",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Online Program Time Options > Monitor Time Left"
	},
	{
		"Moscow",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Moscow"
	},
	{
		"Mouse Hot-spots in Menus/Prompts",
		"Toggle Options",
		"System > Toggle Options > Mouse Hot-spots in Menus/Prompts"
	},
	{
		"Multinode Chat Actions",
		"Chat Features",
		"Chat Features > Multinode Chat Actions"
	},
	{
		"Multinode Chat Channels",
		"Chat Features",
		"Chat Features > Multinode Chat Channels"
	},
	{
		"Multiple Concurrent Users",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Multiple Concurrent Users"
	},
	{
		"Multiple File Numberings",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Multiple File Numberings"
	},
	{
		"Name",
		"Chat Channel",
		"Chat Features > Multinode Chat Channels > Chat Channel > Name"
	},
	{
		"Name",
		"Command Shell",
		"Command Shells > Command Shell > Name"
	},
	{
		"Name",
		"Editor",
		"External Programs > Message Editors > Editor > Name"
	},
	{
		"Name",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Name"
	},
	{
		"Name",
		"Program Section",
		"External Programs > Online Programs (Doors) > Program Section > Name"
	},
	{
		"Name",
		"Text Section Internal Code",
		"Text File Sections > Text Section Internal Code > Name"
	},
	{
		"Name / Command-line",
		"Module",
		"System > Loadable Modules... > Login > Module > Name / Command-line"
	},
	{
		"Native Call-out Command",
		"Network Hubs...",
		"Networks > Network Hubs... > Native Call-out Command"
	},
	{
		"Native Program List",
		"External Programs",
		"External Programs > Native Program List"
	},
	{
		"NetMail Defaults to Crash",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > NetMail Defaults to Crash"
	},
	{
		"NetMail Defaults to Direct",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > NetMail Defaults to Direct"
	},
	{
		"NetMail Defaults to Hold",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > NetMail Defaults to Hold"
	},
	{
		"NetMail Directory",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > NetMail Directory"
	},
	{
		"NetMail Semaphore",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > NetMail Semaphore"
	},
	{
		"Network Hubs...",
		"Networks",
		"Networks > Network Hubs..."
	},
	{
		"Network Interfaces",
		"FTP Server",
		"Servers > FTP Server > Network Interfaces"
	},
	{
		"Network Interfaces",
		"Services Server",
		"Servers > Services Server > Network Interfaces"
	},
	{
		"Network Interfaces (IPv4/6)",
		"Global Settings",
		"Servers > Global Settings > Network Interfaces (IPv4/6)"
	},
	{
		"Network Options",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Network Options"
	},
	{
		"Network Options...",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Network Options..."
	},
	{
		"Networked Sub-boards...",
		"Network Hubs...",
		"Networks > Network Hubs... > Networked Sub-boards..."
	},
	{
		"Networks",
		"",
		"Networks"
	},
	{
		"New User",
		"Fixed Events",
		"External Programs > Fixed Events > New User"
	},
	{
		"New User Created",
		"Loadable Modules",
		"System > Loadable Modules > New User Created"
	},
	{
		"New User Feedback",
		"Notifications...",
		"System > Notifications... > New User Feedback"
	},
	{
		"New User Info",
		"Loadable Modules",
		"System > Loadable Modules > New User Info"
	},
	{
		"New User Magic Word",
		"Advanced Options",
		"System > Advanced Options > New User Magic Word"
	},
	{
		"New User Prompts",
		"Loadable Modules",
		"System > Loadable Modules > New User Prompts"
	},
	{
		"New User Prompts...",
		"System",
		"System > New User Prompts..."
	},
	{
		"New User Values",
		"System",
		"System > New User Values"
	},
	{
		"New User Values...",
		"System",
		"System > New User Values..."
	},
	{
		"New Zealand",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > New Zealand"
	},
	{
		"Newsgroup Name",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Newsgroup Name"
	},
	{
		"Node Configuration",
		"Nodes",
		"Nodes > Node Configuration"
	},
	{
		"Node Directory",
		"Node Configuration",
		"Nodes > Node Configuration > Node Directory"
	},
	{
		"Nodes",
		"",
		"Nodes"
	},
	{
		"Non-U.S. Time Zone",
		"",
		"Non-U.S. Time Zone"
	},
	{
		"Notifications...",
		"System",
		"System > Notifications..."
	},
	{
		"Notify Local Recipients",
		"Mail Server",
		"Servers > Mail Server > Notify Local Recipients"
	},
	{
		"Notify Offline Recipients",
		"Mail Server",
		"Servers > Mail Server > Notify Offline Recipients"
	},
	{
		"Noumea",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Noumea"
	},
	{
		"Online Program",
		"Online Programs...",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program"
	},
	{
		"Online Program Time Options",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Online Program Time Options"
	},
	{
		"Online Programs (Doors)",
		"External Programs",
		"External Programs > Online Programs (Doors)"
	},
	{
		"Online Programs...",
		"Online Programs (Doors)",
		"External Programs > Online Programs (Doors) > Online Programs..."
	},
	{
		"Online Programs...",
		"Program Section",
		"External Programs > Online Programs (Doors) > Program Section > Online Programs..."
	},
	{
		"Open to New Users",
		"Security Options...",
		"System > Security Options... > Open to New Users"
	},
	{
		"Operator",
		"System",
		"System > Operator"
	},
	{
		"Operator Requirements",
		"Directory",
		"File Areas > Directories > Directory > Operator Requirements"
	},
	{
		"Operator Requirements",
		"Library",
		"File Areas > Library > Operator Requirements"
	},
	{
		"Operator Requirements",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Operator Requirements"
	},
	{
		"Other...",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Other..."
	},
	{
		"Outbound E-mail Semaphore",
		"Internet E-mail",
		"Networks > Internet E-mail > Outbound E-mail Semaphore"
	},
	{
		"Outbound Interface (IPv4)",
		"Global Settings",
		"Servers > Global Settings > Outbound Interface (IPv4)"
	},
	{
		"Output Buffer Drain Timeout",
		"Terminal Server",
		"Servers > Terminal Server > Output Buffer Drain Timeout"
	},
	{
		"Output Buffer Drain Timeout",
		"Web Server",
		"Servers > Web Server > Output Buffer Drain Timeout"
	},
	{
		"Output SIF Questionnaire",
		"Advanced Options",
		"System > Advanced Options > Output SIF Questionnaire"
	},
	{
		"Pack Command Line",
		"Advanced Options",
		"Networks > Network Hubs... > Advanced Options > Pack Command Line"
	},
	{
		"Parent Directory",
		"Library",
		"File Areas > Library > Parent Directory"
	},
	{
		"Passive Interface (IPv4)",
		"FTP Server",
		"Servers > FTP Server > Passive Interface (IPv4)"
	},
	{
		"Passive Port Range",
		"FTP Server",
		"Servers > FTP Server > Passive Port Range"
	},
	{
		"Password",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Password"
	},
	{
		"Password Protection",
		"Chat Channel",
		"Chat Features > Multinode Chat Channels > Chat Channel > Password Protection"
	},
	{
		"Pause After Execution",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Pause After Execution"
	},
	{
		"Permanent Operator Msgs",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Permanent Operator Msgs"
	},
	{
		"Phone Number",
		"Node Configuration",
		"Nodes > Node Configuration > Phone Number"
	},
	{
		"Phone Number Format",
		"Advanced Options",
		"System > Advanced Options > Phone Number Format"
	},
	{
		"Place Drop File In",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Place Drop File In"
	},
	{
		"Pointer File Index",
		"Advanced Options",
		"Message Areas > Sub-boards > Sub-board > Advanced Options > Pointer File Index"
	},
	{
		"POP3 Interfaces",
		"Mail Server",
		"Servers > Mail Server > POP3 Interfaces"
	},
	{
		"POP3 Support",
		"Mail Server",
		"Servers > Mail Server > POP3 Support"
	},
	{
		"POP3/TLS Support",
		"Mail Server",
		"Servers > Mail Server > POP3/TLS Support"
	},
	{
		"Port",
		"HTTP Support...",
		"Servers > Web Server > HTTP Support... > Port"
	},
	{
		"Port",
		"HTTPS Support...",
		"Servers > Web Server > HTTPS Support... > Port"
	},
	{
		"Port",
		"POP3 Support",
		"Servers > Mail Server > POP3 Support > Port"
	},
	{
		"Port",
		"POP3/TLS Support",
		"Servers > Mail Server > POP3/TLS Support > Port"
	},
	{
		"Port",
		"RLogin Support...",
		"Servers > Terminal Server > RLogin Support... > Port"
	},
	{
		"Port",
		"SSH Support...",
		"Servers > Terminal Server > SSH Support... > Port"
	},
	{
		"Port",
		"Submission Support",
		"Servers > Mail Server > Submission Support > Port"
	},
	{
		"Port",
		"Submission/TLS Support",
		"Servers > Mail Server > Submission/TLS Support > Port"
	},
	{
		"Port",
		"Telnet Support...",
		"Servers > Terminal Server > Telnet Support... > Port"
	},
	{
		"Post Recipient",
		"Mail Server",
		"Servers > Mail Server > Post Recipient"
	},
	{
		"Post Using Real Names",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Post Using Real Names"
	},
	{
		"Post Xtrn",
		"Loadable Modules",
		"System > Loadable Modules > Post Xtrn"
	},
	{
		"Posting Requirements",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Posting Requirements"
	},
	{
		"Posts Per Day",
		"Security Level Values",
		"System > Security Options... > Security Level Values > Posts Per Day"
	},
	{
		"Pre Xtrn",
		"Loadable Modules",
		"System > Loadable Modules > Pre Xtrn"
	},
	{
		"Private Msg",
		"Loadable Modules",
		"System > Loadable Modules > Private Msg"
	},
	{
		"Program Section",
		"Online Programs (Doors)",
		"External Programs > Online Programs (Doors) > Program Section"
	},
	{
		"Prompt for System Password",
		"Security Options...",
		"System > Security Options... > Prompt for System Password"
	},
	{
		"Protocol Name",
		"File Transfer Protocol",
		"File Options > File Transfer Protocols > File Transfer Protocol > Protocol Name"
	},
	{
		"Protocol Version",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Protocol Version"
	},
	{
		"Public 'To' User",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Public 'To' User"
	},
	{
		"Publish QOS",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Publish QOS"
	},
	{
		"Publish Verbosity",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Publish Verbosity"
	},
	{
		"Purge by Age",
		"Directory",
		"File Areas > Directories > Directory > Purge by Age"
	},
	{
		"Purge by Age",
		"Directory Default Settings",
		"File Areas > Directory Default Settings > Purge by Age"
	},
	{
		"Purge by Age",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Purge by Age"
	},
	{
		"Purge by Last Download",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Purge by Last Download"
	},
	{
		"Purge Deleted E-mail",
		"Message Options",
		"Message Options > Purge Deleted E-mail"
	},
	{
		"Purge E-mail by Age",
		"Message Options",
		"Message Options > Purge E-mail by Age"
	},
	{
		"Purge SPAM by Age",
		"Message Options",
		"Message Options > Purge SPAM by Age"
	},
	{
		"Quick-Validation Set",
		"Security Options...",
		"System > Security Options... > Quick-Validation Set"
	},
	{
		"Quick-Validation Values...",
		"Security Options...",
		"System > Security Options... > Quick-Validation Values..."
	},
	{
		"QWK Conference Number",
		"Advanced Options",
		"Message Areas > Sub-boards > Sub-board > Advanced Options > QWK Conference Number"
	},
	{
		"QWK Message Packet Timeout",
		"FTP Server",
		"Servers > FTP Server > QWK Message Packet Timeout"
	},
	{
		"QWK Message Packet Transfers",
		"FTP Server",
		"Servers > FTP Server > QWK Message Packet Transfers"
	},
	{
		"QWK Name",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > QWK Name"
	},
	{
		"QWK Networked",
		"Network Options",
		"Message Areas > Sub-boards > Sub-board > Network Options > QWK Networked"
	},
	{
		"QWK Packet Settings...",
		"New User Values",
		"System > New User Values > QWK Packet Settings..."
	},
	{
		"Read Mail",
		"Loadable Modules",
		"System > Loadable Modules > Read Mail"
	},
	{
		"Reading Requirements",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Reading Requirements"
	},
	{
		"Receive By Sysop Aliases",
		"Mail Server",
		"Servers > Mail Server > Receive By Sysop Aliases"
	},
	{
		"Receive E-mail by Real Name",
		"Message Options",
		"Message Options > Receive E-mail by Real Name"
	},
	{
		"Record Terminal Width",
		"Editor",
		"External Programs > Message Editors > Editor > Record Terminal Width"
	},
	{
		"Relay Server Address",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Relay Server Address"
	},
	{
		"Relay Server Authentication",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Relay Server Authentication"
	},
	{
		"Relay Server Password",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Relay Server Password"
	},
	{
		"Relay Server TCP Port",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Relay Server TCP Port"
	},
	{
		"Relay Server Username",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Relay Server Username"
	},
	{
		"Requires Exclusive Exec",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Requires Exclusive Exec"
	},
	{
		"Rescan Interval",
		"SendMail Support...",
		"Servers > Mail Server > SendMail Support... > Rescan Interval"
	},
	{
		"Restrictions",
		"New User Values",
		"System > New User Values > Restrictions"
	},
	{
		"Restrictions",
		"Quick-Validation Set",
		"System > Security Options... > Quick-Validation Set > Restrictions"
	},
	{
		"Restrictions to Add",
		"Expired Account Values",
		"System > Security Options... > Expired Account Values > Restrictions to Add"
	},
	{
		"Retain Ctrl-A Codes in Quotes",
		"Editor",
		"External Programs > Message Editors > Editor > Retain Ctrl-A Codes in Quotes"
	},
	{
		"Rio de Janeiro",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Rio de Janeiro"
	},
	{
		"RLogin Support...",
		"Terminal Server",
		"Servers > Terminal Server > RLogin Support..."
	},
	{
		"Scan Dirs",
		"Loadable Modules",
		"System > Loadable Modules > Scan Dirs"
	},
	{
		"Scan Msgs",
		"Loadable Modules",
		"System > Loadable Modules > Scan Msgs"
	},
	{
		"Scan Subs",
		"Loadable Modules",
		"System > Loadable Modules > Scan Subs"
	},
	{
		"Search for Auto-ADDFILES",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Search for Auto-ADDFILES"
	},
	{
		"Search for Duplicates",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Search for Duplicates"
	},
	{
		"Search for New Files",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Search for New Files"
	},
	{
		"Security Level Values",
		"Security Options...",
		"System > Security Options... > Security Level Values"
	},
	{
		"Security Level Values...",
		"Security Options...",
		"System > Security Options... > Security Level Values..."
	},
	{
		"Security Options...",
		"System",
		"System > Security Options..."
	},
	{
		"Select Item",
		"Loadable Modules",
		"System > Loadable Modules > Select Item"
	},
	{
		"Sem File Check Interval",
		"Global Settings",
		"Servers > Global Settings > Sem File Check Interval"
	},
	{
		"Semaphore File",
		"Advanced Options",
		"Message Areas > Sub-boards > Sub-board > Advanced Options > Semaphore File"
	},
	{
		"Send E-mail Using Alias",
		"Internet E-mail",
		"Networks > Internet E-mail > Send E-mail Using Alias"
	},
	{
		"Send Feedback",
		"Loadable Modules",
		"System > Loadable Modules > Send Feedback"
	},
	{
		"Send Go-Aheads",
		"Telnet Support...",
		"Servers > Terminal Server > Telnet Support... > Send Go-Aheads"
	},
	{
		"Send NetMail Using Alias",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > Send NetMail Using Alias"
	},
	{
		"SendMail Support...",
		"Mail Server",
		"Servers > Mail Server > SendMail Support..."
	},
	{
		"Servers",
		"",
		"Servers"
	},
	{
		"Services Server",
		"Servers",
		"Servers > Services Server"
	},
	{
		"Serving Nodes",
		"Terminal Server",
		"Servers > Terminal Server > Serving Nodes"
	},
	{
		"Set Required Age",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Age"
	},
	{
		"Set Required Day of Week",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Day of Week"
	},
	{
		"Set Required Gender",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Gender"
	},
	{
		"Set Required Number of Credits",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Number of Credits"
	},
	{
		"Set Required Post/Call Ratio (percentage)",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Post/Call Ratio (percentage)"
	},
	{
		"Set Required Security Flag",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Security Flag"
	},
	{
		"Set Required Security Level",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Security Level"
	},
	{
		"Set Required Terminal Type/Capability",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Terminal Type/Capability"
	},
	{
		"Set Required Time of Day",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Time of Day"
	},
	{
		"Set Required Time Remaining",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Time Remaining"
	},
	{
		"Set Required Upload/Download Byte Ratio (percentage)",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Upload/Download Byte Ratio (percentage)"
	},
	{
		"Set Required Upload/Download File Ratio (percentage)",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required Upload/Download File Ratio (percentage)"
	},
	{
		"Set Required User Number",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required User Number"
	},
	{
		"Set Required User Type (e.g. Sysop, Guest)",
		"Access Requirements",
		"Chat Features > Multinode Chat Channels > Access Requirements > Set Required User Type (e.g. Sysop, Guest)"
	},
	{
		"Short Date Format",
		"System",
		"System > Short Date Format"
	},
	{
		"Short Name",
		"Directory",
		"File Areas > Directories > Directory > Short Name"
	},
	{
		"Short Name",
		"Group",
		"Message Areas > Group > Short Name"
	},
	{
		"Short Name",
		"Library",
		"File Areas > Library > Short Name"
	},
	{
		"Short Name",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Short Name"
	},
	{
		"Short Sysop Page",
		"Toggle Options",
		"System > Toggle Options > Short Sysop Page"
	},
	{
		"SMTP Interfaces",
		"Mail Server",
		"Servers > Mail Server > SMTP Interfaces"
	},
	{
		"SMTP Support",
		"Mail Server",
		"Servers > Mail Server > SMTP Support"
	},
	{
		"Socket",
		"I/O Method",
		"Chat Features > External Sysop Chat Pagers > I/O Method > Socket"
	},
	{
		"Socket I/O",
		"File Transfer Protocol",
		"File Options > File Transfer Protocols > File Transfer Protocol > Socket I/O"
	},
	{
		"Sort Group by Sub-board",
		"Group",
		"Message Areas > Group > Sort Group by Sub-board"
	},
	{
		"Sort Library By Directory",
		"Library",
		"File Areas > Library > Sort Library By Directory"
	},
	{
		"Sort Value and Direction",
		"Advanced Options",
		"File Areas > Directories > Directory > Advanced Options > Sort Value and Direction"
	},
	{
		"Sort Value and Direction",
		"Directory Default Settings",
		"File Areas > Directory Default Settings > Sort Value and Direction"
	},
	{
		"Spammer IP-Filter Duration",
		"Mail Server",
		"Servers > Mail Server > Spammer IP-Filter Duration"
	},
	{
		"Spinning Cursor at Pause Prompts",
		"Toggle Options",
		"System > Toggle Options > Spinning Cursor at Pause Prompts"
	},
	{
		"SSH Support...",
		"Terminal Server",
		"Servers > Terminal Server > SSH Support..."
	},
	{
		"SSJS File Extension",
		"Web Server",
		"Servers > Web Server > SSJS File Extension"
	},
	{
		"Standard",
		"I/O Method",
		"Chat Features > External Sysop Chat Pagers > I/O Method > Standard"
	},
	{
		"Start-up Directory",
		"Online Program",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Start-up Directory"
	},
	{
		"Start-up Directory",
		"Timed Event",
		"External Programs > Timed Events > Timed Event > Start-up Directory"
	},
	{
		"Statistics Interval",
		"Advanced Options",
		"System > Advanced Options > Statistics Interval"
	},
	{
		"Storage Directory",
		"Advanced Options",
		"Message Areas > Sub-boards > Sub-board > Advanced Options > Storage Directory"
	},
	{
		"Storage Method",
		"Advanced Options",
		"Message Areas > Sub-boards > Sub-board > Advanced Options > Storage Method"
	},
	{
		"Strict Transport Security",
		"HTTPS Support...",
		"Servers > Web Server > HTTPS Support... > Strict Transport Security"
	},
	{
		"Strip FidoNet Kludges",
		"Editor",
		"External Programs > Message Editors > Editor > Strip FidoNet Kludges"
	},
	{
		"Sub-board",
		"Sub-boards",
		"Message Areas > Sub-boards > Sub-board"
	},
	{
		"Sub-board Index",
		"Advanced Options",
		"Message Areas > Sub-boards > Sub-board > Advanced Options > Sub-board Index"
	},
	{
		"Sub-boards",
		"Message Areas",
		"Message Areas > Sub-boards"
	},
	{
		"Submission Support",
		"Mail Server",
		"Servers > Mail Server > Submission Support"
	},
	{
		"Submission/TLS Support",
		"Mail Server",
		"Servers > Mail Server > Submission/TLS Support"
	},
	{
		"Subscribe QOS",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Subscribe QOS"
	},
	{
		"Support UTF-8 Encoding",
		"Editor",
		"External Programs > Message Editors > Editor > Support UTF-8 Encoding"
	},
	{
		"Supported Archive Formats",
		"File Options",
		"File Options > Supported Archive Formats"
	},
	{
		"Supports DSZLOG",
		"File Transfer Protocol",
		"File Options > File Transfer Protocols > File Transfer Protocol > Supports DSZLOG"
	},
	{
		"Suppress User Signatures",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Suppress User Signatures"
	},
	{
		"Suspended (Free) Time",
		"Online Program Time Options",
		"External Programs > Online Programs (Doors) > Online Programs... > Online Program > Online Program Time Options > Suspended (Free) Time"
	},
	{
		"Sync",
		"Loadable Modules",
		"System > Loadable Modules > Sync"
	},
	{
		"Sysop Chat Override",
		"Advanced Options",
		"System > Advanced Options > Sysop Chat Override"
	},
	{
		"Sysop Chat Pager #",
		"External Sysop Chat Pagers",
		"Chat Features > External Sysop Chat Pagers > Sysop Chat Pager #"
	},
	{
		"Sysop File System Access",
		"FTP Server",
		"Servers > FTP Server > Sysop File System Access"
	},
	{
		"System",
		"",
		"System"
	},
	{
		"System Address",
		"Internet E-mail",
		"Networks > Internet E-mail > System Address"
	},
	{
		"System Addresses",
		"FidoNet EchoMail and NetMail",
		"Networks > FidoNet EchoMail and NetMail > System Addresses"
	},
	{
		"System Password",
		"Security Options...",
		"System > Security Options... > System Password"
	},
	{
		"Telnet Support...",
		"Terminal Server",
		"Servers > Terminal Server > Telnet Support..."
	},
	{
		"Temp Transfer",
		"Loadable Modules",
		"System > Loadable Modules > Temp Transfer"
	},
	{
		"Template for New Subs",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Template for New Subs"
	},
	{
		"Temporary Ban Duration",
		"Failed Login Attempts...",
		"Servers > FTP Server > Failed Login Attempts... > Temporary Ban Duration"
	},
	{
		"Temporary Ban Threshold",
		"Failed Login Attempts...",
		"Servers > FTP Server > Failed Login Attempts... > Temporary Ban Threshold"
	},
	{
		"Terminal Server",
		"Servers",
		"Servers > Terminal Server"
	},
	{
		"Testable File Type",
		"Testable File Types",
		"File Options > Testable File Types > Testable File Type"
	},
	{
		"Testable File Types",
		"File Options",
		"File Options > Testable File Types"
	},
	{
		"Text Directory",
		"Node Configuration",
		"Nodes > Node Configuration > Text Directory"
	},
	{
		"Text File Sections",
		"",
		"Text File Sections"
	},
	{
		"Text Section",
		"Loadable Modules",
		"System > Loadable Modules > Text Section"
	},
	{
		"Text Section Internal Code",
		"Text File Sections",
		"Text File Sections > Text Section Internal Code"
	},
	{
		"Throttle",
		"Failed Login Attempts...",
		"Servers > FTP Server > Failed Login Attempts... > Throttle"
	},
	{
		"Time Limit",
		"JavaScript Settings...",
		"Servers > Global Settings > JavaScript Settings... > Time Limit"
	},
	{
		"Time Per Call",
		"Security Level Values",
		"System > Security Options... > Security Level Values > Time Per Call"
	},
	{
		"Time Per Day",
		"Security Level Values",
		"System > Security Options... > Security Level Values > Time Per Day"
	},
	{
		"Timed Event",
		"Timed Events",
		"External Programs > Timed Events > Timed Event"
	},
	{
		"Timed Events",
		"External Programs",
		"External Programs > Timed Events"
	},
	{
		"TLS (encryption)",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > TLS (encryption)"
	},
	{
		"TLS Error Level",
		"Global Settings",
		"Servers > Global Settings > TLS Error Level"
	},
	{
		"Toggle Options",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Toggle Options"
	},
	{
		"Toggle Options",
		"System",
		"System > Toggle Options"
	},
	{
		"Toggle Options...",
		"Directories",
		"File Areas > Directories > Toggle Options..."
	},
	{
		"Toggle Options...",
		"Directory",
		"File Areas > Directories > Directory > Toggle Options..."
	},
	{
		"Toggle Options...",
		"Directory Default Settings",
		"File Areas > Directory Default Settings > Toggle Options..."
	},
	{
		"Toggle Options...",
		"Sub-board",
		"Message Areas > Sub-boards > Sub-board > Toggle Options..."
	},
	{
		"Toggle Options...",
		"System",
		"System > Toggle Options..."
	},
	{
		"Tokyo",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Tokyo"
	},
	{
		"UART Only",
		"I/O Method",
		"Chat Features > External Sysop Chat Pagers > I/O Method > UART Only"
	},
	{
		"Unpack Command Line",
		"Advanced Options",
		"Networks > Network Hubs... > Advanced Options > Unpack Command Line"
	},
	{
		"Upload Command Line",
		"File Transfer Protocol",
		"File Options > File Transfer Protocols > File Transfer Protocol > Upload Command Line"
	},
	{
		"Upload Date in Listings",
		"Toggle Options...",
		"File Areas > Directories > Toggle Options... > Upload Date in Listings"
	},
	{
		"Upload Requirements",
		"Directory",
		"File Areas > Directories > Directory > Upload Requirements"
	},
	{
		"Upload Requirements",
		"Library",
		"File Areas > Library > Upload Requirements"
	},
	{
		"Upload Semaphore File",
		"Advanced Options",
		"File Areas > Directories > Directory > Advanced Options > Upload Semaphore File"
	},
	{
		"Upload Semaphore File",
		"Directory Default Settings",
		"File Areas > Directory Default Settings > Upload Semaphore File"
	},
	{
		"Use Location in User Lists",
		"Toggle Options",
		"System > Toggle Options > Use Location in User Lists"
	},
	{
		"User Authentication Type",
		"SSH Support...",
		"Servers > Terminal Server > SSH Support... > User Authentication Type"
	},
	{
		"User Config",
		"Loadable Modules",
		"System > Loadable Modules > User Config"
	},
	{
		"User Database Backups",
		"Advanced Options",
		"System > Advanced Options > User Database Backups"
	},
	{
		"User Expires When Out-of-time",
		"Security Options...",
		"System > Security Options... > User Expires When Out-of-time"
	},
	{
		"User Inactivity Warning",
		"Advanced Options",
		"System > Advanced Options > User Inactivity Warning"
	},
	{
		"Username",
		"Message Queue Telemetry Transport",
		"Networks > Message Queue Telemetry Transport > Username"
	},
	{
		"Users Can Delete Posts",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Users Can Delete Posts"
	},
	{
		"Users Can Edit Posts",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Users Can Edit Posts"
	},
	{
		"Users Can View Deleted Messages",
		"Message Options",
		"Message Options > Users Can View Deleted Messages"
	},
	{
		"Vancouver",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Vancouver"
	},
	{
		"View File Info",
		"Loadable Modules",
		"System > Loadable Modules > View File Info"
	},
	{
		"Viewable File Type",
		"Viewable File Types",
		"File Options > Viewable File Types > Viewable File Type"
	},
	{
		"Viewable File Types",
		"File Options",
		"File Options > Viewable File Types"
	},
	{
		"Virtual File Path",
		"Directory",
		"File Areas > Directories > Directory > Virtual File Path"
	},
	{
		"Virtual Host Support",
		"Web Server",
		"Servers > Web Server > Virtual Host Support"
	},
	{
		"Virtual Sub-directories",
		"Library",
		"File Areas > Library > Virtual Sub-directories"
	},
	{
		"VPath for VHosts",
		"Filebase Support...",
		"Servers > Web Server > Filebase Support... > VPath for VHosts"
	},
	{
		"VPath Prefix",
		"Filebase Support...",
		"Servers > Web Server > Filebase Support... > VPath Prefix"
	},
	{
		"Warning Days Till Expire",
		"Advanced Options",
		"System > Advanced Options > Warning Days Till Expire"
	},
	{
		"Web Server",
		"Servers",
		"Servers > Web Server"
	},
	{
		"Western Europe (WET)",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Western Europe (WET)"
	},
	{
		"Who's Online",
		"Loadable Modules",
		"System > Loadable Modules > Who's Online"
	},
	{
		"Winnipeg",
		"Non-U.S. Time Zone",
		"Non-U.S. Time Zone > Winnipeg"
	},
	{
		"Word-wrap Exported Messages",
		"Network Hubs...",
		"Networks > Network Hubs... > Word-wrap Exported Messages"
	},
	{
		"Word-wrap Messages",
		"Toggle Options",
		"Message Areas > Sub-boards > Sub-board > Toggle Options > Word-wrap Messages"
	},
	{
		"Word-wrap Quoted Text",
		"Editor",
		"External Programs > Message Editors > Editor > Word-wrap Quoted Text"
	},
	{
		"Working String",
		"Download Event",
		"File Options > Download Events > Download Event > Working String"
	},
	{
		"Working String",
		"Testable File Type",
		"File Options > Testable File Types > Testable File Type > Working String"
	},
	{
		"Xtrn Section",
		"Loadable Modules",
		"System > Loadable Modules > Xtrn Section"
	},
	{
		"Yield Interval",
		"JavaScript Settings...",
		"Servers > Global Settings > JavaScript Settings... > Yield Interval"
	},
};

static const size_t scfg_option_index_count =
	sizeof(scfg_option_index) / sizeof(scfg_option_index[0]);

#endif /* SCFGINDEX_H */
