NK€€€€€€€€€€€€€€€€€€€€€€WÇHG‹2≤≤0›NG‹ Hﬂ‹2≤±≤0‹ ‹  ﬂ‹NÉHG€  ‹2≤±∞NG‹
WàGﬂWçH2G≤N  HGﬂ 2∞NG› ﬁ‹ ﬂH2±0›ﬁ2±N  HGﬁ›  ﬁ› ﬂNÇGﬂH2∞NG› HK[Clone]NÑGﬂ
WÇHK‹ﬂ≤ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ ﬂﬂ ˛ Gﬁ2±NG›  ‹ﬁ› H2∞N GﬂH2∞NG‹  H2∞NG› ‹H2±N  H2G±NÇG‹‹ﬂﬂﬂ  HK˛ ﬂﬂ ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ≤ﬂ‹
NÇHKﬂﬂ  N˛ G€ Wﬂﬂﬂﬂﬂﬂﬂ ﬂÉHGﬂ2∞NG‹€€ﬂ ﬁ€ﬂ‹‹ﬂ  ﬂH2∞ NGﬂ  ﬁ›  H2∞NGﬂ‹‹‹ﬂWÉﬂ ﬂﬂﬂﬂﬂﬂﬂ G€ W˛  HKﬂﬂ
GﬂNGﬂHﬂNGﬂﬂﬂﬂﬂﬂﬂWèGﬂﬂWêGﬂWñGﬂﬂﬂﬂHﬂNGﬂﬂﬂﬂHﬂ
NÇHK€NÇ€ÇHGa  NGareHKa changeNÑHGm NGgotHKo messagesNÖHGx  NGsysHKop's want listN€ÇHK€
NÇHK≤NÇ›ÇHGb  NGlisHKt batchNÖHGn NGnew HKfile scanNÖHG-  NGdirHKectory dwnNÉﬁÇHK≤
NÇHK±NÇ›ÇHGc  NGconHKfig pointer  Gq NGquiHKt to mainNÜHG+  NGdirHKectory upNÑﬁÇHK±
NÇHK∞NÇ›ÇHGd  NGdowHKnload files  Gr NGuntHKag fileNàHG/- NGlibHKrary dwnNÖﬁÇHK∞
NÜ›ÇHGe  NGediHKt a fileNÑHGs NGseaHKrch for fileNÉHG/+ NGlibHKrary upNÜﬁ
ÇHK∞NÇ›ÇHGg  NGlogHKoff bbsNÖHGt NGtemHKp file areaNÑHG*  NGshoHKw dirNàﬁÇHK∞
NÇHK±NÇ›ÇHG/g NGlogHKoff fastNÑHGu NGuplHKoad file/files  G/* NGshoHKw libNàﬁÇHK±
NÇHK≤NÇ›ÇHGk  NGconHKfig listing  Gv NGvieHKw a fileNáHG/u NGuplHKoad/userNÖﬁÇHK≤
NÇHK€NÇH7K NÇHGl  NGlisHKt filesNÖHGw NGextHKended listings  G/d NGdowHKnload/userNÉ€ÇHK€
G‹NG‹‹‹‹H‹NG‹‹‹‹WçHG‹‹NàHG‹NÖHG‹‹‹‹  NG‹H2∞±≤0‹NÖHKXsword's  NG‹‹‹‹‹‹‹H‹NG‹H‹
NÇHK‹‹  N˛ G€ HKX S W O R D.  2G≤±∞NGﬂﬂﬂ‹ Hﬂ ﬁ›NÉH2G≤0ﬂNÇHGﬂNGﬁH2∞NGﬂWÇHGﬂNÑHKProducts  NG€ W˛  HK‹‹
NÇHKﬂ‹≤‹‹‹‹‹‹‹‹‹‹‹‹‹ ‹‹ ˛  2G∞NGﬂ ﬂWÇH2G∞NG› H2±NÉGﬁH2±NG‹ﬂWÇGﬂﬂﬂ‹‹  HK˛ ‹‹ ‹‹‹‹‹‹‹‹‹‹‹‹‹≤‹ﬂ
NÜ‹ G‹WèGﬁ›WÑGﬂ ﬁH2∞NG‹‹‹ﬂ H2∞N  G‹  ‹  ‹H2∞NG›WéG‹ W‹
ÜﬂíGﬂWÜGﬂﬂWÖGﬂﬂWÉGﬂﬂﬂWíﬂ
Z