NK€€€€€€€€€€€€€€€€€€€€€€ÇHG‹2≤≤0›NG‹ Hﬂ‹2≤±≤0‹ ‹  ﬂ‹É€  ‹2≤±∞NG‹
WàGﬂWçH2G≤N  HGﬂ 2∞NG› ﬁ‹ ﬂH2±0›ﬁ2±N  HGﬁ›  ﬁ› ﬂÇNGﬂH2∞NG› HK[Clone]NÑGﬂ
ÇHK‹ﬂ≤ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ ﬂﬂ ˛ Gﬁ2±NG›  ‹ﬁ› H2∞N GﬂH2∞NG‹  H2∞NG› ‹H2±N  H2G±NÇG‹‹ﬂﬂﬂ  HK˛ ﬂﬂ ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ≤ﬂ‹
Çﬂﬂ  N˛ G€ Wﬂﬂﬂﬂﬂﬂﬂ ﬂÉHGﬂ2∞NG‹€€ﬂ ﬁ€ﬂ‹‹ﬂ  ﬂH2∞ NGﬂ  ﬁ›  H2∞NGﬂ‹‹‹ﬂÉWﬂ ﬂﬂﬂﬂﬂﬂﬂ G€ W˛  HKﬂﬂ
GﬂNGﬂHﬂNGﬂﬂﬂﬂﬂﬂﬂWèGﬂﬂWêGﬂWñGﬂﬂﬂﬂHﬂNGﬂﬂﬂﬂHﬂ
ÇK€ÇN€æ€ÇHK€
Ç≤ÇN›  HGa NGautHKo-msgNãHGi NGchaHKt sectionNâHGw  NGrecHKent call NﬁÇHK≤
Ç±ÇN›  HGb NGbbs HKlistNãHGk NGuseHKr configNäHGu  NGtimHKe bankÇNﬁÇHK±
Ç∞ÇN›  HGc NGpagHKe s-opNäHGl NGuseHKr listNåHGy  NGuseHKr infoÇNﬁÇHK∞
NÜ›  HGd NGdaiHKly logNäHGm NGmesHKsagesNçHGz  NGresHKet msg ptNﬁ
ÇHK∞ÇN›  HGe NGemaHKilNéHGp NGopeHKn doorsNãHG+  NGchaHKnge pwÇNﬁÇHK∞
Ç±ÇN›  HGf NGfeeHKdbackNãHGq NGquiHKckie menuNâHG$  NGdonHKationsÇNﬁÇHK±
Ç≤ÇN›  HGg NGlogHKoffNçHGs NGsysHKtem infoNäHG/g NGfasHKt logoff NﬁÇHK≤
Ç€Ç7 N  HGh NGwhoHK's onlineNáHGt NGfilHKes sectionNó€ÇHK€
G‹NG‹‹‹‹H‹NG‹‹‹‹WéHG‹‹NäHG‹‹NãHG‹›ÉKXSWORD'SÇNG‹‹‹‹‹‹‹H‹NG‹H‹
ÇK‹‹  N˛ G€ HKX S W O R D.Ç2G≤±∞NG‹ H2∞±0‹  NG‹ﬂH2±≤N  HGﬂ  ﬂ‹2±NÇHGﬁ2±NÑHKProductsÇNG€ W˛  HK‹‹
Çﬂ‹≤‹‹‹‹‹‹‹‹‹‹‹‹‹ ‹‹ ˛Ç2G∞NGﬂ ﬂ› H2±0›NGﬁ› ‹H2∞NG› H2±NG› ﬁH2∞N Gﬂ‹ H2∞NG›  HK˛ ‹‹ ‹‹‹‹‹‹‹‹‹‹‹‹‹≤‹ﬂ
NÜ‹ G‹WêGﬁ›Éﬁ ﬂÇﬁ› ﬂ  ﬁÉﬁ›WêG‹ W‹
ÜﬂìGﬂWäGﬂWàGﬂWìﬂ
Z