NÉK€€€€€€€€€€€€€€WÜHG‹2≤≤0›NG‹ Hﬂ‹2≤±≤0‹ ‹  ﬂ‹É€  ‹2≤±∞NG‹
WåGﬂWâH2G≤N  HGﬂ 2∞NG› ﬁ‹ ﬂH2±0›ﬁ2±N  HGﬁ›  ﬁ› ﬂÇNGﬂH2∞NG›WàGﬂ
WÜHK‹ﬂ≤ﬂﬂﬂﬂﬂﬂﬂ ﬂﬂ ˛ Gﬁ2±NG›  ‹ﬁ› H2∞N GﬂH2∞NG‹  H2∞NG› ‹H2±N  H2G±NÇG‹‹ﬂﬂﬂ  HK˛ ﬂﬂ ﬂﬂﬂﬂﬂﬂﬂ≤ﬂ‹
NÜHKﬂﬂ  N˛ G€ Wﬂﬂﬂ ﬂÉHGﬂ2∞NG‹€€ﬂ ﬁ€ﬂ‹‹ﬂ  ﬂH2∞ NGﬂ  ﬁ›  H2∞NGﬂ‹‹‹ﬂÉWﬂ ﬂﬂﬂ G€ W˛  HKﬂﬂ
ÉGﬂNGﬂHﬂNGﬂﬂﬂﬂﬂﬂﬂWãGﬂﬂWêGﬂWäHK{Xsword}NGﬂﬂﬂﬂHﬂNGﬂﬂﬂﬂHﬂ
NÜHK±ÇN€ÖHGc NGcalHKl the sysopNâHG/g NGgooHKdbye fast!NÜ€ÇHK±
NÜHK∞ÇN›ÖHGe NGe-mHKail menuNåHGm  NGjumHKp to message menuNﬁÇHK∞
Nä›ÖHGf NGleaHKve feedbackNâHGq  NGquiHKt to main menuÇNﬁ
ÜHK∞ÇN›ÖHGg NGgooHKdbye!NèHGt  NGjumHKp to transferÉNﬁÇHK∞
NÜHK±Ç7 N∂€ÇHK±
ÉG‹NG‹‹‹‹H‹NG‹‹‹‹ÉH‹2≤≤0›NG‹  H‹Ç‹NçHGﬂ›É2≤0ﬂNÜHG‹‹‹ÇNG‹‹‹‹‹‹‹H‹NG‹H‹
NÜHK‹‹  N˛ G€ÇH2≤N  HGﬂ 2∞NG›Hﬁ›Çﬁ›  ﬂÇ‹ﬂﬂ‹É2≤±N  HG‹ÇﬂÉ2±NÇH2G≤N  G€ W˛  HK‹‹
NÜHKﬂ‹≤‹‹‹‹ ˛Gﬁ2±NG› ﬂ‹ﬁ› H2±NG‹ÇH2±N  H2G±NG›  H2∞NáH2G∞N H2G∞NÉH2G±NG›  H2∞N HGﬂﬂﬂ K˛ ‹‹‹‹≤‹ﬂ
Nä‹ G‹ÇHﬂ2∞NG‹€€ﬂ‹  ﬂ€H2±∞NGﬂ  ﬂÉﬂ‹‹ﬂÇ€Ç‹ÇﬂÉH2±NG‹‹‹Ç‹ W‹
äﬂÜGﬂﬂW≠ﬂ
Z