N@CLEAR@
ÉK€€€€€€€€€€€€€€WÜHG‹2≤≤0›NG‹ Hﬂ‹2≤±≤0‹ ‹  ﬂ‹NÉHG€  ‹2≤±∞NG‹
WåGﬂWâH2G≤N  HGﬂ 2∞NG› ﬁ‹ ﬂH2±0›ﬁ2±N  HGﬁ›  ﬁ› ﬂNÇGﬂH2∞NG›WàGﬂ
WÜHK‹ﬂ≤ﬂﬂﬂﬂﬂﬂﬂ ﬂﬂ ˛ Gﬁ2±NG›  ‹ﬁ› H2∞N GﬂH2∞NG‹  H2∞NG› ‹H2±N  H2G±NÇG‹‹ﬂﬂﬂ  HK˛ ﬂﬂ ﬂﬂﬂﬂﬂﬂﬂ≤ﬂ‹
NÜHKﬂﬂ  N˛ G€ Wﬂﬂﬂ ﬂÉHGﬂ2∞NG‹€€ﬂ ﬁ€ﬂ‹‹ﬂ  ﬂH2∞ NGﬂ  ﬁ›  H2∞NGﬂ‹‹‹ﬂWÉﬂ ﬂﬂﬂ G€ W˛  HKﬂﬂ
NÉHGﬂNGﬂHﬂNGﬂﬂﬂﬂﬂﬂﬂWãGﬂﬂWêGﬂWäHK{Xsword}NGﬂﬂﬂﬂHﬂNGﬂﬂﬂﬂHﬂ
NÜHK±NÇ€ÖHGc NGchaHKnge packet configNö€ÇHK±
NÜHK∞NÇ›ÖHGs NGselHKect msg area scanNÉHGd NGdowHKnload qwkNàﬁÇHK∞
Nä›ÖHGp NGmodHKify newscan ptrsNÑHGb NGbidHKirect rep/qwkNÑﬁ
ÜHK∞NÇ›ÖHGu NGuplHKoad qwk reply packNÇHGq NGquiHKt to messageNÖﬁÇHK∞
NÜHK±NÇH7K N∂€ÇHK±
NÉHG‹NG‹‹‹‹H‹NG‹‹‹‹WÉHG‹2≤≤0›NG‹  H‹NÇHG‹ ﬁ‹NÇHG‹NÇHG‹NèHG‹NÜG‹‹‹‹‹‹‹H‹NG‹H‹
NÜHK‹‹  N˛ G€WÇH2G≤N  HGﬂ 2∞NG›Hﬁ›NÇHGﬁ› 2±0› ﬁNG›WÇHGﬁ2±∞NG‹ H2∞±0‹  NG‹ﬂH2±0‹ ﬂ ﬁ›NÖG€ W˛  HK‹‹
NÜHKﬂ‹≤‹‹‹‹ ˛Gﬁ2±NG› ﬂ‹ﬁ› H2±NG‹ ‹ H2±N GﬁH2∞NG‹ﬂWÑH2G∞NGﬂ ﬂ› H2±0›NGﬁ›˛ H2∞NG›H2±NG› H2±NÉHK˛ ‹‹‹‹≤‹ﬂ
Nä‹ G‹WÇHGﬂ2∞NG‹€€ﬂ‹  ﬂ€›H2∞NGﬂ ﬁ›ﬂ€‹WÉGﬁ›WÉGﬁ ﬂWÇGﬁ ﬂ ﬁH2∞NG‹‹‹ﬂ  ‹ W‹
äﬂÜGﬂﬂWäGﬂWÉGﬂWÉGﬂWçGﬂﬂWáﬂ
Z