NBH__[ HWList of available commandsN: BH]_____________________________
WH/CinfoN‰HK:N View information about a BBSHK:N H/CinfoN H#
WH/Cmsg Kor W/Ct„K:N Send a direct messageHK:N‡H/CtN HnickN HBmessage
WH/CrNŒHK:N Reply to last direct messageHK:N H/CrB message
WH/Cjoin Kor W/CjN HK    :N Join a new roomHK:WŠ   /CjN Hroom_name
WH/CtopicNˆHK:N Change room topicHK:‹HW/CtopicW topic
WH/CmeN            HK:N Perform an actionHK:            HW/Cme NHwaves
WH/CroomsNˆHK:N List available rooms
WH/CusersNˆHK:N List users
WH/CwhoonNˆHK:N List users and BBSes
WH/CmotdN‰HK:N Display the Message of the Day
WH/Cscroll Kor CPGUPK:N Scroll the chat window
WH/Cmentions Kor CUPK:N Reset mention counter and review mentions
WH/Csound         K:N Toggle chat sounds (mentions & system msgs)
WH/CthemeNˆHK:N Select a theme HK..........N seeHK:N H/ChelpN Htheme
WH/CtwitN‰HK:N Twit List management HK....N seeHK:N H/ChelpN Htwit
WH/CctcpN‰HK:N Send a CTCP command HK.....N seeHK:N H/ChelpN Hctcp
WH/Cquit Kor W/CqN HK    :N Exit the program
WHCLEFTK/CRIGHTW„K:N Change your text color HK..N seeHK:N H/ChelpN Hnick
WHCCTRLK+CDNˆHK:N Clear the input line
WH/ChelpN‰HK:N Shows this help list HK....N seeHK:N H/ChelpN Hmore
NFor a list of additional HSERVERN commands, see H/CquoteN Hhelp Nor H/C?