NBH__[ HWHow to use the twit listN: B]H_______________________________

N The Htwit list Nhides messages from problematic chatters.

N Usage:
   WH/Ctwit NHadd HBnameoftwit K:W NFilters out nameoftwit's messages
   WH/Ctwit NHdel HBnameoftwit K:W Nnameoftwit's messages are re-allowed
   WH/Ctwit NHlist           K:W NLists twits you have added
   WH/Ctwit NHclear          K:W NEmpties your twit list
