NB__[ HWHow to use the twit listN: B]_______________________________

N Basic twit list implemented! Hides messages from problematic 
N chatters.

N Usage:
   WH/Ctwit NHadd HBnameoftwit K:W NFilters out nameoftwit's messages
   WH/Ctwit NHdel HBnameoftwit K:W Nnameoftwit's messages are re-allowed
   WH/Ctwit NHlist           K:W NLists twits the user has added
   WH/Ctwit NHclear          K:W NEmpty's the user's twit list
