NB__[ HWNick customization optionsN: B]_____________________________
HW/Cnick_prefix K:W NSet a single-character prefix for your handle
NŽeg.H /Cnick_prefixN H@
WH/Cnick_colorN  HK:W NSet your nick color
HŽNG02HW NC03HW NR04HW NM05HW NY06HW B09W G10W C11W R12M 13W Y14W 15
WH/Cnick_suffix K:W NSet an eight-character suffix for your handle
NŽeg.H N/HCnick_suffix W<afilz>

N You can include pipe color codes in your nick_prefix and
N nick_suffix. Get as creative as you want!

HB NExample: HB@CUserNameB<GaFiLZB>
