NB__[ HWList of available commandsN: B]_____________________________
WH/CinfoN‰HK:N View information about a BBSHK:N H/CinfoN H#
WH/Ct Kor W/Cmsg„K:N Send a direct messageHK:N‡H/CtN HnickN HBmessage
WH/CrNŒHK:N Reply to last direct messageHK:N H/CrB message
WH/CjoinN‰HK:N Move to a new roomHK:WŠ/CjoinN Hroom_name
WH/CtopicNˆHK:N Change room topic:‹H/CtopicW topic
WH/CroomsNˆHK:N List available rooms
WH/CusersNˆHK:N List users
WH/CwhoonNˆHK:N List users and BBSes
WH/CmotdN‰HK:N Display the Message of the Day
WH/Cscroll Kor CPGUPK:N Scroll the chat window
WH/Cmentions Kor CUPK:N Reset mention counter and review mentions
WH/Cscroll_nicksN  HK:N Scroll the nicklist
WH/Ctoggle_nicksN  HK:N Show/hide the nicklist
WH/Ctoggle_statsN  HK:N Toggle MRC stats view
WH/CthemeNˆHK:N Select a theme HK..........N seeHK:N H/ChelpN Htheme
WH/CtwitN‰HK:N Twit List management HK....N seeHK:N H/ChelpN Htwit
WH/CquitN‰HK:N Exit the program
WHCLEFTK/CRIGHTW„K:N Change your text color HK..N seeHK:N H/ChelpN Hnick
WHCCTRLK+CDNˆHK:N Clear the input line
NFor a list of additional HSERVERN commands, see H/CquoteN Hhelp