NBH__[ HWHow to use CTCP commandsN: BH]_______________________________

N CTCP (Client-to-Client Protocol) commands are special messages
N that can be sent to a channel or other clients.

N Usage:
   WH/Cctcp NHtarget HBcommand K

N A Htarget Nis a user or room name. HB* Ntargets all.

N Supported commands: 
HB   VERSION  TIME  PING  CLIENTINFO

N Type WH/Ctoggle_ctcp Nto hide/show incoming requests.