CIOLIB-MT	=	$(CIOLIB_SRC)$(DIRSEP)$(LIBODIR)$(DIRSEP)$(LIBPREFIX)ciolib_mt$(LIBFILE)

CIOLIB-MT_CFLAGS	=	-I$(CIOLIB_SRC) -DCIOLIB_APP
CIOLIB-MT_LDFLAGS	=	-L$(CIOLIB_SRC)$(DIRSEP)$(LIBODIR)
CIOLIB-MT_LIBS		=	$(UL_PRE)ciolib_mt$(UL_SUF)
