CIOLIB-MT	=	$(CIOLIB_SRC)$(DIRSEP)$(LIBODIR)$(DIRSEP)$(LIBPREFIX)ciolib$(LIBFILE)

CIOLIB-MT_CFLAGS	=	-I$(CIOLIB_SRC)
CIOLIB-MT_LDFLAGS	=	-L$(CIOLIB_SRC)$(DIRSEP)$(LIBODIR)
CIOLIB-MT_LIBS		=	-lciolib
