OBJS	=	$(MTOBJODIR)$(DIRSEP)ansi_cio$(OFILE)\
			$(MTOBJODIR)$(DIRSEP)ciolib$(OFILE)\
			$(MTOBJODIR)$(DIRSEP)cterm$(OFILE)\
			$(MTOBJODIR)$(DIRSEP)vidmodes$(OFILE)\
			$(MTOBJODIR)$(DIRSEP)mouse$(OFILE)
