# conio/targets.mk
CIOLIB-MT_BUILD	=	$(LIBODIR)$(DIRSEP)$(LIBPREFIX)ciolib_mt$(LIBFILE)
CIOLIB-MT_SHLIB_BUILD	=	$(LIBODIR)$(DIRSEP)$(LIBPREFIX)ciolib_mt$(SOFILE)

mtlib:	$(MTOBJODIR) $(LIBODIR) $(CIOLIB-MT_BUILD)

dl-mtlib: $(MTOBJODIR) $(LIBODIR) $(CIOLIB-MT_SHLIB_BUILD)

