# Tournament Trivia JavaScript installer data for install-xtrn.js

Name: Tournament Trivia (JS)
Desc: A question and answer based trivia game, ported to Synchronet JS from the C++ source code. Multi-node/multi-user aware.
By:   Claude AI and Nightfox -at- digitaldistortionbbs.com (or digdist.synchro.net)
Cats: Games
Subs: Trivia, JavaScript
Inst: 2026/03/14

[prog:TTRIVIA_JS]
cmd  = ?ttriv.js
settings = XTRN_MULTIUSER
required = true
