#include "deucessh-portable.h"
#undef DSSH_PRIVATE
#define DSSH_PRIVATE static

#include "ssh-auth.c"
#include "ssh-conn.c"
#include "ssh-trans.c"
#include "ssh.c"
#include "comp/none.c"
#include "enc/aes256-ctr.c"
#include "enc/none.c"
#include "kex/curve25519-sha256.c"
#include "kex/dh-gex-sha256.c"
#include "kex/mlkem768.c"
#include "kex/mlkem768x25519-sha256.c"
#include "kex/sntrup761.c"
#include "kex/sntrup761x25519-sha512.c"
#include "key_algo/rsa-sha2-256.c"
#include "key_algo/ssh-ed25519.c"
#include "mac/hmac-sha2-256.c"
#include "mac/none.c"
