; Synchronet Chess installer data for install-xtrn.js

Name: Synchronet Chess (SynChess)
Desc: How about a nice game of chess?
By:   Nelgin
Cats: Games
Subs: Classic, JavaScript, Chess, Board Games
Inst: 2026/03/19

[prog:SYNCHESS]
cmd = ?synchess
settings = XTRN_MULTIUSER
required = true
execution_ars = ANSI AND COLS 80

[copy:synchess-dist.ini]
dest = synchess.ini

