; SynChess global configuration
; Edit this file to configure server-wide defaults.

; Full path to the Stockfish binary
; On Ubuntu it's stored in /usr/games/stockfish

;stockfish_path=/usr/games/stockfish

; Set to false to use the built-in engine instead
; Set this to true if you want to use the Stockfish
; engine and have it installed

use_stockfish=false
