//
// ANSI Object
//  
ANSI = new Object();

ANSI.ESC = "[";

ANSI.DEFAULT = ANSI.ESC + "0m";

ANSI.BOLD = ANSI.ESC + "1m";
ANSI.UNBOLD = ANSI.ESC + "22m";

ANSI.FG_BLACK = ANSI.ESC + "30m";
ANSI.FG_RED = ANSI.ESC + "31m";
ANSI.FG_GREEN = ANSI.ESC + "32m";
ANSI.FG_YELLOW = ANSI.ESC + "33m";
ANSI.FG_BLUE = ANSI.ESC + "34m";
ANSI.FG_MAGENTA = ANSI.ESC + "35m";
ANSI.FG_CYAN = ANSI.ESC + "36m";
ANSI.FG_WHITE = ANSI.ESC + "37m";
ANSI.BG_BLACK = ANSI.ESC + "40m";
ANSI.BG_RED = ANSI.ESC + "41m";
ANSI.BG_GREEN = ANSI.ESC + "42m";
ANSI.BG_YELLOW = ANSI.ESC + "43m";
ANSI.BG_BLUE = ANSI.ESC + "44m";
ANSI.BG_MAGENTA = ANSI.ESC + "45m";
ANSI.BG_CYAN = ANSI.ESC + "46m";
ANSI.BG_WHITE = ANSI.ESC + "47m";