#!/usr/bin/env python3
# gen_splash.py -- generate the SyncDOOM waiting-room splash.
#
# Emits sd_splash.h (an 80x25 grid of {CP437 char, CGA attribute} cells, the
# same "ENDOOM" format the door's sd_render_screen() draws) plus a PNG preview
# for eyeballing. The art is a bespoke fiery DOOM-logo screen -- NOT derived
# from any commercial Doom asset, so it is safe to ship in the public tree.
#
# Run from anywhere; writes sd_splash.h beside the door sources (the parent of
# this tools/ dir) and the preview to /tmp/syncdoom_splash.png.
#
#   python3 tools/gen_splash.py
#
# Needs Pillow + a DejaVu Sans Mono font (Debian: fonts-dejavu-core).

import os
import random
from PIL import Image, ImageDraw, ImageFont

W, H = 80, 25
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, os.pardir, "sd_splash.h")
OUT_PNG = "/tmp/syncdoom_splash.png"
FONT_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
FONT_REG = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"

# CGA 16-color palette (RGB), index = CGA color number.
CGA = [(0, 0, 0), (0, 0, 170), (0, 170, 0), (0, 170, 170),
       (170, 0, 0), (170, 0, 170), (170, 85, 0), (170, 170, 170),
       (85, 85, 85), (85, 85, 255), (85, 255, 85), (85, 255, 255),
       (255, 85, 85), (255, 85, 255), (255, 255, 85), (255, 255, 255)]

# grid of (cp437_byte, attr); attr = fg | (bg<<4), fg 0-15, bg 0-7 (the door
# emits only dark backgrounds, so bg is clamped to 0-7).
SP = 0x20
grid = [[(SP, 0x07) for _ in range(W)] for _ in range(H)]
U2C = {'█': 0xDB, '▀': 0xDF, '▄': 0xDC,
       '░': 0xB0, '▒': 0xB1, '▓': 0xB2, ' ': 0x20}


def cell(r, c, ch, fg, bg=0):
    if 0 <= r < H and 0 <= c < W:
        b = U2C.get(ch, ord(ch) if ord(ch) < 128 else 0x3F)
        grid[r][c] = (b, (fg & 0x0F) | ((bg & 7) << 4))


def text(r, c, s, fg, bg=0):
    for i, ch in enumerate(s):
        cell(r, c + i, ch, fg, bg)


def ctext(r, s, fg, bg=0):
    text(r, (W - len(s)) // 2, s, fg, bg)


# Big DOOM: rasterize via PIL, then map filled pixels to full-block cells with a
# per-row chrome->fire gradient (bright fg only -- the attribute intensity bit).
fnt = ImageFont.truetype(FONT_BOLD, 30)
msk = Image.new("L", (320, 48), 0)
ImageDraw.Draw(msk).text((2, 2), "DOOM", fill=255, font=fnt)
msk = msk.crop(msk.getbbox())
LW, LH = 66, 11
msk = msk.resize((LW, LH))
px = msk.load()
grad = [11, 11, 15, 14, 14, 6, 12, 12, 4, 4, 4]   # chrome cyan -> white -> yellow -> orange -> red
R0 = 4
C0 = (W - LW) // 2
for cr in range(LH):
    for cc in range(LW):
        if px[cc, cr] > 110:
            cell(R0 + cr, C0 + cc, '█', grad[cr])
# molten drips below the logo
random.seed(3)
for cc in range(LW):
    if px[cc, LH - 1] > 110 and random.random() < 0.6:
        cell(R0 + LH, C0 + cc, random.choice(['▒', '░', '█']), random.choice([4, 12]))
        if random.random() < 0.3:
            cell(R0 + LH + 1, C0 + cc, '░', 4)
ctext(2, "S Y N C", 11)
ctext(R0 + LH + 3, "Synchronet's multiplayer DOOM door", 14)
ctext(R0 + LH + 4, "co-op & deathmatch carnage over telnet", 7)

# PNG preview
CW, CH = 9, 18
img = Image.new("RGB", (W * CW, H * CH), (0, 0, 0))
dr = ImageDraw.Draw(img)
gf = ImageFont.truetype(FONT_REG, 17)
C2U = {v: k for k, v in U2C.items()}
for r in range(H):
    for c in range(W):
        b, attr = grid[r][c]
        fg = attr & 0x0F
        bg = (attr >> 4) & 7
        if bg:
            dr.rectangle([c * CW, r * CH, c * CW + CW, r * CH + CH], fill=CGA[bg])
        ch = C2U.get(b, chr(b) if 32 <= b < 127 else ' ')
        if ch != ' ':
            dr.text((c * CW, r * CH - 1), ch, fill=CGA[fg], font=gf)
img.save(OUT_PNG)
print("wrote", OUT_PNG, img.size)

# C array (ENDOOM format: char,attr per cell, row-major)
with open(OUT_H, "w") as f:
    f.write("// SyncDOOM waiting-room splash (bespoke, 80x25 char+CGA-attr -- ENDOOM format).\n")
    f.write("// Generated by tools/gen_splash.py; fiery DOOM-logo style. Edit there, not here.\n")
    f.write("static const unsigned char sd_splash[80 * 25 * 2] = {\n")
    out = []
    for r in range(H):
        for c in range(W):
            b, a = grid[r][c]
            out.append("0x%02x,0x%02x" % (b, a))
    for i in range(0, len(out), 8):
        f.write("\t" + ",".join(out[i:i + 8]) + ",\n")
    f.write("};\n")
print("wrote", OUT_H)
