SYNCDRAW	=	$(EXEODIR)$(DIRSEP)syncdraw$(EXEFILE)
FONTUTIL	=	$(EXEODIR)$(DIRSEP)fontutil$(EXEFILE)
BUILDFONT	=	$(EXEODIR)$(DIRSEP)buildfont$(EXEFILE)

all: xpdev-mt xpdev ciolib-mt $(OBJODIR) $(MTOBJODIR) $(EXEODIR) $(SYNCDRAW) $(FONTUTIL) $(BUILDFONT)

$(SYNCDRAW):	$(XPDEV-MT_LIB) $(CIOLIB-MT)
$(FONTUTIL):	$(XPDEV-MT_LIB) $(CIOLIB-MT)
$(BUILDFONT):	$(XPDEV-MT_LIB)
