void CountPlayers(void);
void FundTransfer(short x);
short GetResponse(short l, short g);
void WriteTherapy(char *a, char *n);
void NewPlayer();
void ReadMail(short t);
void ReadNews(char *a);
void ShowRoom(long l);
void ShowTitle(void);
void TypeCode(void);
short WriteALetter(char *From, char *To, short Vx);
void UseItem(long c,short b);
