; mime_types.ini

; This file controls what Internet media types are sent to the client for
; given file extension(s).  Sending the correct media type to the client
; is important so they know how to handle the content of the file.
; Extra types can either be added here
; The Internet media type
; registry is at <ftp://ftp.iana.org/in-notes/iana/assignments/media-types/>.

; Extension = MIME-type
htm	= text/html
html	= text/html
hqx	= application/mac-binhex40
cpt	= application/mac-compactpro
doc	= application/msword
lha	= application/octet-stream
lzh	= application/octet-stream
exe	= application/octet-stream
class	= application/octet-stream
pdf	= application/pdf
ps	= application/postscript
eps	= application/postscript
xls	= application/vnd.ms-excel
ppt	= application/vnd.ms-powerpoint
csh	= application/x-csh
js	= application/javascript
latex	= application/x-latex
sh	= application/x-sh
shar	= application/x-shar
swf	= application/x-shockwave-flash
sit	= application/x-stuffit
tar	= application/x-tar
zip	= application/zip
mid	= audio/midi
midi	= audio/midi
mpga	= audio/mpeg
mp2	= audio/mpeg
mp3	= audio/mpeg
aif	= audio/x-aiff
aiff	= audio/x-aiff
aifc	= audio/x-aiff
m3u	= audio/x-mpegurl
rm	= audio/x-pn-realaudio
ram	= audio/x-pn-realaudio
rpm	= audio/x-pn-realaudio-plugin
ra	= audio/x-realaudio
wav	= audio/x-wav
bmp	= image/bmp
gif	= image/gif
ief	= image/ief
jpeg	= image/jpeg
jpg	= image/jpeg
jpe	= image/jpeg
png	= image/png
tif	= image/tiff
tiff	= image/tiff
wbmp	= image/vnd.wap.wbmp
ras	= image/x-cmu-raster
pnm	= image/x-portable-anymap
pbm	= image/x-portable-bitmap
pgm	= image/x-portable-graymap
ppm	= image/x-portable-pixmap
rgb	= image/x-rgb
xbm	= image/x-xbitmap
xpm	= image/x-xpixmap
xwd	= image/x-xwindowdump
wrl	= model/vrml
vrml	= model/vrml
css	= text/css
asc	= text/plain
txt	= text/plain
rtx	= text/richtext
rtf	= text/rtf
sgml	= text/sgml
sgm	= text/sgml
tsv	= text/tab-separated-values
wml	= text/vnd.wap.wml
wmls	= text/vnd.wap.wmlscript
xml	= text/xml
xsl	= text/xml
mpg	= video/mpeg
mpe	= video/mpeg
mpeg	= video/mpeg
mp4	= video/mp4
qt	= video/quicktime
mov	= video/quicktime
mxu	= video/vnd.mpegurl
avi	= video/x-msvideo
movie	= video/x-sgi-movie
ice	= x-conference/x-cooltalk
log	= text/plain
rss	= application/rss+xml
svg	= image/svg+xml
