/* SPDX-License-Identifier: GPL-2.0-or-later */
#ifndef WREN_HOST_INTERNAL_H
#define WREN_HOST_INTERNAL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "wren.h"

/* Maximum simultaneous registrations per hook event and per timer slot.
 * These are intentionally small — there's no use case for hundreds of
 * scripts hooking the same event, and exceeding the cap simply drops
 * the registration with an error message. */
#define WREN_HOST_MAX_HOOKS_PER_EVENT 8
#define WREN_HOST_MAX_TIMERS          16

enum wren_hook_event {
	WREN_HOOK_KEY,
	WREN_HOOK_INPUT,
	WREN_HOOK_OUTPUT,
	WREN_HOOK_MOUSE,
	WREN_HOOK_STATUS,
	WREN_HOOK_COUNT
};

struct wren_timer_entry {
	WrenHandle  *callable;
	uint32_t     interval_ms;
	long double  next_fire_s;   /* xp_timer() epoch in seconds */
};

struct wren_host_state {
	WrenVM      *vm;
	/* Cached method handles: call() with 0 and 1 arg.  Wren's Fn class
	 * uses signature "call()" / "call(_)". */
	WrenHandle  *call0_handle;
	WrenHandle  *call1_handle;

	/* Cached class handles for foreign classes that the C side
	 * allocates instances of (via wrenSetSlotNewForeign).  Captured
	 * after the syncterm module compiles; released at shutdown. */
	WrenHandle  *cell_class;
	WrenHandle  *cells_class;

	WrenHandle  *hooks[WREN_HOOK_COUNT][WREN_HOST_MAX_HOOKS_PER_EVENT];
	int          hook_count[WREN_HOOK_COUNT];

	struct wren_timer_entry timers[WREN_HOST_MAX_TIMERS];
	int                     timer_count;

	struct bbslist *bbs;
};

/* Singleton state pointer (NULL when shut down). */
extern struct wren_host_state *wren_host_state(void);

/* Hook registration helpers used by wren_bind.c.  Takes a slot-1
 * function value, captures a handle for it, appends to the registry
 * for the event.  Returns false if the per-event limit is reached. */
bool wren_host_register_hook(WrenVM *vm, enum wren_hook_event ev, int fn_slot);

/* Timer registration: ms is the recurrence interval, fn_slot holds the
 * callable. */
bool wren_host_register_timer(WrenVM *vm, int ms, int fn_slot);

/* Foreign-method dispatch table, defined in wren_bind.c.  Returns NULL
 * if no method matches, in which case Wren reports a runtime error. */
WrenForeignMethodFn wren_bind_lookup(const char *module,
                                     const char *className,
                                     bool isStatic,
                                     const char *signature);

/* Foreign-class allocator/finalizer dispatch.  Returns {NULL, NULL} when
 * no foreign class matches.  Defined in wren_bind.c. */
WrenForeignClassMethods wren_bind_lookup_class(const char *module,
                                                const char *className);

/* Embedded scripts table.  Generated by wren_embed_gen at build time
 * from src/syncterm/scripts/ *.wren and linked in as a separate .c.
 * Terminated by a {NULL, NULL} sentinel. */
struct embedded_script {
	const char *name;
	const char *source;
};
extern const struct embedded_script EMBEDDED_SCRIPTS[];

/* Log buffer (always-on print/error scrollback).  Stores up to 1024
 * messages; oldest evicted on overflow.  System.print and the three
 * WrenErrorType cases all flow into this buffer.  Wren scripts read
 * via the foreign Console class (count, [i], clear, iterate,
 * iteratorValue).  Per-message text is capped at 8 KB. */
enum wren_log_source {
	WREN_LOG_PRINT,
	WREN_LOG_COMPILE_ERROR,
	WREN_LOG_RUNTIME_ERROR,
	WREN_LOG_STACK_FRAME
};

int      wren_log_count(void);
/* Total writes since wren_host_init.  Monotonic across the session,
 * not reset by wren_log_clear.  Wren scripts use it as a high-water
 * mark to drive incremental "show only new entries" rendering. */
uint64_t wren_log_total(void);
void     wren_log_clear(void);
/* Build (or reuse the cached) Wren tuple [ts, source, text] for the
 * entry whose sequence number is `seq` into Wren slot `slot`.  Sets
 * the slot to null if `seq` is outside the currently-buffered range
 * (already evicted, or not yet written). */
void     wren_log_emit(WrenVM *vm, uint64_t seq, int slot);

#endif /* WREN_HOST_INTERNAL_H */
