/* wren_embed_gen — read .wren script files from argv, write a freestanding
 * C source file to stdout that defines:
 *
 *     const struct embedded_script EMBEDDED_SCRIPTS[] = {
 *         { "name", "...source..." },
 *         ...
 *         { NULL, NULL }
 *     };
 *
 * `struct embedded_script` is declared in wren_host_internal.h, which the
 * generated file includes.  The output is a real .c — compiled to its own
 * object and linked alongside wren_host.o; the SyncTERM build system runs
 * this tool with the *host* CC (BUILD_CC) so cross-builds work.
 *
 * Plain C99, no platform deps.  Module name = basename of the input path
 * with the trailing ".wren" extension stripped. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *
basename_no_ext(const char *path, char *out, size_t outsz)
{
	const char *base = strrchr(path, '/');
#ifdef _WIN32
	const char *bs = strrchr(path, '\\');
	if (bs != NULL && (base == NULL || bs > base))
		base = bs;
#endif
	base = (base == NULL) ? path : base + 1;

	size_t i = 0;
	while (i + 1 < outsz && base[i] != '\0')
		out[i] = base[i], i++;
	out[i] = '\0';

	char *dot = strrchr(out, '.');
	if (dot != NULL)
		*dot = '\0';
	return out;
}

/* Emit a C string literal for `bytes` (length n) to stdout, broken into
 * one literal per source line so the generated file stays readable. */
static void
emit_c_string(const unsigned char *bytes, size_t n)
{
	fputs("\"", stdout);
	for (size_t i = 0; i < n; i++) {
		unsigned char c = bytes[i];
		switch (c) {
			case '\\': fputs("\\\\", stdout); break;
			case '\"': fputs("\\\"", stdout); break;
			case '\n': fputs("\\n\"\n        \"", stdout); break;
			case '\r': fputs("\\r", stdout); break;
			case '\t': fputs("\\t", stdout); break;
			default:
				if (c < 0x20 || c >= 0x7f)
					fprintf(stdout, "\\x%02x", c);
				else
					putchar(c);
				break;
		}
	}
	fputs("\"", stdout);
}

static int
emit_one(const char *path)
{
	FILE *f = fopen(path, "rb");
	if (f == NULL) {
		fprintf(stderr, "wren_embed_gen: cannot open %s\n", path);
		return -1;
	}
	if (fseek(f, 0, SEEK_END) != 0) {
		fclose(f);
		return -1;
	}
	long sz = ftell(f);
	if (sz < 0 || fseek(f, 0, SEEK_SET) != 0) {
		fclose(f);
		return -1;
	}
	unsigned char *buf = malloc((size_t)sz);
	if (buf == NULL && sz > 0) {
		fclose(f);
		return -1;
	}
	size_t got = sz > 0 ? fread(buf, 1, (size_t)sz, f) : 0;
	fclose(f);

	char modname[256];
	basename_no_ext(path, modname, sizeof(modname));

	fprintf(stdout, "    { \"%s\",\n        ", modname);
	emit_c_string(buf, got);
	fputs(" },\n", stdout);

	free(buf);
	return 0;
}

int
main(int argc, char **argv)
{
	fputs("/* Generated by wren_embed_gen. DO NOT EDIT. */\n", stdout);
	fputs("#include \"wren_host_internal.h\"\n\n", stdout);
	fputs("const struct embedded_script EMBEDDED_SCRIPTS[] = {\n",
	    stdout);

	for (int i = 1; i < argc; i++) {
		if (emit_one(argv[i]) != 0)
			return EXIT_FAILURE;
	}

	fputs("    { NULL, NULL }\n};\n", stdout);
	return EXIT_SUCCESS;
}
