SMBLIB	=	$(SMBLIB_SRC)$(DIRSEP)$(LIBODIR)$(DIRSEP)$(LIBPREFIX)smblib$(LIBFILE)
SMBLIB-MT	=	$(SMBLIB_SRC)$(DIRSEP)$(LIBODIR)$(DIRSEP)$(LIBPREFIX)smblib-mt$(LIBFILE)

SMBLIB_CFLAGS	=	-I$(SMBLIB_SRC)
SMBLIB_LDFLAGS	=	-L$(SMBLIB_SRC)$(DIRSEP)$(LIBODIR)
SMBLIB-MT_CFLAGS	=	-I$(SMBLIB_SRC)
SMBLIB-MT_LDFLAGS	=	-L$(SMBLIB_SRC)$(DIRSEP)$(LIBODIR)
