<!-- $Id$ -->
<br />
<table width="100%" cellspacing="0" border="0" cellpadding="0" align="center">
  <tbody>
    <tr>
      <td>
          <div align="left">
          <a href="http://www.synchro.net/"><img src="/graphics/sync_pb.gif" alt="Powered by: Synchronet" width="259" height="32" border="0" /></a></div>
      </td>
      <td>
          <div align="right">
          <a href="http://validator.w3.org/check?uri=referer"><img
             src="http://www.w3.org/Icons/valid-xhtml10"
             alt="Valid XHTML 1.0!" height="31" width="88" border="0" /></a><br />
          </div>
      </td>
    </tr>
  </tbody>
</table>
</body>
</html>
