<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<!-- $Id$ -->
<HEAD>
<TITLE>%%title%%</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
<link rel="stylesheet" href="/synchronet.css" type="text/css">
</HEAD>
<body bgcolor="teal" text="white" link="yellow" vlink="lime" alink="white">
<center><H3>%%JS:system.name%%</H3></center>
