<p class="navigation"><a class="navigation" href="http://^^JS:system.inet_addr^^/">Home</a> : <a class="navigation" href="/members/">Members</a> : Information</p>
<table class="info" cellspacing="2" cellpadding="2">
    <tbody>
        <tr>
        <td class="info">
            <p>Information Menu:</p>
            <a href="userstats.ssjs">View your statistics</a><br />
            <a href="sysinfo.ssjs">System information</a><br /><br />
        </td>
        </tr>
    </tbody>
</table>