<p class="navigation"><a class="navigation" href="http://^^JS:system.inet_addr^^/">Home</a> : Members</p>
<table class="member" cellspacing="2" cellpadding="2">
    <tbody>
        <tr>
        <td class="member">
            <p>Welcome to the members area.<br />
               Please choose an option ...</p>
            <a href="userlist.ssjs">User List</a><br />
            <a href="msgs/">Message Areas</a><br />
            <a href="info.ssjs">Information menu</a><br />
            <a href="@@ftplink@@">File areas</a><br /><br />
        </td>
        </tr>
    </tbody>
</table>
