<div align="center"><p><a href="http://^^JS:system.inet_addr^^/">Home</a> : <a href="/members/">Members</a> : <b>User List</b></p></div>
<table class="centeralign">
<tr class="userlist"><th><a class="userlist" href="userlist.ssjs?sort=alias">Alias</a></th><th><a class="userlist" href="userlist.ssjs?sort=location">Location</a></TH><TH><a class="userlist" href="userlist.ssjs?sort=connection">Connection</a></TH><TH><a class="userlist" href="userlist.ssjs?sort=laston">Last On</a></th></tr>
<<REPEAT users>>
<tr>
  <td>
    @@users:alias@@
  </td>
  <td>
    @@users:location@@
  </td>
  <td>
    @@users:connection@@
  </td>
  <td>
    @@users:logon@@
  </td>
</tr>
<<END REPEAT users>>
</table>

