<div align="center"><P><A HREF="http://^^JS:system.inet_addr^^/">Home</A> : <A href="/members/">Members</A> : <B>User List</B></P></div>
<TABLE class="centeralign">
<TR class="userlist"><TH><a class="userlist" href="userlist.ssjs?sort=alias">Alias</a></TH><TH><a class="userlist" href="userlist.ssjs?sort=location">Location</a></TH><TH><a class="userlist" href="userlist.ssjs?sort=connection">Connection</a></TH><TH><a class="userlist" href="userlist.ssjs?sort=laston">Last On</a></TH></TR>
<<REPEAT users>>
<TR>
  <TD>
    @@users:alias@@
  </TD>
  <TD>
    @@users:location@@
  </TD>
  <TD>
    @@users:connection@@
  </TD>
  <TD>
    @@users:logon@@
  </TD>
</TR>
<<END REPEAT users>>
</TABLE>

