#!/bin/sh
echo "                                                 LastUpdate: Mar-28-2001"
echo ""
echo "  This SHELL file will reset your LoRD2 game."
echo ""
echo "          Available only for:"
echo "                   - New World"
echo "                   - Complete New World"
echo ""
echo " An updated version can be found here:"
echo " http://greenmachinebbs.com/lord2/cnwfiles/RESET.BAT"
echo ""
echo "  Press CTRL+C NOW if you do NOT want to reset the game."
echo ""
read -p "Press enter to continue" ignore
rm -f mail/*
rm -f *.ioh
rm -f *.idf
rm -f tense*.dat
rm -f tense*.idf
rm -f tense*.txt
rm -f lockers*.idf
rm -f lock*.idf
rm -f *.chk
rm -f *.tmp
rm -f *.cod
rm -f *.auc
rm -f *.shw
rm -f chw*.dat
rm -f list*.dat
rm -f resetbug.rpt
rm -f thedraw.pck
rm -f wedpro?.txt
rm -f wedpro??.txt
rm -f prison.1??
rm -f prison.2??
rm -f prison.1?
rm -f prison.2?
rm -f prison.3?
rm -f prison.4?
rm -f prison.5?
rm -f prison.6?
rm -f prison.7?
rm -f prison.8?
rm -f prison.9?
rm -f prison.1
rm -f prison.2
rm -f prison.3
rm -f prison.4
rm -f prison.5
rm -f prison.6
rm -f prison.7
rm -f prison.8
rm -f prison.9
rm -f table.1??
rm -f table.2??
rm -f table.1?
rm -f table.2?
rm -f table.3?
rm -f table.4?
rm -f table.5?
rm -f table.6?
rm -f table.7?
rm -f table.8?
rm -f table.9?
rm -f table.1
rm -f table.2
rm -f table.3
rm -f table.4
rm -f table.5
rm -f table.6
rm -f table.7
rm -f table.8
rm -f table.9
rm -f bounty.1??
rm -f bounty.2??
rm -f bounty.1?
rm -f bounty.2?
rm -f bounty.3?
rm -f bounty.4?
rm -f bounty.5?
rm -f bounty.6?
rm -f bounty.7?
rm -f bounty.8?
rm -f bounty.9?
rm -f bounty.1
rm -f bounty.2
rm -f bounty.3
rm -f bounty.4
rm -f bounty.5
rm -f bounty.6
rm -f bounty.7
rm -f bounty.8
rm -f bounty.9
rm -f challeng.1??
rm -f challeng.2??
rm -f challeng.1?
rm -f challeng.2?
rm -f challeng.3?
rm -f challeng.4?
rm -f challeng.5?
rm -f challeng.6?
rm -f challeng.7?
rm -f challeng.8?
rm -f challeng.9?
rm -f challeng.1
rm -f challeng.2
rm -f challeng.3
rm -f challeng.4
rm -f challeng.5
rm -f challeng.6
rm -f challeng.7
rm -f challeng.8
rm -f challeng.9
rm -f jennie.1??
rm -f jennie.2??
rm -f jennie.1?
rm -f jennie.2?
rm -f jennie.3?
rm -f jennie.4?
rm -f jennie.5?
rm -f jennie.6?
rm -f jennie.7?
rm -f jennie.8?
rm -f jennie.9?
rm -f jennie.1
rm -f jennie.2
rm -f jennie.3
rm -f jennie.4
rm -f jennie.5
rm -f jennie.6
rm -f jennie.7
rm -f jennie.8
rm -f jennie.9
rm -f jw-isle1.mil
rm -f jw-isle2.mil
rm -f jw-isle3.mil
rm -f jw-isle4.mil
rm -f jw-islex.mil
rm -f jw-isleg.mil
rm -f jw-islel.mil
rm -f woodland.0??
rm -f woodland.1??
rm -f woodland.200
rm -f prisitem.*
rm -f prisinfo.*
rm -f jw-isle*.mil
rm -f castle.idx
rm -f 1stclass.dat
rm -f error.log
rm -f pyr4.dat
rm -f pyr5.dat
rm -f pyr6.dat
rm -f pyr7.dat
rm -f pr4.dat
rm -f pr5.dat
rm -f pr6.dat
rm -f pr7.dat
rm -f pys.idf
rm -f cott.dat
rm -f cotta.dat
rm -f alientel.inf
rm -f tlsscrew.dat
rm -f tlsinnrd.dat
rm -f tlswant.dat
rm -f tlsbur.dat
rm -f tlsinnrd.dat
rm -f tlsblando.dat
rm -f tlsyoda.dat
rm -f tlsturns.dat
rm -f tlstodag.dat
rm -f tlsyoda1.dat
rm -f bann.dat
rm -f time.dat
rm -f camelot.dat
rm -f cam.dat
rm -f trader.dat
rm -f bucket.dat
rm -f felhouse.dat
rm -f l2tree.dat
rm -f tensekb.dat
rm -f tensepk.dat
rm -f castle75.dat
rm -f tenseqz.dat
rm -f gorilla2.dat
rm -f mtres.dat
rm -f hong3.dat
rm -f hong3a.dat
rm -f myst.dat
rm -f myst1.dat
rm -f myst1a.dat
rm -f stime.dat
rm -f ninn2b.dat
rm -f tltres1.dat
rm -f tltres2.dat
rm -f tltres3.dat
rm -f tltres4.dat
rm -f tltres5.dat
rm -f isle35.dat
rm -f tltpet1.dat
rm -f tltpet2.dat
rm -f tltpet3.dat
rm -f tltpet4.dat
rm -f tltpet5.dat
rm -f tltname1.dat
rm -f tltname2.dat
rm -f tltname3.dat
rm -f tltname4.dat
rm -f tltname5.dat
rm -f castle1.dat
rm -f castle2.dat
rm -f castle3.dat
rm -f castle4.dat
rm -f castle71.dat
rm -f ninn?.dat
rm -f ninn??.dat
rm -f passage2.dat
rm -f castle4a.dat
rm -f castle76.dat
rm -f castle72.dat
rm -f regsysin.dat
rm -f house1.dat
rm -f tlhouse1.dat
rm -f tlhouse2.dat
rm -f tlhouse3.dat
rm -f tlhouse4.dat
rm -f tlhouse5.dat
rm -f room*.dat
rm -f jcastle.dat
rm -f tres*.dat
rm -f colisb.dat
rm -f coliseum.dat
rm -f coliseum.txt
rm -f coldesk1.txt
rm -f coldesk2.txt
rm -f coldesk3.txt
rm -f coldesk4.txt
rm -f coldesk5.txt
rm -f coldesk6.txt
rm -f coldesk7.txt
rm -f coldesk8.txt
rm -f coldesk9.txt
rm -f coldskb1.txt
rm -f coldskb2.txt
rm -f coldskb3.txt
rm -f coldskb4.txt
rm -f coldskb5.txt
rm -f coldskb6.txt
rm -f coldskb7.txt
rm -f coldskb8.txt
rm -f coldskb9.txt
rm -f qcastle.dat
rm -f swdtower.dat
rm -f srdtower.dat
rm -f wishwel2.dat
rm -f owtc.dat
rm -f keep.dat
rm -f ffhouse1.dat
rm -f ffhouse2.dat
rm -f ffhouse3.dat
rm -f ffhouse4.dat
rm -f ffhouse5.dat
rm -f cnwsign.*
rm -f castle78.dat
rm -f ship$.dat
rm -f castle74.dat
rm -f tlsbland.dat
rm -f tlsant.dat
rm -f pisle.dat
rm -f islez.dat
rm -f team1.dat
rm -f team2.dat
rm -f team3.dat
rm -f team4.dat
rm -f team5.dat
rm -f teamu.dat
rm -f lst20.dat
rm -f pass1.dat
rm -f pass2.dat
rm -f pass3.dat
rm -f pastre1.dat
rm -f pastre2.dat
rm -f pastre3.dat
rm -f temp*.dat
rm -f time.dat
rm -f stime.dat
rm -f gescape.*
rm -f canoe.chk
rm -f taxes.chk
rm -f hotel.dat
rm -f hotela.dat
mkdir npc
cd npc
rm -f *
cd ..
echo ""
echo ""
echo " Do you want to delete the writtings on the walls also?"
echo ""
echo "  Press CTRL+C NOW if you do NOT want to erase the walls."
echo ""
read -p "Press enter to continue" ignore
rm -f tlchat*.txt
rm -f bar*.txt
rm -f doc*.txt
rm -f fel*.txt
rm -f myst*.txt
rm -f wall.txt
rm -f tree.txt
rm -f passage.txt
rm -f hongwall.txt
rm -f lgossip.txt
rm -f gracom.txt
rm -f gummayor.txt
rm -f garden.txt
rm -f gossip.txt
rm -f book.txt
rm -f cloak.txt
rm -f pychat.txt
rm -f revenge.txt
rm -f revenge2.txt
rm -f *.txt
rm -f lock*.txt
rm -f info*.dat
echo ""
echo " DONE! All reset."
echo ""
echo " You may also want to run the RESET in L2CFG.EXE program."
echo ""
