<!-- Header.

Supports:
%%PATH%%  - URL to this script
%%TITLE%% - Replaced by title
%%NEXT%%  - URL to "next" screen
%%PREV%%  - URL to "previous" screen

--NEXT%% ... %%NEXT-- removed if there is a next screen.
++NEXT%% ... %%NEXT++ removed unless there is a next screen

-->
<BR>
<BR>
<!-- --PREV%% -->
<B>Prev</B>
<!-- %%PREV-- -->
<!-- ++PREV%% -->
<A HREF="%%PREV%%">Prev</A>
<!-- %%PREV++ -->

<!-- --NEXT%% -->
<B>Next</B>
<!-- %%NEXT-- -->
<!-- ++NEXT%% -->
<A HREF="%%NEXT%%">Next</A>
<!-- %%NEXT++ -->
</CENTER>
<br><br><a href="http://www.synchro.net/"><img src="/graphics/sync_pb.gif" border=0></a>
</BODY>
</HTML>
