<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=x-user-defined">
<TITLE>%%TITLE%%</TITLE>
</head>
<BODY>
<CENTER><H3>Welcome to FreeBSD Synchronet!</H3>
<!-- Header.

Supports:
%%PATH%%  - URL to this script
%%TITLE%% - Replaced by title
%%NEXT%%  - URL to "next" screen
%%PREV%%  - URL to "previous" screen

--NEXT%% ... %%NEXT-- removed if there is a next screen.
++NEXT%% ... %%NEXT++ removed unless there is a next screen
--PREV%% ... %%PREV-- removed if there is a next screen.
++PREV%% ... %%PREV++ removed unless there is a next screen

-->
