<!-- Group header.

Supports:
%%PATH%% - Valid URL for this script.
%%NEXT%%  - URL to "next" screen
%%PREV%%  - URL to "previous" screen
%%GRP_*%%               - Property from msg_area.grp_list ie: GRP_description

--NEXT%% ... %%NEXT-- removed if there is a next screen.
++NEXT%% ... %%NEXT++ removed unless there is a next screen


-->
<P><A HREF="http://freebsd.synchro.net/">Home</A> : <A HREF="%%PATH%%">Groups</A> : <B>%%GRP_description%%</B></P>
<TABLE>
