<!-- $Id: footer.inc,v 1.2 2018/03/14 02:19:55 deuce Exp $ -->

<!-- Begin footer -->

<div id="footer">
	<a class="footer" href="http://www.synchro.net/">@@server:version@@</a><br />
    <a class="footer" href="http://www.synchro.net/">@@system:version_notice@@</a>
</div>  

<div id="footerright">
	<a href="http://validator.w3.org/check?uri=referer"><img src="https://www.w3.org/Icons/valid-xhtml10" title="Valid XHTML 1.0!" alt="Valid XHTML 1.0!" height="31" width="88" border="0" /></a> 
<a href="http://jigsaw.w3.org/css-validator/"><img style="border:0;width:88px;height:31px" src="https://jigsaw.w3.org/css-validator/images/vcss" alt="Valid CSS!" /></a><br />
</div>
</body>
</html>
