<!-- $Id$ -->

<!-- Main Content -->  

<div id="contentcontainer">
	<div id="content">

            <p>From here you can <a class="tlink2" href="userstats.ssjs">View your stats</a>, <a class="tlink2" href="viewprofile.ssjs?showuser=%%user_num%%">View</a> or <a class="tlink2" href="editprofile.ssjs">Edit</a> your profile, or view the <a class="tlink2" href="sysinfo.ssjs">System information</a>.
			</p>
		</div>
	</div>
	<div class="cleardiv2"></div>
	</div>
</div>


<!-- end Main Content -->
