<div id="contentcontainer3">
	<div id="content2">
	<div align="center">
	
<h3>SyncDev IRC via RuneKeep BBS</h3>
<hr />
<applet code=IRCApplet.class archive="irc.jar,pixx.jar" width=640 height=400>
<param name="CABINETS" value="irc.cab,securedirc.cab,pixx.cab" />

<param name="nick" value="@@user_alias@@" />
<param name="alternatenick" value="@@user_handle@@???" />
<param name="fullname" value="@@user_name@@" />
<param name="host" value="runekeep.darktech.org" />
<param name="gui" value="pixx">

<param name="quitmessage" value="Synchronet Rulez!" />
<param name="asl" value="true" />
<param name="useinfo" value="true" />

<param name="style:bitmapsmileys" value="true" />
<param name="style:smiley1" value=":) img/sourire.gif" />
<param name="style:smiley2" value=":-) img/sourire.gif" />
<param name="style:smiley3" value=":-D img/content.gif" />
<param name="style:smiley4" value=":d img/content.gif" />
<param name="style:smiley5" value=":-O img/OH-2.gif" />
<param name="style:smiley6" value=":o img/OH-1.gif" />
<param name="style:smiley7" value=":-P img/langue.gif" />
<param name="style:smiley8" value=":p img/langue.gif" />
<param name="style:smiley9" value=";-) img/clin-oeuil.gif" />
<param name="style:smiley10" value=";) img/clin-oeuil.gif" />
<param name="style:smiley11" value=":-( img/triste.gif" />
<param name="style:smiley12" value=":( img/triste.gif" />
<param name="style:smiley13" value=":-| img/OH-3.gif" />
<param name="style:smiley14" value=":| img/OH-3.gif" />
<param name="style:smiley15" value=":'( img/pleure.gif" />
<param name="style:smiley16" value=":$ img/rouge.gif" />
<param name="style:smiley17" value=":-$ img/rouge.gif" />
<param name="style:smiley18" value="(H) img/cool.gif" />
<param name="style:smiley19" value="(h) img/cool.gif" />
<param name="style:smiley20" value=":-@ img/enerve1.gif" />
<param name="style:smiley21" value=":@ img/enerve2.gif" />
<param name="style:smiley22" value=":-S img/roll-eyes.gif" />
<param name="style:smiley23" value=":s img/roll-eyes.gif" />
<param name="style:backgroundimage" value="true" />
<param name="style:backgroundimage1" value="all all 0 background.png" />
<param name="style:sourcefontrule1" value="all all Serif 12" />
<param name="style:floatingasl" value="true" />

<param name="command1" value="/join #SyncDev" />
<param name="command2" value="/join #Synchronet" />

<param name="pixx:timestamp" value="true" />
<param name="pixx:highlight" value="true" />
<param name="pixx:highlightnick" value="true" />
<param name="pixx:nickfield" value="true" />
<param name="pixx:styleselector" value="true" />
<param name="pixx:setfontonstyle" value="true" />

</applet>

</div>
</div>
</div>

