<!-- $Id: lastcallers.inc,v 1.1 2006/02/22 02:16:17 runemaster Exp $ -->

<!-- Main Content -->  
   
<div id="contentcontainer3">
	<div id="content2">
	<div align="center">
<h3 align="center">Last Few Callers on @@system:name@@</h3>
<table class="lastcallers">
    <tr><td><pre class="leftalign">@@lastcallers@@</pre></td></tr>
</table>
<br />
		</div>
		</div>
	</div>
	<div class="cleardiv2"></div>
	</div>
</div>

<!-- end Main Content -->


