<!-- $Id: main.inc,v 1.4 2018/03/14 02:19:55 deuce Exp $ -->

<!-- Begin Main Content -->

		<div id="contentcontainer">
			<div id="content">
				<h3>NightShade Theme running on @@system:name@@</h3>
				<p>
				There are several minor annoyances for users of Internet Explorer (See notes below)</p><br />
				<p>I strongly urge you to download and use Firefox or Opera for better standards compliance and better security.</p><br />
				<p align="center"><a href="http://www.spreadfirefox.com/?q=affiliates&amp;id=0&amp;t=58"><img border="0" alt="Get Firefox!" title="Get Firefox!" src="https://sfx-images.mozilla.org/affiliates/Buttons/180x60/get.gif"/></a>&nbsp;&nbsp;<a href="http://my.opera.com/RuneMaster/affiliate/"><img src="https://promote.opera.com/buttons/official/180x60/png-8/180x60noads.png" alt="No ads. Better browsing" border="0" /></a></p><br />
				<p>
				--RuneMaster
				</p>
				<br /><br />
				<h3>Notes About This Theme</h3>
				<p>
				This theme uses no Tables for the main layout.  The only tables currently in use are for the Who's Online when displayed at the right and the Stats display.  All other layout features employ only CSS (Cascading Style Sheets)  Although not exact, the layout remains extremely close between all major browsers tested: </p>
				<ul>
					<li>Working
					<ul>
						<li>Firefox 1.5 (Win32)</li> 
						<li>Mozilla 1.7.12 (Win32)</li>
						<li>Opera 8.51 (Win32)</li> 
						<li>Firefox 1.0.7 (Linux)</li>
						<li>Konquerer 3.4.3 (Linux)</li>
					</ul>
					</li>
					<li>Working but with issues<sup>1</sup>
					<ul>
						<li>Internet Explorer 6.0.29</li>
						<li>Internet Explorer 7.0.5296.0 (Beta 2 Preview)</li>
					</ul>
					</li>
				</ul>
				<p>
					Of all the tested browsers, only Internet Explorer caused major headaches due to Microsoft not adhering to technical standards for web design.  It took major &quot;hacks&quot; to get Internet Explorer to look the sames as all the other browsers tested.</p>
				<p>
					I do need testing and reporting on Internet Explorer versions prior to v6 and Safari 
				</p>
				<div align="center"><p>Additional Services<br /><br />@@additional_services@@</p></div>
								<hr />
				<p>
					<sup>1</sup>If a table is used in the center section and has a width of 100% or if a smaller width is used and the browser window is too small, Internet Explorer completely messes up the layout putting a <em>huge</em> blank section at the top matching the height of the tallest element to either side.  So far this is the <em>only</em> browser to be affected due to non-standards compliance.  All other browsers render it correctly.
					Of interest, it took a different set of &quot;hacks&quot; to get IE7 to behave.  However IE7 is slightly better behaved than prior versions. 
				</p>
		</div>
	</div>
	<div class="cleardiv2"></div>
	</div>
</div>

<!-- End Main Content -->
