<!-- $Id$ -->

<!-- Main Content -->  

<div id="contentcontainer">
	<div id="content2">

<br />
<p>Your account has been created and the password has been mailed to: <b>%%posted:netmail%%</b></p>
<p>You can Login using your Username and the supplied password by using the <b>Login</b> button on the left.</p>
<br />
<br />

		</div>
	</div>
	<div class="cleardiv2"></div>
	</div>
</div>

<!-- end Main Content --> 