<!-- $Id: picktheme.inc,v 1.1 2006/02/22 02:16:17 runemaster Exp $ -->

<!-- Main Content -->  
    
<div id="contentcontainer">
	<div id="content2">
	<div align="center">
			<br />
            Current theme set to: %%theme:desc%%<br /><br />
            <a href="/">Back</a><br /><br />
			<br />
		</div>
		</div>
	</div>
	<div class="cleardiv2"></div>
	</div>
</div>

<!-- end Main Navigation -->


