<!-- $Id$ -->

<!-- Main Content -->  


<div id="contentcontainer">
	<div id="content2">
	<div align="center">
            <form action="picktheme.ssjs" method="post">
                <br />
                @@theme_list@@<br /><br />
                <input type="submit" name="Select Theme" value="Select Theme" />
            </form>
			<br />
		</div>
		</div>
	</div>
	<div class="cleardiv2"></div>
	</div>
</div>


<!-- end Main Content -->