<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <OpenDoorsLibraryDir Condition="'$(OpenDoorsLibraryDir)' == '' and '$(Platform)' == 'Win32' and Exists('$(MSBuildThisFileDirectory)ODoorW.lib')">$(MSBuildThisFileDirectory)</OpenDoorsLibraryDir>
    <OpenDoorsLibraryDir Condition="'$(OpenDoorsLibraryDir)' == '' and '$(Platform)' == 'Win32'">$(MSBuildThisFileDirectory)build\msvc\x86\lib\$(Configuration)</OpenDoorsLibraryDir>
    <OpenDoorsLibraryDir Condition="'$(OpenDoorsLibraryDir)' == '' and '$(Platform)' == 'x64'">$(MSBuildThisFileDirectory)build\msvc\x64\lib\$(Configuration)</OpenDoorsLibraryDir>
    <OpenDoorsLibraryDir Condition="'$(OpenDoorsLibraryDir)' == ''">$(MSBuildThisFileDirectory)</OpenDoorsLibraryDir>
  </PropertyGroup>
  <PropertyGroup>
    <_PropertySheetDisplayName>OpenDoors Library</_PropertySheetDisplayName>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory);%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(OpenDoorsLibraryDir);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>
