OBJS = \
	$(MTOBJODIR)$(DIRSEP)bbscur$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)plycur$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)plylst$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)bbslst$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)gamesdki$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)gamesdko$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)gamesdk$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)netmail$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)gregedit$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)ibbscfg$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)gac_wh_s$(OFILE) \
	$(MTOBJODIR)$(DIRSEP)wahoo$(OFILE) 

