OBJS = \
	$(OBJODIR)$(DIRSEP)b_printc$(OFILE) \
	$(OBJODIR)$(DIRSEP)barcolor$(OFILE) \
	$(OBJODIR)$(DIRSEP)changchr$(OFILE) \
	$(OBJODIR)$(DIRSEP)changeco$(OFILE) \
	$(OBJODIR)$(DIRSEP)crt_gtxy$(OFILE) \
	$(OBJODIR)$(DIRSEP)crt_init$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtbord$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtclrsc$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtdtect$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtfntsp$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtframe$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtframw$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtmode$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtvar$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtwin$(OFILE) \
	$(OBJODIR)$(DIRSEP)cursorsh$(OFILE) \
	$(OBJODIR)$(DIRSEP)fillbar$(OFILE) \
	$(OBJODIR)$(DIRSEP)fillbarw$(OFILE) \
	$(OBJODIR)$(DIRSEP)fillbox$(OFILE) \
	$(OBJODIR)$(DIRSEP)fillboxw$(OFILE) \
	$(OBJODIR)$(DIRSEP)fillscr$(OFILE) \
	$(OBJODIR)$(DIRSEP)getcrtch$(OFILE) \
	$(OBJODIR)$(DIRSEP)getcrtco$(OFILE) \
	$(OBJODIR)$(DIRSEP)getxy$(OFILE) \
	$(OBJODIR)$(DIRSEP)mkline$(OFILE) \
	$(OBJODIR)$(DIRSEP)printc$(OFILE) \
	$(OBJODIR)$(DIRSEP)printcn$(OFILE) \
	$(OBJODIR)$(DIRSEP)printct$(OFILE) \
	$(OBJODIR)$(DIRSEP)prints$(OFILE) \
	$(OBJODIR)$(DIRSEP)printsf$(OFILE) \
	$(OBJODIR)$(DIRSEP)printsj$(OFILE) \
	$(OBJODIR)$(DIRSEP)printsjc$(OFILE) \
	$(OBJODIR)$(DIRSEP)printsjf$(OFILE) \
	$(OBJODIR)$(DIRSEP)printsn$(OFILE) \
	$(OBJODIR)$(DIRSEP)printsnf$(OFILE) \
	$(OBJODIR)$(DIRSEP)printt$(OFILE) \
	$(OBJODIR)$(DIRSEP)printtf$(OFILE) \
	$(OBJODIR)$(DIRSEP)printx$(OFILE) \
	$(OBJODIR)$(DIRSEP)printxf$(OFILE) \
	$(OBJODIR)$(DIRSEP)printxy$(OFILE) \
	$(OBJODIR)$(DIRSEP)printxyf$(OFILE) \
	$(OBJODIR)$(DIRSEP)prntsjcf$(OFILE) \
	$(OBJODIR)$(DIRSEP)rstcrt$(OFILE) \
	$(OBJODIR)$(DIRSEP)rstcrtw$(OFILE) \
	$(OBJODIR)$(DIRSEP)rstcrtw2$(OFILE) \
	$(OBJODIR)$(DIRSEP)rstvideo$(OFILE) \
	$(OBJODIR)$(DIRSEP)rstvidw$(OFILE) \
	$(OBJODIR)$(DIRSEP)rstvidw2$(OFILE) \
	$(OBJODIR)$(DIRSEP)savcrtw2$(OFILE) \
	$(OBJODIR)$(DIRSEP)savecrt$(OFILE) \
	$(OBJODIR)$(DIRSEP)savecrtw$(OFILE) \
	$(OBJODIR)$(DIRSEP)savevidw$(OFILE) \
	$(OBJODIR)$(DIRSEP)savvideo$(OFILE) \
	$(OBJODIR)$(DIRSEP)savvidw2$(OFILE) \
	$(OBJODIR)$(DIRSEP)textblnk$(OFILE) \
	$(OBJODIR)$(DIRSEP)vmode$(OFILE) \
	$(OBJODIR)$(DIRSEP)stubs$(OFILE)

REMOVED = \
	$(OBJODIR)$(DIRSEP)crtdacr$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtpage$(OFILE) \
	$(OBJODIR)$(DIRSEP)crtpal$(OFILE) \
	$(OBJODIR)$(DIRSEP)boxwidth$(OFILE)
