/* main.c -- SyncRetro frontend entry point.
 *
 * Order (DESIGN.md sec 3):
 *   1. sr_door_setup()          resolve socket / time / name / home / core / rom
 *   2. sr_door_sanitize_argv()  strip the door's own args
 *   3. sr_config_apply()        per-user sandbox + system/save dirs
 *   4. rc_core_open()           dlopen the libretro core
 *   5. sr_io_init()             terminal enter + probe (geometry / caps)
 *   6. rc_core_load_game()      install callbacks, retro_init, load ROM
 *   7. loop: rc_core.run() at native fps; termgfx drops video frames as needed
 *   8. teardown (always): unload core + restore the BBS terminal
 */
#include "retro_core.h"
#include "syncretro.h"
#include "syncretro_binds.h"
#include "syncretro_audio.h"
#include "syncretro_profile.h"
#include "syncretro_plat.h"

#include "charset.h"    /* termgfx: client charset + box-drawing glyphs */
#include "git_hash.h"   /* GIT_HASH, GIT_DATE -- generated by synchronet_gitinfo() */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

/* Pace the CORE to its native rate. Video presentation is frame-dropped
 * downstream (syncretro_io.c's DSR-ACK gate); audio, when M4 enables it, stays
 * real-time. Slowing retro_run() to match the pipe instead would pitch-shift the
 * audio and run the game in slow motion -- DESIGN.md sec 3's "frame-rate
 * decision".
 *
 * Absolute deadlines accumulated from a fixed epoch, NOT a relative sleep per
 * frame: a relative sleep pays for the frame's own compute time twice (once
 * running it, once sleeping a full period afterward) and the error compounds, so
 * a 60 fps core would drift slow forever. Recomputing the next deadline from the
 * previous one keeps the long-run average exact.
 *
 * The deadline lives in the monotonic-microsecond domain (sr_plat_now_us),
 * reframed from the POSIX build's clock_nanosleep(TIMER_ABSTIME) so it ports to
 * a platform with only a millisecond sleep: we sleep the whole-millisecond part
 * of the remaining time and let the loop's recheck absorb the sub-millisecond
 * rounding. Accumulating `next` regardless of how long a sleep actually took is
 * what keeps that rounding from becoming drift.
 *
 * When a frame overruns its budget (a slow sixel encode, a stalled write) the
 * deadline is already in the past, we do NOT try to catch up by running frames
 * back to back -- the deadline is reset to now, so an overrun costs that frame's
 * lateness and nothing more. Catching up would fast-forward the game.
 */
static void sr_pace_to_rate(double fps)
{
	static int64_t next_us;
	static int     armed;
	int64_t        period_us, now;

	if (fps <= 0.0)
		fps = 60.0;                     /* a core with no timing: assume 60 */
	period_us = (int64_t)(1000000.0 / fps);

	if (!armed) {
		next_us = sr_plat_now_us();
		armed = 1;
	}

	next_us += period_us;

	now = sr_plat_now_us();
	if (now > next_us) {
		next_us = now;                  /* overran: resync, never fast-forward */
		return;
	}
	/* Sleep the whole-ms remainder, then recheck: a millisecond-granularity
	 * sleep can wake early or late, so loop until the deadline is reached (or
	 * passed). A sub-ms remainder is left unslept rather than busy-spun -- `next`
	 * still advanced by a full period, so the average stays exact. */
	for (;;) {
		int64_t rem = next_us - sr_plat_now_us();

		if (rem < 1000)
			break;
		sr_plat_sleep_ms((int)(rem / 1000));
	}
}

/* The door owns pause and help. FreeIntv has its own -- reachable from RetroPad
 * START, painted into the framebuffer -- but its help screen describes the
 * core's RetroPad convention, which our bindings replace, and we could not
 * intercept a word of it. See M2_INPUT.md sec 2.
 *
 * Both screens are plain ANSI text over a cleared screen, NOT pixels. That
 * works on every graphics tier and on a client with no graphics at all. Leaving
 * either screen invalidates the frame cache, so the game repaints in full
 * rather than diffing against a frame the player never saw. */

static void sr_puts(const char *s)
{
	sr_out_put(s, strlen(s));
}

/* The door is dead before it drew a thing. SAY SO, ON THE PLAYER'S SCREEN.
 *
 * `why` is the failure in a sentence; `hint` is for the sysop (it is his install
 * that is broken, and he is usually the first one to hit it) and may be NULL.
 * Both go to stderr as well, for the BBS log on a platform that keeps one.
 *
 * The message is left up for a few seconds: the BBS clears the screen the moment
 * the door returns, and a message the player cannot read is no better than the
 * silence this replaces. */
static void sr_fatal(const char *why, const char *hint)
{
	char line[512];
	int  n;

	fprintf(stderr, "syncretro: %s\n", why);
	if (hint != NULL)
		fprintf(stderr, "syncretro: %s\n", hint);

	n = snprintf(line, sizeof line,
	             "\x1b[0m\x1b[2J\x1b[H\r\n"
	             "  \x1b[1;31mSyncRetro cannot start.\x1b[0m\r\n\r\n"
	             "  \x1b[1;37m%s\x1b[0m\r\n", why);
	if (n > 0)
		sr_out_put(line, (size_t)n);
	if (hint != NULL) {
		n = snprintf(line, sizeof line, "\r\n  \x1b[0;36m%s\x1b[0m\r\n", hint);
		if (n > 0)
			sr_out_put(line, (size_t)n);
	}
	sr_puts("\r\n  \x1b[0;37mReturning to the BBS...\x1b[0m\r\n");
	sr_io_out_flush();
	sr_plat_sleep_ms(5000);      /* long enough to be read, short enough not to annoy */
	sr_io_out_flush();
}

/* The door's own version line. SR_VERSION is bumped per release by hand; the
 * hash and date are the SBBS repo's git state at build time (git_hash.h, from
 * the shared synchronet_gitinfo() CMake helper), so they stamp THIS build. Same
 * shape the sibling doors use: "<ver> <hash> <date> synchro.net". */
#define SR_VERSION "v0.1"

/* Attributes. Named, because a screen full of raw \x1b[1;36m is unreadable and
 * a change of taste should be a change in one place. */
#define A_OFF    "\x1b[0m"
#define A_FRAME  "\x1b[1;34m"      /* the box: bright blue */
#define A_DOOR   "\x1b[1;37m"      /* "SyncRetro" */
#define A_CON    "\x1b[1;33m"      /* the console's name */
/* The badge sets a BACKGROUND, and a background is sticky: the next SGR that
 * only names a foreground (A_FRAME) leaves the red in place, and the box glyphs
 * after the badge get drawn on it -- the red bled out of the badge and along the
 * rule to the corner. Anything that follows the badge must reset FIRST. */
#define A_PAUSED "\x1b[1;33;41m"   /* the PAUSED badge: yellow on red */
#define A_UNBADGE A_OFF A_FRAME    /* ...and back to a plain frame, background and all */
#define A_KEY    "\x1b[1;36m"      /* key names */
#define A_DESC   "\x1b[0;37m"      /* what they do */
#define A_NOTE   "\x1b[0;36m"      /* the closing paragraph */
#define A_VER    "\x1b[0;37m"      /* the version: quiet, but it has to be READABLE --
	                                * 0;34 (dark blue on black) was not */
#define A_HOST   "\x1b[0;36m"      /* "synchro.net" */
#define A_GAME   "\x1b[1;32m"      /* the cartridge being played */
#define A_PROMPT "\x1b[1;37m"      /* how to leave */

/* Emit `n` copies of a (possibly multi-byte) glyph. */
static void sr_repeat(const char *glyph, int n)
{
	while (n-- > 0)
		sr_puts(glyph);
}

/* One framed row: the left bar, `body` (which carries its own attributes and is
 * `vis` columns wide once they are stripped), spaces out to `inner`, the right
 * bar. Cursor-addressed, never newline-terminated -- a \r\n on the last row of
 * the page scrolls the screen out from under the box. */
static void sr_row(int row, int col, const termgfx_box_t *b, const char *body, int vis, int inner)
{
	char pos[24];

	snprintf(pos, sizeof pos, "\x1b[%d;%dH", row, col);
	sr_puts(pos);
	sr_puts(A_FRAME);
	sr_puts(b->v);
	sr_puts(A_OFF);
	if (body != NULL)
		sr_puts(body);
	sr_repeat(" ", (inner > vis) ? inner - vis : 0);
	sr_puts(A_FRAME);
	sr_puts(b->v);
	sr_puts(A_OFF);
}

/* Expand SR_SEP ('\1', see syncretro_binds.c) into `sep` -- the client charset's
 * box-drawing vertical bar. The strings in the bind tables used to carry a literal
 * '|', which in a key legend reads as a key to press ("W A S D | arrows" -- is the
 * pipe part of it?); a rule glyph cannot be misread that way, but it is one byte in
 * CP437 and three in UTF-8, so it cannot live in the table either.
 *
 * Returns the VISIBLE width of the result (each marker counts as one column,
 * whatever it cost in bytes), which is what the padding math needs. */
static int sr_sep_expand(char *dst, size_t cap, const char *src, const char *sep)
{
	size_t sl  = strlen(sep);
	int    vis = 0;
	size_t o   = 0;

	for (; *src != '\0'; src++) {
		if (*src == '\1') {
			if (o + sl >= cap)
				break;
			memcpy(dst + o, sep, sl);
			o += sl;
		} else {
			if (o + 1 >= cap)
				break;
			dst[o++] = *src;
		}
		vis++;
	}
	dst[o] = '\0';
	return vis;
}

/* One screen serves pause, '?' and an unbound key: a player who reaches any of
 * the three wants the same thing -- the list of keys. The core is stopped behind
 * all three of them -- the door never runs it while a screen is up -- so the
 * PAUSED badge is unconditional: it reports the core's state, not which key got
 * the player here. Only the closing prompt differs, because only the Space pause
 * needs a specific key to leave.
 *
 * PLAIN TEXT, NOT PIXELS, and drawn with box-drawing glyphs in the CLIENT'S
 * charset (termgfx_client_charset): it has to render on a graphics-less terminal
 * and on a UTF-8 ssh client alike, and a door writes raw bytes -- nothing between
 * here and the player converts CP437 for us. */
static void sr_screen_keys(int from_pause)
{
	termgfx_charset_t    cs   = termgfx_client_charset();
	const termgfx_box_t *b    = termgfx_box_double(cs);
	const char *         sep  = termgfx_box_single(cs)->v;   /* the key-list separator */
	const char *         con  = sr_door_console();
	const char *         game = sr_door_title();
	const char *         note[4];
	const char *         key, *desc;
	char                 body[256], pos[24];
	int                  rows = 0, cols = 0;
	int                  nkeys, nnote, need, top, left, w, inner;
	int                  spacer = 1;      /* the blank row between keys and prose */
	int                  i, r, vis;

	sr_io_grid(&rows, &cols);
	if (cols < 40)
		cols = 80;                          /* the terminal never said: assume 80x24 */
	if (rows < 10)
		rows = 24;

	w = (cols > 78) ? 76 : cols - 2;        /* the box, with a column of air each side */
	if (w < 40)
		w = 40;
	inner = w - 2;

	/* The closing paragraph is the console's, not the door's -- the Intellivision
	 * needs four lines that would be nonsense on a gamepad. */
	if (sr_profile() == SR_PROFILE_INTV) {
		note[0] = "Both controllers are live: player 1 = W A S D / Z X C / number row,";
		note[1] = "player 2 = arrows / , . / / numeric keypad.  Two can play on one";
		note[2] = "keyboard; solo, use whichever set the game reads (or Tab to swap).";
		note[3] = "Most games start on a keypad digit, not an action button.";
		nnote   = 4;
	} else {
		note[0] = "Most games start at Enter (Start).  If nothing responds at all, the";
		note[1] = "game may be reading the second controller port: press Tab and try";
		note[2] = "again.";
		nnote   = 3;
	}

	for (nkeys = 0; sr_bind_help_line(nkeys, &key, &desc); nkeys++)
		;

	/* top rule [+ cartridge + air] + keys + spacer + note + divider + version +
	 * bottom rule */
	need = 1 + (game != NULL ? 2 : 0) + nkeys + 1 + nnote + 1 + 1 + 1;

	/* TOO TALL FOR THIS TERMINAL. An 80x24 screen has no room to spare, and the
	 * key list grows every time the door learns a key -- adding F4 was enough to
	 * push the bottom border off the bottom of the screen, which is not a thing
	 * anyone would notice until a player saw it. So shed the ornaments, in order of
	 * how little they matter, and never let the box run past the last row: the
	 * cartridge line is a nicety, the blank line is a breath, the closing paragraph
	 * is advice -- the KEY LIST and the BORDER are the screen. */
	if (need > rows && game != NULL) {
		game  = NULL;
		need -= 2;
	}
	if (need > rows && spacer) {
		spacer = 0;
		need  -= 1;
	}
	while (need > rows && nnote > 0) {
		nnote--;
		need--;
	}
	top  = (rows > need) ? 1 + (rows - need) / 2 : 1;
	left = 1 + (cols - w) / 2;

	sr_puts("\x1b[2J");                     /* clear; every row below is addressed */

	/* The top rule carries the title, and the PAUSED badge rides its right end
	 * rather than costing a row of its own. `vis` counts the cells drawn BETWEEN
	 * the two corners, so the fill run below lands the closing corner exactly. */
	snprintf(pos, sizeof pos, "\x1b[%d;%dH", top, left);
	sr_puts(pos);
	sr_puts(A_FRAME);
	sr_puts(b->tl);
	sr_repeat(b->h, 2);
	sr_puts(" " A_DOOR "SyncRetro" A_FRAME " ");
	vis = 2 + 11;
	if (con != NULL) {
		sr_repeat(b->h, 1);
		sr_puts(" " A_CON);
		sr_puts(con);
		sr_puts(A_FRAME " ");
		vis += 1 + 1 + (int)strlen(con) + 1;
	}
	{
		int fill = inner - vis - 10;    /* badge (8) + the rule's own two cells */

		sr_repeat(b->h, (fill > 0) ? fill : 0);
		sr_repeat(b->h, 1);
		sr_puts(A_PAUSED " PAUSED " A_UNBADGE);
		sr_repeat(b->h, 1);
	}
	sr_puts(b->tr);
	sr_puts(A_OFF);

	r = top + 1;

	/* The cartridge, when the lobby told us which one. A player who paused in the
	 * middle of a session should not have to remember what he is playing. */
	if (game != NULL) {
		snprintf(body, sizeof body, "  " A_GAME "%s", game);
		sr_row(r++, left, b, body, 2 + (int)strlen(game), inner);
		sr_row(r++, left, b, NULL, 0, inner);
	}
	for (i = 0; sr_bind_help_line(i, &key, &desc); i++, r++) {
		char k[64], d[96];
		int  kn = sr_sep_expand(k, sizeof k, key, sep);
		int  dn = sr_sep_expand(d, sizeof d, desc, sep);

		snprintf(body, sizeof body, "  " A_KEY "%s" A_DESC "%*s%s",
		         k, (kn < 18) ? 18 - kn : 1, "", d);
		vis = 2 + ((kn < 18) ? 18 : kn + 1) + dn;
		sr_row(r, left, b, body, vis, inner);
	}

	if (spacer)
		sr_row(r++, left, b, NULL, 0, inner);   /* a breath between keys and prose */

	for (i = 0; i < nnote; i++, r++) {
		snprintf(body, sizeof body, "  " A_NOTE "%s", note[i]);
		sr_row(r, left, b, body, 2 + (int)strlen(note[i]), inner);
	}

	/* A full-width divider, then the version + how to leave, on the same row. */
	snprintf(pos, sizeof pos, "\x1b[%d;%dH", r++, left);
	sr_puts(pos);
	sr_puts(A_FRAME);
	sr_puts(b->lt);
	sr_repeat(b->h, inner);
	sr_puts(b->rt);
	sr_puts(A_OFF);

	{
		const char *leave = from_pause ? "Space to resume" : "any key to return";
		char        ver[80];
		int         vn;

		/* GIT_DATE is "Jul 12 2026 02:48"; the clock time is noise on a version
		 * line, so keep the date and drop it. */
		vn = snprintf(ver, sizeof ver, "%s  %s  %.11s  synchro.net",
		              SR_VERSION, GIT_HASH, GIT_DATE);
		snprintf(body, sizeof body,
		         "  " A_VER "%s  %s  %.11s  " A_HOST "synchro.net" A_OFF
		         "%*s" A_PROMPT "%s" A_OFF "  ",
		         SR_VERSION, GIT_HASH, GIT_DATE,
		         (inner - 2 - vn - (int)strlen(leave) - 2 > 0)
		            ? inner - 2 - vn - (int)strlen(leave) - 2 : 1, "", leave);
		sr_row(r++, left, b, body, inner, inner);
	}

	snprintf(pos, sizeof pos, "\x1b[%d;%dH", r, left);
	sr_puts(pos);
	sr_puts(A_FRAME);
	sr_puts(b->bl);
	sr_repeat(b->h, inner);
	sr_puts(b->br);
	sr_puts(A_OFF);

	sr_io_out_flush();
}

/* Sleep out the frame budget while the core is not running. */
static void sr_idle_ms(long ms)
{
	sr_plat_sleep_ms((int)ms);
}

int main(int argc, char **argv)
{
	rc_core_t core;
	int       rc = 1;

	if (sr_door_setup(argc, argv) != 0)
		return 1;
	sr_door_sanitize_argv(&argc, argv);
	sr_config_apply();
	sr_audio_init();                    /* reads syncretro.ini; no I/O yet */

	/* THE TERMINAL COMES UP BEFORE THE CORE, and that ordering is the whole point.
	 *
	 * Every fatal startup error used to be an fprintf to stderr -- and a door's
	 * stderr reaches nobody: the BBS spawns it with no console (on Windows, with
	 * EX_NODISPLAY, there is not even one to spawn). So a door with a missing core
	 * printed "Loading SyncRetro...", died, and handed the player back to the BBS
	 * with no message on the screen and no line in any log. "It doesn't work" was
	 * all anyone could say about it, and that is exactly how the Windows install
	 * failed: the core .dll was never installed beside the .exe, and the door had
	 * no way to say so.
	 *
	 * A stdio door reads fd 0 and writes fd 1 -- two descriptors, each half-duplex
	 * -- where a socket door reads and writes one. */
	if (sr_door_stdio()) {
		if (sr_io_init_fds(0, 1) != 0)
			return 1;
	} else if (sr_io_init(sr_door_socket()) != 0)
		return 1;

	/* sr_config_apply() has already chdir'd into the per-user sandbox, so the
	 * core and ROM must come from IT (absolutized against the launch dir), not
	 * from the raw sr_door_*_path() command-line values. */
	if (sr_config_core_path() == NULL) {
		sr_fatal("No libretro core is installed for this console.",
		         "Sysop: run getcore.js in the door's directory -- and note that it"
		         " installs the core for the host it RUNS on, so a BBS that spans a"
		         " Linux and a Windows machine needs it run on both.");
		return 1;
	}
	if (rc_core_open(&core, sr_config_core_path()) != 0) {
		sr_fatal(rc_core_error(),
		         "Sysop: the core must match the door binary -- a 32-bit .dll for the"
		         " Win32 .exe, a .so for the *nix build. getcore.js installs the right"
		         " one for the host it runs on.");
		return 1;
	}

	if (rc_core_load_game(&core, sr_config_rom_path()) != 0) {
		sr_fatal(rc_core_error(), NULL);
		goto done;
	}

	/* AFTER load_game, and before the first input pump or audio chunk: neither of
	 * these facts exists any earlier. The core's library_name is only defined once
	 * it is loaded, and its sample rate only once a game is (the NES is 48000, the
	 * Intellivision 44100 -- and the door hardcoded 44100 until M3). */
	sr_profile_select(sr_door_profile(), core.si.library_name);

	/* Select a controller type, if this install pinned one. AFTER load_game --
	 * a core builds its port/device tables while loading content, and MAME
	 * 2003-Plus in particular decides how many buttons a driver wants there.
	 * Silent by default ([input] device = 0): saying nothing leaves the core on
	 * its own choice, which is what the door has always done and is right for
	 * every console that offers only a plain RetroPad. */
	{
		int dev = sr_config_input_device();

		if (dev > 0) {
			core.set_controller_port_device(0, (unsigned)dev);
			core.set_controller_port_device(1, (unsigned)dev);
			fprintf(stderr, "syncretro: controller device %d selected"
			        " on ports 0 and 1\n", dev);
		}
	}
	/* Before sr_audio_start(), which reads a sample rate the OPTIONS decided:
	 * MAME 2003-Plus derives its rate from an option and reports 0 Hz when the
	 * frontend answers nothing. The report is a log line, but it is also the
	 * only place a mis-typed console pin is ever mentioned. */
	sr_options_report();
	sr_audio_start((int)core.av.timing.sample_rate);

	/* The frame's DISPLAY shape. A console's pixels are not square: the NES's
	 * 256x240 was shown on a 4:3 television, and fitting it as 256:240 draws it a
	 * quarter too narrow. FreeIntv masked this for a whole milestone -- its
	 * 352x224 IS the 1.5714 it reports. See syncretro_io.c / [video] aspect. */
	{
		double core_par = (double)core.av.geometry.aspect_ratio;
		double par      = sr_config_aspect(core_par);

		/* Say which shape we settled on, and where it came from. The door already
		 * logs its profile and its sample rate; leaving the aspect silent is what
		 * made a mis-sectioned `aspect =` key (one sitting outside [video]) look
		 * like the setting was being ignored. */
		if (par > 0.0)
			fprintf(stderr, "syncretro: aspect %.3f  ([video] aspect = %s; the core"
			        " reports %.3f)\n", par, sr_config_aspect_mode(), core_par);
		else
			fprintf(stderr, "syncretro: aspect SQUARE pixels ([video] aspect = %s;"
			        " the core reports %.3f)\n", sr_config_aspect_mode(), core_par);
		sr_io_set_aspect(par);
	}

	/* Who's-online now names the CARTRIDGE -- "playing Astrosmash (Intellivision)"
	 * -- the way SyncDOOM names its WAD and map, instead of the BBS's generic
	 * "running external program". Set once and cleared on exit: a cartridge, unlike
	 * a map, does not change mid-session. */
	sr_door_node_playing(sr_config_rom_path());

	{
		int paused  = 0;   /* Space: the core is not being run */
		int helping = 0;   /* the key legend is up ('?', or an unbound key) */

		for (;;) {
			int action;

			if (sr_door_should_exit())
				break;

			/* A door screen is up: the core is not running, so nothing polls the
			 * socket for us, and game keys must be swallowed rather than held. */
			if (paused || helping) {
				sr_input_pump();
				action = sr_input_take_action();

				if (helping) {
					/* Any key returns -- bound or not, which is why
					 * sr_input_set_suspended() clears the anykey latch when the
					 * screen opens. */
					if (action != SR_DOOR_NONE || sr_input_take_anykey()) {
						helping = 0;
						sr_input_set_suspended(0);
						sr_audio_pause(0);
						sr_io_invalidate();
					}
				} else if (action == SR_DOOR_PAUSE) {
					paused = 0;
					sr_input_set_suspended(0);
					sr_audio_pause(0);
					sr_io_invalidate();
				} else if (action == SR_DOOR_HELP) {
					/* The pause screen already IS the key legend, so '?' behind it
					 * has nothing to add. Swallow it, and swallow any game key
					 * struck behind the screen along with it. */
					(void)sr_input_take_anykey();
				} else if (action == SR_DOOR_RESET) {
					core.reset();
					sr_audio_reset();       /* queued audio outlived its game */
					paused = 0;
					sr_input_set_suspended(0);
					sr_audio_pause(0);
					sr_io_invalidate();
				}
				sr_idle_ms(16);
				continue;
			}

			/* Once a second under keytrace: is the core still being run, and what
			 * pad does it see? Separates "the door stalled" from "the core has
			 * the input and draws nothing" -- the two look identical on screen. */
			{
				static unsigned nrun;

				if ((nrun++ % 60) == 0)
					sr_trace("core.run #%u pad L=%d R=%d U=%d D=%d", nrun,
					         sr_pad_get(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_LEFT),
					         sr_pad_get(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_RIGHT),
					         sr_pad_get(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_UP),
					         sr_pad_get(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_DOWN));
			}
			core.run();             /* -> video/audio/input callbacks fire */
			sr_io_stats_tick();     /* advance/refresh the Ctrl-S stats overlay */

			action = sr_input_take_action();
			if (action == SR_DOOR_PAUSE || action == SR_DOOR_HELP) {
				sr_input_release_all();     /* no key survives the screen */
				sr_input_set_suspended(1);
				sr_audio_pause(1);          /* core stops -> FIFO drains on purpose */
				if (action == SR_DOOR_PAUSE) {
					paused = 1;
					sr_screen_keys(1);
				} else {
					helping = 1;
					sr_screen_keys(0);
				}
				continue;
			}
			if (action == SR_DOOR_STATS)
				sr_io_stats_toggle();       /* Ctrl-S: flip the overlay, keep playing */
			if (action == SR_DOOR_TIER)
				sr_io_cycle_tier();         /* F4: sixel <-> the text tiers, keep playing */
			if (action == SR_DOOR_VOL_UP || action == SR_DOOR_VOL_DOWN) {
				float db = sr_audio_volume_step(action == SR_DOOR_VOL_UP ? +6.0f : -6.0f);
				char  msg[64];

				/* Below the floor the door sends no audio AT ALL
				 * (sr_audio_volume_step snaps to mute), so say so -- a bare
				 * level reads like a quiet stream still costing bandwidth. */
				if (sr_audio_muted())
					snprintf(msg, sizeof msg, "Volume off -- nothing sent");
				else
					snprintf(msg, sizeof msg, "Volume %.0f dB", db);
				sr_io_toast(msg);
			}
			if (action == SR_DOOR_RESET) {
				sr_input_release_all();
				core.reset();
				sr_audio_reset();           /* queued audio outlived its game */
				sr_io_invalidate();
			}
			sr_pace_to_rate(core.av.timing.fps);
		}
	}
	rc = 0;

done:
	sr_audio_shutdown();                /* A;Flush + telemetry, before the restore */
	sr_io_leave();                      /* restore the BBS terminal, always */
	rc_core_close(&core);
	return rc;
}
