@TRUNCATE@N‹HRÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
N‹HR³4         WSynchronet Reneclone Main System @MenuNoun@ @POS:68@0R³
N‹HRÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ4Y@HOT@
0R  4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
0  4³ [YMC]essage @MenuNoun@ @POS:24@[YFC]ile @MenuNoun@ @POS:43@[YOC]nline Doors @POS:61@[YEC]mail @MenuNoun@ @POS:78@³
0  4³ [YSC]ystem Bulletins [YUC]ser Listing     [YYC]our Info       [YAC]uto-message   ³
0  4³ [YBC]BS List         [YLC]ist of Callers  [Y!C]Offline @MailNoun@ @POS:61@[YNC]ote to SysOp @POS:78@³
N  H4C³ Y                 C   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄY  C  Y               C  ³
N  H4C³ [YVC]ote             [YWC]ho's online     [YCC]hat @MenuNoun@ @POS:61@[Y/LC]ist Nodes @POS:78@³
0  4³ [Y$C]Time Bank       [Y/AC]vatar Chooser  [YIC]nfo on System  [YXC]pert Toggle   ³
0  4³ [YPC]ersonal InfoY   C [YGC]oodbye & Logoff [Y/GC]oodbye Fast!Y                  C ³
0  4ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
N@SYSONLY@
ƒHC[Y@~*@C] Sysop @MenuNoun@
Z