N‹HRÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
N‹HR³4         WSynchronet Reneclone Main System Menu        0R³
N‹HRÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ4Y@HOT@
0R  4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
0  4³ [YMC]essage Menu     [YFC]ile Menu        [YOC]nline Doors    [YEC]mail Menu     ³
0  4³ [YSC]ystem Bulletins [YUC]ser Listing     [YYC]our Info       [YAC]uto-message   ³
0  4³ [YBC]BS List         [YLC]ist of Callers  [Y!C]Offline Mail   [YNC]ote to SysOp  ³
N  H4C³ Y                 C   ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄY  C  Y               C  ³
N  H4C³ [YVC]ote             [YWC]ho's online     [YCC]hat Menu       [Y/LC]ist Nodes    ³
0  4³ [Y$C]Time Bank       [Y/AC]vatar Chooser  [YIC]nfo on System  [YXC]pert Toggle   ³
0  4³ [YPC]ersonal InfoY   C [YGC]oodbye & Logoff [Y/GC]oodbye Fast!Y                  C ³
0  4ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
N@SYSONLY@
ƒHC[Y@~*@C] Sysop Menu
Z