N‹HRÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
N‹HR³4        WSynchronet Reneclone Message System Menu      0R³
N‹HRÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ4Y@HOT@
0R  4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
0  4³ [Y#C]Sub Change      [Y/#C]Group Change   [Y[C]Previous Sub  [Y]C]Next Sub      ³
NHC  4³ [YAC]rea List        [YRC]ead Messages    [YSC]can Messages  [YYC]our Messages  ³
0  4³ [YNC]ew Messages     [YPC]ost Message     [Y/MC]eme Post     [Y/PC]ost Poll     ³
N  H4C³ [YZC]Set Scan Areas Y  CÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄY C  [YVC]ote           ³
0  4³ [Y$C]Time Bank       [YGC]oodbye          [Y/GC]oodbye FastY C [YUC]sers w/Access ³
0  4³ [Y/LC]ist Nodes      [YWC]ho's online     [YCC]hat Menu      [YXC]pert Toggle   ³
0  4³ [Y!C]Offline Mail    [YEC]mail Menu       [YFC]ile Menu      [YQC]uit to Main   ³
0  4ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
Z