N‹HRÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
N‹HR³4         WSynchronet Reneclone File System Menu        0R³
N‹HRÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ4Y@HOT@
0R  4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
0  4³ [Y#C]Dir Change     [Y/#C]Lib Change     [Y[C]Previous Dir Y C[Y]C]Next Dir        ³
0  4³ [YAC]rea List       [YBC]atch Transfer   [YCC]hat Menu     Y C[YDC]ownload File    ³
N  H4C³ [YLC]ist Files      [YSC]earch FilenameY C [YNC]ew Files Y    C [YFC]ind Description ³
0  4³ [YUC]pload File      ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ   [YRC]emove/Edit File ³
0  4³ [YZC]end to Sysop   [YEC]xt File Info    [YVC]iew FilesY C   Y C[YYC]our Stats       ³
0  4³ [YPC]ointer Date    [YTC]emp Transfers   [YGC]oodbye       Y C[Y/GC]oodbye         ³
0  4³ [YWC]ho's online    [Y/LC]ist Nodes     N4K HC[YMC]essage Menu  N4K HC[YQC]uit to MainY   C  ³
0  4ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
N@SYSONLY@
ƒHC[Y@~*@C] Sysop Menu
Z