@TRUNCATE@N‹HRÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
N‹HR³4         WSynchronet Reneclone @FileNoun@ System @MenuNoun@ @POS:68@0R³
N‹HRÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ4Y@HOT@
0R  4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
0  4³ [Y#C]Dir Change     [Y/#C]Lib Change     [Y[C]Previous Dir Y C[Y]C]Next Dir        ³
0  4³ [YAC]rea List       [YBC]atch Transfer   [YCC]hat @MenuNoun@ @POS:58@Y C[YDC]ownload @FileNoun@ @POS:78@³
N  H4C³ [YLC]ist @FilesNoun@ @POS:23@[YSC]earch FilenameY C [YNC]ew @FilesNoun@ Y @POS:58@C [YFC]ind Description ³
0  4³ [YUC]pload @FileNoun@ @POS:24@ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ @POS:59@[YRC]emove/Edit @FileNoun@ ³
0  4³ [YZC]end to Sysop   [YEC]xt @FileNoun@ Info @POS:42@[YVC]iew @FilesNoun@Y C @POS:58@Y C[YYC]our Stats @POS:78@³
0  4³ [YPC]ointer Date    [YTC]emp Transfers   [YGC]oodbye       Y C[Y/GC]oodbye         ³
0  4³ [YWC]ho's online    [Y/LC]ist Nodes     N4K HC[YMC]essage @MenuNoun@ @POS:58@N4K HC[YQC]uit to MainY @POS:76@C @POS:78@³
0  4ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
N@SYSONLY@
ƒHC[Y@~*@C] Sysop @MenuNoun@
Z