DGNLNCE	=	$(EXEODIR)$(DIRSEP)dgnlnce$(EXEFILE)
DGNLNCE_DST=	..$(DIRSEP)dgnlnce.$(machine)$(EXEFILE)
ODOORS_LIB=	$(SRC_ROOT)$(DIRSEP)odoors$(DIRSEP)libs-${OS}$(DIRSEP)$(SHLIBPREFIX)ODoors$(SOFILE)

all: $(OBJODIR) $(EXEODIR) $(DGNLNCE)
