#ifndef _HTMLANSI_H
#define _HTMLANSI_H

const char *htmlansi[256]=
{
	"color: black; background-color: black;",
	"color: #aa0000; background-color: black;",
	"color: #00aa00; background-color: black;",
	"color: #aaaa00; background-color: black;",
	"color: #0000aa; background-color: black;",
	"color: #aa00aa; background-color: black;",
	"color: #00aaaa; background-color: black;",
	"color: #aaaaaa; background-color: black;",
	"color: #444444; background-color: black;",
	"color: #ff4444; background-color: black;",
	"color: #44ff44; background-color: black;",
	"color: #ffff44; background-color: black;",
	"color: #4444ff; background-color: black;",
	"color: #ff44ff; background-color: black;",
	"color: #44ffff; background-color: black;",
	"color: white; background-color: black;",
	"color: black; background-color: #aa0000;",
	"color: #aa0000; background-color: #aa0000;",
	"color: #00aa00; background-color: #aa0000;",
	"color: #aaaa00; background-color: #aa0000;",
	"color: #0000aa; background-color: #aa0000;",
	"color: #aa00aa; background-color: #aa0000;",
	"color: #00aaaa; background-color: #aa0000;",
	"color: #aaaaaa; background-color: #aa0000;",
	"color: #444444; background-color: #aa0000;",
	"color: #ff4444; background-color: #aa0000;",
	"color: #44ff44; background-color: #aa0000;",
	"color: #ffff44; background-color: #aa0000;",
	"color: #4444ff; background-color: #aa0000;",
	"color: #ff44ff; background-color: #aa0000;",
	"color: #44ffff; background-color: #aa0000;",
	"color: white; background-color: #aa0000;",
	"color: black; background-color: #00aa00;",
	"color: #aa0000; background-color: #00aa00;",
	"color: #00aa00; background-color: #00aa00;",
	"color: #aaaa00; background-color: #00aa00;",
	"color: #0000aa; background-color: #00aa00;",
	"color: #aa00aa; background-color: #00aa00;",
	"color: #00aaaa; background-color: #00aa00;",
	"color: #aaaaaa; background-color: #00aa00;",
	"color: #444444; background-color: #00aa00;",
	"color: #ff4444; background-color: #00aa00;",
	"color: #44ff44; background-color: #00aa00;",
	"color: #ffff44; background-color: #00aa00;",
	"color: #4444ff; background-color: #00aa00;",
	"color: #ff44ff; background-color: #00aa00;",
	"color: #44ffff; background-color: #00aa00;",
	"color: white; background-color: #00aa00;",
	"color: black; background-color: #aaaa00;",
	"color: #aa0000; background-color: #aaaa00;",
	"color: #00aa00; background-color: #aaaa00;",
	"color: #aaaa00; background-color: #aaaa00;",
	"color: #0000aa; background-color: #aaaa00;",
	"color: #aa00aa; background-color: #aaaa00;",
	"color: #00aaaa; background-color: #aaaa00;",
	"color: #aaaaaa; background-color: #aaaa00;",
	"color: #444444; background-color: #aaaa00;",
	"color: #ff4444; background-color: #aaaa00;",
	"color: #44ff44; background-color: #aaaa00;",
	"color: #ffff44; background-color: #aaaa00;",
	"color: #4444ff; background-color: #aaaa00;",
	"color: #ff44ff; background-color: #aaaa00;",
	"color: #44ffff; background-color: #aaaa00;",
	"color: white; background-color: #aaaa00;",
	"color: black; background-color: #0000aa;",
	"color: #aa0000; background-color: #0000aa;",
	"color: #00aa00; background-color: #0000aa;",
	"color: #aaaa00; background-color: #0000aa;",
	"color: #0000aa; background-color: #0000aa;",
	"color: #aa00aa; background-color: #0000aa;",
	"color: #00aaaa; background-color: #0000aa;",
	"color: #aaaaaa; background-color: #0000aa;",
	"color: #444444; background-color: #0000aa;",
	"color: #ff4444; background-color: #0000aa;",
	"color: #44ff44; background-color: #0000aa;",
	"color: #ffff44; background-color: #0000aa;",
	"color: #4444ff; background-color: #0000aa;",
	"color: #ff44ff; background-color: #0000aa;",
	"color: #44ffff; background-color: #0000aa;",
	"color: white; background-color: #0000aa;",
	"color: black; background-color: #aa00aa;",
	"color: #aa0000; background-color: #aa00aa;",
	"color: #00aa00; background-color: #aa00aa;",
	"color: #aaaa00; background-color: #aa00aa;",
	"color: #0000aa; background-color: #aa00aa;",
	"color: #aa00aa; background-color: #aa00aa;",
	"color: #00aaaa; background-color: #aa00aa;",
	"color: #aaaaaa; background-color: #aa00aa;",
	"color: #444444; background-color: #aa00aa;",
	"color: #ff4444; background-color: #aa00aa;",
	"color: #44ff44; background-color: #aa00aa;",
	"color: #ffff44; background-color: #aa00aa;",
	"color: #4444ff; background-color: #aa00aa;",
	"color: #ff44ff; background-color: #aa00aa;",
	"color: #44ffff; background-color: #aa00aa;",
	"color: white; background-color: #aa00aa;",
	"color: black; background-color: #44ffff;",
	"color: #aa0000; background-color: #44ffff;",
	"color: #00aa00; background-color: #44ffff;",
	"color: #aaaa00; background-color: #44ffff;",
	"color: #0000aa; background-color: #44ffff;",
	"color: #aa00aa; background-color: #44ffff;",
	"color: #00aaaa; background-color: #44ffff;",
	"color: #aaaaaa; background-color: #44ffff;",
	"color: #444444; background-color: #44ffff;",
	"color: #ff4444; background-color: #44ffff;",
	"color: #44ff44; background-color: #44ffff;",
	"color: #ffff44; background-color: #44ffff;",
	"color: #4444ff; background-color: #44ffff;",
	"color: #ff44ff; background-color: #44ffff;",
	"color: #44ffff; background-color: #44ffff;",
	"color: white; background-color: #44ffff;",
	"color: black; background-color: #aaaaaa;",
	"color: #aa0000; background-color: #aaaaaa;",
	"color: #00aa00; background-color: #aaaaaa;",
	"color: #aaaa00; background-color: #aaaaaa;",
	"color: #0000aa; background-color: #aaaaaa;",
	"color: #aa00aa; background-color: #aaaaaa;",
	"color: #00aaaa; background-color: #aaaaaa;",
	"color: #aaaaaa; background-color: #aaaaaa;",
	"color: #444444; background-color: #aaaaaa;",
	"color: #ff4444; background-color: #aaaaaa;",
	"color: #44ff44; background-color: #aaaaaa;",
	"color: #ffff44; background-color: #aaaaaa;",
	"color: #4444ff; background-color: #aaaaaa;",
	"color: #ff44ff; background-color: #aaaaaa;",
	"color: #44ffff; background-color: #aaaaaa;",
	"color: white; background-color: #aaaaaa;",
	"text-decoration: blink; color: black; background-color: black;",
	"text-decoration: blink; color: #aa0000; background-color: black;",
	"text-decoration: blink; color: #00aa00; background-color: black;",
	"text-decoration: blink; color: #aaaa00; background-color: black;",
	"text-decoration: blink; color: #0000aa; background-color: black;",
	"text-decoration: blink; color: #aa00aa; background-color: black;",
	"text-decoration: blink; color: #00aaaa; background-color: black;",
	"text-decoration: blink; color: #aaaaaa; background-color: black;",
	"text-decoration: blink; color: #444444; background-color: black;",
	"text-decoration: blink; color: #ff4444; background-color: black;",
	"text-decoration: blink; color: #44ff44; background-color: black;",
	"text-decoration: blink; color: #ffff44; background-color: black;",
	"text-decoration: blink; color: #4444ff; background-color: black;",
	"text-decoration: blink; color: #ff44ff; background-color: black;",
	"text-decoration: blink; color: #44ffff; background-color: black;",
	"text-decoration: blink; color: white; background-color: black;",
	"text-decoration: blink; color: black; background-color: #aa0000;",
	"text-decoration: blink; color: #aa0000; background-color: #aa0000;",
	"text-decoration: blink; color: #00aa00; background-color: #aa0000;",
	"text-decoration: blink; color: #aaaa00; background-color: #aa0000;",
	"text-decoration: blink; color: #0000aa; background-color: #aa0000;",
	"text-decoration: blink; color: #aa00aa; background-color: #aa0000;",
	"text-decoration: blink; color: #00aaaa; background-color: #aa0000;",
	"text-decoration: blink; color: #aaaaaa; background-color: #aa0000;",
	"text-decoration: blink; color: #444444; background-color: #aa0000;",
	"text-decoration: blink; color: #ff4444; background-color: #aa0000;",
	"text-decoration: blink; color: #44ff44; background-color: #aa0000;",
	"text-decoration: blink; color: #ffff44; background-color: #aa0000;",
	"text-decoration: blink; color: #4444ff; background-color: #aa0000;",
	"text-decoration: blink; color: #ff44ff; background-color: #aa0000;",
	"text-decoration: blink; color: #44ffff; background-color: #aa0000;",
	"text-decoration: blink; color: white; background-color: #aa0000;",
	"text-decoration: blink; color: black; background-color: #00aa00;",
	"text-decoration: blink; color: #aa0000; background-color: #00aa00;",
	"text-decoration: blink; color: #00aa00; background-color: #00aa00;",
	"text-decoration: blink; color: #aaaa00; background-color: #00aa00;",
	"text-decoration: blink; color: #0000aa; background-color: #00aa00;",
	"text-decoration: blink; color: #aa00aa; background-color: #00aa00;",
	"text-decoration: blink; color: #00aaaa; background-color: #00aa00;",
	"text-decoration: blink; color: #aaaaaa; background-color: #00aa00;",
	"text-decoration: blink; color: #444444; background-color: #00aa00;",
	"text-decoration: blink; color: #ff4444; background-color: #00aa00;",
	"text-decoration: blink; color: #44ff44; background-color: #00aa00;",
	"text-decoration: blink; color: #ffff44; background-color: #00aa00;",
	"text-decoration: blink; color: #4444ff; background-color: #00aa00;",
	"text-decoration: blink; color: #ff44ff; background-color: #00aa00;",
	"text-decoration: blink; color: #44ffff; background-color: #00aa00;",
	"text-decoration: blink; color: white; background-color: #00aa00;",
	"text-decoration: blink; color: black; background-color: #aaaa00;",
	"text-decoration: blink; color: #aa0000; background-color: #aaaa00;",
	"text-decoration: blink; color: #00aa00; background-color: #aaaa00;",
	"text-decoration: blink; color: #aaaa00; background-color: #aaaa00;",
	"text-decoration: blink; color: #0000aa; background-color: #aaaa00;",
	"text-decoration: blink; color: #aa00aa; background-color: #aaaa00;",
	"text-decoration: blink; color: #00aaaa; background-color: #aaaa00;",
	"text-decoration: blink; color: #aaaaaa; background-color: #aaaa00;",
	"text-decoration: blink; color: #444444; background-color: #aaaa00;",
	"text-decoration: blink; color: #ff4444; background-color: #aaaa00;",
	"text-decoration: blink; color: #44ff44; background-color: #aaaa00;",
	"text-decoration: blink; color: #ffff44; background-color: #aaaa00;",
	"text-decoration: blink; color: #4444ff; background-color: #aaaa00;",
	"text-decoration: blink; color: #ff44ff; background-color: #aaaa00;",
	"text-decoration: blink; color: #44ffff; background-color: #aaaa00;",
	"text-decoration: blink; color: white; background-color: #aaaa00;",
	"text-decoration: blink; color: black; background-color: #0000aa;",
	"text-decoration: blink; color: #aa0000; background-color: #0000aa;",
	"text-decoration: blink; color: #00aa00; background-color: #0000aa;",
	"text-decoration: blink; color: #aaaa00; background-color: #0000aa;",
	"text-decoration: blink; color: #0000aa; background-color: #0000aa;",
	"text-decoration: blink; color: #aa00aa; background-color: #0000aa;",
	"text-decoration: blink; color: #00aaaa; background-color: #0000aa;",
	"text-decoration: blink; color: #aaaaaa; background-color: #0000aa;",
	"text-decoration: blink; color: #444444; background-color: #0000aa;",
	"text-decoration: blink; color: #ff4444; background-color: #0000aa;",
	"text-decoration: blink; color: #44ff44; background-color: #0000aa;",
	"text-decoration: blink; color: #ffff44; background-color: #0000aa;",
	"text-decoration: blink; color: #4444ff; background-color: #0000aa;",
	"text-decoration: blink; color: #ff44ff; background-color: #0000aa;",
	"text-decoration: blink; color: #44ffff; background-color: #0000aa;",
	"text-decoration: blink; color: white; background-color: #0000aa;",
	"text-decoration: blink; color: black; background-color: #aa00aa;",
	"text-decoration: blink; color: #aa0000; background-color: #aa00aa;",
	"text-decoration: blink; color: #00aa00; background-color: #aa00aa;",
	"text-decoration: blink; color: #aaaa00; background-color: #aa00aa;",
	"text-decoration: blink; color: #0000aa; background-color: #aa00aa;",
	"text-decoration: blink; color: #aa00aa; background-color: #aa00aa;",
	"text-decoration: blink; color: #00aaaa; background-color: #aa00aa;",
	"text-decoration: blink; color: #aaaaaa; background-color: #aa00aa;",
	"text-decoration: blink; color: #444444; background-color: #aa00aa;",
	"text-decoration: blink; color: #ff4444; background-color: #aa00aa;",
	"text-decoration: blink; color: #44ff44; background-color: #aa00aa;",
	"text-decoration: blink; color: #ffff44; background-color: #aa00aa;",
	"text-decoration: blink; color: #4444ff; background-color: #aa00aa;",
	"text-decoration: blink; color: #ff44ff; background-color: #aa00aa;",
	"text-decoration: blink; color: #44ffff; background-color: #aa00aa;",
	"text-decoration: blink; color: white; background-color: #aa00aa;",
	"text-decoration: blink; color: black; background-color: #44ffff;",
	"text-decoration: blink; color: #aa0000; background-color: #44ffff;",
	"text-decoration: blink; color: #00aa00; background-color: #44ffff;",
	"text-decoration: blink; color: #aaaa00; background-color: #44ffff;",
	"text-decoration: blink; color: #0000aa; background-color: #44ffff;",
	"text-decoration: blink; color: #aa00aa; background-color: #44ffff;",
	"text-decoration: blink; color: #00aaaa; background-color: #44ffff;",
	"text-decoration: blink; color: #aaaaaa; background-color: #44ffff;",
	"text-decoration: blink; color: #444444; background-color: #44ffff;",
	"text-decoration: blink; color: #ff4444; background-color: #44ffff;",
	"text-decoration: blink; color: #44ff44; background-color: #44ffff;",
	"text-decoration: blink; color: #ffff44; background-color: #44ffff;",
	"text-decoration: blink; color: #4444ff; background-color: #44ffff;",
	"text-decoration: blink; color: #ff44ff; background-color: #44ffff;",
	"text-decoration: blink; color: #44ffff; background-color: #44ffff;",
	"text-decoration: blink; color: white; background-color: #44ffff;",
	"text-decoration: blink; color: black; background-color: #aaaaaa;",
	"text-decoration: blink; color: #aa0000; background-color: #aaaaaa;",
	"text-decoration: blink; color: #00aa00; background-color: #aaaaaa;",
	"text-decoration: blink; color: #aaaa00; background-color: #aaaaaa;",
	"text-decoration: blink; color: #0000aa; background-color: #aaaaaa;",
	"text-decoration: blink; color: #aa00aa; background-color: #aaaaaa;",
	"text-decoration: blink; color: #00aaaa; background-color: #aaaaaa;",
	"text-decoration: blink; color: #aaaaaa; background-color: #aaaaaa;",
	"text-decoration: blink; color: #444444; background-color: #aaaaaa;",
	"text-decoration: blink; color: #ff4444; background-color: #aaaaaa;",
	"text-decoration: blink; color: #44ff44; background-color: #aaaaaa;",
	"text-decoration: blink; color: #ffff44; background-color: #aaaaaa;",
	"text-decoration: blink; color: #4444ff; background-color: #aaaaaa;",
	"text-decoration: blink; color: #ff44ff; background-color: #aaaaaa;",
	"text-decoration: blink; color: #44ffff; background-color: #aaaaaa;",
	"text-decoration: blink; color: white; background-color: #aaaaaa;",
};

#define HTML_COLOR_PREFIX		"</span><span style=\""
#define HTML_COLOR_SUFFIX		"\">"

#define MAX_COLOR_STRING 100

#endif /* Don't add anything after this #endif statement */
