#ifndef _HTMLANSI_H
#define _HTMLANSI_H

/* Note: These are defined in ANSI order (i.e. black, red, green, yellow, ...) */
/* and *not* the IBM CGA order (i.e. black, blue, green, cyan, ...) */
/* Maybe this was not original intention? */

/* Note: dark yellow (brown) follows the IBM CGA convention of lowering the */
/* green component to yield a more pleasing brown-tone.
/* See http://en.wikipedia.org/wiki/Color_Graphics_Adapter for more details */

const char *htmlansi[256]=
{
	"color: black; background-color: black;",		/* black */
	"color: #aa0000; background-color: black;",		/* dark red */
	"color: #00aa00; background-color: black;",		/* dark green */
	"color: #aa4400; background-color: black;",		/* brown (dark yellow) */
	"color: #0000aa; background-color: black;",		/* dark blue */
	"color: #aa00aa; background-color: black;",		/* magenta */
	"color: #00aaaa; background-color: black;",		/* cyan */
	"color: #aaaaaa; background-color: black;",		/* white */
	"color: #444444; background-color: black;",		/* bright black (grey) */
	"color: #ff4444; background-color: black;",		/* bright red */
	"color: #44ff44; background-color: black;",		/* bright green */
	"color: #ffff44; background-color: black;",		/* bright yellow */
	"color: #4444ff; background-color: black;",		/* bright blue */
	"color: #ff44ff; background-color: black;",		/* bright magenta */
	"color: #44ffff; background-color: black;",		/* bright cyan */
	"color: white; background-color: black;",		/* bright white */
	/* Background: red */
	"color: black; background-color: #aa0000;",
	"color: #aa0000; background-color: #aa0000;",
	"color: #00aa00; background-color: #aa0000;",
	"color: #aa4400; background-color: #aa0000;",
	"color: #0000aa; background-color: #aa0000;",
	"color: #aa00aa; background-color: #aa0000;",
	"color: #00aaaa; background-color: #aa0000;",
	"color: #aaaaaa; background-color: #aa0000;",
	"color: #444444; background-color: #aa0000;",
	"color: #ff4444; background-color: #aa0000;",
	"color: #44ff44; background-color: #aa0000;",
	"color: #ffff44; background-color: #aa0000;",
	"color: #4444ff; background-color: #aa0000;",
	"color: #ff44ff; background-color: #aa0000;",
	"color: #44ffff; background-color: #aa0000;",
	"color: white; background-color: #aa0000;",
	/* Background: green */
	"color: black; background-color: #00aa00;",
	"color: #aa0000; background-color: #00aa00;",
	"color: #00aa00; background-color: #00aa00;",
	"color: #aa4400; background-color: #00aa00;",
	"color: #0000aa; background-color: #00aa00;",
	"color: #aa00aa; background-color: #00aa00;",
	"color: #00aaaa; background-color: #00aa00;",
	"color: #aaaaaa; background-color: #00aa00;",
	"color: #444444; background-color: #00aa00;",
	"color: #ff4444; background-color: #00aa00;",
	"color: #44ff44; background-color: #00aa00;",
	"color: #ffff44; background-color: #00aa00;",
	"color: #4444ff; background-color: #00aa00;",
	"color: #ff44ff; background-color: #00aa00;",
	"color: #44ffff; background-color: #00aa00;",
	"color: white; background-color: #00aa00;",
	/* Background: brown (dark yellow) */
	"color: black; background-color: #aa4400;",
	"color: #aa0000; background-color: #aa4400;",
	"color: #00aa00; background-color: #aa4400;",
	"color: #aa4400; background-color: #aa4400;",
	"color: #0000aa; background-color: #aa4400;",
	"color: #aa00aa; background-color: #aa4400;",
	"color: #00aaaa; background-color: #aa4400;",
	"color: #aaaaaa; background-color: #aa4400;",
	"color: #444444; background-color: #aa4400;",
	"color: #ff4444; background-color: #aa4400;",
	"color: #44ff44; background-color: #aa4400;",
	"color: #ffff44; background-color: #aa4400;",
	"color: #4444ff; background-color: #aa4400;",
	"color: #ff44ff; background-color: #aa4400;",
	"color: #44ffff; background-color: #aa4400;",
	"color: white; background-color: #aa4400;",
	/* Background: blue */
	"color: black; background-color: #0000aa;",
	"color: #aa0000; background-color: #0000aa;",
	"color: #00aa00; background-color: #0000aa;",
	"color: #aa4400; background-color: #0000aa;",
	"color: #0000aa; background-color: #0000aa;",
	"color: #aa00aa; background-color: #0000aa;",
	"color: #00aaaa; background-color: #0000aa;",
	"color: #aaaaaa; background-color: #0000aa;",
	"color: #444444; background-color: #0000aa;",
	"color: #ff4444; background-color: #0000aa;",
	"color: #44ff44; background-color: #0000aa;",
	"color: #ffff44; background-color: #0000aa;",
	"color: #4444ff; background-color: #0000aa;",
	"color: #ff44ff; background-color: #0000aa;",
	"color: #44ffff; background-color: #0000aa;",
	"color: white; background-color: #0000aa;",
	/* Background: magenta */
	"color: black; background-color: #aa00aa;",
	"color: #aa0000; background-color: #aa00aa;",
	"color: #00aa00; background-color: #aa00aa;",
	"color: #aa4400; background-color: #aa00aa;",
	"color: #0000aa; background-color: #aa00aa;",
	"color: #aa00aa; background-color: #aa00aa;",
	"color: #00aaaa; background-color: #aa00aa;",
	"color: #aaaaaa; background-color: #aa00aa;",
	"color: #444444; background-color: #aa00aa;",
	"color: #ff4444; background-color: #aa00aa;",
	"color: #44ff44; background-color: #aa00aa;",
	"color: #ffff44; background-color: #aa00aa;",
	"color: #4444ff; background-color: #aa00aa;",
	"color: #ff44ff; background-color: #aa00aa;",
	"color: #44ffff; background-color: #aa00aa;",
	"color: white; background-color: #aa00aa;",
	/* Background: cyan */
	"color: black; background-color: #00aaaa;",
	"color: #aa0000; background-color: #00aaaa;",
	"color: #00aa00; background-color: #00aaaa;",
	"color: #aa4400; background-color: #00aaaa;",
	"color: #0000aa; background-color: #00aaaa;",
	"color: #aa00aa; background-color: #00aaaa;",
	"color: #00aaaa; background-color: #00aaaa;",
	"color: #aaaaaa; background-color: #00aaaa;",
	"color: #444444; background-color: #00aaaa;",
	"color: #ff4444; background-color: #00aaaa;",
	"color: #44ff44; background-color: #00aaaa;",
	"color: #ffff44; background-color: #00aaaa;",
	"color: #4444ff; background-color: #00aaaa;",
	"color: #ff44ff; background-color: #00aaaa;",
	"color: #44ffff; background-color: #00aaaa;",
	"color: white; background-color: #00aaaa;",
	/* Background: white */
	"color: black; background-color: #aaaaaa;",
	"color: #aa0000; background-color: #aaaaaa;",
	"color: #00aa00; background-color: #aaaaaa;",
	"color: #aa4400; background-color: #aaaaaa;",
	"color: #0000aa; background-color: #aaaaaa;",
	"color: #aa00aa; background-color: #aaaaaa;",
	"color: #00aaaa; background-color: #aaaaaa;",
	"color: #aaaaaa; background-color: #aaaaaa;",
	"color: #444444; background-color: #aaaaaa;",
	"color: #ff4444; background-color: #aaaaaa;",
	"color: #44ff44; background-color: #aaaaaa;",
	"color: #ffff44; background-color: #aaaaaa;",
	"color: #4444ff; background-color: #aaaaaa;",
	"color: #ff44ff; background-color: #aaaaaa;",
	"color: #44ffff; background-color: #aaaaaa;",
	"color: white; background-color: #aaaaaa;",
	"text-decoration: blink; color: black; background-color: black;",
	"text-decoration: blink; color: #aa0000; background-color: black;",
	"text-decoration: blink; color: #00aa00; background-color: black;",
	"text-decoration: blink; color: #aa4400; background-color: black;",
	"text-decoration: blink; color: #0000aa; background-color: black;",
	"text-decoration: blink; color: #aa00aa; background-color: black;",
	"text-decoration: blink; color: #00aaaa; background-color: black;",
	"text-decoration: blink; color: #aaaaaa; background-color: black;",
	"text-decoration: blink; color: #444444; background-color: black;",
	"text-decoration: blink; color: #ff4444; background-color: black;",
	"text-decoration: blink; color: #44ff44; background-color: black;",
	"text-decoration: blink; color: #ffff44; background-color: black;",
	"text-decoration: blink; color: #4444ff; background-color: black;",
	"text-decoration: blink; color: #ff44ff; background-color: black;",
	"text-decoration: blink; color: #44ffff; background-color: black;",
	"text-decoration: blink; color: white; background-color: black;",
	"text-decoration: blink; color: black; background-color: #aa0000;",
	"text-decoration: blink; color: #aa0000; background-color: #aa0000;",
	"text-decoration: blink; color: #00aa00; background-color: #aa0000;",
	"text-decoration: blink; color: #aa4400; background-color: #aa0000;",
	"text-decoration: blink; color: #0000aa; background-color: #aa0000;",
	"text-decoration: blink; color: #aa00aa; background-color: #aa0000;",
	"text-decoration: blink; color: #00aaaa; background-color: #aa0000;",
	"text-decoration: blink; color: #aaaaaa; background-color: #aa0000;",
	"text-decoration: blink; color: #444444; background-color: #aa0000;",
	"text-decoration: blink; color: #ff4444; background-color: #aa0000;",
	"text-decoration: blink; color: #44ff44; background-color: #aa0000;",
	"text-decoration: blink; color: #ffff44; background-color: #aa0000;",
	"text-decoration: blink; color: #4444ff; background-color: #aa0000;",
	"text-decoration: blink; color: #ff44ff; background-color: #aa0000;",
	"text-decoration: blink; color: #44ffff; background-color: #aa0000;",
	"text-decoration: blink; color: white; background-color: #aa0000;",
	"text-decoration: blink; color: black; background-color: #00aa00;",
	"text-decoration: blink; color: #aa0000; background-color: #00aa00;",
	"text-decoration: blink; color: #00aa00; background-color: #00aa00;",
	"text-decoration: blink; color: #aa4400; background-color: #00aa00;",
	"text-decoration: blink; color: #0000aa; background-color: #00aa00;",
	"text-decoration: blink; color: #aa00aa; background-color: #00aa00;",
	"text-decoration: blink; color: #00aaaa; background-color: #00aa00;",
	"text-decoration: blink; color: #aaaaaa; background-color: #00aa00;",
	"text-decoration: blink; color: #444444; background-color: #00aa00;",
	"text-decoration: blink; color: #ff4444; background-color: #00aa00;",
	"text-decoration: blink; color: #44ff44; background-color: #00aa00;",
	"text-decoration: blink; color: #ffff44; background-color: #00aa00;",
	"text-decoration: blink; color: #4444ff; background-color: #00aa00;",
	"text-decoration: blink; color: #ff44ff; background-color: #00aa00;",
	"text-decoration: blink; color: #44ffff; background-color: #00aa00;",
	"text-decoration: blink; color: white; background-color: #00aa00;",
	"text-decoration: blink; color: black; background-color: #aa4400;",
	"text-decoration: blink; color: #aa0000; background-color: #aa4400;",
	"text-decoration: blink; color: #00aa00; background-color: #aa4400;",
	"text-decoration: blink; color: #aa4400; background-color: #aa4400;",
	"text-decoration: blink; color: #0000aa; background-color: #aa4400;",
	"text-decoration: blink; color: #aa00aa; background-color: #aa4400;",
	"text-decoration: blink; color: #00aaaa; background-color: #aa4400;",
	"text-decoration: blink; color: #aaaaaa; background-color: #aa4400;",
	"text-decoration: blink; color: #444444; background-color: #aa4400;",
	"text-decoration: blink; color: #ff4444; background-color: #aa4400;",
	"text-decoration: blink; color: #44ff44; background-color: #aa4400;",
	"text-decoration: blink; color: #ffff44; background-color: #aa4400;",
	"text-decoration: blink; color: #4444ff; background-color: #aa4400;",
	"text-decoration: blink; color: #ff44ff; background-color: #aa4400;",
	"text-decoration: blink; color: #44ffff; background-color: #aa4400;",
	"text-decoration: blink; color: white; background-color: #aa4400;",
	"text-decoration: blink; color: black; background-color: #0000aa;",
	"text-decoration: blink; color: #aa0000; background-color: #0000aa;",
	"text-decoration: blink; color: #00aa00; background-color: #0000aa;",
	"text-decoration: blink; color: #aa4400; background-color: #0000aa;",
	"text-decoration: blink; color: #0000aa; background-color: #0000aa;",
	"text-decoration: blink; color: #aa00aa; background-color: #0000aa;",
	"text-decoration: blink; color: #00aaaa; background-color: #0000aa;",
	"text-decoration: blink; color: #aaaaaa; background-color: #0000aa;",
	"text-decoration: blink; color: #444444; background-color: #0000aa;",
	"text-decoration: blink; color: #ff4444; background-color: #0000aa;",
	"text-decoration: blink; color: #44ff44; background-color: #0000aa;",
	"text-decoration: blink; color: #ffff44; background-color: #0000aa;",
	"text-decoration: blink; color: #4444ff; background-color: #0000aa;",
	"text-decoration: blink; color: #ff44ff; background-color: #0000aa;",
	"text-decoration: blink; color: #44ffff; background-color: #0000aa;",
	"text-decoration: blink; color: white; background-color: #0000aa;",
	"text-decoration: blink; color: black; background-color: #aa00aa;",
	"text-decoration: blink; color: #aa0000; background-color: #aa00aa;",
	"text-decoration: blink; color: #00aa00; background-color: #aa00aa;",
	"text-decoration: blink; color: #aa4400; background-color: #aa00aa;",
	"text-decoration: blink; color: #0000aa; background-color: #aa00aa;",
	"text-decoration: blink; color: #aa00aa; background-color: #aa00aa;",
	"text-decoration: blink; color: #00aaaa; background-color: #aa00aa;",
	"text-decoration: blink; color: #aaaaaa; background-color: #aa00aa;",
	"text-decoration: blink; color: #444444; background-color: #aa00aa;",
	"text-decoration: blink; color: #ff4444; background-color: #aa00aa;",
	"text-decoration: blink; color: #44ff44; background-color: #aa00aa;",
	"text-decoration: blink; color: #ffff44; background-color: #aa00aa;",
	"text-decoration: blink; color: #4444ff; background-color: #aa00aa;",
	"text-decoration: blink; color: #ff44ff; background-color: #aa00aa;",
	"text-decoration: blink; color: #44ffff; background-color: #aa00aa;",
	"text-decoration: blink; color: white; background-color: #aa00aa;",
	"text-decoration: blink; color: black; background-color: #00aaaa;",
	"text-decoration: blink; color: #aa0000; background-color: #00aaaa;",
	"text-decoration: blink; color: #00aa00; background-color: #00aaaa;",
	"text-decoration: blink; color: #aa4400; background-color: #00aaaa;",
	"text-decoration: blink; color: #0000aa; background-color: #00aaaa;",
	"text-decoration: blink; color: #aa00aa; background-color: #00aaaa;",
	"text-decoration: blink; color: #00aaaa; background-color: #00aaaa;",
	"text-decoration: blink; color: #aaaaaa; background-color: #00aaaa;",
	"text-decoration: blink; color: #444444; background-color: #00aaaa;",
	"text-decoration: blink; color: #ff4444; background-color: #00aaaa;",
	"text-decoration: blink; color: #44ff44; background-color: #00aaaa;",
	"text-decoration: blink; color: #ffff44; background-color: #00aaaa;",
	"text-decoration: blink; color: #4444ff; background-color: #00aaaa;",
	"text-decoration: blink; color: #ff44ff; background-color: #00aaaa;",
	"text-decoration: blink; color: #44ffff; background-color: #00aaaa;",
	"text-decoration: blink; color: white; background-color: #00aaaa;",
	"text-decoration: blink; color: black; background-color: #aaaaaa;",
	"text-decoration: blink; color: #aa0000; background-color: #aaaaaa;",
	"text-decoration: blink; color: #00aa00; background-color: #aaaaaa;",
	"text-decoration: blink; color: #aa4400; background-color: #aaaaaa;",
	"text-decoration: blink; color: #0000aa; background-color: #aaaaaa;",
	"text-decoration: blink; color: #aa00aa; background-color: #aaaaaa;",
	"text-decoration: blink; color: #00aaaa; background-color: #aaaaaa;",
	"text-decoration: blink; color: #aaaaaa; background-color: #aaaaaa;",
	"text-decoration: blink; color: #444444; background-color: #aaaaaa;",
	"text-decoration: blink; color: #ff4444; background-color: #aaaaaa;",
	"text-decoration: blink; color: #44ff44; background-color: #aaaaaa;",
	"text-decoration: blink; color: #ffff44; background-color: #aaaaaa;",
	"text-decoration: blink; color: #4444ff; background-color: #aaaaaa;",
	"text-decoration: blink; color: #ff44ff; background-color: #aaaaaa;",
	"text-decoration: blink; color: #44ffff; background-color: #aaaaaa;",
	"text-decoration: blink; color: white; background-color: #aaaaaa;",
};

#define HTML_COLOR_PREFIX		"</span><span style=\""
#define HTML_COLOR_SUFFIX		"\">"

#define MAX_COLOR_STRING 100

#endif /* Don't add anything after this #endif statement */
