#!/usr/bin/env python3
"""Query Synchronet's JS object-model reference (docs/jsobjs.html).

Reads the live docs/jsobjs.html (generated by `jsexec jsdocs.js`) and prints
a flat, greppable index of objects, methods, and properties -- so you can
find a native API instead of hand-rolling one.

The HTML is table-structured:
  <h2><a name=OBJ_object>OBJ object</a> ...
  <caption>...<a name=OBJ_object_methods>methods</a>     -> Name|Returns|Usage|Ver|Description
  <caption>...<a name=OBJ_object_properties>properties</a>-> Name|Type|Ver|Description
  <tr valign=top><td><b>name</b><td>...<td>...

Usage:
  jsobjs.py                 # list every object + member counts
  jsobjs.py <pattern>       # regex (case-insensitive) over every member line
  jsobjs.py --obj <name>    # every member of objects matching <name>
  jsobjs.py --file PATH     # read a specific jsobjs.html

Examples:
  jsobjs.py strftime              # is there a native strftime? where?
  jsobjs.py 'date|time|iso'       # all time/date helpers
  jsobjs.py --obj system          # the system object's whole surface
  jsobjs.py 'strip_|truncstr'     # native string helpers
"""
import argparse
import html
import re
import sys
from pathlib import Path

OBJ_RE     = re.compile(r'<h2><a name=([\w.]+)_object>', re.I)
CAP_RE     = re.compile(r'<a name=[\w.]+_object_(methods|properties)>', re.I)
ROW_RE     = re.compile(r'<tr valign=top>(.*?)(?=<tr\b|<caption|</table>|<h2|$)', re.I | re.S)
TAG_RE     = re.compile(r'<[^>]+>')
WS_RE      = re.compile(r'\s+')


def find_jsobjs():
    """Locate docs/jsobjs.html by walking up from this script, then the CWD.
    No hardcoded install path -- works wherever the checkout lives."""
    seeds = [Path(__file__).resolve(), Path.cwd().resolve()]
    for seed in seeds:
        for d in [seed] + list(seed.parents):
            cand = d / 'docs' / 'jsobjs.html'
            if cand.is_file():
                return cand
    return None


def clean(cell):
    return WS_RE.sub(' ', html.unescape(TAG_RE.sub('', cell))).strip()


def parse(text):
    """Yield (obj, kind, name, col2, usage, desc) records in document order.
    kind is 'm' (method) or 'p' (property); col2 is the return type for a
    method or the value type for a property."""
    objs = [(m.start(), m.group(1)) for m in OBJ_RE.finditer(text)]
    caps = [(m.start(), m.group(1).lower()) for m in CAP_RE.finditer(text)]

    def last_before(items, pos, default=None):
        val = default
        for start, v in items:
            if start < pos:
                val = v
            else:
                break
        return val

    for rm in ROW_RE.finditer(text):
        pos = rm.start()
        obj = last_before(objs, pos)
        if obj is None:
            continue
        kind = last_before(caps, pos)
        cells = [clean(c) for c in rm.group(1).split('<td>')[1:]]
        if not cells or not cells[0]:
            continue
        name = cells[0]
        if kind == 'methods':
            ret   = cells[1] if len(cells) > 1 else ''
            usage = cells[2] if len(cells) > 2 else ''
            desc  = cells[4] if len(cells) > 4 else (cells[-1] if len(cells) > 3 else '')
            yield (obj, 'm', name, ret, usage, desc)
        else:  # properties (default when no caption seen)
            typ  = cells[1] if len(cells) > 1 else ''
            desc = cells[3] if len(cells) > 3 else (cells[-1] if len(cells) > 2 else '')
            yield (obj, 'p', name, typ, '', desc)


def fmt(rec):
    obj, kind, name, col2, usage, desc = rec
    if kind == 'm':
        sig = usage or (obj + '.' + name + '()')
        head = '[m] ' + sig + (' -> ' + col2 if col2 else '')
    else:
        head = '[p] ' + obj + '.' + name + (' : ' + col2 if col2 else '')
    return head + ('  --  ' + desc if desc else '')


def main():
    ap = argparse.ArgumentParser(
        description='Query Synchronet JS object-model docs (docs/jsobjs.html).')
    ap.add_argument('pattern', nargs='?', help='case-insensitive regex over member lines')
    ap.add_argument('--obj', help='limit to objects whose name matches (substring, case-insensitive)')
    ap.add_argument('--file', help='path to jsobjs.html (default: auto-discover)')
    args = ap.parse_args()

    path = Path(args.file) if args.file else find_jsobjs()
    if not path or not path.is_file():
        sys.exit('jsobjs.html not found. Pass --file, or regenerate with '
                 '`jsexec jsdocs.js` (writes docs/jsobjs.html).')
    text = path.read_text(errors='replace')
    records = list(parse(text))

    hdr = text[:600]
    ver = re.search(r'Generated for (Synchronet[^<]+)', hdr)
    sys.stderr.write('# source: %s%s\n' % (path, ('  (' + ver.group(1).strip() + ')') if ver else ''))

    if args.obj:
        ol = args.obj.lower()
        records = [r for r in records if ol in r[0].lower()]

    if not args.pattern and not args.obj:
        # Summary: object -> member counts.
        from collections import OrderedDict
        counts = OrderedDict()
        for obj, kind, *_ in records:
            m, p = counts.get(obj, (0, 0))
            counts[obj] = (m + (kind == 'm'), p + (kind == 'p'))
        print('%d objects:' % len(counts))
        for obj, (m, p) in counts.items():
            print('  %-28s %dm %dp' % (obj, m, p))
        print('\n(use a <pattern> or --obj <name> to list members)')
        return

    pat = re.compile(args.pattern, re.I) if args.pattern else None
    n = 0
    for rec in records:
        line = fmt(rec)
        if pat is None or pat.search(line):
            print(line)
            n += 1
    sys.stderr.write('# %d match%s\n' % (n, '' if n == 1 else 'es'))


if __name__ == '__main__':
    main()
