# $Id$
# Available Options:

ENCODE_LIB		=	$(ENCODE_SRC)$(DIRSEP)$(LIBODIR)$(DIRSEP)$(LIBPREFIX)encode$(LIBFILE)

ENCODE_CFLAGS	=	-I$(ENCODE_SRC)
ENCODE_LDFLAGS	=	-L$(ENCODE_SRC)$(DIRSEP)$(LIBODIR)
ENCODE_LIBS	=	$(UL_PRE)encode$(UL_SUF)
