/* Single byte instructions */

var CS_IF_TRUE=0;			/* Same as IF_EQUAL */
var CS_IF_FALSE=1;			/* Same as IF_NOT_EQUAL */
var CS_ELSE=2;
var CS_ENDIF=3;
var CS_CMD_HOME=4;
var CS_CMD_POP=5;
var CS_END_CMD=6;
var CS_RETURN=7;
var CS_GETKEY=8;
var CS_GETKEYE=9;
var CS_UNGETKEY=10;
var CS_UNGETSTR=11;
var CS_PRINTKEY=12;
var CS_PRINTSTR=13;
var CS_HANGUP=14;
var CS_SYNC=15;
var CS_ASYNC=16;
var CS_CHKSYSPASS=17;
var CS_LOGKEY=18;
var CS_LOGKEY_COMMA=19;
var CS_LOGSTR=20;
var CS_CLS=21;
var CS_CRLF=22;
var CS_PAUSE=23;
var CS_PAUSE_RESET=24;
var CS_GETLINES=25;
var CS_GETFILESPEC=26;
var CS_FINDUSER=27;
var CS_CLEAR_ABORT=28;
var CS_SELECT_SHELL=29;
var CS_SET_SHELL=30;
var CS_SELECT_EDITOR=31;
var CS_SET_EDITOR=32;			/* 0x20 */
var CS_INKEY=33;
var CS_INCHAR=34;				/* Was RIOSYNC (now deprecated) 02/18/01 */
var CS_GETTIMELEFT=35;
var CS_SAVELINE=36;
var CS_RESTORELINE=37;
var CS_IF_GREATER=38;
var CS_IF_GREATER_OR_EQUAL=39;
var CS_IF_LESS=40;
var CS_IF_LESS_OR_EQUAL=41;
var CS_DEFAULT=42; 			/* 0x2a */
var CS_END_SWITCH=43;
var CS_END_CASE=44;
var CS_PUT_NODE=45;
var CS_GETCHAR=46;
var CS_ONE_MORE_BYTE=47;

/* Two byte instructions */

var CS_CMDKEY=48;
var CS_NODE_ACTION=49;
var CS_GETSTR=50;
var CS_GETNAME=51;
var CS_GETSTRUPR=52;
var CS_SHIFT_STR=53;
var CS_COMPARE_KEY=54;
var CS_SETLOGIC=55;
var CS_SET_USER_LEVEL=56;
var CS_SET_USER_STRING=57;
var CS_GETLINE=58; 			/* 0x3a */
var CS_NODE_STATUS=59;
var CS_CMDCHAR=60;
var CS_COMPARE_CHAR=61;
var CS_MULTINODE_CHAT=62;
var CS_TWO_MORE_BYTES=63;

/* Three byte instructions */

var CS_GOTO=64;
var CS_CALL=65;
var CS_TOGGLE_NODE_MISC=66;
var CS_ADJUST_USER_CREDITS=67;
var CS_TOGGLE_USER_FLAG=68;
var CS_GETNUM=69;
var CS_COMPARE_NODE_MISC=70;
var CS_MSWAIT=71;
var CS_ADJUST_USER_MINUTES=72;
var CS_REVERT_TEXT=73;
var CS_THREE_MORE_BYTES=79;

/* String arg instructions */

var CS_MENU=80;
var CS_PRINT=81;
var CS_PRINT_LOCAL=82;
var CS_PRINT_REMOTE=83;
var CS_PRINTFILE=84;
var CS_PRINTFILE_LOCAL=85;
var CS_PRINTFILE_REMOTE=86;
var CS_YES_NO=87;
var CS_NO_YES=88;
var CS_COMPARE_STR=89;
var CS_COMPARE_WORD=90;		/* 0x5a */
var CS_EXEC=91;
var CS_EXEC_INT=92;
var CS_EXEC_BIN=93;
var CS_EXEC_XTRN=94;
var CS_GETCMD=95;
var CS_LOG=96; 				/* 0x60 */
var CS_MNEMONICS=97;
var CS_SETSTR=98;
var CS_SET_MENU_DIR=99;
var CS_SET_MENU_FILE=100;
var CS_CMDSTR=101;
var CS_CHKFILE=102;
var CS_GET_TEMPLATE=103;
var CS_TRASHCAN=104;
var CS_CREATE_SIF=105;
var CS_READ_SIF=106;			/* 0x6a */
var CS_CMDKEYS=107;
var CS_COMPARE_KEYS=108;
var CS_STR_FUNCTION=111;

/* Var length instructions */

var CS_COMPARE_ARS=112;
var CS_TOGGLE_USER_MISC=113;
var CS_COMPARE_USER_MISC=114;
var CS_REPLACE_TEXT=115;
var CS_TOGGLE_USER_CHAT=116;
var CS_COMPARE_USER_CHAT=117;
var CS_TOGGLE_USER_QWK=118;
var CS_COMPARE_USER_QWK=119;
var CS_SWITCH=120;
var CS_CASE=121;
var CS_USE_INT_VAR=122; 		/* 0x7a */

/* Network (TCP/IP) Functions */

var CS_NET_FUNCTION=125;

/* File I/O Functions */

var CS_FIO_FUNCTION=126;

/* Variable instruction sub-ops */

var CS_VAR_INSTRUCTION=127;

/* Functions */

var CS_MAIL_READ=128;
var CS_MAIL_READ_SENT=129;
var CS_MAIL_READ_ALL=130;
var CS_MAIL_SEND=131;
var CS_MAIL_SEND_BULK=132;
var CS_MAIL_SEND_FILE=133;
var CS_MAIL_SEND_FEEDBACK=134;
var CS_MAIL_SEND_NETMAIL=135;
var CS_MAIL_SEND_NETFILE=136;
var CS_LOGOFF=137;
var CS_LOGOFF_FAST=138;
var CS_AUTO_MESSAGE=139;
var CS_MSG_SET_AREA=140;
var CS_MSG_SELECT_AREA=141;
var CS_MSG_SHOW_GROUPS=142;
var CS_MSG_SHOW_SUBBOARDS=143;
var CS_MSG_GROUP_UP=144;			/* 0x90 */
var CS_MSG_GROUP_DOWN=145;
var CS_MSG_SUBBOARD_UP=146;
var CS_MSG_SUBBOARD_DOWN=147;
var CS_MSG_GET_SUB_NUM=148;
var CS_MSG_GET_GRP_NUM=149;
var CS_MSG_READ=150;
var CS_MSG_POST=151;
var CS_MSG_QWK=152;
var CS_MSG_PTRS_CFG=153;
var CS_MSG_PTRS_REINIT=154;
var CS_MSG_NEW_SCAN_CFG=155;
var CS_MSG_NEW_SCAN=156;
var CS_MSG_NEW_SCAN_ALL=157;
var CS_MSG_CONT_SCAN=158;
var CS_MSG_CONT_SCAN_ALL=159;
var CS_MSG_BROWSE_SCAN=160; 		/* 0xA0 */
var CS_MSG_BROWSE_SCAN_ALL=161;
var CS_MSG_FIND_TEXT=162;
var CS_MSG_FIND_TEXT_ALL=163;
var CS_MSG_YOUR_SCAN_CFG=164;
var CS_MSG_YOUR_SCAN=165;
var CS_MSG_YOUR_SCAN_ALL=166;
var CS_MSG_NEW_SCAN_SUB=167;
var CS_MSG_SET_GROUP=168;
var CS_MSG_UNUSED4=169;
var CS_MSG_UNUSED3=170;
var CS_MSG_UNUSED2=171;
var CS_MSG_UNUSED1=172;
var CS_FILE_SET_AREA=173;
var CS_FILE_SELECT_AREA=174;
var CS_FILE_SHOW_LIBRARIES=175;
var CS_FILE_SHOW_DIRECTORIES=176;	/* 0xB0 */
var CS_FILE_LIBRARY_UP=177;
var CS_FILE_LIBRARY_DOWN=178;
var CS_FILE_DIRECTORY_UP=179;
var CS_FILE_DIRECTORY_DOWN=180;
var CS_FILE_GET_DIR_NUM=181;
var CS_FILE_GET_LIB_NUM=182;
var CS_FILE_LIST=183;
var CS_FILE_LIST_EXTENDED=184;
var CS_FILE_VIEW=185;
var CS_FILE_UPLOAD=186;
var CS_FILE_UPLOAD_USER=187;
var CS_FILE_UPLOAD_SYSOP=188;
var CS_FILE_DOWNLOAD=189;
var CS_FILE_DOWNLOAD_USER=190;
var CS_FILE_DOWNLOAD_BATCH=191;
var CS_FILE_REMOVE=192; 			/* 0xC0 */
var CS_FILE_BATCH_SECTION=193;
var CS_FILE_TEMP_SECTION=194;
var CS_FILE_NEW_SCAN_CFG=195;
var CS_FILE_NEW_SCAN=196;
var CS_FILE_NEW_SCAN_ALL=197;
var CS_FILE_FIND_TEXT=198;
var CS_FILE_FIND_TEXT_ALL=199;
var CS_FILE_FIND_NAME=200;
var CS_FILE_FIND_NAME_ALL=201;
var CS_FILE_PTRS_CFG=202;
var CS_FILE_BATCH_ADD=203;
var CS_FILE_BATCH_CLEAR=204;
var CS_FILE_SET_LIBRARY=205;
var CS_FILE_SEND=206;				/* Like file_get, but no password needed */
var CS_FILE_BATCH_ADD_LIST=207;
var CS_FILE_RECEIVE=208;			/* 0xD0 */
var CS_NODELIST_ALL=209;
var CS_NODELIST_USERS=210;
var CS_CHAT_SECTION=211;
var CS_USER_DEFAULTS=212;
var CS_USER_EDIT=213;
var CS_TEXT_FILE_SECTION=214;
var CS_INFO_SYSTEM=215;
var CS_INFO_SUBBOARD=216;
var CS_INFO_DIRECTORY=217;
var CS_INFO_USER=218;
var CS_INFO_VERSION=219;
var CS_INFO_XFER_POLICY=220;
var CS_XTRN_EXEC=221;
var CS_XTRN_SECTION=222;
var CS_USERLIST_SUB=223;
var CS_USERLIST_DIR=224;			/* 0xE0 */
var CS_USERLIST_ALL=225;
var CS_USERLIST_LOGONS=226;
var CS_PAGE_SYSOP=227;
var CS_PRIVATE_CHAT=228;
var CS_PRIVATE_MESSAGE=229;
var CS_MINUTE_BANK=230;
var CS_GURU_LOG=231;
var CS_ERROR_LOG=232;
var CS_SYSTEM_LOG=233;
var CS_SYSTEM_YLOG=234;
var CS_SYSTEM_STATS=235;
var CS_NODE_STATS=236;
var CS_SHOW_MEM=237;
var CS_CHANGE_USER=238;
var CS_ANSI_CAPTURE=239;
var CS_LIST_TEXT_FILE=240;			/* 0xF0 */
var CS_EDIT_TEXT_FILE=241;
var CS_FILE_SET_ALT_PATH=242;
var CS_FILE_RESORT_DIRECTORY=243;
var CS_FILE_GET=244;
var CS_FILE_PUT=245;
var CS_FILE_UPLOAD_BULK=246;
var CS_FILE_FIND_OLD=247;
var CS_FILE_FIND_OPEN=248;
var CS_FILE_FIND_OFFLINE=249;
var CS_FILE_FIND_OLD_UPLOADS=250;
var CS_INC_MAIN_CMDS=251;
var CS_INC_FILE_CMDS=252;
var CS_PRINTFILE_STR=253;
var CS_PAGE_GURU=254;				
var CS_SPY=255;						/* 0xFF */
	

/* Variable instructions (sub-op-code) */
/* Preceeded by CS_VAR_INSTRUCTION */
var SHOW_VARS=0;						/* Show all variables */
var PRINT_VAR=1;						/* Print a single variable */
var VAR_PRINTF=2; 					/* Print a formated line of text */
var VAR_PRINTF_LOCAL=3;				/* Print a formated line of text to local display */
var VAR_RESERVED_3=4;
var VAR_RESERVED_2=5;
var VAR_RESERVED_1=6;
var DEFINE_STR_VAR=7; 				/* Define Local Variable */
var DEFINE_INT_VAR=8;
var VAR_RESERVED_A4=9;
var VAR_RESERVED_A3=10;
var VAR_RESERVED_A2=11;
var VAR_RESERVED_A1=12;
var DEFINE_GLOBAL_STR_VAR=13;			/* Define Global Variable */
var DEFINE_GLOBAL_INT_VAR=14;
var VAR_RESERVED_B4=15;
var VAR_RESERVED_B3=16;	/* 0x10 */
var VAR_RESERVED_B2=17;
var VAR_RESERVED_B1=18;
var SET_STR_VAR=19;					/* Set string variable */
var SET_INT_VAR=20;					/* Set integer variable */
var VAR_RESERVED_C4=21;
var VAR_RESERVED_C3=22;
var VAR_RESERVED_C2=23;
var VAR_RESERVED_C1=24;
var COMPARE_STR_VAR=25;				/* Compare string variable (static) */
var COMPARE_INT_VAR=26;				/* Compare integer variable (static) */
var STRNCMP_VAR=27;					/* Compare n chars of str var (static) */
var STRSTR_VAR=28; 					/* Sub-string compare of str var (static) */
var VAR_RESERVED_D2=29;
var VAR_RESERVED_D1=30;
var COMPARE_VARS=31;					/* Compare two variables */
var STRNCMP_VARS=32;		/* 0x20 	// Compare n chars of str vars (dynamic) */
var STRSTR_VARS=33;					/* Sub-string compare between two str vars */
var VAR_RESERVED_E2=34;
var VAR_RESERVED_E1=35;
var COPY_VAR=36;						/* Copy from one variable to another */
var VAR_RESERVED_F4=37;
var VAR_RESERVED_F3=38;
var VAR_RESERVED_F2=39;
var VAR_RESERVED_F1=40;
var SWAP_VARS=41;						/* Swap two variables */
var VAR_RESERVED_G4=42;
var VAR_RESERVED_G3=43;
var VAR_RESERVED_G2=44;
var VAR_RESERVED_G1=45;
var CAT_STR_VAR=46;					/* Concatenate string variable (static) */
var CAT_STR_VARS=47;                   /* Concatenate strint variable (dynamic) */
var FORMAT_STR_VAR=48; 	/* 0x30 	// Format string variable */
var TIME_STR=49;						/* Write formated date/time to string */
var DATE_STR=50;						/* Write MM/DD/YY to string */
var FORMAT_TIME_STR=51;				/* Create custom date/time string */
var SECOND_STR=52; 					/* Create a string in format hh:mm:ss */
var STRUPR_VAR=53; 					/* Convert string to upper case */
var STRLWR_VAR=54; 					/* Convert string to lower case */
var ADD_INT_VAR=55;					/* Add to int variable (static) */
var ADD_INT_VARS=56;					/* Add to int variable (dynamic) */
var VAR_RESERVED_I4=57;
var VAR_RESERVED_I3=58;
var VAR_RESERVED_I2=59;
var VAR_RESERVED_I1=60;
var SUB_INT_VAR=61;					/* Subtract from int variable (static) */
var SUB_INT_VARS=62;					/* Subtract from int variable (dynamic) */
var VAR_RESERVED_J4=63;
var VAR_RESERVED_J3=64;	/* 0x40 */
var VAR_RESERVED_J2=65;
var VAR_RESERVED_J1=66;
var MUL_INT_VAR=67;					/* Multiply int variable (static) */
var MUL_INT_VARS=68;					/* Multiply int variable (dynamic) */
var VAR_RESERVED_K4=69;
var VAR_RESERVED_K3=70;
var VAR_RESERVED_K2=71;
var VAR_RESERVED_K1=72;
var DIV_INT_VAR=73;					/* Divide int variable (static) */
var DIV_INT_VARS=74;					/* Divide int variable (dynamic) */
var MOD_INT_VAR=75;
var MOD_INT_VARS=76;
var VAR_RESERVED_L2=77;
var VAR_RESERVED_L1=78;
var AND_INT_VAR=79;					/* Bit-wise AND int variable (static) */
var AND_INT_VARS=80;		/* 0x50 	// Bit-wise AND int variable (dynamic) */
var COMPARE_ANY_BITS=81;
var COMPARE_ALL_BITS=82;
var VAR_RESERVED_M2=83;
var VAR_RESERVED_M1=84;
var OR_INT_VAR=85; 					/* Bit-wise OR int variable (static) */
var OR_INT_VARS=86;					/* Bit-wise OR int variable (dynamic) */
var VAR_RESERVED_N4=87;
var VAR_RESERVED_N3=88;
var VAR_RESERVED_N2=89;
var VAR_RESERVED_N1=90;
var NOT_INT_VAR=91;					/* Bit-wise NOT int variable (static) */
var NOT_INT_VARS=92;					/* Bit-wise NOT int variable (dynamic) */
var VAR_RESERVED_O4=93;
var VAR_RESERVED_O3=94;
var VAR_RESERVED_O2=95;
var VAR_RESERVED_O1=96;	/* 0x60 */
var XOR_INT_VAR=97;					/* XOR int variable (static) */
var XOR_INT_VARS=98;					/* XOR int variable (dynamic) */
var VAR_RESERVED_P4=99;
var VAR_RESERVED_P3=100;
var VAR_RESERVED_P2=101;
var VAR_RESERVED_P1=102;
var RANDOM_INT_VAR=103; 				/* Set integer to random number */
var TIME_INT_VAR=104;					/* Set integer to current time/date */
var DATE_STR_TO_INT=105;				/* Convert a date string to integer */
var STRLEN_INT_VAR=106; 				/* Set integer to length of str */
var CRC16_TO_INT=107;					/* Get CRC-16 of str var */
var CRC32_TO_INT=108;					/* Get CRC-32 of str var */
var FLENGTH_TO_INT=109; 				/* Put length of str var file into int */
var CHARVAL_TO_INT=110; 				/* Put character val of str var into int */
var GETNUM_VAR=111; 					/* Get number */
var GETSTR_VAR=112; 		/* 0x70 	// Get string */
var GETNAME_VAR=113;					/* Get string (upper/lower) */
var GETSTRUPR_VAR=114;					/* Get string (upper) */
var GETLINE_VAR=115;					/* Get string (input bar/line) */
var SHIFT_STR_VAR=116;					/* Shift str in variable */
var GETSTR_MODE=117;					/* Get string with various modes */
var TRUNCSP_STR_VAR=118;				/* Truncate space off end of str var */
var CHKFILE_VAR=119;
var PRINTFILE_VAR_MODE=120; 			/* Printfile str var with mode */
var PRINTTAIL_VAR_MODE=121; 			/* Print tail-end of str var with mode */
var CHKSUM_TO_INT=122;					/* Get CHKSUM of str var */
var STRIP_CTRL_STR_VAR=123; 			/* Strip ctrl chars from str var */
var SEND_FILE_VIA=124;					/* Send file (static) via protocol */
var SEND_FILE_VIA_VAR=125;				/* Send file (dynamic) via protocol */
var FTIME_TO_INT=126;					/* Put time of str var file into int */
var RECEIVE_FILE_VIA=127;				/* Receive file (static) via protocol */
var RECEIVE_FILE_VIA_VAR=128; /* 0x80	// Receive file (dynamic) via protocol */
var TELNET_GATE_STR=129;				/* Run telnet gateway to static address with mode */
var TELNET_GATE_VAR=130;				/* Run telnet gateway to variable address with mode */
var COPY_FIRST_CHAR=131;				/* Copy first char of str var to int var */
var COMPARE_FIRST_CHAR=132;				/* Compare first char of str var to static char */
var COPY_CHAR=133;						/* Copy cmdkey to int var or str var */
var SHIFT_TO_FIRST_CHAR=134;			/* Shift str var to first occurance of static char */
var SHIFT_TO_LAST_CHAR=135;				/* Shift str var to last occurance of static char */
var MATCHUSER=136;						/* Set int var to user number of user name (str var) */

/* Preceeded by CS_STR_FUNCTION */
var CS_LOGIN=0;						/* Login/password prompt */
var CS_LOAD_TEXT=1;					/* Load alternative TEXT.DAT */

/* Preceeded by CS_ONE_MORE_BYTE */
var CS_ONLINE=0;						/* Online execution only */
var CS_OFFLINE=1; 					/* Offline execution allowed */
var CS_NEWUSER=2; 					/* New user procedure */
var CS_LOGON=3;						/* Logon procedure */
var CS_LOGOUT=4;						/* Logout procedure */
var CS_EXIT=5;						/* Exit current module immediately */
var CS_LOOP_BEGIN=6;					/* Looping anchor */
var CS_CONTINUE_LOOP=7;				/* "next" loop */
var CS_BREAK_LOOP=8;					/* Stop executing loop */
var CS_END_LOOP=9;					/* End of looping code block */

/* Preceeded by CS_TWO_MORE_BYTES */
var CS_USER_EVENT=0;					/* External user event */

/* Preceeded by CS_NET_FUNCTION */
var CS_SOCKET_OPEN=0;					/* Open a socket */
var CS_SOCKET_CLOSE=1;				/* Close a socket */
var CS_SOCKET_CONNECT=2;				/* Outbound connection */
var CS_SOCKET_ACCEPT=3;				/* Accept an incomming connection */
var CS_SOCKET_NREAD=4;				/* Get number of bytes in input buffer */
var CS_SOCKET_PEEK=5;					/* Peek at input buffer */
var CS_SOCKET_READ=6;					/* Read input buffer */
var CS_SOCKET_WRITE=7;				/* Write to socket */
var CS_SOCKET_CHECK=8;				/* Check connection */
var CS_SOCKET_READLINE=9;				/* Read a cr/lf delimited line from socket */
var CS_SOCKET_UNUSED6=10;
var CS_SOCKET_UNUSED5=11;
var CS_SOCKET_UNUSED4=12;
var CS_SOCKET_UNUSED3=13;
var CS_SOCKET_UNUSED2=14;
var CS_SOCKET_UNUSED1=15;

var CS_FTP_LOGIN=16;					/* socket, username, password */
var CS_FTP_LOGOUT=17;
var CS_FTP_PWD=18;						/* print working dir */
var CS_FTP_CWD=19;						/* change working dir */
var CS_FTP_DIR=20;						/* path */
var CS_FTP_PUT=21;						/* path */
var CS_FTP_GET=22;						/* path, offset */
var CS_FTP_RENAME=23;					
var CS_FTP_DELETE=24;
var CS_FTP_UNUSED7=25;
var CS_FTP_UNUSED6=26;
var CS_FTP_UNUSED5=27;
var CS_FTP_UNUSED4=28;
var CS_FTP_UNUSED3=29;
var CS_FTP_UNUSED2=30;
var CS_FTP_UNUSED1=31;

/* Preceeded by CS_FIO_FUNCTION */
var FIO_OPEN=0;						/* Open file (static filename) */
var FIO_CLOSE=1;						/* Close file */
var FIO_READ=2;						/* Read from file */
var FIO_READ_VAR=3;					/* Read from file, variable # of bytes */
var FIO_WRITE=4;						/* Write to file */
var FIO_WRITE_VAR=5;					/* Write to file, variable # of bytes */
var FIO_GET_LENGTH=6; 				/* Get length */
var FIO_EOF=7;						/* Set logic to TRUE if eof */
var FIO_GET_POS=8;					/* Get current file position */
var FIO_SEEK=9;						/* Seek within file */
var FIO_SEEK_VAR=10;					/* Seek within file, variable offset */
var FIO_LOCK=11;						/* Lock a region */
var FIO_LOCK_VAR=12;					/* Lock a region, variable length */
var FIO_UNLOCK=13; 					/* Unlock a region */
var FIO_UNLOCK_VAR=14; 				/* Unlock a region, variable length */
var FIO_SET_LENGTH=15; 				/* Change size */
var FIO_SET_LENGTH_VAR=16; 			/* Change size, variable length */
var FIO_PRINTF=17; 					/* Write formated string to file */
var FIO_SET_ETX=18;					/* Set end-of-text character */
var FIO_GET_TIME=19;					/* Gets the current date/time of file */
var FIO_SET_TIME=20;					/* Sets the current date/time of file */
var FIO_OPEN_VAR=21;					/* Open a file (dynamic filename) */
var FIO_READ_LINE=22;					/* Read a single line from file */
var FIO_FLUSH=23;						/* Flush buffered output to disk */
var FIO_UNUSED8=24;
var FIO_UNUSED7=25;
var FIO_UNUSED6=26;
var FIO_UNUSED5=27;
var FIO_UNUSED4=28;
var FIO_UNUSED3=29;
var FIO_UNUSED2=30;
var FIO_UNUSED1=31;
var REMOVE_FILE=32;					/* Remove a file */
var RENAME_FILE=33;					/* Rename a file */
var COPY_FILE=34;						/* Copy a file to another file */
var MOVE_FILE=35;						/* Move a file to another file */
var GET_FILE_ATTRIB=36;				/* Get file attributes */
var SET_FILE_ATTRIB=37;				/* Set file attributes */
var MAKE_DIR=38;						/* Make directory */
var CHANGE_DIR=39; 					/* Change current directory */
var REMOVE_DIR=40; 					/* Remove directory */
var OPEN_DIR=41;						/* Open a directory */
var READ_DIR=42;						/* Read a directory entry */
var REWIND_DIR=43; 					/* Rewind an open directory */
var CLOSE_DIR=44;						/* Close an open directory */

var CS_ONE_BYTE=CS_IF_TRUE;
var CS_TWO_BYTE=CS_CMDKEY;
var CS_THREE_BYTE=CS_GOTO;
var CS_ASCIIZ=CS_MENU;
var CS_MISC=CS_COMPARE_ARS;
var CS_FUNCTIONS=CS_MAIL_READ;
var CS_ELSEORENDIF=255;
var CS_NEXTCASE=254;

var CS_DIGIT=255;
var CS_EDIGIT=254;
var LOGIC_LESS=-1;
var LOGIC_EQUAL=0;
var LOGIC_GREATER=1;
var LOGIC_TRUE=LOGIC_EQUAL;
var LOGIC_FALSE=LOGIC_LESS;
