<!-- $Id: externals.inc,v 1.1 2011/07/02 18:30:39 ree Exp $ -->

<td class="main" valign="top" style='text-align: center;'><br />
	<br />
	<h3 align='center'>External Program Section</h3>

	Click a link below to run the external program from your web browser without having to re-authenticate!**<br />
	(If a link is disabled, that means you do not have access to run that external program)	
	
	@@html@@
	
	<p class='disclaimer' style='text-align: left;'>** Using this feature will cause your username and password to be sent 'in the clear'.  This is probably only an issue if you're connecting to the internet using an unencrypted public wifi hotspot, so if you are, please manually connect to the BBS via SSH instead.</p>