<!-- $Id: footer.inc,v 1.12 2018/03/14 02:17:41 deuce Exp $ -->

<!-- Begin Footer -->

    </td>
    <td width="1%" valign="top" align="right"><img alt="" src="@@image_dir@@/tr_curve_grey.gif" height="6" width="6" /></td>
  </tr>
</table>
    </td>
  </tr>
</table>
<br />
<table class="footer" width="100%" cellspacing="0" border="0" cellpadding="0" align="center">
  <tbody>
    <tr>
      <td>
          <div align="left">
         <!-- <a href="http://www.synchro.net/"><img src="@@image_dir@@/sync_pbgj1_grey_bg.gif" title="Powered by: Synchronet" alt="Powered by: Synchronet" width="175" height="85" border="0" /></a></div> -->
          <font size="-3">
            <a class="footer" href="http://www.synchro.net/">@@server:version@@</a><br />
            <a class="footer" href="http://www.synchro.net/">@@system:version_notice@@</a>
          </font>
        </div>    
        </td>
        <td>
            <div align="right">
            <a href="http://validator.w3.org/check?uri=referer"><img
            src="https://www.w3.org/Icons/valid-xhtml10" title="Valid XHTML 1.0!"
            alt="Valid XHTML 1.0!" height="31" width="88" border="0" /></a><br />
            </div>
        </td>
        </tr>
    </tbody>
    </table>
</td>
</tr>
</table>    
<br />
</body>
</html>
