<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <!-- $Id$ -->
<head>
<title>%%title%%</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

@@JS:if(http_request.virtual_path=="/nodelist.ssjs")'<meta http-equiv="refresh" content="30" />';@@
<link rel="stylesheet" href="@@Theme_CSS_File@@" type="text/css" />
</head>
<body>

<!--[if gte IE 7]>
<style type="text/css">
#sectionLinks a:link, #sectionLinks a:visited { 
	margin-left: 0px;
	margin-right: 13px;
}
#sectionLinks a:active { 
	margin-left: -39px;
	margin-right: 13px;
}
</style>
<![endif]-->

<!-- Remove comment tages for text System Name below -->
<!-- <h1 id="siteName">@@system:name@@</h1> -->

<!-- Comment out or delete below <span> for no logo display -->



<h1 id="siteName">@@name_logo@@</h1>

   <div id="Greeting"> 
        @@user_greeting@@
   </div>
   
   <table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>
