<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <!-- $Id$ -->
<head>
<title>%%title%%</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
@@JS:if(http_request.virtual_path=="/nodelist.ssjs")'<meta http-equiv="refresh" content="30" />';@@
<link rel="stylesheet" href="@@Theme_CSS_File@@" type="text/css" />
</head>
<body>

<!-- Remove comment tages for text System Name below -->
<!-- <h1 id="siteName">@@system:name@@</h1> -->

<!-- Comment out or delete below <span> for no logo display -->

@@name_logo@@

   <div id="Greeting"> 
        @@user_greeting@@
   </div>
   
   <table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td>
