<!-- $Id: infomenu.inc,v 1.9 2006/01/31 23:13:43 runemaster Exp $ -->

<!-- Main Content -->  

<td class="main" valign="top"><br />
<table class="info" cellspacing="2" cellpadding="2">
    <tbody>
        <tr>
        <td class="info">
            From here you can <a class="tlink2" href="userstats.ssjs">View your stats</a>, <a class="tlink2" href="editprofile.ssjs">Edit your profile</a>, or view the <a class="tlink2" href="sysinfo.ssjs">System information</a>.
        </td>
        </tr>
    </tbody>
</table>

<!-- end Main Content -->
