<!-- $Id$ -->

<!-- Main Content -->  

<td class="main" valign="top"><br />
<table class="info" cellspacing="2" cellpadding="2">
    <tbody>
        <tr>
        <td class="info">
            From here you can <a class="tlink2" href="userstats.ssjs">View your information</a> or view the 
            <a class="tlink2" href="sysinfo.ssjs">System information</a>.
        </td>
        </tr>
    </tbody>
</table>

<!-- end Main Content -->
