<p class="navigation">Home</p>
<table class="main" cellspacing="2" cellpadding="2">
    <tbody>
        <tr>
        <td class="main">
            <h2>Welcome to @@JS:system.name@@!</h2>
            <p>Your sysop, @@JS:system.operator@@, has not yet customized these pages.</p>
            <p>In the meantime ...</p>
            <a href="nodelist.ssjs">See who is currently online</a><br />
            <a href="newuser.ssjs">Sign up as a new user</a><br />
            <a href="members/">Members Area</a><br />
            <a href="members/msgs">Message Groups (Members only)</a><br /><br />
        </td>
        </tr>
    </tbody>
</table>
