<!-- $Id$ -->

<!-- Main Content --> 
</td>

    <td class="main" valign="top"><br />
        <br />
       
       <div align="center"><h3>Your sysop, <i>@@system:operator@@</i>, welcomes you to 
        <b>@@system:name@@</b></h3></div>
                
        <table align="center">
          <tr>
          <td align="center">Today's Statistics<br /><br />
          
            <!--  Stats go here and table is closed by index.ssjs -->
            
<!-- end Main Content -->
