<!-- $Id$ -->

<!-- Main Content --> 
</td>

    <td class="main" valign="top"><br />
		<br />
       
        		
		<div align="center"><h3>Some Stats for @@JS:system.name@@</h3></div>

        <table align="center">
          <tr>
          <td align="center">Today<br /><br />
          
            <!--  Stats go here and table is closed by index.ssjs -->
    		
<!-- end Main Content -->
