<!-- $Id$ -->

<!-- Main Content --> 
</td>

    <td class="main" valign="top"><br />
        <br />
       
       <div align="center"><h3>Your sysop, <i>@@system:operator@@</i>, welcomes you to 
        <b>@@system:name@@</b></h3></div>
                
        <table align="center">
          <tr>
          <td align="center">Today's Statistics<br /><br />
          
    <table class="main_stats">
      <tr>
        <td class="main_stats">Up Time</td><td class="main_stats_bold">@@uptime@@</td>
        <td class="main_stats">Logons</td><td class="main_stats_bold">@@logons_today@@</td>
        <td class="main_stats">Posts</td><td class="main_stats_bold">@@posted_today@@</td>
        <td class="main_stats">Uploads</td><td class="main_stats_bold">@@uploaded_today@@</td>
      </tr>
      <tr>
        <td class="main_stats">Time On</td><td class="main_stats_bold">@@timeon_today@@ minutes</td>
        <td class="main_stats">New Users</td><td class="main_stats_bold">@@new_users_today@@</td>
        <td class="main_stats">Emails</td><td class="main_stats_bold">@@email_sent_today@@</td>
        <td class="main_stats">Downloads</td><td class="main_stats_bold">@@downloaded_today@@</td>
      </tr>
    </table>
    <br />
    </td>
    </tr>
    <tr>
    <td align="center">System Totals<br /><br />
    <table class="main_stats">
      <tr>
        <td class="main_stats">Time On</td><td class="main_stats_bold">@@total_timeon@@ minutes</td>
        <td class="main_stats">Logons</td><td class="main_stats_bold">@@total_logons@@</td>
        <td class="main_stats">Messages</td><td class="main_stats_bold">@@total_messages@@</td>
      </tr>
      <tr>
        <td class="main_stats">Users</td><td class="main_stats_bold">@@total_users@@</td>
        <td class="main_stats">Emails</td><td class="main_stats_bold">@@total_email@@</td>
        <td class="main_stats">Files</td><td class="main_stats_bold">@@total_files@@</td>
      </tr>
    </table>
    <br />
    </td>
    </tr>
    <tr>
    <td align="center">Additional Services<br /><br />@@additional_services@@</td>
    </tr>
    </table>
    <br /><br />

<center>
    <table style="font-size: 8pt; font-weight: normal;" border="0" cellpadding="4" width="368" >
        <tr>
            <td align="center"><a href="http://www.fidonet.us/fidoring" target="_top">
            <img src="http://www.fidonet.us/smdogwhiteright.gif" border="0" height="116" width="88" /></a> <br>
            This <a href="http://www.fidonet.us/fidoring" target="_top">FidoRing-FidoNet Web Ring</a> site owned by 
            <a href="mailto:rpa4email@gmail.com" target="_top">Robert Couture</a>.
            <br>
            <a href="http://www.fidonet.us/cgi-bin/fidoring/list.cgi?num=10&order=prev&link=2">Previous 10</a> | 
            <a href="http://www.fidonet.us/cgi-bin/fidoring/jump.cgi?action=previous&num=1&link=2" target="_top">Skip prev</a> | 
            <a href="http://www.fidonet.us/cgi-bin/fidoring/jump.cgi?action=previous&num=0&link=2" target="_top">Previous</a> | 
            <a href="http://www.fidonet.us/cgi-bin/fidoring/jump.cgi?action=next&num=0&link=2" target="_top">Next</a> | 
            <a href="http://www.fidonet.us/cgi-bin/fidoring/jump.cgi?action=next&num=1&link=2" target="_top">Skip next</a> | 
            <a href="http://www.fidonet.us/cgi-bin/fidoring/list.cgi?num=10&order=next&link=2">Next 10</a><br>
            <a href="http://www.fidonet.us/cgi-bin/fidoring/jump.cgi?action=random" target="_top">Random Site</a> | 
            <a href="http://www.fidonet.us/fidoring/sitelist.html" target="_top">List Sites</a> | 
            <a href="http://www.fidonet.us/fidoring" target="_top">Join FidoRing Web Ring</a>
            </td>
        </tr>
    </table>
</center>
<br />
<!-- end Main Content -->

