<!-- $Id: picktheme.inc,v 1.6 2006/01/31 23:13:43 runemaster Exp $ -->

<!-- Main Content -->  
    
    <td class="main" valign="top"><br />

<table class="theme" cellspacing="2" cellpadding="2">
    <tbody>
        <tr>
        <td class="theme">
            Current theme set to: %%theme:desc%%<br /><br />
            <a href="/">Back</a><br /><br />
        </td>
        </tr>
    </tbody>
</table>

<!-- end Main Navigation -->


