<!-- $Id: themes.inc,v 1.8 2006/01/31 23:13:43 runemaster Exp $ -->

<!-- Main Content -->  
    
    <td class="main" valign="top"><br />


<table class="theme" cellspacing="2" cellpadding="2">
    <tbody>
        <tr>
        <td class="theme">
            <form action="picktheme.ssjs" method="post">
                <br />
                @@theme_list@@<br /><br />
                <input type="image" src="@@image_dir@@/select_theme.gif" name="Select Theme" value="Select Theme" />
            </form>
        </td>
        </tr>
    </tbody>
</table>


<!-- end Main Content -->