<p class="navigation"><a class="navigation" href="/index.ssjs">Home</a> : Pick Theme
<table class="theme" cellspacing="2" cellpadding="2">
    <tbody>
        <tr>
        <td class="theme">
            <form action="picktheme.ssjs" method="post">
                <br />
                @@theme_list@@<br /><br />
                <input type="submit" name="Select Theme" value="Select Theme" />
            </form>
        </td>
        </tr>
    </tbody>
</table>
