<!-- $Id$ -->

    <!-- Top Navigation -->
    
        <table align="center" width="90%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="ltn"><img src="@@image_dir@@/tnav_left.gif" width="5" height="32" alt="" /></td>
    <td class="tn">
      <<REPEAT topnav>>
	@@topnav:html@@
      <<END REPEAT topnav>>
    </td>
    <td class="rtn"><img src="@@image_dir@@/tnav_right.gif" width="5" height="32" alt="" /></td>
  </tr>
</table>
<br />

    <!-- end Top Navigation --> 
    
