NHY@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYBatch File Transfer Menu N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜÜÜÜÜ
Ûß„ß4 HWUpload/DownloadNBÛH4WFilesNBÛß„ßÛ
Û HYU NCUploadH NCfiles in upload queueW…BÛ
Û HYD NCDownload files in download queueG  BÛ
Û²ÄÄÄÄß4 HWBatch Queue ManagementNBÛßÄÄÄÄÄ²Û
Û HYL NCList files in batch queuesWB‡Û
Û HYR NCRemove files from batch queuesGWƒBÛ
Û HYC NCClear batch queuesWBÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
ÛW HYQ NCQuit to File Transfer menuWB‡Û
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z