NHY@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYBatch @FileNoun@ Transfer @MenuNoun@ N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜÜÜÜÜ
Ûß„ß4 HWUpload/DownloadNBÛH4WFilesNBÛß„ßÛ
Û HYU NC@Upload@H NCfiles in upload queueW @POS:39@BÛ
Û HYD NC@Download@ files in download queueG @POS:39@BÛ
Û²ÄÄÄÄß4 HWBatch Queue ManagementNBÛßÄÄÄÄÄ²Û
Û HYL NC@List@ files in batch queuesWB @POS:39@Û
Û HYR NCRemove files from batch queuesGWƒBÛ
Û HYC NCClear batch queuesWBÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
ÛW HY@QUITCHAR@ NC@Quit@ to @FileNoun@ Transfer menuWB@POS:39@Û
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z