N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYChat Menu N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÙ
0BÛÛÛÛÛÛÛÛÛÛÛÛÛ4 HWJoin a Chat NBÛÛÛÛÛÛÛÛÛÛÛÛÛ
Û HY@~J@ NGJoin/initiate multinode chatW…BÛ
Û HY@~P@ NGJoin/start private node/node chat BÛ
Û HY@~C@ NGChat with @SYSOP-L##############@ BÛ
Û HY@~T@ NGTalk with The Guru (AI)WŠBÛ
Û HY@~F@ NGFingerW G(query) remote user/systemW BÛ
Û HY@~R@ NGInternet Relay ChatW G(IRC)WˆBÛ
Û HY@~I@ NGInterBBS Instant MessagingW‡BÛ
ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ4 HWToggles NBÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ
Û HY@~D@ NGChatHY NGavailabilityW…Gstate:HW Y@PAGER-L3@W NBÛ
Û HY@~A@ NGNode activity alertsW‚Gstate:HW Y@ALERTS-L3@NG BÛ
Û HY@~S@ NGSplit-screen chatW…Gstate: HY@SPLITP-L3@N BÛ
ÛÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÛ
Û HY@~Q@ NGQuit chat menuW“BÛ
4K C HYAnytime: C^UN4Csers online  H^PN4Crivate msgH 
Z