NHC@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYChat Menu N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ÛßW‰Bß4 HWJoin a Chat NBßW‰BßÛ
Û HCJY NCJoin/initiate multinode chatW…BÛ
Û HCPNC Join/start private node/node chatG BÛ
Û HCCY NCChat with Sysop: HY@SYSAVAIL-L####@NG BÛ
Û HCTY NCTalk with The Guru (AI)WŠBÛ
Û HCFY NCFinger (query) remote user/systemW BÛ
Û HCRY NCInternet Relay Chat (IRC)WˆBÛ
Û HCIY NCInterBBS Instant MessagingW‡BÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄß4 HWToggles NBßÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HCD NCChat availabilityW…Cstate: HY@PAGER-L3@W NBÛ
Û HCA NCNode activity alertsW‚Cstate: HY@ALERTS-L3@NG BÛ
ÛHC SY NCSplit-screen chatW…Cstate:G HY@SPLITP-L3@N BÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HCQY NCQuit chat menuW“BÛ
4K C HYAnytime: C^UN4Csers online  H^PN4Crivate msgH 
Z