N@CLEAR@
4CЪДДДДДДДДДДДKї
Cі HYChat Menu N4Kі
CАKДДДДДДДДДДДЩ
0BЫЫЫЫЫЫЫЫЫЫЫЫЫ4 HWJoin a Chat NBЫЫЫЫЫЫЫЫЫЫЫЫЫ
Ы HYJ NGJoin/initiate multinode chat…BЫ
Ы HYP NGJoin/start private node/node chat BЫ
Ы HYC NGChat with the sysopЋBЫ
Ы HYT NGTalk with The Guru (AI)ЉBЫ
Ы HYF NGFinger (Query) remote user/system BЫ
Ы HYR NGInternet Relay ChatЋBЫ
Ы HYI NGInter-BBS Instant Messaging†BЫ
ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ4 HWToggles NBЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ
Ы HYD NGAllow paging off/onЋBЫ
Ы HYA NGActivity alerts off/on‹BЫ
Ы HYS NGSplit screen private chat€BЫ
ЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫЫ
Ы HYQ NGQuit chat menu“BЫ
4K C HYAnytime: C^UN4Csers online  H^PN4Crivate msgH 
