NHC@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYElectronic Mail Menu N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ÛßWŠBßÛH4WSend MailNBÛßWŠBßÛ
Û HCSY NCSend mail to a local userWˆBÛ
Û HCAY NCSend file attachmentWBÛ
Û HCFY NCSend feedback to the sysopW‡BÛ
Û HCNY NCSend NetMail (Fido/QWK/Internet)W  BÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
ÛßWŠBßH4W Read Mail NBßWŠBßH4W 
NBÛW HCRY NCRead mail sent to youWŒH4 
NBÛW HCUY NCRead your un-read mail onlyW†H4 
NBÛW HCKY NCRead/Kill mail you have sentW…H4 
NBÛÛÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÛH4W 
NBÛ HCQY NCQuit the E-Mail MenuWH4 
NBÛÛH4YAnytime: W^UCsers onlineY  W^PCrivate msgW 
Z