N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYElectronic Mail Menu N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
0BÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛH4WSend MailNBÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ
Û HY@~S@ NGSend mail to a local userWˆBÛ
Û HY@~A@ NGSend file attachmentWGWBÛ
Û HY@~F@ NGSend feedback to the sysopW‡BÛ
Û HY@~N@ NGSend NetMail (Fido/QWK/Internet)W  BÛ
ÛH4Y      W        Read Mail            NBÛH4W  
NBÛW HY@~R@ NGRead mail sent to youWŒH4 
NBÛW HY@~U@ NGRead your un-read mail onlyW†H4 
NBÛW HY@~K@ NGRead/Kill mail you have sentW…H4 
NBÛÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄH4W 
NBÛ HY@~Q@ NGQuit the E-Mail MenuWH4 
NBÛÛH4YAnytime: W^UCsers onlineY  W^PCrivate msgW 
Z