@TRUNCATE@NHC@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYElectronic @MailNoun@ @MenuNoun@ N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ÛßWŠBßÛH4WSend MailNBÛßWŠBßÛ
Û HCSY NC@Send@ mail to a local userW @POS:39@BÛ
Û HCAY NC@Send@ file attachmentW @POS:39@BÛ
Û HCFY NC@Send@ feedback to the sysopW @POS:39@BÛ
Û HCNY NC@Send@ NetMail (Fido/QWK/Internet)W @POS:39@BÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
ÛßWŠBßH4W Read Mail NBßWŠBßH4W 
NBÛW HCRY NC@Read@ mail sent to youW @POS:39@H4 
NBÛW HCUY NC@Read@ your un-read mail onlyW @POS:39@H4 
NBÛW HCKY NC@Read@/Kill mail you have sentW @POS:39@H4 
NBÛÛÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÛH4W 
NBÛ HCQY NC@Quit@ the E-Mail @MenuNoun@W @POS:39@H4 
NBÛÛH4YAnytime: W^UCsers onlineY  W^PCrivate msgW 
Z