N@CLEAR@HC@HOT@
N4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³  HYReading Mail Menu    N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ÛßWB³WBßÛ
ÛHC<CR> NCNext msgW„B³C -  Previous msgW  BÛ
Û HC[ ]NC Search ToWƒB³HC{ }Y NCSearch FromW‚BÛ
Û HC< > NCSearch Subj  B³ HC/NB  CSearch TextW‚BÛ
Û  HCLNB  CList all msgsB³C H!NC  Reverse listW  BÛ
Û  HCTNB  CNext ten msgsB³C HNNB  CNext unreadW‚BÛ
Û  HC@MSGREREAD@NB  CRe-read msg  B³W HC@MSGREPLY@NB  CReply to msg  BÛ
Û  HCDNB  CDelete msgW‚B³ HCKNC  Delete allWƒBÛ
Û  HCFNB  CForward msg  B³W HC#NC  GoW Cto msg num BÛ
ÛÜ HCVNB  CView SPAMWƒB³C HQNC  Quit readingB ÜÛ
ÛÛH4YAnytime: W^UCsers online  W^PCrivate msg 
Z