N@CLEAR@HC@HOT@
N4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³  HYReading @MailNoun@ @MenuNoun@ @POS:25@N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ÛßWB³WBßÛ
ÛHC<CR> NC@Next@ msgW @POS:20@B³C - @POS:25@Previous msgW @POS:39@BÛ
Û HC[ ]NC @Search@ ToW @POS:20@B³HC{ }Y NC@Search@ FromW @POS:39@BÛ
Û HC< > NC@Search@ Subj @POS:20@B³ HC/NB @POS:25@C@Search@ TextW @POS:39@BÛ
Û  HCLNB  C@List@ msgs @POS:20@B³C H!NC @POS:25@Reverse listW @POS:39@BÛ
Û  HCTNB  C@Next@ ten msgsB³C HNNB @POS:25@C@Next@ unreadW @POS:39@BÛ
Û  HC@MSGREREAD@NB  CRe-read msg  B³W HC@MSGREPLY@NB  C@Reply@ to msg @POS:39@BÛ
Û  HCDNB  C@Delete@ msgW @POS:20@B³ HCKNC @POS:25@@Delete@ allW @POS:39@BÛ
Û  HCFNB  C@Forward@ msg @POS:20@B³W HC#NC @POS:25@GoW Cto msg num BÛ
Û  HCWNW  CWide toggle  B³W HCQNC  @Quit@ reading @POS:39@BÛ
ÛÜ HCVNB  C@View@ SPAMW @POS:20@B³ @POS:38@ÜÛ
ÛÛH4YAnytime: W^UCsers online  W^PCrivate msg 
Z
