@TRUNCATE@N@CLS@HG@BBS-C39@
WÚÄNÄÄÄÄÄÄÄÄÄ¿
³H B@MessagesNoun@W N³
ÀÄÄÄÄÄÄÄÄÄHÄÙ
 B[CNB]ew @MessageNoun@ scan [C&B]N HBconfig/reset
 [CJB]ump to a @MessageNoun@ @Area@
 [CRB]ead @MessagesNoun@
 [CPB]ost a @MessageNoun@
 [CFB]ind @Text@ in @MessagesNoun@
 [CSB]can for @MessagesNoun@ to you
 [CEB]mail
NHC@Main@ @MenuNoun@N @POS:29@HBGetNK HB[CQB]WK
WÚÄNÄÄÄÄÄÄ¿…HM~~~~~~~~~NƒHBGet [CIB]nfo
N³H BGo ToW N³‘HB@List@ [CUB]sers
NÀÄÄÄÄÄÄHÄÙN’HBLog [COB]ff
W B[CTB]ransfer @FilesNoun@N @POS:27@@SYSONLY@HBSysop [C!B]menuN@SYSONLY@
HB [CGB]eneral @Text@ @FileNoun@ @Area@
 [CCB]hat @Section@
 [CXB]ternal programs
 [CDB]isplay/change your configuration
Z