NHC@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYMessage Scan Configuration N4K³
CÀKÄ0Bßßßßßßßßßßßßßßßßßßßßßßßßßßß4KÙ0BÜÜÜÜÜÜÜÜÜ
Û HCNY NCAreas to scan for new messagesW‚BßÛ
ÛW HCSY NCAreas to scan for your messages‚BÛ
Û HCP NCSet new-scan pointersWBŒÛ
Û HCI NCReinitialize new-scan pointersGBƒÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HCQ NCQuit to Main menuWBWBÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z