NHC@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYMain Section Information Menu N4K³
CÀKÄ0Bßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß4KÙ0BÜÜÜÜÜÜ
ÛW HCY NCYour statisticsWBW‘BßÛ
Û HCIY NCSystem informationWBWBÛ
ÛW HCVY NCSynchronet version informationWBWƒBÛ
Û HCSY NCInformation on current sub-boardBG  BÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HCQ NCQuit to Main menuWBWBÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z