@INCLUDE:%zmenu/head.msg@hc@HOT@n
 bşhş wRead/Post @MessagesNoun@ @POS:29@nbşhş w@MessageNoun@ Area Selection @POS:57@nbşhş wElectronic @MailNoun@
bÚnbÄÄ¿–hÚnbÄÄ¿—hÚnbÄÄ¿
³ hcNnb³ w@New@ message scan @POS:28@b³ hcJnb³ wJump to new msg area @POS:56@b³ hcEnb³ w@Read@/@Send@ E-mail
b³ hcRnb³ w@Read@ message prompt @POS:28@bÀÄÄÙ @POS:35@hc* n@List@ sub-boards @POS:56@bÀÄÄÙ
³ hcLnb³ w@List@/@View@ messages @POS:34@hc/* n@List@ groups @POS:57@bşhş wOther Commands
nb³ hcVnb³ w@View@/Vote-in Polls @POS:30@hc{ } @POS:35@w# n@Select@ sub-board @POS:56@hbÚnbÄÄ¿
³ hcQnb³ wQWK packet transfer„hc[ ] w/# n@Select@ group @POS:56@b³ hcDnb³ wDefault user config
b³ hcPnb³ w@PostVerb@ msg hc/Pnoll hc/Mneme @POS:56@b³ hc&nb³ w@MessageNoun@ scan config
b³ hcAnb³ w@PostVerb@ auto-message @POS:29@bşhş wGo to @POS:56@nb³ hcUnb³ w@UserNoun@ lists
bÀÄÄÙ–hÚnbÄÄ¿—³ hcInb³ wInformation
 bşhş w@MessageNoun@ Search @POS:28@nb³ hcTnb³ w@FileNoun@ Transfer section @POS:56@b³hc/Anb³ w@Change@ your avatar
hbÚnbÄÄ¿–³ hcGnb³ wText file section…b³hc/Lnb³ wNode activity
b³ hcFnb³ w@Find@ text in messages b³ hcCnb³ wChat section @POS:56@b³hc^Knb³ wCtrl-key @MenuNoun@
b³ hcSnb³ w@Scan@ for msgs to you @POS:28@b³ hcXnb³ wExternal programs @POS:56@b³ hcOnb³ wLogoff BBS (or hc/On)
bÀÄÄÙ–ÀÄÄÙ—ÀÄÄÙ @SYSONLY@nhc!n Sysop Menu@SYSONLY@
@HOT:OFF@@INCLUDE:%zmenu/tail.msg@