@INCLUDE:%zmenu/head.msg@hc@HOT@n
bh wRead/Post Messagesnbh wMessage Area Selection   nbh wElectronic Mail
bnbĿhnbĿhnbĿ
 hcNnb wNew message scanb hcJnb wJump to new msg area   b hcEnb wRead/Send E-mail
b hcRnb wRead message prompt   b   hc* nList sub-boards    b
 hcLnb wList/View messages    hc/* nList groupsbh wOther Commands
nb hcVnb wView/Vote-in Polls      hc{ }  w# nSelect sub-board   hbnbĿ
 hcQnb wQWK packet transferhc[ ] w/# nSelect groupb hcDnb wDefault user config
b hcPnb wPost a msg or hc/Pnoll                               b hc&nb wMessage scan config
b hcAnb wPost auto-messagebh wGo tonb hcUnb wUser lists
bhnbĿ hcInb wInformation
 bh wMessage Searchnb hcTnb wFile Transfer section  bhc/Anb wChange your avatar
hbnbĿ hcGnb wText file sectionbhc/Lnb wNode activity
b hcFnb wFind text in messages b hcCnb wChat sectionbhc^Knb wCtrl-key Menu
b hcSnb wScan for msgs to you  b hcXnb wExternal programsb hcOnb wLogoff BBS (or hc/On)
b @SYSONLY@nhc!n Sysop Menu@SYSONLY@
@HOT:OFF@@INCLUDE:%zmenu/tail.msg@