@TRUNCATE@NHC@HOT@
N4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿0
4C³ HYMultinode Chat Menu N4K³0
4CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜK
BÛßHCN¢BßÛK
BÛHC /W NCWhisper to another @UserNoun@W @POS:39@BÛK
BÛHC /L NC@List@ all @Node@ activityW @POS:39@BÛK
BÛHC /* NC@List@ chat channelsW @POS:39@BÛK
BÛHC /# NC@Change@ chat channel number @POS:39@BÛK
BÛ HC/E NC@Toggle@ echo statusWC @POS:39@BÛK
BÛHC /A NC@Toggle@ action commands @POS:39@BÛK
BÛHC /C NC@List@ action commands @POS:39@BÛK
BÛHC /Q NC@Quit@ multinode chat @POS:39@BÛK
BÛÜWC¢BÜÛK
4  HYAnytime: C^UN4Csers online  H^PN4Crivate msg 0K
Z
