NHC@HOT@
N4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿0
4C³ HYMultinode Chat Menu N4K³0
4CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜK
BÛßHCN¢BßÛK
BÛHC /W NCWhisper to another userW‰BÛK
BÛHC /L NCList all node activityWŠBÛK
BÛHC /* NCList chat channelsWBÛK
BÛHC /# NCChange chat channel number†BÛK
BÛ HC/E NCToggle echo statusWCBÛK
BÛHC /A NCToggle action commandsŠBÛK
BÛHC /C NCList action commandsŒBÛK
BÛHC /Q NCQuit multinode chatBÛK
BÛÜWC¢BÜÛK
4  HYAnytime: C^UN4Csers online  H^PN4Crivate msg 0K
Z
