NHC@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³  HYQWK Offline Reader Menu  N4K³
CÀKÄ0Bßßßßßßßßßßßßßßßßßßßßßßßßßß4KÙ0BÜÜÜÜÜÜÜ
Û HCCY NCChange Packet ConfigurationW‚BßÛ
Û HCSY NCSelectG CMessage Areas to ScanW‚BÛ
Û HCPY NCModify New-message PointersWƒBÛ
Û HCUY NCUpload REP reply packetW‡BÛ
Û HCDY NCDownload QWK message packetWƒBÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HCQY NCQuit back to Main menuWˆBÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z