N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³  HYQWK Offline Reader Menu  N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜ
ÛßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßÛ
Û HY@~C@ NGChange Packet ConfigurationWƒBÛ
Û HY@~S@ NGSelect Message Areas to ScanW‚BÛ
Û HY@~P@ NGModify New-message PointersWƒBÛ
Û HY@~U@ NGUpload REP reply packetW‡BÛ
Û HY@~D@ NGDownload QWK message packetWƒBÛ
ÛÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÛ
Û HY@~Q@ NGQuit back to Main menuWˆBÛ
ÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛ
Z