NHC@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³  HYQWK Offline Reader Menu  N4K³
CÀKÄ0Bßßßßßßßßßßßßßßßßßßßßßßßßßß4KÙ0BÜÜÜÜÜÜÜ
Û HC@CONFIGURECHAR@Y NCChange Packet ConfigurationW‚BßÛ
Û HC@SELECTCHAR@Y NC@Select|L6@G CMessage Areas to ScanW‚BÛ
Û HC@POINTERSCHAR@Y NCModify New-message @Pointers|L8@WƒBÛ
Û HC@UPLOADCHAR@Y NC@Upload|L6@ REP reply packetW‡BÛ
Û HC@DOWNLOADCHAR@Y NC@Download|L8@ QWK message packetWƒBÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HC@QUITCHAR@Y NC@Quit|L4@ back to Main menuWˆBÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z