@TRUNCATE@N@CLEAR@HC@HOT@
N4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³  HYReading Sent @MailNoun@ @MenuNoun@ @POS:30@N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜÜÜ
ÛßWB³WBßÛ
ÛHC<CR> NC@Next@ msgW @POS:20@B³C - @POS:25@Previous msgW @POS:39@BÛ
Û HC[ ]NC @Search@ ToW @POS:20@B³HC{ }Y NC@Search@ FromW @POS:39@BÛ
Û HC< > NC@Search@ Subj @POS:20@B³ HC/NB @POS:25@C@Search@ TextW @POS:39@BÛ
Û  HCLNB  C@List@ msgs @POS:20@B³C H!NC @POS:25@Reverse listW @POS:39@BÛ
Û  HCTNB  C@Next@ ten msgsB³C HNNB @POS:25@C@Next@ unreadW @POS:39@BÛ
Û  HC@MSGREREAD@NB  CRe-read msg  B³W HCENC  @Edit@ msg @POS:35@W @POS:39@BÛ
Û  HCDNB  C@Delete@ msgW @POS:20@B³ HC#NC @POS:25@GoW Cto msg num BÛ
Û  HCFNB  C@Forward@ msg @POS:20@WB³ HCQNC @POS:25@@Quit@ reading @POS:39@BÛ
ÛÜ HCWNB  CWide toggle  B³                 ÜÛ
ÛÛH4YAnytime: W^UCsers online  W^PCrivate msg 
Z
