NG@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³  HYSub-board Operator Menu  N4K³
CÀKÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ0BÜÜÜÜÜÜÜ
ÛW¡BÛ
Û HYA NGAdd Comment to Last MessageƒBÛ
Û HYC NGChange Message AttributesW…BÛ
Û HYD NGDelete Messages (in a range)‚BÛ
Û HYH NGView Message HeaderW‹BÛ
Û HYM NGMove Message to Another SubƒBÛ
Û HYS NGSave Message to Text FileW…BÛ
Û HYU NGEdit Author's User AccountW„BÛ
Û HYP NGPurge Author's User AccountƒBÛ
Û HYV NGValidate Previous MessageW…BÛ
ÛÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÛ
Û HYQ NGQuit back to Reading promptƒBÛ
ÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛ
Z