@INCLUDE:%zmenu/head.msg@hy@HOT@n
4b0ЫЫЫЫЫ4 hwList/Flag Files nbЫЫЫЫЫЫЫ4 hwFile Area Selection nbЫЫЫЫЫЫЫЫЫ4 hwFile Search  nbЫЫЫЫЫЫ
ЫЫЫЫ
Ы  hyL ncList files in dir    bЫ hyJ ncJump to new file area bЫ  hyF ncFind text in descrip bЫ
Ы  hyN ncNew file scan        bЫДДДДДДДДДДДДДДДДДДДДДДДДДЫ  hyS ncSearch for filename  bЫ
Ы  hyE ncExtended file info   bЫ…hy* ncList directories bЫЫ
ЫЫ„hy/* ncList libraries   bЫЫЫЫЫЫ4 hwOther Commands nbЫЫЫЫЫ
ЫЫЫЫЫ4 hwUpload/Download nbЫЫЫЫЫ hy{ }  c# ncSelect directory bЫ
 Ы hy[ ] c/# ncSelect library   bЫ  hy& ncFile scan config
   hyD ncDownload file‡bЫЫ  hyR ncRemove/edit file
   hyU ncUpload file‰bЫЫЫЫЫЫЫЫЫЫ4 hwGo to nbЫЫЫЫЫЫЫЫЫЫ  hyI ncInformation
  hy/D ncDownload from user   bЫЫ  hyV ncView file contents
  hy/U ncUpload to user†bЫ hyQ ncMain/Message section  bЫ hy/L ncNode activity
   hyZ ncUpload to sysop…bЫ hyC ncChat section‰bЫ hy^K ncCtrl-key menu
   hyB ncBatch/Bi-dir xfers   bЫ hyT ncTemp dir/Archive cmds bЫ  hyO ncLogoff BBS (or hy/Onc)
b ЫЫ  @SYSONLY@hy!nc Sysop Menu@SYSONLY@
@HOT:OFF@@INCLUDE:%zmenu/tail.msg@