@TRUNCATE@N@CLS@HG@BBS-C39@
WÚÄNÄÄÄÄÄÄÄÄÄ¿
³H BListingsW N³
ÀÄÄÄÄÄÄÄÄÄHÄÙ
 B[CNB]ew @FilesNoun@ scan [C&B]N HBconfig/reset
 [CLB]ist @FilesNoun@ in current directory
C B[CJB]ump to a @FileNoun@N HBarea
 [CEB]xtended @FileNoun@ information
 [CFB]ind text in descriptions
 [CSB]earch for filenames
 [CVB]iew @FileNoun@ contents
N HB[CRB]emove @FileNoun@
NHC@FileNoun@ @MenuNoun@
WÚÄNÄÄÄÄÄÄÄÄÄ¿‚HM~~~~~~~~~NƒHBGet [CIB]nfo
N³H BTransferW N³HBLog [COB]ff
NÀÄÄÄÄÄÄÄÄÄHÄÙNHBorN HB[CQB]uit
W B[CDB]ownload @FileNoun@(s)N @POS:27@@SYSONLY@HBSysop [C!B]menuN@SYSONLY@
 HB[CUB]pload @FileNoun@(s)C @POS:20@B[CZB]N HBto sysop
 [CBB]atch transfer @MenuNoun@
 [CTB]emporary directory
Z