@TRUNCATE@N@CLS@HG@BBS-C39@
WÚÄNÄÄÄÄÄÄÄÄÄ¿
³H BListingsW N³
ÀÄÄÄÄÄÄÄÄÄHÄÙ
 B[CNB]ew @FilesNoun@ scan [C&B]N HBconfig/reset
 [CLB]ist @FilesNoun@ in current directory
C B[CJB]ump to a @FileNoun@N HB@Area@
 [CEB]xtended @FileNoun@ information
 [CFB]ind @Text@ in descriptions
 [CSB]earch for filenames
 [CVB]iew @FileNoun@ contents
N HB[CRB]emove @FileNoun@
NHC@FileNoun@ @MenuNoun@
WÚÄNÄÄÄÄÄÄÄÄÄ¿‚HM~~~~~~~~~NƒHBGet [CIB]nfo
N³H B@Transfer@W N³ @POS:29@HBLog [COB]ff
NÀÄÄÄÄÄÄÄÄÄHÄÙNHBorN HB[CQB]uit
W B[CDB]ownload @FileNoun@(s)N @POS:27@@SYSONLY@HBSysop [C!B]menuN@SYSONLY@
 HB[CUB]pload @FileNoun@(s)C @POS:20@B[CZB]N HBto @Sysop@
 [CBB]atch @Transfer@ @MenuNoun@
 [CTB]emporary directory
Z