N@CLS@HG@BBS-C39@
WÚÄNÄÄÄÄÄÄÄÄÄ¿
³H BListingsW N³
ÀÄÄÄÄÄÄÄÄÄHÄÙ
 B[CNB]ew files scan [C&B]N HBconfig/reset
 [CLB]ist files in current directory
C B[CJB]ump to a fileN HBarea
 [CEB]xtended file information
 [CFB]ind text in descriptions
 [CSB]earch for filenames
 [CVB]iew file contents
N HB[CRB]emove file
NHCFile Menu
WÚÄNÄÄÄÄÄÄÄÄÄ¿‚HM~~~~~~~~~NƒHBGet [CIB]nfo
N³H BTransferW N³HBLog [COB]ff
NÀÄÄÄÄÄÄÄÄÄHÄÙNHBorN HB[CQB]uit
W B[CDB]ownload file(s)N†@SYSONLY@HBSysop [C!B]menuN@SYSONLY@
 HB[CUB]pload file(s)C  B[CZB]N HBto sysop
 [CBB]atch transfer menu
 [CTB]emporary directory
Z