@TRUNCATE@@INCLUDE:%zmenu/head.msg@hy@HOT@n
4b0ЫЫЫЫЫ4 hwList/Flag Files nbЫЫЫЫЫЫЫ4 hwFile Area Selection nbЫЫЫЫЫЫЫЫЫ4 hwFile Search  nbЫЫЫЫЫЫ
ЫЫЫЫ
Ы  hyL nc@List@ @FilesNoun@ in dir @POS:27@bЫ hyJ ncJump to new @FileNoun@ @Area@ bЫ @POS:56@hyF nc@Find@ @Text@ in descrip bЫ
Ы  hyN nc@New@ @FileNoun@ scan @POS:27@bЫДДДДДДДДДДДДДДДДДДДДДДДДДЫ @POS:56@hyS nc@Search@ for filename @POS:79@bЫ
Ы  hyE ncExtended @FileNoun@ info @POS:27@bЫ @POS:34@hy* nc@List@ directories bЫ @POS:79@Ы
ЫЫ„hy/* nc@List@ libraries @POS:53@bЫЫЫЫЫЫ4 hwOther Commands nbЫЫЫЫЫ
ЫЫЫЫЫ4 hwUpload/Download nbЫЫЫЫЫ hy{ }  c# nc@Select@ directory bЫ
 Ы hy[ ] c/# nc@Select@ library @POS:53@bЫ @POS:56@hy& nc@FileNoun@ scan config
   hyD nc@Download@ @FileNoun@ @POS:27@bЫ @POS:53@Ы @POS:56@hyR ncRemove/edit @FileNoun@
   hyU nc@Upload@ @FileNoun@ @POS:27@bЫЫЫЫЫЫЫЫЫЫ4 hwGo to nbЫЫЫЫЫЫЫЫЫЫ @POS:56@hyI ncInformation
  hy/D nc@Download@ from @UserNoun@ @POS:27@bЫ @POS:53@Ы @POS:56@hyV nc@View@ @FileNoun@ contents
  hy/U nc@Upload@ to @UserNoun@ @POS:27@bЫ hyQ nc@Main@/@MessageNoun@ @Section@ @POS:53@bЫ hy/L nc@Node@ activity
   hyZ nc@Upload@ to @Sysop@ @POS:27@bЫ hyC ncChat @Section@ @POS:53@bЫ hy^K ncCtrl-key @MenuNoun@
   hyB ncBatch/Bi-dir xfers   bЫ hyT ncTemp dir/Archive cmds bЫ  hyO nc@Logoff@ BBS (or hy/Onc)
b ЫЫ  @SYSONLY@hy!nc @Sysop@ Menu@SYSONLY@
@HOT:OFF@@INCLUDE:%zmenu/tail.msg@