@CLEAR@
nmUsage Statistics for h@ALIAS@ nm#@USERNUM@n

ncFirst on w:hc @SINCE|L9@nc  Expire  w:hc @EXDATE|L11@nc Last on  w:hc @LASTDATEON@ @LASTTIMEON@
ncTime on  w:hc @TOTALHR|L9@nc  Today   w:hc @TTODAY|L5@ @TPERD|R5@nc Last callw:hc @TLAST|L4@ @TPERC|R5@nc Extraw:hc @MEXTRA@
ncLogons   w:hc @CALLS|TL9@nc  Today   w:hc @LTODAY|L5@ @MAXCALLS|TR5@nc Posts    w:hc @MSGLEFT|TL6@ @PCR-R3@nc Todayw:hc @PTODAY@
ncE-mails  w:hc @EMAILS|TL9@nc  To sysopw:hc @FBACKS|TL11@nc Waiting  w:hc @MAILW|TL10@nc Todayw:hc @ETODAY@

ncUploads  w:hc @UPB|R9@nc bytes in h@UPFILES|T@nc files
ncDownloadsw:hc @DLB|R9@nc bytes in h@DLFILES|T@nc files (h@BTODAY@nc bytes in h@DTODAY@nc files today)
ncCredits  w:hc @CDT|R9@nc free: h@CDTFREE@nc \(h@CDTPERD@nc per day)
ncTimeBank w:hc @TMBANK|R9@                                       
