@CLEAR@
nmUsage Statistics for h@ALIAS@ nm#@USERNUM@n

ncFirst on b:hc @SINCE|L9@nc  Expire  b:hc @EXDATE|L11@nc Last on  b:hc @LASTDATEON@ @LASTTIMEON@
ncTime on  b:hc @TTOTAL:C|L9@nc  Today   b:hc @TTODAY|L5@ @TPERD|R5@nc Last callb:hc @TLAST|L4@ @TPERC|R5@nc Extraw:hc @MEXTRA@
ncLogons   b:hc @CALLS|TL9@nc  Today   b:hc @LTODAY|L5@ @MAXCALLS|TR5@nc Posts    b:hc @MSGLEFT|TL6@ @PCR-R3@nc Todayw:hc @PTODAY@
ncE-mails  b:hc @EMAILS|TL9@nc  To sysopb:hc @FBACKS|TL11@nc Waiting  b:hc @MAILW|TL10@nc Todayw:hc @ETODAY@

ncUploads  b:hc @UPB|R9@nc bytes in h@UPFILES|T@nc files
ncDownloadsb:hc @DLB|R9@nc bytes in h@DLFILES|T@nc files (h@BTODAY@nc bytes in h@DTODAY@nc files today)
ncCredits  b:hc @CREDITS:V|R9@nc free: h@FREECDT:V@nc \(h@CDTPERD@nc per day)
ncTimeBank b:hc @TBANKED:V|R9@
