NHY@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYFile Section Information Menu N4K³
CÀKÄ0Bßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß4KÙßß0BÜÜÜÜ
ÛW HYY NCYour file transfer statisticsWBƒßÛ
Û HYT NCFile transfer policyWBWBÛ
ÛW HYD NCInformation on current directoryBG  BÛ
Û HYU NCUsers with access to current dirBG  BÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HYQ NCQuit to File Transfer menuW‡BÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z