@TRUNCATE@NHY@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HY@FileNoun@ @Section@ Information @MenuNoun@ N4K³
CÀKÄ0Bßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß4KÙßß0BÜÜÜÜ
ÛW HYY NCYour @FileNoun@ @Transfer@ statisticsWB @POS:38@ßÛ
Û HYT NC@FileNoun@ @Transfer@ policyWBW @POS:39@BÛ
ÛW HYD NCInformation on current directoryBG  BÛ
ÛW HYV NCSynchronet version informationBG    BÛ
Û HYU NC@UsersNoun@ with access to current dirBG @POS:39@BÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HYQ NC@Quit@ to @FileNoun@ @Transfer@ @MenuNoun@W @POS:39@BÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z