NHC@HOT@N@CLEAR@
4CÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄK¿
C³ HYFile Configuration N4K³
CÀKÄ0Bßßßßßßßßßßßßßßßßßßß4KÙ0BÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
Û HCPY NCNew scan pointer: HY@LASTNEW-L@NHYƒNBßÛ
Û HCZY NCDefault protocol: HY@PROTNAME-L15@NG BÛ
ÛWHYNCHYNC“auto-hangup:W HY@AUTOHANG|L3@NG BÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄßÛH4WTogglesNBÛßÄÄÄÄÄÄÄÄÄÄÄÄÄ²
ÛW HCBNC Batch file flaggingƒstate:W HY@FILEFLAG|L3@NG BÛ
Û HCEY NCExtended descriptions  state: HY@FILEDESC|L3@N BÛ
Û²ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ²Û
Û HCQY NCQuit to File Transfer menuW‡BÛ
ÛÛÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÛÛ
Z