<div align="center"><p><a href="http://^^JS:system.inet_addr^^/">Home</a> : <a href="/members/">Members</a> : <b>Groups</b></p></div>
<table class="centeralign" border="0">
<tr>
<th class="grouplist">Group</th><th class="grouplist">Description</th>
</tr>
<<REPEAT groups>>
<tr>
	<td>
		<a href="subs.ssjs?msg_grp=^^groups:number^^">%%groups:name%%</a>
	</td>
	<td class="grouplist">
		%%groups:description%%
	</td>
</tr>
<<END REPEAT groups>>
<tr>
        <td>
                <a href="msgs.ssjs?msg_sub=mail">E-Mail</a>
        </td>
        <td class="grouplist">
		Personal E-Mail
        </td>
</tr>
</table>

