<CENTER>
<P><A HREF="http://^^JS:system.inet_addr^^/">Home</A> : <A href="/members/">Members</A> : <B>Groups</B></P>
<TABLE>
<<REPEAT groups>>
<TR>
	<TD>
		<A HREF="subs.ssjs?msg_grp=^^groups:number^^">%%groups:name%%</A>
	</TD>
	<TD>
		%%groups:description%%
	</TD>
</TR>
<<END REPEAT groups>>
<TR>
        <TD>
                <A HREF="msgs.ssjs?msg_sub=mail">E-Mail</A>
        </TD>
        <TD>
		Personal E-Mail
        </TD>
</TR>
</TABLE>
</CENTER>
