<div align="center"><P><A HREF="http://^^JS:system.inet_addr^^/">Home</A> : <A href="/members/">Members</A> : <B>Groups</B></P></div>
<TABLE class="centeralign" border="0">
<tr>
<th class="grouplist">Group</th><th class="grouplist">Description</th>
</tr>
<<REPEAT groups>>
<TR>
	<TD>
		<A HREF="subs.ssjs?msg_grp=^^groups:number^^">%%groups:name%%</A>
	</TD>
	<TD class="grouplist">
		%%groups:description%%
	</TD>
</TR>
<<END REPEAT groups>>
<TR>
        <TD>
                <A HREF="msgs.ssjs?msg_sub=mail">E-Mail</A>
        </TD>
        <TD class="grouplist">
		Personal E-Mail
        </TD>
</TR>
</TABLE>

