<form action="savemsg.ssjs" method="post">
<table class="postmsg" border="0" cellspacing="2" cellpadding="0">
<input type="hidden" name="msg_grp" value="%%group:number%%" />
<input type="hidden" name="msg_sub" value="%%sub:code%%" />
  <tbody>
    <tr>
      <td class="postmsg">Subject: <input class="postmsg" type="text" name="subject" value="" /></td>
      <td class="postmsg">To: <input class="postmsg" type="text" name="to" value="All" /></td>
    </tr>
    <tr>
      <td class="postmsg" colspan="2"><textarea class="postmsg" name=body rows="20" cols="80"></textarea></td>
      </tr>
    <tr>
      <td align="center" class="postmsg" colspan="2"><button type="Submit">Post Message</button></td>
    </tr>
  </tbody>
</table>
</form>

