<table class="subinfo">
  <tr class="subinfo">
    <td>
	  Description:
	</td>
    <td>
	  %%sub:description%%
	</td>
  </tr>
  <tr class="subinfo">
    <td>
	  Newsgroup Name:
	</td>
    <td>
	  %%sub:newsgroup%%
	</td>
  </tr>
  <tr class="subinfo">
    <td>
	  Name:
	</td>
    <td>
	  %%sub:name%%
	</td>
  </tr>
  <tr class="subinfo">
    <td>
	  QWK Name:
	</td>
    <td>
	  %%sub:qwk_name%%
	</td>
  </tr>
  <tr class="subinfo">
    <td>
	  Is Moderated:
	</td>
    <td>
	  %%sub:is_moderated%%
	</td>
  </tr>
  <tr class="subinfo">
    <td>
	  Can Post:
	</td>
    <td>
	  %%sub:can_post%%
	</td>
  </tr>
  <tr class="subinfo">
    <td>
	  Can Read:
	</td>
    <td>
	  %%sub:can_read%%
	</td>
  </tr>
  <tr class="subinfo">
    <td>
	  Am Operator:
	</td>
    <td>
	  %%sub:is_operator%%
	</td>
  </tr>
  <tr class="subinfo">
    <td>
	  Max Msgs:
	</td>
    <td>
	  %%sub:max_msgs%%
	</td>
  </tr>
  <tr class="subinfo">
    <td>
	  Network Type:
	</td>
    <td>
	  %%type%%
	</td>
  </tr>
  <tr class="subinfo">
    <td>
	  Tagline/Origin:
	</td>
    <td>
	  %%tagline%%
	</td>
  </tr>
</table>

