<center>
<table>
  <tr>
    <td>
	  Long Name:
	</td>
    <td>
	  %%sub:description%%
	</td>
  </tr>
  <tr>
    <td>
	  Newsgroup Name:
	</td>
    <td>
	  %%sub:newsgroup%%
	</td>
  </tr>
  <tr>
    <td>
	  Short Name:
	</td>
    <td>
	  %%sub:name%%
	</td>
  </tr>
  <tr>
    <td>
	  QWK Name:
	</td>
    <td>
	  %%sub:qwk_name%%
	</td>
  </tr>
  <tr>
    <td>
	  Is Moderated:
	</td>
    <td>
	  %%sub:is_moderated%%
	</td>
  </tr>
  <tr>
    <td>
	  Can Post:
	</td>
    <td>
	  %%sub:can_post%%
	</td>
  </tr>
  <tr>
    <td>
	  Can Read:
	</td>
    <td>
	  %%sub:can_read%%
	</td>
  </tr>
  <tr>
    <td>
	  Max Msgs:
	</td>
    <td>
	  %%sub:max_msgs%%
	</td>
  </tr>
  <tr>
    <td>
	  Network Type:
	</td>
    <td>
	  %%type%%
	</td>
  </tr>
  <tr>
    <td>
	  Tagline/Origin:
	</td>
    <td>
	  %%tagline%%
	</td>
  </tr>
</table>
</center>
