<CENTER>
<P><A HREF="http://^^JS:system.inet_addr^^/">Home</A> :  <A href="/members/">Members</A> : <A HREF="index.ssjs">Groups</A> : <B>%%group:description%%</B></P>
<TABLE>
<<REPEAT subs>>
<TR>
	<TD>
		<A HREF="msgs.ssjs?msg_grp=^^group:number^^&amp;msg_sub=^^subs:code^^">%%subs:name%%</A>
		<A HREF="subinfo.ssjs?msg_grp=^^group:number^^&amp;msg_sub=^^subs:code^^">[?]</A>
	</TD>
	<TD>
		%%subs:description%%
	</TD>
</TR>
<<END REPEAT subs>>
</TABLE>
</CENTER>
