SBL	=	$(EXEODIR)$(DIRSEP)sbl$(EXEFILE)
SBL2SMB	=	$(EXEODIR)$(DIRSEP)sbl2smb$(EXEFILE)
SMB2SBL	=	$(EXEODIR)$(DIRSEP)smb2sbl$(EXEFILE)
SBLPACK	=	$(EXEODIR)$(DIRSEP)sblpack$(EXEFILE)
SBBSLIST =	$(EXEODIR)$(DIRSEP)sbbslist$(EXEFILE)

all: xpdev xpdev-mt smblib $(EXEODIR) $(MTOBJODIR) $(OBJODIR) \
		$(SBL) $(SBL2SMB) $(SMB2SBL) $(SBLPACK)

