CC = tcc
FLAGS = -ml -wall -C

all: pcedit.exe langcomp.exe mcomp.exe

mcomp.exe:      mcomp.c
	$(CC) $(FLAGS) mcomp.c

pcedit.exe:      pcedit.c
	$(CC) $(FLAGS) pcedit.c

langcomp.exe:      langcomp.c
	$(CC) $(FLAGS) langcomp.c

