@echo off
rem
rem Deletes all intermediate files for Synchronet projects - Rob Swindell
rem
echo y | del stp\*.obj > nul
echo y | del stp\*.map > nul
echo y | del stp\*.exe > nul
echo y | del tone\*.obj > nul
echo y | del tone\*.map > nul
echo y | del tone\*.exe > nul
echo y | del sbbs\dos > nul
echo y | del sbbs\os2 > nul
echo y | del sbbs\w32 > nul
echo y | del sbbs\addfiles\dos > nul
echo y | del sbbs\addfiles\dosx > nul
echo y | del sbbs\addfiles\nt > nul
echo y | del sbbs\addfiles\os2 > nul
echo y | del sbbs\allusers\*.obj > nul
echo y | del sbbs\allusers\*.map > nul
echo y | del sbbs\allusers\*.exe > nul
echo y | del sbbs\baja\*.obj > nul
echo y | del sbbs\baja\*.map > nul
echo y | del sbbs\baja\*.exe > nul
echo y | del sbbs\dcdwatch\*.obj > nul
echo y | del sbbs\dcdwatch\*.map > nul
echo y | del sbbs\dcdwatch\*.exe > nul
echo y | del sbbs\delfiles\dos > nul
echo y | del sbbs\delfiles\dosx > nul
echo y | del sbbs\delfiles\nt > nul
echo y | del sbbs\delfiles\os2 > nul
echo y | del sbbs\dstsedit\*.obj > nul
echo y | del sbbs\dstsedit\*.map > nul
echo y | del sbbs\dstsedit\*.exe > nul
echo y | del sbbs\dupefind\dos > nul
echo y | del sbbs\dupefind\dosx > nul
echo y | del sbbs\dupefind\nt > nul
echo y | del sbbs\dupefind\os2 > nul
echo y | del sbbs\echo\*.obj > nul
echo y | del sbbs\echo\*.map > nul
echo y | del sbbs\echo\*.exe > nul
echo y | del sbbs\echo\dos > nul
echo y | del sbbs\echo\dos4G > nul
echo y | del sbbs\echo\nt > nul
echo y | del sbbs\echo\os2 > nul
echo y | del sbbs\execsbbs\dos > nul
echo y | del sbbs\execsbbs\os2 > nul
echo y | del sbbs\filelist\dos > nul
echo y | del sbbs\filelist\dosx > nul
echo y | del sbbs\filelist\nt > nul
echo y | del sbbs\filelist\os2 > nul
echo y | del sbbs\install\dos > nul
echo y | del sbbs\install\os2 > nul
echo y | del sbbs\mlabels\*.obj > nul
echo y | del sbbs\mlabels\*.map > nul
echo y | del sbbs\mlabels\*.exe > nul
echo y | del sbbs\node\dos > nul
echo y | del sbbs\node\os2 > nul
echo y | del sbbs\qwknodes\*.obj > nul
echo y | del sbbs\qwknodes\*.map > nul
echo y | del sbbs\qwknodes\*.exe > nul
echo y | del sbbs\sbl\*.obj > nul
echo y | del sbbs\sbl\*.map > nul
echo y | del sbbs\sbl\*.exe > nul
echo y | del sbbs\sbj\*.obj > nul
echo y | del sbbs\sbj\*.map > nul
echo y | del sbbs\sbj\*.exe > nul
echo y | del sbbs\scb\*.obj > nul
echo y | del sbbs\scb\*.map > nul
echo y | del sbbs\scb\*.exe > nul
echo y | del sbbs\scfg\dos > nul
echo y | del sbbs\scfg\dos32 > nul
echo y | del sbbs\scfg\os2 > nul
echo y | del sbbs\slog\dos > nul
echo y | del sbbs\slog\os2 > nul
echo y | del sbbs\smb\chksmb\dos > nul
echo y | del sbbs\smb\chksmb\os2 > nul
echo y | del sbbs\smb\fixsmb\dos > nul
echo y | del sbbs\smb\fixsmb\os2 > nul
echo y | del sbbs\smb\smbutil\dos > nul
echo y | del sbbs\smb\smbutil\dos4G > nul
echo y | del sbbs\smb\smbutil\nt > nul
echo y | del sbbs\smb\smbutil\os2 > nul
echo y | del sbbs\smbactiv\dos > nul
echo y | del sbbs\smbactiv\dosx > nul
echo y | del sbbs\smbactiv\nt > nul
echo y | del sbbs\smbactiv\os2 > nul
echo y | del sbbs\smm\*.obj > nul
echo y | del sbbs\smm\*.map > nul
echo y | del sbbs\smm\*.exe > nul
echo y | del sbbs\uti\*.obj > nul
echo y | del sbbs\uti\*.map > nul
echo y | del sbbs\uti\*.exe > nul
echo y | del sbbs\execdos\*.obj > nul
echo y | del sbbs\execdos\*.map > nul
echo y | del sbbs\execdos\*.exe > nul

