@X1E@CLEAR@@CENTER@Synchronet Utopia
@CENTER@~~~~~~~~~~~~~~~~~
@CENTER@by Rob Swindell (digital man)

#Can you build a better Utopian society?#

This game is a single-player stategy/simulation heavily inspired by the
multi-player Mattel Electronics game designed and programmed by Don Daglow for
the Intellivision gaming console.  The original "Utopia" could be played single
player as well, but its real shine came from the head-to-head (or rather
side-by-side) competition it encouraged between two friends sharing a small TV.
For now at least, "Synchronet Utopia" is strictly single player - though other
BBS users can play concurrently, they'll be playing their own maps with their
choice of difficulty/rules.

*Synchronet Utopia* can be played with a randomly-generated map or a predesigned
map.  The game comes with a couple of maps and your sysop may have have added
or created some of their own.  When starting the game, you are initially
prompted to choose which map to play, if there are multiple to choose from:

Select Map to Play:

  1: Classic Islands
  2: Hawaiian Islands
  3: Randomly Generated

Which, Quit or [1]: 

After choosing a map, you will then be prompted to choose which rules to play
by, again, only if there are multiple options to choose from:

Select Rules to Play By:

  1: Easy
  2: Challenging

Which, Quit or [1]:

After a map and set of rules are selected, you will be welcomed with the
display of a map covering the majority of an 80x24 terminal screen.  To the
right of this map is a legend of buildable items along with the average health
of the items of each type that have been already built (initially, all 0%):

                                Items     Health
                              ± Crops          0%
                              ± Animals        0%
                               Trawler        0%
                               PT Boat        0%
                              ö Villas         0%
                              Û Dock           0%
                              Î Bridge         0%
                              Û Industry       0%
                               School         0%
                              Å Hospital       0%
                              ã Fortress       0%

You start the game by moving the cursor (the red block in the middle of the
map) with your arrow keys to a land mass of your choosing and building a
land-based item there.  A Villa to house people would be a good starting item
to build.  The land masses are the blobs of green blocks while the area of blue
surrounding them represents water.  Little dots in the water are fish.  You may
notice occasional waves out of the west as well.

The cost to purchase and effectiveness of owning the different items varies
with the rules being played by, so we won't detail those parameters here.  You
can see the current cost of items you may build by pressing the ENTER key.
Land-based items (e.g. Villas and Crops) may only be built on land while
water-based items (e.g. boats) may only be built on water.  Bridges may be
built on land or water.

You can only build on your "homeland" or water directly adjacent to your
homeland.  Your first built item will determine which land mass is your
homeland and it will remain your homeland for the duration of that game.
Foreign lands are colored cyan rather than green.  You can extend your homeland
to other land masses by building bridges.  If a bridge is used to extend your
homeland and is later destroyed or demolished, you will not be able to use or
benefit from the items built there until the bridge is replaced.  The bigger
your homeland, the more you can build and the more land taxes you will collect
each round.

A "round" is made of 10 "turns".  The maximum duration of the game is specified
in rounds and is one of the parameters of the rules the game is played under.
As an example, a 50 round game made of 10 turns each, where each turn is 2
seconds in duration, would take about 17 minutes to play.  In reality, viewing
the build menu, pausing the game (with the 'Q' key), or just slowing down the
"clock" (with the '-' key) can make the same game take longer to play out.
There is no penalty for pausing or slowing a game in progress.  At any time,
the player can choose to quit a game and either "Save" for later resumption,
"Abort" it, or "Finish" the game, recording their final calculated score in the
annals of Utopian history.  Getting disconnected while playing a game will
automatically save that game for later continuance, when your little sister is
off the phone.

Now, back to the buildable items.  Some items can house people (and thus
expand the population capacity): Villas (primarily), Forts, and sometimes and
to a lesser degree, Industry, Hospitals, Docks, and Schools.  Again, it depends
on the rules.

Some items produce food: Crops, Animals, and Trawlers (commercial fishing
boats).  Some items produce income (money), primarily Industry and Trawlers.
The productivity of Trawlers is heavily dependent on their luck with the fish.
The productivity of Crops is heavily dependent on their luck with the weather.
Animals are more hearty, but they produce less food per acre and are more
expensive to buy/build and produce (much) more pollution.

#The weather?#

Yes, there will be occasional rain clouds out of the north and severe storms
out of the east.  Rain is important for the health and productivity of Crops
and Animals, but a direct hit from a severe storm will destroy anything in its
path.

Some items produce pollution that is harmful to people: Animals, Industry, and
boats.  Crops help offset the pollution.

Some items are interdependent: Industry needs crops for raw materials, boats
cannot be built without docks, Trawlers benefit from PT Boats for protection.
All items can benefit from the protection of Forts.  And of course, the people
need food.  A lot of food.

Speaking of Docks, you can extend a Dock (e.g. for building boats closer to
fish in open waters) by building a "pier" with Bridge segments.

#Back to food:#

Unlike the real world, you can't just directly turn money (Gold) into food. You
must grow, raise, catch, and harvest the food used to feed your people.  You
also need to educate your people by building Schools and keep them healthy
by building Hospitals.  Schools and Hospitals cost the public (you) money each
round to maintain, but educated people are less likely to rebel and healthy
people are more likely to stay alive and procreate, thus increasing the
population.  The needs of the people multiply with the size of the population.

Keep an eye on your percentage of rebels.  More rebels means higher costs of
demolition (intentionally destroying any built item with the Delete key) and
the risk of a Mutiny (rebels turning a PT Boat into a dangerous Pirate ship).
Lack of food, housing, and education are factors in an increasing rebellion.
Under extreme rebellion, you can declare Martial Law, and for a limited amount
of time all your productivity will go towards reducing the dangers and quantity
of the rebels; no revenues will be collected while under martial law.

#Pirates you say?#

Yes, pirates can invade your Utopia at any time.  The pirates usually approach
from the eastern horizon.  While pirates most often attack other ships
(Trawlers, PT Boats, and Merchants), they can also attack coastal properties
not protected by Forts.  Forts also protect nearby boats.  If one of your PT
Boats destroys a pirate ship, you will likely be financially rewarded in
proportion to the size of their loot.  If a pirate ship escapes to the western
horizon, you will be financially penalized.  Pirates will only pursue targets
to the north, south, and west.  While pirates are normally a bit faster than
Merchants (and very fast when pursuing their prey), they are slowed and subdued
by easterly currents.

#Merchants#

Merchant ships will appear on occasion out of the west.  Slow and vulnerable,
Merchant ships are aided by westerly waves.  For every turn that a Merchant is
present in your island waters, you will receive a small fee.  A Merchant will
occasionally dock and trade with your homeland, but their ultimate goal is to
safely reach the eastern horizon to trade with far away lands and on those
occasions, you will be rewarded handsomely.

#Gameplay Tips#

- Moving the cursor over an item will show its current health in the legend
- Moving the cursor over a Merchant or Pirate ship will show its purse value
- Most items can be built immediately by pressing the corresponding build menu
  key (e.g. 'V' for Villas), without needing to pull up the Build Item menu
- The SPACE BAR will repeat an attempt of the previously successful item-build
  and move the cursor to the right - useful for fast build-outs
- The [Q]uit key can also be used to pause the game in-progress
- The '+' and '-' keys can be used to adjust the speed of the clock
- Alerts may fly by, but if you think you missed an important News bulletin,
  use the 'L' key to view the log of news in reverse chronological order
- You can move the cursor with the arrow keys, Home, End, PageUp, and PageDown
  keys as well as the number keys (e.g. on the keypad) for all directions
  including diagonals
- For convenience, the INSert, Ctrl-V and '0' keys may also be used to pull up
  the build menu
- The '.' key may also be used to demolish an item
- The Ctrl-R key can be used to refresh the screen if needed

#Finally#

So now that you're prepared to take office as governor, what say you girl or
boy, can you do better?