NÜHB‹‹‹‹NïHB‹‹N†HB‹‹
NÖHB€€ﬂ€€NïHB€€N†HB€€
NÖH4B≤≤N H4B≤≤NïH4B≤≤N†H4B≤≤
NÖH4B≤≤N H4B≤≤N  HB‹‹N HB‹‹NéH4B≤≤NÑHB‹NöH4B≤≤
NÖH4B±±NÑH4B±±N H4B±±N  HB‹‹‹‹NÉHB‹‹‹N  H4B±±0‹‹NÇH4B±±0‹4±±NÇHB‹‹‹NÇHB‹‹‹‹NÉHB‹‹‹‹N  H4B±±±±
NÖBﬂH4±±±NB‹W  H4B∞∞N H4B∞∞N  H4B±±N H4B±±N  H4B±±N H4B±N  H4B±±N H4B±±N  H4B±±N H4B±±N  H4B±±N H4B±±N  H4B±±N H4B±±N  H4B±±N H4B±±N  H4B±±
NàH4B∞∞N  H4B∞∞N H4B∞∞N  H4B∞∞N H4B∞∞N  H4B∞∞NÉH4B∞∞N H4B∞∞N  H4B∞∞NÑH4B∞∞N H4B∞∞N  H4B∞∞N H4B∞∞N  H4B∞∞NB‹H4∞∞N  H4B∞∞
NÖH4B∞∞N H4B∞∞N  B€€W B€€W  H4B∞∞N H4B∞∞N  H4B∞∞NÉH4B∞∞N H4B∞∞N  H4B∞∞NÑH4B∞∞N H4B∞∞N  H4B∞∞N H4B∞∞N  H4B∞∞N B‹‹W  H4B∞∞
NÖB€€‹€€WÇBﬂﬂ€€W  B€€W B€€W  B€€W B€W  B€€W B€€W  B€€WÑB€€W B€€W  B€€W B€€W  B€€W B€€W  B€€W B€
WÖBﬂﬂﬂﬂWÇB‹€W B€€W  BﬂﬂW BﬂﬂWÇBﬂﬂﬂW  BﬂﬂW BﬂﬂW  BﬂﬂWÖBﬂﬂﬂWÇBﬂﬂW BﬂﬂWÇBﬂﬂﬂﬂWÇBﬂﬂﬂ
WKWåBﬂ€W B€€WÇHC‹‹ ‹‹  ‹‹‹‹Ç‹‹‹Ç‹‹‹‹Ç‹‹Ç‹‹‹
NKWéBﬂ€€WÇHC€€ €€  ﬂ€€ﬂ  €€ﬂ€€  €€ﬂ€€  €€  €€ﬂ€€
NHCîNC≤≤ ≤≤Ç≤≤Ç≤≤ ≤≤  ≤≤ ≤≤  ≤≤  ≤≤ ≤≤
WHCîNC≤≤ ≤≤Ç≤≤Ç≤≤ ≤≤  ≤≤ ≤≤  ≤≤  ≤≤ ≤≤
WHCîNC±± ±±Ç±±Ç±± ±±  ±± ±±  ±±  ±± ±±
WîH4B±±N H4B±±NÇH4B±±NÇH4B±±N H4B±±N  H4B±±±±NBﬂW  H4B±±N  H4B±±±±±
NîH4B∞∞N H4B∞∞NÇH4B∞∞NÇH4B∞∞N H4B∞∞N  H4B∞∞NÑH4B∞∞N  H4B∞∞N H4B∞∞
NîH4B∞∞N H4B∞∞NÇH4B∞∞NÇH4B∞∞N H4B∞∞N  H4B∞∞NÑH4B∞∞N  H4B∞∞N H4B∞∞
NîB€€‹€€WÇB€€WÇB€€‹€€W  B€€WÑB€€W  B€€W B€€
WïBﬂﬂﬂWÉBﬂﬂWÉBﬂﬂﬂWÇBﬂﬂWÑBﬂﬂW  BﬂﬂW Bﬂﬂ

WÜA reimagining of the Mattel Electronics game for Intellivision,
âa nation-building strategy/simulation game by Don Daglow
Z