@WORDWRAP@@CONDMENU:../banner@
nhCLIENT ncCONN: h@CONN@
nh       ncADDR: h@HOST@ [@IP@]
nh       ncTERM: h@COLS@x@ROWS@ @TERM@ 
nhSERVER ncNAME: hy@BBS@
nh       ncADDR: h@HOSTNAME@
nh       ncNODE: h@NODE@ nc(of h@TNODE@nc) - h@OS_VER@
nh       ncTIME: h@DATETIME-L############@ @TIMEZONE@
nh       ncADMN: h@SYSOP@

bIf you are a new user to the system, type c"New"b now.
Otherwise, enter your user name or number now.
