Hey @user.name@, just a head's up that on @system.name@ (@system.inet_addr@)
user accounts are automatically deleted after @system.autodel@ days of inactivity
and your account is getting close to that mark.

I just wanted to make sure you had the opportunity to login soon and
reset that clock to keep your account intact and say hi while we're at it!

Thank you and hope to you on the BBS soon,

@system.operator@
