ncYour Internet e-mail address here on @BBS@ is:
<h@EMAILADDR@nc>

You can access the file areas using any hyFTPnc client by pointing
it at h@HOSTNAME@nc (port 21) 
and logging in with your username and password. If the sysop
has a Guest/Anonymous user account configured, you can point
a web browser at hftp://@HOSTNAME@/00index.htmlnc
for a nice HTML interface to the file areas.

You can retrieve your e-mail using any Internet (POP3) hye-mailnc client
by pointing it at h@HOSTNAME@nc (port 110) 
and logging in with your username and password. The sysop may
even allow relaying of mail through the SMTP server (port 25),
ask h@SYSOP@nc for details.

You can access the message areas using any yhNewsgroupnc (NNTP) reader
by pointing it at h@HOSTNAME@nc (port 119) 
and logging in with your username and password.

You may also use hyGophernc (port 70) and yhFingernc (port 79) clients
to access many read-only facilities on this BBS.
