@CLEAR@
nhInternet E-mail:
ncYour Internet e-mail address here on h@BBS@nc is:
<h@EMAILADDR@nc>

If your sysop (@SYSOP@) has enabled the Synchronet mail (SMTP)
server, you may be able to send and receive Internet e-mail using this address,
so you may want to make a note of it.

nhSystem Policies:
ncMaximum inactivity before user account deletion: h@AUTODEL@ days
ncMaximum interval of user password modifications: h@PWDAYS@ days