ngThe rules of the BBS are normally displayed here, but the sysop has not
yet defined them. So in the meantime, please use common sense and follow the
golden rule: "hTreat others as you yourself wish to be treatedng."

Of course technical rules like "hDo not upload commercial softwareng" and
"hDo not upload virus or trojan horse filesng" also apply, so please ask the
sysop for details.

