			       nch1 ๙ Synchronet ๙ n
			    yhMultinode BBS Software

           bDeveloped 1990-2000 by Rob Swindell - whttp://www.synchro.net

			     ngีออออออออออออออออออธ
			     ณ hKeys to Rememberng ณ
			     ฦออออออออออออออออออต
			     ณ	whCtrl-C ngAbort    ณ
			     ณ	whCtrl-S ngPause    ณ
			     ณ	whCtrl-Q ngContinue ณ
			     ณ       wh? ngMenu     ณ
			     ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู

		     hExample Prompt: wOngne, hwTngwo, or [Three]:

			  hIndicates: wO ngOne
				     whT ngTwo
				 whEnter ngThree
