@CLS@nhcThis BBS is running...

y .|'''.|                        '||                                      .   
y ||..  ' .... ..... ...    ....  || ..  ... ..   ...   .. ...    ....  .||.  
y  ''|||.  '|.  |  ||  || .|   '' ||' ||  ||' ''.|  '|.  ||  || .|...||  ||   
y.     '||  '|.|   ||  || ||      ||  ||  ||    ||   ||  ||  || ||       ||   
y|'....|'    '|   .||. ||. '|...'.||. ||..||.    '|..|' .||. ||. '|...'  '|.' 
y         .. |
y          ''
w              Synchronet BBS for @PLATFORM@ - Version @FULL_VER@
w              @COPYRIGHT@ - http://www.synchro.net
gh
32-bit Multi-threaded Bulletin Board System Software for the Internet Age
ng
Integrated TCP/IP Servers: hong Telnet/RLogin/SSH
                           hong SMTP/POP3 (inbound and outbound e-mail)
                           hong FTP (with dynamic ASCII and HTML index files)
                           hong Network News Transfer Protocol (e.g. USENET)
                           hong Web (HTTP with server-side JavaScript and CGI)
                           hong Finger, Gopher, and IRC
h
Native versions for Win32 and Unix (e.g. Linux, FreeBSD, and OpenBSD) platforms
n@CLS@-----------------------------------------------------------------------------
hRemembering these keys will help you enjoy your cSynchronetw Telnet experience:
n-----------------------------------------------------------------------------
c
At hr[Hit a key]n prompts, you can hit hCtrl-Cn or 'hQn' to stop listing text.

Hitting hDown Arrown (or Ctrl-J) at auto-hrpausen prompts will scroll one line at a
time, while hitting any other key will continue one page at a time.

The global rhABORTn-operation key sequence is: hCtrl-Cn.

Other global control-key sequences include: hCtrl-Uy: List users onlinen
					    hCtrl-Py: Send a private messagen
                                            hCtrl-Ty: Show time informationn
                                            hCtrl-Oy: Toggle auto-pause Off/Onn

Use 'h?n' to display help menus, and use 'hQn' to quit.
