@CLS@nhcThis BBS is running...

y .|'''.|                        '||                                      .   
y ||..  ' .... ..... ...    ....  || ..  ... ..   ...   .. ...    ....  .||.  
y  ''|||.  '|.  |  ||  || .|   '' ||' ||  ||' ''.|  '|.  ||  || .|...||  ||   
y.     '||  '|.|   ||  || ||      ||  ||  ||    ||   ||  ||  || ||       ||   
y|'....|'    '|   .||. ||. '|...'.||. ||..||.    '|..|' .||. ||. '|...'  '|.' 
y         .. |
y          ''
w              Synchronet BBS for @PLATFORM@ - Version @FULL_VER@
w              @COPYRIGHT@ - http://www.synchro.net
gh
32-bit Multi-threaded Bulletin Board Sytem Software for the Internet Age
ng
Integerated TCP/IP Servers: hong Telnet/RLogin
                            hong SMTP/POP3 (inbound and outbound e-mail)
                            hong FTP (with dynamic ASCII and HTML index files)
                            hong Network News Transfer Protocol (USENET)
                            hong Finger (with real-time node listings)
                            hong Gopher (browse message areas online)
h
Native versions for Win32 and Unix-x86 (Linux, FreeBSD, and OpenBSD)
n@CLS@-----------------------------------------------------------------------------
hRemembering these keys will help you enjoy your cSynchronetw Telnet experience:
n-----------------------------------------------------------------------------
c
At hr[Hit a key]nc prompts, you can hit hCtrl-Cnc or 'hQnc' to stop listing text.

Hitting hDown Arrownc (or Ctrl-J) at auto-hrpausenc prompts will scroll one line at a
time, while hitting any other key will continue one page at a time.

The global rhABORTnc-operation key sequence is: hCtrl-Cnc.

Other global control-key sequences include: hCtrl-Uy: List users onlinenc
					    hCtrl-Py: Send a private messagenc
                                            hCtrl-Ty: Show time informationnc

Use 'h?nc' to display help menus, and use 'hQnc' to quit.