nhwThis is y@BBS@w located in y@LOCATION@w
with your sysop, y@SYSOP@w here to serve you.

y@HOSTNAME@w is running y@OS_VER@w
and has been online continuously for y@UPTIME@w hours.

ySystem Totals:w

Users:     m@TUSER-L.......@w today: m@STATS.NUSERS@w
Logons:    m@STATS.LOGONS-L@w today: m@STATS.LTODAY@w
Timeused:  m@STATS.TIMEON-L@w today: m@STATS.TTODAY@w
Messages:  m@TMSG-L........@w today: m@STATS.PTODAY@w
E-mail:    m@MAILW:0-L.....@w today: m@STATS.ETODAY@w
Feedback:  m@MAILW:1-L.....@w today: m@STATS.FTODAY@w
Files:     m@TFILE-L.......@w today: m@STATS.ULS@w
                 Downloaded today: m@STATS.DLS@w (m@STATS.DLB@w nbytesh)
