@CLS@nhwThis is y@BBS@w located in \y@LOCATION|>@w
with your sysop, y@SYSOP@w \here to serve you.

y@HOSTNAME@w is running y@OS_VER|>@w
and has been online continuously for \y@UPTIME:W@w.

ySystem Totals:w

Users    nm:h @TUSER|TL11@w todaynm:h @STATS.NUSERS@w
Logons   nm:h @STATS.LOGONS|TL11@w todaynm:h @STATS.LTODAY@w
Time Usednm:h @STATS.TIMEON:V|11@w  todaynm:h @STATS.TTODAY:V@w
Messages nm:h @TMSG|TL11@w todaynm:h @STATS.PTODAY@w
E-mail   nm:h @MAILW:0|TL11@w todaynm:h @STATS.ETODAY@w
Feedback nm:h @MAILW:1|TL11@w todaynm:h @STATS.FTODAY@w
Files    nm:h @TFILE|TL11@w todaynm:h @STATS.ULS@w
            \Downloaded todaynm:h @STATS.DLS@w (m@STATS.DLB:V@w nbytesh)
