#!/bin/sh

# PROVIDE sbbs
# REQUIRE LOGIN

# Location of rc.subr
if [ `/usr/bin/uname -r | /usr/bin/sed 's/[^0-9].*//g'` -lt 5 ]
then
	rc_subr_path="/usr/local/etc/rc.subr.bob"
else
	rc_subr_path="/etc/rc.subr"
fi

if [ ! -f ${rc_subr_path} ]
then
	echo "${rc_subr_path} not found" >> /dev/stderr
	if [ `/usr/bin/uname -r | /usr/bin/sed 's/[^0-9].*//g'` -lt 5 ]
		echo "Please install the sysutils/rc_subr port" >> /dev/stderr
	exit 1
fi

. ${rc_subr_path}


status_cmd=sbbs_status
name="sbbs"
rcvar=`set_rcvar`

load_rc_config $name

# Setup defaults...
# Define these sbbs_* variables in one of these files:
#       /etc/rc.conf
#       /etc/rc.conf.local
#       /etc/rc.conf.d/sbbs
#
# DO NOT CHANGE THESE DEFAULT VALUES HERE
#
sbbs=${sbbs-"NO"}
sbbs_enable=${sbbs_enable-"NO"}
sbbs_flags=${sbbs_flags-""}
sbbs_pidfile=${sbbs_pidfile-"/var/run/sbbs.pid"}
sbbs_dir=${sbbs_dir-"/sbbs/"}
sbbs_ctrldir=${sbbs_ctrldir-"${sbbs_dir}/ctrl/"}
sbbs_execdir=${sbbs_execdir-"${sbbs_dir}/exec/"}
sbbs_program=${sbbs_program-"${sbbs_execdir}/sbbs"}
sbbs_procname=${sbbs_procname-"${sbbs_program}"}
sbbs_shell=${sbbs_shell-"/bin/sh"}

sbbs_status()
{
	${sbbs_execdir}/node list

	echo
	if [ -n "$rc_pid" ]; then
		echo "${name} is running as pid $rc_pid."
	else
		echo "${name} is not running."
		return 1
	fi
}

extra_commands="config monitor uedit"
config_cmd=${sbbs_execdir}/scfg
monitor_cmd=${sbbs_execdir}/umonitor
uedit_cmd=${sbbs_execdir}/uedit

SHELL=$sbbs_shell
export SHELL
SBBSCTRL=$sbbs_ctrldir
export SBBSCTRL
run_rc_command "$1"
