# Available Options:

XPDEV_LIB		=	$(XPDEV_SRC)$(DIRSEP)$(LIBODIR)$(DIRSEP)$(LIBPREFIX)xpdev$(LIBFILE)
XPDEV-MT_LIB		=	$(XPDEV_SRC)$(DIRSEP)$(LIBODIR)$(DIRSEP)$(LIBPREFIX)xpdev_mt$(LIBFILE)

XPDEV_CFLAGS	=	-I$(XPDEV_SRC)
XPDEV_LDFLAGS	=	-L$(XPDEV_SRC)$(DIRSEP)$(LIBODIR)
XPDEV-MT_CFLAGS	=	$(XPDEV_CFLAGS) -DLINK_LIST_THREADSAFE
XPDEV-MT_LDFLAGS=	$(XPDEV_LDFLAGS)
XPDEV_LIBS	=	$(UL_PRE)xpdev$(UL_SUF)
XPDEV-MT_LIBS	=	$(UL_PRE)xpdev_mt$(UL_SUF)
