/* Synchronet Unicode definitions */

/* $Id$ */

/****************************************************************************
 * @format.tab-size 4		(Plain Text/Source Code File Header)			*
 * @format.use-tabs true	(see http://www.synchro.net/ptsc_hdr.html)		*
 *																			*
 * Copyright Rob Swindell - http://www.synchro.net/copyright.html			*
 *																			*
 * This library is free software; you can redistribute it and/or			*
 * modify it under the terms of the GNU Lesser General Public License		*
 * as published by the Free Software Foundation; either version 2			*
 * of the License, or (at your option) any later version.					*
 * See the GNU Lesser General Public License for more details: lgpl.txt or	*
 * http://www.fsf.org/copyleft/lesser.html									*
 *																			*
 * Anonymous FTP access to the most recent released source is available at	*
 * ftp://vert.synchro.net, ftp://cvs.synchro.net and ftp://ftp.synchro.net	*
 *																			*
 * Anonymous CVS access to the development source and modification history	*
 * is available at cvs.synchro.net:/cvsroot/sbbs, example:					*
 * cvs -d :pserver:anonymous@cvs.synchro.net:/cvsroot/sbbs login			*
 *     (just hit return, no password is necessary)							*
 * cvs -d :pserver:anonymous@cvs.synchro.net:/cvsroot/sbbs checkout src		*
 *																			*
 * For Synchronet coding style and modification guidelines, see				*
 * http://www.synchro.net/source.html										*
 *																			*
 * You are encouraged to submit any modifications (preferably in Unix diff	*
 * format) via e-mail to mods@synchro.net									*
 *																			*
 * Note: If this box doesn't appear square, then you need to fix your tabs.	*
 ****************************************************************************/

#ifndef UNICODE_DEFS_H_
#define UNICODE_DEFS_H_

enum unicode_codepoint {
	UNICODE_NO_BREAK_SPACE = 0x00A0,

	UNICODE_INVERTED_EXCLAMATION_MARK = 0x00A1,
	UNICODE_CENT_SIGN = 0x00A2,
	UNICODE_POUND_SIGN = 0x00A3,
	UNICODE_CURRENCY_SIGN = 0x00A4,
	UNICODE_YEN_SIGN = 0x00A5,
	UNICODE_BROKEN_BAR = 0x00A6,
	UNICODE_SECTION_SIGN = 0x00A7,

	UNICODE_DEGREE_SIGN = 0x00B0,
	UNICODE_PLUS_MINUS_SIGN = 0x00B1,
	UNICODE_SUPERSCRIPT_TWO = 0x00B2,
	UNICODE_ACUTE_ACCENT = 0x00B4,
	UNICODE_PILCROW_SIGN = 0x00B6,	// Paragraph mark

	UNICODE_INVERTED_QUESTION_MARK = 0x00BF,

	UNICODE_LATIN_CAPITAL_LETTER_A_WITH_GRAVE = 0x00C0,
	UNICODE_LATIN_CAPITAL_LETTER_A_WITH_ACUTE = 0x00C1,
	UNICODE_LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX = 0x00C2,
	UNICODE_LATIN_CAPITAL_LETTER_A_WITH_TILDE = 0x00C3,
	UNICODE_LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS = 0x00C4,
	UNICODE_LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE = 0x00C5,
	UNICODE_LATIN_CAPITAL_LETTER_AE = 0x00C6,
	UNICODE_LATIN_CAPITAL_LETTER_C_WITH_CEDILLA = 0x00C7,
	UNICODE_LATIN_CAPITAL_LETTER_E_WITH_GRAVE = 0x00C8,
	UNICODE_LATIN_CAPITAL_LETTER_E_WITH_ACUTE = 0x00C9,
	UNICODE_LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX = 0x00CA,
	UNICODE_LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS = 0x00CB,
	UNICODE_LATIN_CAPITAL_LETTER_I_WITH_GRAVE = 0x00CC,
	UNICODE_LATIN_CAPITAL_LETTER_I_WITH_ACUTE = 0x00CD,
	UNICODE_LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX = 0x00CE,
	UNICODE_LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS = 0x00CF,
	UNICODE_LATIN_CAPITAL_LETTER_ETH = 0x00D0,
	UNICODE_LATIN_CAPITAL_LETTER_N_WITH_TILDE = 0x00D1,
	UNICODE_LATIN_CAPITAL_LETTER_O_WITH_GRAVE = 0x00D2,
	UNICODE_LATIN_CAPITAL_LETTER_O_WITH_ACUTE = 0x00D3,
	UNICODE_LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX = 0x00D4,
	UNICODE_LATIN_CAPITAL_LETTER_O_WITH_TILDE = 0x00D5,
	UNICODE_LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS = 0x00D6,
	UNICODE_MULTIPLICATION_SIGN = 0x00D7,
	UNICODE_LATIN_CAPITAL_LETTER_O_WITH_STROKE = 0x00D8,
	UNICODE_LATIN_CAPITAL_LETTER_U_WITH_GRAVE = 0x00D9,
	UNICODE_LATIN_CAPITAL_LETTER_U_WITH_ACUTE = 0x00DA,
	UNICODE_LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX = 0x00DB,
	UNICODE_LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS = 0x00DC,
	UNICODE_LATIN_CAPITAL_LETTER_Y_WITH_ACUTE = 0x00DD,
	UNICODE_LATIN_CAPITAL_LETTER_THORN = 0x00DE,
	UNICODE_LATIN_SMALL_LETTER_SHARP_S = 0x00DF,
	UNICODE_LATIN_SMALL_LETTER_A_WITH_GRAVE = 0x00E0,
	UNICODE_LATIN_SMALL_LETTER_A_WITH_ACUTE = 0x00E1,
	UNICODE_LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX = 0x00E2,
	UNICODE_LATIN_SMALL_LETTER_A_WITH_TILDE = 0x00E3,
	UNICODE_LATIN_SMALL_LETTER_A_WITH_DIAERESIS = 0x00E4,
	UNICODE_LATIN_SMALL_LETTER_A_WITH_RING_ABOVE = 0x00E5,
	UNICODE_LATIN_SMALL_LETTER_AE = 0x00E6,
	UNICODE_LATIN_SMALL_LETTER_C_WITH_CEDILLA = 0x00E7,
	UNICODE_LATIN_SMALL_LETTER_E_WITH_GRAVE = 0x00E8,
	UNICODE_LATIN_SMALL_LETTER_E_WITH_ACUTE = 0x00E9,
	UNICODE_LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX = 0x00EA,
	UNICODE_LATIN_SMALL_LETTER_E_WITH_DIAERESIS = 0x00EB,
	UNICODE_LATIN_SMALL_LETTER_I_WITH_GRAVE = 0x00EC,
	UNICODE_LATIN_SMALL_LETTER_I_WITH_ACUTE = 0x00ED,
	UNICODE_LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX = 0x00EE,
	UNICODE_LATIN_SMALL_LETTER_I_WITH_DIAERESIS = 0x00EF,
	UNICODE_LATIN_SMALL_LETTER_ETH = 0x00F0,
	UNICODE_LATIN_SMALL_LETTER_N_WITH_TILDE = 0x00F1,
	UNICODE_LATIN_SMALL_LETTER_O_WITH_GRAVE = 0x00F2,
	UNICODE_LATIN_SMALL_LETTER_O_WITH_ACUTE = 0x00F3,
	UNICODE_LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX = 0x00F4,
	UNICODE_LATIN_SMALL_LETTER_O_WITH_TILDE = 0x00F5,
	UNICODE_LATIN_SMALL_LETTER_O_WITH_DIAERESIS = 0x00F6,
	UNICODE_DIVISION_SIGN = 0x00F7,
	UNICODE_LATIN_SMALL_LETTER_O_WITH_STROKE = 0x00F8,
	UNICODE_LATIN_SMALL_LETTER_U_WITH_GRAVE = 0x00F9,
	UNICODE_LATIN_SMALL_LETTER_U_WITH_ACUTE = 0x00FA,
	UNICODE_LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX = 0x00FB,
	UNICODE_LATIN_SMALL_LETTER_U_WITH_DIAERESIS = 0x00FC,
	UNICODE_LATIN_SMALL_LETTER_Y_WITH_ACUTE = 0x00FD,
	UNICODE_LATIN_SMALL_LETTER_THORN = 0x00FE,
	UNICODE_LATIN_SMALL_LETTER_Y_WITH_DIAERESIS = 0x00FF,
	UNICODE_LATIN_CAPITAL_LETTER_Y_WITH_DIAERESIS = 0x0178,

	UNICODE_EN_QUAD = 0x2000,
	UNICODE_EM_QUAD = 0x2001,
	UNICODE_EN_SPACE = 0x2002,
	UNICODE_EM_SPACE = 0x2003,
	UNICODE_ZERO_WIDTH_SPACE = 0x200B,
	UNICODE_ZERO_WIDTH_NON_JOINER = 0x200C,
	UNICODE_ZERO_WIDTH_JOINER = 0x200D,
	UNICODE_EM_DASH = 0x2014,
	UNICODE_BULLET = 0x2022,
	UNICODE_DOUBLE_EXCLAMATION_MARK = 0x203c,
	UNICODE_OVERLINE = 0x203E,

	UNICODE_GREEK_CAPITAL_LETTER_HETA = 0x0370,
	UNICODE_GREEK_SMALL_LETTER_HETA = 0x0371,
	UNICODE_GREEK_CAPITAL_LETTER_ARCHAIC_SAMPI = 0x0372,
	UNICODE_GREEK_SMALL_LETTER_ARCHAIC_SAMPI = 0x0373,
	UNICODE_GREEK_NUMERAL_SIGN = 0x0374,
	UNICODE_GREEK_LOWER_NUMERAL_SIGN = 0x0375,
	UNICODE_GREEK_CAPITAL_LETTER_PAMPHYLIAN_DIGAMMA = 0x0376,
	UNICODE_GREEK_SMALL_LETTER_PAMPHYLIAN_DIGAMMA = 0x0377,
	UNICODE_GREEK_YPOGEGRAMMENI = 0x037A,
	UNICODE_GREEK_SMALL_REVERSED_LUNATE_SIGMA_SYMBOL = 0x037B,
	UNICODE_GREEK_SMALL_DOTTED_LUNATE_SIGMA_SYMBOL = 0x037C,
	UNICODE_GREEK_SMALL_REVERSED_DOTTED_LUNATE_SIGMA_SYMBOL = 0x037D,
	UNICODE_GREEK_QUESTION_MARK = 0x037E,
	UNICODE_GREEK_CAPITAL_LETTER_YOT = 0x037F,
	UNICODE_GREEK_TONOS = 0x0384,
	UNICODE_GREEK_DIALYTIKA_TONOS = 0x0385,
	UNICODE_GREEK_CAPITAL_LETTER_ALPHA_WITH_TONOS = 0x0386,
	UNICODE_GREEK_ANO_TELEIA = 0x0387,
	UNICODE_GREEK_CAPITAL_LETTER_EPSILON_WITH_TONOS = 0x0388,
	UNICODE_GREEK_CAPITAL_LETTER_ETA_WITH_TONOS = 0x0389,
	UNICODE_GREEK_CAPITAL_LETTER_IOTA_WITH_TONOS = 0x038A,
	UNICODE_GREEK_CAPITAL_LETTER_OMICRON_WITH_TONOS = 0x038C,
	UNICODE_GREEK_CAPITAL_LETTER_UPSILON_WITH_TONOS = 0x038E,
	UNICODE_GREEK_CAPITAL_LETTER_OMEGA_WITH_TONOS = 0x038F,
	UNICODE_GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA_AND_TONOS = 0x0390,
	UNICODE_GREEK_CAPITAL_LETTER_ALPHA = 0x0391,
	UNICODE_GREEK_CAPITAL_LETTER_BETA = 0x0392,
	UNICODE_GREEK_CAPITAL_LETTER_GAMMA = 0x0393,
	UNICODE_GREEK_CAPITAL_LETTER_DELTA = 0x0394,
	UNICODE_GREEK_CAPITAL_LETTER_EPSILON = 0x0395,
	UNICODE_GREEK_CAPITAL_LETTER_ZETA = 0x0396,
	UNICODE_GREEK_CAPITAL_LETTER_ETA = 0x397,
	UNICODE_GREEK_CAPITAL_LETTER_THETA = 0x0398,
	UNICODE_GREEK_CAPITAL_LETTER_IOTA = 0x0399,
	UNICODE_GREEK_CAPITAL_LETTER_KAPPA = 0x039A,
	UNICODE_GREEK_CAPITAL_LETTER_LAMDA = 0x039B,
	UNICODE_GREEK_CAPITAL_LETTER_MU = 0x039C,
	UNICODE_GREEK_CAPITAL_LETTER_NU = 0x039D,
	UNICODE_GREEK_CAPITAL_LETTER_XI = 0x039E,
	UNICODE_GREEK_CAPITAL_LETTER_OMICRON = 0x039F,
	UNICODE_GREEK_CAPITAL_LETTER_PI = 0x03A0,
	UNICODE_GREEK_CAPITAL_LETTER_RHO = 0x03A1,
	UNICODE_GREEK_CAPITAL_LETTER_SIGMA = 0x03A3,
	UNICODE_GREEK_CAPITAL_LETTER_TAU = 0x03A4,
	UNICODE_GREEK_CAPITAL_LETTER_UPSILON = 0x03A5,
	UNICODE_GREEK_CAPITAL_LETTER_PHI = 0x03A6,
	UNICODE_GREEK_CAPITAL_LETTER_CHI = 0x03A7,
	UNICODE_GREEK_CAPITAL_LETTER_PSI = 0x03A8,
	UNICODE_GREEK_CAPITAL_LETTER_OMEGA = 0x03A9,
	UNICODE_GREEK_CAPITAL_LETTER_IOTA_WITH_DIALYTIKA = 0x03AA,
	UNICODE_GREEK_CAPITAL_LETTER_UPSILON_WITH_DIALYTIKA = 0x03AB,
	UNICODE_GREEK_SMALL_LETTER_ALPHA_WITH_TONOS = 0x03AC,
	UNICODE_GREEK_SMALL_LETTER_EPSILON_WITH_TONOS = 0x03AD,
	UNICODE_GREEK_SMALL_LETTER_ETA_WITH_TONOS = 0x03AE,
	UNICODE_GREEK_SMALL_LETTER_IOTA_WITH_TONOS = 0x03AF,
	UNICODE_GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA_AND_TONOS = 0x03B0,
	UNICODE_GREEK_SMALL_LETTER_ALPHA = 0x03B1,
	UNICODE_GREEK_SMALL_LETTER_BETA = 0x03B2,
	UNICODE_GREEK_SMALL_LETTER_GAMMA = 0x03B3,
	UNICODE_GREEK_SMALL_LETTER_DELTA = 0x03B4,
	UNICODE_GREEK_SMALL_LETTER_EPSILON = 0x03B5,
	UNICODE_GREEK_SMALL_LETTER_ZETA = 0x03B6,
	UNICODE_GREEK_SMALL_LETTER_ETA = 0x03B7,
	UNICODE_GREEK_SMALL_LETTER_THETA = 0x03B8,
	UNICODE_GREEK_SMALL_LETTER_IOTA = 0x03B9,
	UNICODE_GREEK_SMALL_LETTER_KAPPA = 0x03BA,
	UNICODE_GREEK_SMALL_LETTER_LAMDA = 0x03BB,
	UNICODE_GREEK_SMALL_LETTER_MU = 0x03BC,
	UNICODE_GREEK_SMALL_LETTER_NU = 0x03BD,
	UNICODE_GREEK_SMALL_LETTER_XI = 0x03BE,
	UNICODE_GREEK_SMALL_LETTER_OMICRON = 0x03BF,
	UNICODE_GREEK_SMALL_LETTER_PI = 0x03C0,
	UNICODE_GREEK_SMALL_LETTER_RHO = 0x03C1,
	UNICODE_GREEK_SMALL_LETTER_FINAL_SIGMA = 0x03C2,
	UNICODE_GREEK_SMALL_LETTER_SIGMA = 0x03C3,
	UNICODE_GREEK_SMALL_LETTER_TAU = 0x03C4,
	UNICODE_GREEK_SMALL_LETTER_UPSILON = 0x03C5,
	UNICODE_GREEK_SMALL_LETTER_PHI = 0x03C6,
	UNICODE_GREEK_SMALL_LETTER_CHI = 0x03C7,
	UNICODE_GREEK_SMALL_LETTER_PSI = 0x03C8,
	UNICODE_GREEK_SMALL_LETTER_OMEGA = 0x03C9,
	UNICODE_GREEK_SMALL_LETTER_IOTA_WITH_DIALYTIKA = 0x03CA,
	UNICODE_GREEK_SMALL_LETTER_UPSILON_WITH_DIALYTIKA = 0x03CB,
	UNICODE_GREEK_SMALL_LETTER_OMICRON_WITH_TONOS = 0x03CC,
	UNICODE_GREEK_SMALL_LETTER_UPSILON_WITH_TONOS = 0x03CD,
	UNICODE_GREEK_SMALL_LETTER_OMEGA_WITH_TONOS = 0x03CE,
	UNICODE_GREEK_CAPITLA_KAI_SYMBOL = 0x03CF,
	UNICODE_GREEK_BETA_SYMBOL = 0x03D0,
	UNICODE_GREEK_THETA_SYMBOL = 0x03D1,
	UNICODE_GREEK_UPSILON_WITH_HOOK_SYMBOL = 0x03D2,
	UNICODE_GREEK_UPSILON_WITH_ACUTE_AND_HOOK_SYMBOL = 0x03D3,
	UNICODE_GREEK_UPSILON_WITH_DIAERESIS_AND_HOOK_SYMBOL = 0x03D4,
	UNICODE_GREEK_PHI_SYMBOL = 0x03D5,
	UNICODE_GREEK_PI_SYMBOL = 0x03D6,
	UNICODE_GREEK_KAI_SYMBOL = 0x03D7,
	UNICODE_GREEK_LETTER_ARCHAIC_KOPPA = 0x03D8,
	UNICODE_GREEK_SMALL_LETTER_ARCHAIC_KOPPA = 0x03D9,
	UNICODE_GREEK_LETTER_STIGMA = 0x03DA,
	UNICODE_GREEK_SMALL_LETTER_STIGMA = 0x03DB,
	UNICODE_GREEK_LETTER_DIGAMMA = 0x03DC,
	UNICODE_GREEK_SMALL_LETTER_DIGAMMA = 0x03DD,
	UNICODE_GREEK_LETTER_KOPPA = 0x03DE,
	UNICODE_GREEK_SMALL_LETTER_KOPPA = 0x03DF,
	UNICODE_GREEK_LETTER_SAMPI = 0x03E0,
	UNICODE_GREEK_SMALL_LETTER_SAMPI = 0x03E1,

	UNICODE_BLACK_SQUARE = 0x25A0,

	UNICODE_VARIATION_SELECTOR_1 = 0xFE00,
	UNICODE_VARIATION_SELECTOR_2 = 0xFE01,
	UNICODE_VARIATION_SELECTOR_3 = 0xFE02,
	UNICODE_VARIATION_SELECTOR_4 = 0xFE03,
	UNICODE_VARIATION_SELECTOR_5 = 0xFE04,
	UNICODE_VARIATION_SELECTOR_6 = 0xFE05,
	UNICODE_VARIATION_SELECTOR_7 = 0xFE06,
	UNICODE_VARIATION_SELECTOR_8 = 0xFE07,
	UNICODE_VARIATION_SELECTOR_9 = 0xFE08,
	UNICODE_VARIATION_SELECTOR_10 = 0xFE09,
	UNICODE_VARIATION_SELECTOR_11 = 0xFE0A,
	UNICODE_VARIATION_SELECTOR_12 = 0xFE0B,
	UNICODE_VARIATION_SELECTOR_13 = 0xFE0C,
	UNICODE_VARIATION_SELECTOR_14 = 0xFE0D,
	UNICODE_VARIATION_SELECTOR_15 = 0xFE0E,
	UNICODE_VARIATION_SELECTOR_16 = 0xFE0F,
	UNICODE_ZERO_WIDTH_NO_BREAK_SPACE = 0xFEFF,

	UNICODE_HALFWIDTH_BLACK_SQUARE = 0xFFED,
	UNICODE_HALFWIDTH_WHITE_CIRCLE = 0xFFEE,

	UNICODE_REPLACEMENT_CHARACTER = 0xFFFD
};

#endif // Don't add anything after this line